### ISSUE TITLE
ValidationFailed not set to true when unit testing

### ISSUE THREAD

**Issue by CodingJarod** [FastEndpoints/FastEndpoints#236]
Hi,

i'm trying unit testing an EndPoint but I'm unable to proper test Request body validation errors.

When calling the API via a normal web request the validation occurs and the proper response is returned (400 + errormessages)
When calling it inside unit tests (xUnit) it look like the validation step is skipped and the execution throws an exception in a later stage that is not supposed to be executed if the request body is properly validated.

```
 sut = Factory.Create<GetPodPhaseEndpoint>(_podService);
var request = new GetPodPhaseRequest() { PodSerial = null, ReferenceDate = DateTime.Now.Date };
await sut.HandleAsync(request, CancellationToken.None); //the exception is thrown here 
```

if I handle the exeption in the tests and test the ValidationFailed to be true the assertion fails:
`  Func<Task> act =  () =>  sut.HandleAsync(request, CancellationToken.None);

    await act.Should().ThrowAsync<ValidationException>()
        .WithMessage("Pod serial number cannot be null"); 
    var res = sut.Response;

    sut.ValidationFailed.Should().BeTrue();`

The validator for the GetPodPhaseRequest is written as follows:

```
public class GetPodPhaseRequestValidator: Validator<GetPodPhaseRequest>
    {
        public GetPodPhaseRequestValidator()
        {
            RuleFor(x => x.PodSerial).NotEmpty();
        }
   }
```

Am I missing something?

Thanks

**Comment by dj-nitehawk** [comment]
request/input validation is a pipeline step that happens outside/before the endpoint handler gets executed. so you are not supposed to do unit tests for stuff that involves pipeline steps such as validation.

integration testing is needed when you need to test the whole pipeline from top to bottom.

if unit testing, you are supposed to fill the request dto yourself and hand it to the endpoint/sut handler. if you fill it incorrectly, and the handler code throws, you assert against that.

and then you write unit tests for your validators separately.

**Comment by CodingJarod** [comment]
Ok thank you for the aswer.

Just want to clarify since in the documentation section of the site, in the [paragraph ](https://fast-endpoints.com/docs/integration-unit-testing#unit-testing) related to unit testing an assertion on the Validation Failed property is done.

```
[TestMethod]
public async Task AdminLoginSuccess()
{
    // Arrange
    var fakeConfig = A.Fake<IConfiguration>();
    A.CallTo(() => fakeConfig["TokenKey"]).Returns("0000000000000000");

    var ep = Factory.Create<AdminLogin>(
        A.Fake<ILogger<AdminLogin>>(), //mock dependencies for injecting to the constructor
        A.Fake<IEmailService>(),
        fakeConfig);

    var req = new AdminLoginRequest
    {
        UserName = "admin",
        Password = "pass"
    };

    // Act
    await ep.HandleAsync(req, default);
    var rsp = ep.Response;

    // Assert
    Assert.IsNotNull(rsp);
    **Assert.IsFalse(ep.ValidationFailed);**
    Assert.IsTrue(rsp.Permissions.Contains("Inventory_Delete_Item"));
}

```

Another example is [here ](https://github.com/FastEndpoints/Library/blob/d383b40b9484ed01a199754a4c1010805f919669/Tests/UnitTests/FastEndpoints.UnitTests/WebTests/UnitTests.cs#L67-L88)in the repo.

Can you clarify?
Thank again
