### ISSUE TITLE
refit api proxy generation support in `FastEndpoints.ClientGen`

### ISSUE THREAD

**Issue by vipwan** [FastEndpoints/FastEndpoints#247]
If FastEndpoints.ClientGen can provide the option of `refit `api proxy generation, it would be quite great 

Personally, I feel that [Refit](https://github.com/reactiveui/refit) is much more elegant than the code generated by NSwag, and it will be better extensibility and performance 🥇

**Comment by vipwan** [comment]
If interested in this advice
The community has some open source projects to refer to
eg. 
[GenerateAspNetCoreClient ](https://github.com/Dreamescaper/GenerateAspNetCoreClient )
[RefitGenerator](https://github.com/Velorien/RefitGenerator)

**Comment by dj-nitehawk** [comment]
somebody who's already familiar with refit will have to take this on. 
i don't have much time these days to learn refit and it's inner workings to integrate it in to FE.

**Comment by MichaelHochriegl** [comment]
I know Refit, but I'm not sure on the steps to integrate it with FE. I looked at the current NSwag Client creation and it uses the `CSharpClientGenerator` from `NSwag`. The `CSharpClientGenerator` will take the whole OpenApiDoc and generates the client out of it.

How should the Refit client gen should be implemented? Should an already existing client gen package like the ones linked from @vipwan be used? Or should the client gen be written from the ground up in a new `FastEndpoints.RefitClientGen` package?

**Comment by vipwan** [comment]
> I know Refit, but I'm not sure on the steps to integrate it with FE. I looked at the current NSwag Client creation and it uses the `CSharpClientGenerator` from `NSwag`. The `CSharpClientGenerator` will take the whole OpenApiDoc and generates the client out of it.
> 
> How should the Refit client gen should be implemented? Should an already existing client gen package like the ones linked from @vipwan be used? Or should the client gen be written from the ground up in a new `FastEndpoints.RefitClientGen` package?

Here's a build tool that uses the Nswag.CSharpClientGenerator + liquid template, tested a bit of a problem but basically enough  
https://github.com/itsoli91/OpenApiToRefit/blob/main/OpenApiToRefit.Cli/Program.cs

**Comment by dj-nitehawk** [comment]
@MichaelHochriegl would it be possible to make a `FastEndpoints.RefitClientGen` package without changes to our existing code?
basically like an addon/community extra package. you can use a third party library if you want.
if so, i'll create a new gh repo under `FastEndpoints/RefitClientGen` and make you a collaborator there so you can have direct commit access.

**Comment by dj-nitehawk** [comment]
we have [kiota support](https://discord.com/channels/933662816458645504/1114736030109683782/1182711087901184021) now. so don't think this would be worth implementing.
