### ISSUE TITLE
[Feature] Asymmertic JWT Signing

### ISSUE THREAD

**Issue by itsmuntadhar** [FastEndpoints/FastEndpoints#249]
First of all, I'm a huge fan of this lib and this isn't an issue per se

I was wondering if adding the option to use public/private key pair to sign JWT

One great benefit is other consumers being able to verify the token without going back to the issuer, since they can simply obtain the public key safely and do the verification on their own

**Comment by dj-nitehawk** [comment]
merged. thanks!
