### ISSUE TITLE
Custom AuthorizeAttribute

### ISSUE THREAD

**Issue by rsr-maersk** [FastEndpoints/FastEndpoints#256]
Hi
Thanks for an awesome package!

We have a custom rbac, and for this we use custom authorize
![image](https://user-images.githubusercontent.com/76153851/191830374-39a0821c-1288-4be8-b8ab-cd0ec2af1fd3.png)

the policies are added to the DI.. 
![image](https://user-images.githubusercontent.com/76153851/191830538-4c711dc2-da79-4565-a61e-411402719519.png)
and we add the AddJwtBearer with the Scheme

For a minimal API we would just map like so:

![image](https://user-images.githubusercontent.com/76153851/191830720-1d4243b9-cae2-4a07-a2e3-ab062f9ee775.png)

Any tips why the custom authorization isn't resolving properly in FastEndpoints? And could we do this custom attribute with a configuration override instead?

I can see the "BuildAuthorizeAttributes" in the main extensions. Could the be a configuration for "AddAutherization(auth)"?

**Comment by dj-nitehawk** [comment]
just tried the following and it works:
```cs
using FastEndpoints;
using FastEndpoints.Swagger;
using Microsoft.AspNetCore.Authorization;

var builder = WebApplication.CreateBuilder();
builder.Services.AddAuthorization(c => c.AddPolicy("public access", b => b.RequireAssertion(_ => true)));
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();
app.UseOpenApi();
app.UseSwaggerUi3(c => c.ConfigureDefaults());
app.Run();

[AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
public class MyAuthAttribute : AuthorizeAttribute
{
    public MyAuthAttribute()
    {
        Policy = "public access";
    }
}

[MyAuth, HttpGet("test")]
public class Endpoint : EndpointWithoutRequest
{
    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync("ok!");
    }
}
```
will look in to adding a new method `AuthAttribute(...)` that will accept an auth attribute that can be used inside `Configure()` method.

**Comment by dj-nitehawk** [comment]
actually you do use the following minimal api method `RequireAuthorization()` to attach attributes to an endpoint:
```cs
public override void Configure()
{
    Get("test");
    Options(x => x.RequireAuthorization(new MyAuthAttribute()));
}
```

**Comment by rsr-maersk** [comment]
> ```cs
> [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
> ```

Thats awesome. Thanks @dj-nitehawk !

**Comment by rsr-maersk** [comment]
That is awesome @dj-nitehawk. thanks 1 million!

> actually you do use the following minimal api method `RequireAuthorization()` to attach attributes to an endpoint:
> 
> ```cs
> public override void Configure()
> {
>     Get("test");
>     Options(x => x.RequireAuthorization(new MyAuthAttribute()));
> }
> ```

**Comment by dj-nitehawk** [comment]
@nicecurelom 
if you attach a minimalistic repro project, i can try to help you.

**Comment by DorianGreen** [comment]
@dj-nitehawk 
I noticed that you skip endpoint attributes when a Configure method is declared.

see: https://github.com/FastEndpoints/FastEndpoints/blob/5a886a5947b969525a6e0ecbea6d457bdacfcfc1/Src/Library/Endpoint/Auxiliary/EndpointExtensions.cs#L30

This prevents adding custom auth attributes, or any other attribute for that matter

**Comment by dj-nitehawk** [comment]
@DorianGreen 
that behavior is documented:

![Image](https://github.com/user-attachments/assets/3ab17865-7e9a-4a9e-934f-eb2a79d43c13)
