### ISSUE TITLE
Swagger PropertyNamingPolicy guidance in docs

### ISSUE THREAD

**Issue by altmank** [FastEndpoints/FastEndpoints#260]
Hi, in the documentation, this part says to add some serialize settings
https://fast-endpoints.com/docs/swagger-support#swagger-serializer-options

`builder.Services.AddSwaggerDoc(serializerSettings: x =>
{
    x.PropertyNamingPolicy = null;
    x.DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull;
    ...
});`

If I follow this advice, setting PropertyNamingPolicy to null causes me issues. My data models end up in swagger with PascalCase and this downstream breaks how NSwag TS client converts between data models as it ends up using the same PascalCasing which fails to map to the actual data model casing received from the server. 

If I don't set "x.PropertyNamingPolicy = null;" as recommend in the documentation, what exactly breaks or how exactly does this cause issues? Basically I'm looking for some additional background on this recommendation from the documentation since its causing me issues.

**Comment by dj-nitehawk** [comment]
`x.PropertyNamingPolicy = null;` is not a recommendation. it's just an example showing how to change the serializer settings if need be.

in reality you'd be using the same property naming policy in both the asp.net app and swagger/nswag doc.

**Comment by dj-nitehawk** [comment]
nothing breaks if you don't specify a naming policy. the default `camelCase` policy will be used both for endpoint and swagger. 

even the following mismatched policies work for model binding. haven't tried it with TS client generation though.

```cs
builder.Services.AddSwaggerDoc(serializerSettings: x => x.PropertyNamingPolicy = JsonNamingPolicy.CamelCase);

app.UseFastEndpoints(c => c.Serializer.Options.PropertyNamingPolicy = null);
```

**Comment by altmank** [comment]
Thank you, I appreciate your help to try and help me with my questions.
