### ISSUE TITLE
Unable to construct Validator for unit testing 

### ISSUE THREAD

**Issue by frasermclean** [FastEndpoints/FastEndpoints#269]
I am trying to create some unit tests for my request validator but I cannot construct the object due to a null IServiceResolver.RootServiceProvider inside the Validator<TRequest> class.

Here is the simple validator code
```csharp
public class CreateUserRequestValidator : Validator<CreateUserRequest>
{
    public CreateUserRequestValidator()
    {
        RuleFor(request => request.FirstName).NotEmpty();
        RuleFor(request => request.LastName).NotEmpty();
        RuleFor(request => request.EmailAddress).EmailAddress();
    }
}
```
I have used FluentValidation independently in the past. What is the correct way to write unit tests when using FastEndpoints?

**Comment by dj-nitehawk** [comment]
this has been corrected in the [latest beta](https://www.nuget.org/packages/FastEndpoints/5.2.0-beta22)
