### ISSUE TITLE
Validators from `Include()` and `RuleForEach()` are not included into the swagger documentation

### ISSUE THREAD

**Issue by laya-alsh** [FastEndpoints/FastEndpoints#270]
Hello,

It looks like `ValidationSchemaProcessor` does not respect validators from `Include()` and `RuleForEach()` rules. 

this issue is forwarded from the [small discord conversation](https://discord.com/channels/933662816458645504/1024278454948085780).

I have prepared a small example to demostrate the problem. Imagine you have next request model structure
```c#
public class MyRequest: IRequest
{
    public string? FirstName { get; set; }
    public IReadOnlyList<Child>? Children { get; set; }
    public Partner? Partner { get; set; }
}

public record Child(string? FirstName) : IRequest;

public record Partner(string? FirstName) : IRequest;

public interface IRequest { string? FirstName { get; } }
```

and to validate this request you have next validators
```c#
internal sealed class MyRequestValidator : Validator<MyRequest>
{
    public MyRequestValidator()
    {
        //RuleFor(x => x.FirstName).NotEmpty().MaximumLength(255); // this works
        Include(new BaseValidator()); // this does not work

        RuleFor(x => x.Partner).NotNull().SetValidator(new BaseValidator()); // this works
        RuleForEach(x => x.Children).SetValidator(new BaseValidator()); // this does not work
    }
}

internal sealed class BaseValidator : AbstractValidator<IRequest>
{
    public BaseValidator()
    {
        RuleFor(x => x.FirstName).NotEmpty().MaximumLength(255);
    }
}
```

So for the `MyRequest.FirstName` i would exect in swagger
![image](https://user-images.githubusercontent.com/110024370/193806578-aa4ca846-8a99-485b-b132-98990c64f379.png)

but i got 
![image](https://user-images.githubusercontent.com/110024370/193806433-d983e4ac-f70b-424f-a5d1-b22b635dc046.png)

Similar is for `RuleForEach()`... I noticed that `RuleFor().SetValidator()` works fine, but `RuleForEach().SetValidator()` is ignored..

I've attached a tiny runnable example project.
Thanks!
[validators-bug.zip](https://github.com/FastEndpoints/FastEndpoints/files/9705785/validators-bug.zip)

**Comment by laya-alsh** [comment]
..i'm trying to look into the issue on my own, as the `zymlabs/nswag-fluentvalidation` implementation already has that logic

**Comment by dj-nitehawk** [comment]
@laya-alsh would be nice if you're able to do a PR. i currently have no time to look in to it.
