### ISSUE TITLE
`AddSwaggerDoc` setting `FlattenInheritanceHierarchy` has no effect without setting `removeEmptySchemas`

### ISSUE THREAD

**Issue by Mewriick** [FastEndpoints/FastEndpoints#271]
Hello,

It looks that extension method `AddSwaggerDoc` for Swagger is somehow broken, because if I set `FlattenInheritanceHierarchy = true`, it has no effect because `removeEmptySchemas` parameter has default value `false` and override at the end `FlattenInheritanceHierarchy` property. I do not know if this desired behavior or not. Because without flattening hiearchy I do not see inherited properties in Swagger doc.

Thanks for investigation.

**Comment by dj-nitehawk** [comment]
will look in to it. can you try the latest beta: https://www.nuget.org/packages/FastEndpoints/5.2.0-beta22
and set `removeEmptySchemas: true`. that should flatten hierarchy and get rid of any empty schemas.
