### ISSUE TITLE
Are there any ways to send xml type response?

### ISSUE THREAD

**Issue by chen-pseudonym** [FastEndpoints/FastEndpoints#274]
I want to send back a xml type response, but the SendAsync() method only serialize the DTO to Json type.
I'm a newbie to this wonderful framework.
Are there any ways or hints for me to send a xml type response

**Comment by dj-nitehawk** [comment]
you can send anything like so:
```cs
public class MyEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
        Description(b => b.Produces<object>(200, "application/xml"));
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        const string xml = "<html><body>hello world...</body></html>";
        await SendBytesAsync(Encoding.UTF8.GetBytes(xml), contentType: "application/xml");
    }
}
```

you can even wrap that into an extension method targetting `IEndpoint` interface. 
or create a custom base class with your own `SendXXXAsync()` methods.

**Comment by chen-pseudonym** [comment]
That works. Thanks.
