### ISSUE TITLE
Specify parameter example rather than default

### ISSUE THREAD

**Issue by altmank** [FastEndpoints/FastEndpoints#276]
Current documentation talks about how to set a parameter default, which results in this Swagger output:
![image](https://user-images.githubusercontent.com/22986384/195174795-508946e2-c8ab-4b04-94ce-c60f32fa4af4.png)

But it is not clear if examples are supported, which result in this output:
![image](https://user-images.githubusercontent.com/22986384/195174816-1ed098e8-dd99-4349-8ef2-27781d57f698.png)

Is this currently supported?

**Comment by dj-nitehawk** [comment]
with `v5.2.0-beta27` you can now do the following:
```cs
public class Request
{
    /// <example>1245465</example>
    public string Id { get; set; }
}
```

**Comment by altmank** [comment]
@dj-nitehawk I can't seem to get this to work with v5.2.0. Besides having the comment above the property, any other requirements to enable?

**Comment by dj-nitehawk** [comment]
works fine:
```cs
public class Request
{
    ///<summary>the age</summary>
    ///<example>12</example>
    public int Age { get; set; }
}

public class Endpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        await SendOkAsync();
    }
}
```
![image](https://user-images.githubusercontent.com/7043768/195755401-b6f8d696-bdc1-41f1-8385-767935385081.png)

make sure you've enabled xml docs: https://fast-endpoints.com/docs/swagger-support#enabling-xml-documentation

**Comment by altmank** [comment]
I was able to identify the cause, it was breaking the example functionality if I had a [BindFrom] attribute above the XML comment, like this:

![image](https://user-images.githubusercontent.com/22986384/196230700-5ef89942-68f7-41cd-9e3a-4437051428a7.png)

**Comment by dj-nitehawk** [comment]
ah yeah need to add support for that...
will check tomorrow...

**Comment by dj-nitehawk** [comment]
looks like it's not a bug. it's a .net/c# thing.

the compiler does give a warning about the incorrect usage:

![screen-record-1666081454](https://user-images.githubusercontent.com/7043768/196377380-a22df12a-4793-412d-9bd2-069073567f5f.png)


you just need to move the xml comment up.
```cs
public class Request
{
    ///<example>12</example>
    [BindFrom("age")]
    public int Age { get; set; }
}
```
