### ISSUE TITLE
How to set the swagger Summary with Tags?

### ISSUE THREAD

**Issue by bobbydog** [FastEndpoints/FastEndpoints#278]
Swagger  used in ApiController can has summary from the class name like : 
 /// <"summary"">
 /// Just For Test
 /// </"summary">
 public class TestController : BaseController

How to set this summary in FastEndpoints as it has no controller but tags?
![image](https://user-images.githubusercontent.com/17490587/195753134-87a8b762-86ef-4dd4-93c6-184d1df91963.png)

**Comment by dj-nitehawk** [comment]
upgrade to v5.2 and enable xml documentation [like this](https://fast-endpoints.com/docs/swagger-support#enabling-xml-documentation)

or use `Summary(...)` method: https://fast-endpoints.com/docs/swagger-support#swagger-documentation

**Comment by dj-nitehawk** [comment]
```cs
/// <summary>
/// this is the summary
/// </summary>
/// <remarks>this is the description</remarks>
public class Endpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("test");
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendOkAsync();
    }
}
```

**Comment by dj-nitehawk** [comment]
```cs
public override void Configure()
{
    Get("test");
    Summary(s =>
    {
        s.Summary = "this is the summary";
        s.Description = "this is the description";
    });
}
```

**Comment by dj-nitehawk** [comment]
```cs
public class EndpointSummary : Summary<Endpoint>
{
    public EndpointSummary()
    {
        Summary = "this is the summary";
        Description = "this is the description";
    }
}
```

**Comment by bobbydog** [comment]
> upgrade to v5.2 and enable xml documentation [like this](https://fast-endpoints.com/docs/swagger-support#enabling-xml-documentation)
> 
> or use `Summary(...)` method: https://fast-endpoints.com/docs/swagger-support#swagger-documentation

I would want a summary about the Tags, not the Endpoint.
What you said is about the summary about the endpint ,  but the endpoint "abc/getabc/{id}"  has a router "abc", I want swagger to show  router "abc" is use for what purpose, thanks.

public override void Configure()
{
    Get("abc/Getabc/{id}");
    Options(x => x.WithTags("abc"));
    Summary(s =>
    {
        s.Summary = "this is  the Getabc summary";
        s.Description = "this is Getabc the description";
        s.Params[id]="this is param id description";
      //how to set the description about abc ?
    });
}

**Comment by dj-nitehawk** [comment]
with `v5.2.0.1-beta` you can add tag descriptions for a document like this:
```cs
builder.Services.AddSwaggerDoc(s =>
{
    s.TagDescriptions(
        new OpenApiTag() { Name = "my-tag", Description = "my tag description" },
        new OpenApiTag() { Name = "another-tag", Description = "another tag descrptions" });
});
```
so if an endpoint is tagged with a matching tag name (such as `my-tag`), it will show up under the document tags you add as above.
