### ISSUE TITLE
Parameter example not set if its a path-sourced parameter

### ISSUE THREAD

**Issue by altmank** [FastEndpoints/FastEndpoints#287]
If I set an example for a parameter that is meant to be bound to a path variable, the example value is not output in the swagger docs.

![image](https://user-images.githubusercontent.com/22986384/196543838-836ab34a-565d-4ba9-97ba-f174f5aef234.png)

![image](https://user-images.githubusercontent.com/22986384/196543890-43a42d2e-ce50-4bb3-9db7-f711aada51da.png)

**Comment by dj-nitehawk** [comment]
fixed in `v5.2.1.7-beta`
thanks for reporting!
