### ISSUE TITLE
Support for more VERBS Http.Link, Http.UnLink, Http.Options, etc...

### ISSUE THREAD

**Issue by aredfox** [FastEndpoints/FastEndpoints#299]
I have a scenario where I'd need to support the verbs "LINK", "UNLINK", "OPTIONS" and "VIEW"... Is there a way to support other verbs other than the ENUM? 

Thanks,
Y

**Comment by dj-nitehawk** [comment]
currently not supported. let me see if i can add that...

**Comment by dj-nitehawk** [comment]
you can now do this in `v5.2.1.16-beta`
```cs
public override void Configure()
{
    Verbs("VIEW");
    Routes("/api/test");
}
```
with one little caveat though. when using custom verbs like above, and you wanna allow annonymous access, you gotta specify each verb in the `AllowAnonymous()` call like so:
```cs
    AllowAnonymous(new[] { "VIEW" });
```
simply doing `AllowAnonymous()` will only allow anonymous access to the verbs in the `HTTP` enum.

**Comment by aredfox** [comment]
> simply doing `AllowAnonymous()` will only allow anonymous access to the verbs in the `HTTP` enum.

Thank you! This is acceptable, because, the cases when you need it, one can easily wire up some configuration code then to wrap those things in an Extension or Helper method. Thanks for looking at this & implementing it!
