### ISSUE TITLE
System.MissingMethodException: Method not found: 'System.String[] FastEndpoints.EndpointDefinition.get_AuthSchemeNames()'

### ISSUE THREAD

**Issue by ghost** [FastEndpoints/FastEndpoints#302]
I just updated FastEndpoints to 5.2 and Swagger generation fails, I don't understand what was the breaking change.

![image](https://user-images.githubusercontent.com/104450705/198298599-593e57ae-0633-4513-b2f5-61d46859144b.png)
![image](https://user-images.githubusercontent.com/104450705/198298719-979a76de-bfa5-4ce6-9224-d3402417ed00.png)

**Comment by bentoaldohax** [comment]
My Bad, I just updated FastEndpoints package and I forgot to also update FastEndpoints.Swagger
