### ISSUE TITLE
Support multiple labeled examples

### ISSUE THREAD

**Issue by altmank** [FastEndpoints/FastEndpoints#310]
Hey, SwaggerUI and the open APi spec support defining multiple request body examples with descriptions to represent different request use cases and to provide an example request with each use case.

Could the FastEndpoints request example implementation be updated to support multiple examples along with a label describing each example?

![image](https://user-images.githubusercontent.com/22986384/199323944-72807c5c-1621-4881-8524-927603a0fc76.png)

![image](https://user-images.githubusercontent.com/22986384/199323689-8226590a-c359-4659-8640-db0b5ca7eeaa.png)

**Comment by dj-nitehawk** [comment]
will check...
if somebody wants to send a PR, please go ahead.

**Comment by KateyBee** [comment]
This is implemented in `v5.18.0.5-beta`

Multiple examples for the request DTO can be specified by setting the `ExampleRequest` property of the Summary class multiple times like so:

```csharp
Summary(s =>
{
    s.ExampleRequest = new()
    {
        Name = "one",
    };
    
    s.ExampleRequest = new()
    {
        Name = "two",
    };
});

**Comment by Mishatopkek** [comment]
You need to add it in a documentation, it was not obvious to me

**Comment by dj-nitehawk** [comment]
@Mishatopkek it's documented [here](https://fast-endpoints.com/docs/swagger-support#swagger-documentation).

**Comment by Mishatopkek** [comment]
@dj-nitehawk I'm sorry, I've checked in my project and I updated my message. Currently, I want to know who to change label in an example. My mistake

**Comment by dj-nitehawk** [comment]
customizing the label of examples is currently not supported. will look in to implementing that sometime next week.
the alternative would be to write your own nswag [operation processor](https://gist.github.com/dj-nitehawk/d172140b1f7d576e632a0d15e9682f54) to customize the generated swagger spec.

**Comment by KateyBee** [comment]
@Mishatopkek Give `v5.24.0.1-beta` a try. You can now do this:
```csharp
Summary(
    x =>
    {
        x.RequestExamples.Add(new(new MyRequest { ... }, "label goes here"));
    });
```

**Comment by Mishatopkek** [comment]
> @Mishatopkek Give `v5.24.0.1-beta` a try. You can now do this:
> 
> ```cs
> Summary(
>     x =>
>     {
>         x.RequestExamples.Add(new(new MyRequest { ... }, "label goes here"));
>     });
> ```

I've checked and it works fine
![image](https://github.com/FastEndpoints/FastEndpoints/assets/44339330/8598338b-e95c-464a-9e25-e537326f2df9)
