### ISSUE TITLE
Optional Route Value Without DTO is still required on Swagger

### ISSUE THREAD

**Issue by bentoaldohax** [FastEndpoints/FastEndpoints#312]
So, I have this route value that I want it to be optional and be able to test it on Swagger, but even when putting "isRequired: false", in swagger appears as required.

![image](https://user-images.githubusercontent.com/104450705/199485862-6ea9c3d0-2939-4d1f-bcc4-765867a3cc61.png)

![image](https://user-images.githubusercontent.com/104450705/199485913-b1afcd8c-6ebc-4bd9-a015-ae2a8c1cf5eb.png)

**Comment by dj-nitehawk** [comment]
swagger doesn't allow optional path parameters: https://swagger.io/docs/specification/describing-parameters/
