### ISSUE TITLE
On Route method, when fails to retrieve a route param, always calls ThrowIfAnyErrors();

### ISSUE THREAD

**Issue by bentoaldohax** [FastEndpoints/FastEndpoints#313]
Since I am handling errors using ProblemDetails API and a Global ExceptionHandler, I would like to handle the errors when a route param cannot be cast to, for example an integer and use my own error handling.

It will be nice to have this ThrowIfAnyErrors() as optional in the Route<T> method.

![image](https://user-images.githubusercontent.com/104450705/199495181-565c76db-edf0-465c-a2cc-9900b33ce941.png)

And then be able to handle validation like this:

![image](https://user-images.githubusercontent.com/104450705/199496052-734d1d4b-7f24-4548-a718-f9d94f4296c4.png)

PS: I am already using DontThrowIfValidationFails() in the configure method, but the Route<T> method call seems to ignore it.

![image](https://user-images.githubusercontent.com/104450705/199496585-210f7c68-a529-4dfb-b15f-8424853c559e.png)

**Comment by dj-nitehawk** [comment]
have you tried the following:

```cs
public override void Configure()
{
    DontCatchExceptions();
}
```

**Comment by bentoaldohax** [comment]
Oh yeah, that works! So that will also works with DTOs validation and I can remove DontThrowIfValidationFails() method?
