### ISSUE TITLE
Exception happens when trying to access swaggerui running in docker

### ISSUE THREAD

**Issue by vorrtas** [FastEndpoints/FastEndpoints#314]
I think i can't use swagger inside docker or maybe i'm doing something wrong

![image](https://user-images.githubusercontent.com/76257033/199536987-3ae85741-1e04-42c8-8a71-12bbba9412a4.png)

Context: 
Dockerimage: mcr.microsoft.com/dotnet/aspnet:6.0.10-alpine3.16-amd64

Relevant swagger config:
```csharp
services.AddSwaggerDoc(settings =>
        {
            settings.DocumentName = configuration.GetValue<string>("SWAGGER:DOCUMENT_NAME");
            settings.Title = configuration.GetValue<string>("SWAGGER:TITLE");
            settings.Version = configuration.GetValue<string>("SWAGGER:VERSION");
            settings.Description = configuration.GetValue<string>("SWAGGER:DESCRIPTION");
        }, shortSchemaNames: true);

...
        app.UseOpenApi();
        app.UseSwaggerUi3(s =>
            s.ConfigureDefaults()
        );

```

Error message:
System.TypeInitializationException: The type initializer for 'FastEndpoints.Swagger.OperationProcessor' threw an exception.
 ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at FastEndpoints.Swagger.OperationProcessor..cctor()
   --- End of inner exception stack trace ---
   at FastEndpoints.Swagger.OperationProcessor.Process(OperationProcessorContext ctx)
   at NSwag.Generation.AspNetCore.AspNetCoreOpenApiDocumentGenerator.RunOperationProcessors(OpenApiDocument document, ApiDescription apiDescription, Type controllerType, MethodInfo methodInfo, OpenApiOperationDescription operationDescription, List`1 allOperations, OpenApiDocumentGenerator swaggerGenerator, OpenApiSchemaResolver schemaResolver)

I think it is because

https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Swagger/OperationProcessor.cs#L19
I'm not sure if we could replace it by something like:
```csharp
private static readonly TextInfo textInfo = CultureInfo.Invariant.TextInfo;
// or if we need a copy
private static readonly TextInfo textInfo = (TextInfo)CultureInfo.Invariant.TextInfo.Clone();
```

Maybe it would help but I'm not certain. It might be a breaking change I'm not fammiliar with nswag library.

**Comment by dj-nitehawk** [comment]
fixed in `v5.3.1.2-beta`
thanks for reporting.
