### ISSUE TITLE
Response example should be json object

### ISSUE THREAD

**Issue by altmank** [FastEndpoints/FastEndpoints#315]
In the OpenAPI spec, it looks like response examples should be matching the media type.

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#mediaTypeObject

Response examples in FastEndpoints appear to get formatted as JSON strings instead of as a JSON object. I'm also seeing complaints in 3rd party tools that validate swagger (e.g. Stoplight) complaining the example is not formatted as an object.

e.g.
![image](https://user-images.githubusercontent.com/22986384/199562064-95e9ace8-ec5c-4545-8846-f89a2759245a.png)

vs
![image](https://user-images.githubusercontent.com/22986384/199561990-02c62701-6481-46d2-96a6-49b48b9d86bb.png)

**Comment by dj-nitehawk** [comment]
can you try the latest beta. I think this was fixed recently. report back if it's still there.

**Comment by altmank** [comment]
Let me check...

**Comment by altmank** [comment]
Yes, I confirm its coming over as an object in latest beta. Closing this out as a result. Thanks!
