### ISSUE TITLE
System.NullReferenceException when unit testing endpoint with Mapper

### ISSUE THREAD

**Issue by fauresco** [FastEndpoints/FastEndpoints#316]
I have a Unit Test that runs fine in version 4.3.1 of FastEndpoints but throws System.NullReferenceException in the latest version (5.3.1) because "Map" property is null.

Endpoint code:

```
public override async Task HandleAsync(GetRequest r, CancellationToken ct)
    {
        var participant = await ParticipantRepository.GetByIdAsync(r.Campaign, r.Id, ct);

        if(participant == null)
        {
            await SendNotFoundAsync(ct);
            return;
        }

        var response = Map.FromEntity(participant); // Map is null here, but only in latest version of FastEndpoints
        await SendOkAsync(response, ct);
    }
```
    
In the unit test code, I am creating the endpoint instance with the following code:

`var e = Factory.Create<Get>(Mock.Of<IParticipantRepository>());`
   
I have tested with 4.3.1 because I have a very similar api that is working fine in 4.3.1, then I decided to give it a try and it worked.

Version 5 does have some breaking changes, but it seems not related with this case.

**Comment by dj-nitehawk** [comment]
you now have to set the mapper (`Map` property) before calling the handle method like this:
https://github.com/FastEndpoints/FastEndpoints/blob/60c171af30fcd357cbf06e975d7e290cb92146e3/Tests/UnitTests/FastEndpoints.UnitTests/WebTests/UnitTests.cs#L15-L27
