### ISSUE TITLE
Polymorphic response support

### ISSUE THREAD

**Issue by Wuerike** [FastEndpoints/FastEndpoints#321]
**Is there a way to work with polymorphism on response models with FastEndpoints?**

In my usecase I have a response that has a "week" schema, so, my endpoint should return an array of itens that could be of different models.

Here a simplified version of the models I'm using:

```
public class BaseSale
{
    public string Type { get; set; }
    public string TransactionKey { get; set; }
}

public class CardSale : BaseSale
{
    public string AuthorizationCode { get; set; }
}

public class OnlineSale : BaseSale
{
    public string PaymentKey { get; set; }
}
```

I've created an endpoint that returns an enumerable of `BaseSale`
```
public class GetBaseSalesList : Endpoint<SalesListRequestQuery, IEnumerable<BaseSale>>
{

    ....

    public override async Task HandleAsync(SalesListRequestQuery request, CancellationToken token)
    {
        var salesListFilter = _mapper!.Map<SalesListFilter>(request);

        var sales = _repository!.GetBySpecification(
            new BaseSaleSpecification(salesListFilter)
        );

        await SendAsync(sales);
    }
}
```

My problem is that the children classes specific infos are ignored and I only get the BaseSale info at the responses.
```
[
  {
    "type": "pix",
    "transactionKey": "E2c32640d-a170-46d4-877d-9e349086d771"
  },
  {
    "type": "card",
    "transactionKey": "46111757709832"
  },
  {
    "type": "card",
    "transactionKey": "46311780642853"
  }
]
```

**Comment by dj-nitehawk** [comment]
you will have to wait for .net 7 as STJ does not support this in .net 6
https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-6-0

**Comment by dj-nitehawk** [comment]
alternatively i think by specifying the response type as `object` it might work like so:
```cs
public class GetBaseSalesList : Endpoint<SalesListRequestQuery, IEnumerable<object>>
```
haven't tried that myself.
give it a shot and see how it goes.

**Comment by Wuerike** [comment]
Thanks!

Unfortunately it didn't work.

Ive seen people doing this with Newtonsoft Json, but I dont know if theres how to use it with FastEndpoints
https://www.c-sharpcorner.com/article/polymorphism-in-web-api-net-core-6/

**Comment by dj-nitehawk** [comment]
you can use newtonsoft and achieve this with .net 6 mvc but not with minimal api.
if you really must, you can however utilize newtonsoft with FE like this: https://fast-endpoints.com/docs/configuration-settings#custom-response-dto-serialization

but it's not recommended to use newtonsoft due to poor performance.

**Comment by Wuerike** [comment]
Just by adding this lines it worked perfectly
```
c.Serializer.ResponseSerializer = (rsp, dto, cType, jCtx, ct) =>
    {
        rsp.ContentType = cType;
        return rsp.WriteAsync(Newtonsoft.Json.JsonConvert.SerializeObject(dto), ct);
    };
```

I guess I can accept the performance downside for a while

Thanks a lot!
