### ISSUE TITLE
Version (5.3.0+) encountered injection issue

### ISSUE THREAD

**Issue by vipwan** [FastEndpoints/FastEndpoints#322]
![image](https://user-images.githubusercontent.com/13956765/200258679-0648a0d1-ecd3-4db1-b21d-8b5c9f11d5c0.png)

Because I use OrchardCore's modularity, the IEndpointRouteBuilder and IServiceProvider inside UseFastEndpoints are provided by their respective tenants, can you provide the following extension method to meet such needs:

```
    public static IApplicationBuilder UseFastEndpoints(
        this IApplicationBuilder app,
        IEndpointRouteBuilder routeBuilder,
        IServiceProvider serviceProvider,
        Action<Config>? configAction = null)
    {
        Config.ServiceResolver = serviceProvider.GetRequiredService<IServiceResolver>();
        UseFastEndpointsMiddleware(app);
        MapFastEndpoints(routeBuilder, configAction);
        return app;
    }
```

the previous code will throw an exception if I don't use the internal code directly 

`Cannot cast app to IEndpointRouteBuilder
`

**Comment by vipwan** [comment]
In earlier versions, I used it directly 

```
app. UseFastEndpointsMiddleware();
routes. MapFastEndpoints();
```

Equivalent can be achieved, but in the new version Config.ServiceResolver is internally assigned, so it will not be possible to provide extension methods now

**Comment by dj-nitehawk** [comment]
merged. thanks for the PR.

**Comment by dj-nitehawk** [comment]
removed the extension method in `5.3.2.10-beta` as you can use the old way again and the extension method seems redundant.
