### ISSUE TITLE
Cannot resolve scoped service 'Web.Services.IEmailService' from root provider.

### ISSUE THREAD

**Issue by WahidBitar** [FastEndpoints/FastEndpoints#326]
I don't know if it's happening with somebody else, I keep getting
Unhandled exception. System.InvalidOperationException: Cannot resolve scoped service 'Web.Services.IEmailService' from root provider.
at the startup of the sample Web application

`prop.PropSetter(epInstance, ctx.Resolve(prop.PropType));`

**Comment by dj-nitehawk** [comment]
is this happenning within the duration of an http request or outside that duration?

**Comment by dj-nitehawk** [comment]
from the docs:
> If the command handler execution happens outside the duration of an http request and it needs to access a scoped dependency, an exception will be thrown. In such situations you can inject an IServiceScopeFactory in the constructor and create a scope as described in the event handler section above. I.e. the need for a scope factory would only arise if/when you execute commands outside of endpoints.

**Comment by WahidBitar** [comment]
It's related to the Property Injection
there was a public IEmailService property in the Sales.Orders.Create endpoint and the Create endpoint trying to resolve it at the startup, so we're getting this exception.

For now I just removed this public property and will push PR

**Comment by dj-nitehawk** [comment]
all tests are passing. how are you triggering this?

**Comment by WahidBitar** [comment]
I've just tried to run the Web project

**Comment by dj-nitehawk** [comment]
ah right got it... let me investigate...

**Comment by dj-nitehawk** [comment]
problem solved in `5.3.2.11-beta`
