### ISSUE TITLE
Dto to Model  Custom Mapping

### ISSUE THREAD

**Issue by SViradiya-MarutiTech** [FastEndpoints/FastEndpoints#329]
I am coming from MVC minimal API, we are integrating Fast-Endpoints in our .net 6 Application , and following https://fast-endpoints.com document.

We want to map Request DTO(API Request DTO) to Some Model( to be used in Business Logic) , we dont have currently any Entity.

As per document https://fast-endpoints.com/docs/domain-entity-mapping, It seems Fast endpoints does not have way to map Dto->Model Mapping , So is there any alternative?

**Comment by dj-nitehawk** [comment]
in `Mapper<TRequest, TResponse, TEntity>` the `TEntity` can be anything you want.
it doesn't have to be data entities. it can any model you want to map to.
does that answer your question?

**Comment by SViradiya-MarutiTech** [comment]
Let me phrase my question.

Request Dto used in API Endpoint
```
public class AddPersonDto{

public int PersonId{get; set;}
Public string FirstName{get; set;}
public string LastName{get; set;}
}
```

Person Model 

```
public class PersonModel{

public int Id{get; set;}
Public string FullNameName{get; set;}
}
```

To map `AddPersonDto` to `PersonModel`,  If I add below class , there would be no direct method which takes `AddPersonDto` as request and `PersonModel` as response.

PersonMapper.cs
```csharp

public class PersonMapper : Mapper<AddPersonDto, PersonModel, AnyEntity >
{
    public override AnyEntity ToEntity(AddPersonDto r) => new()
    {
       
    };

    public override PersonModel FromEntity(AnyEntity e) => new()
    {
     
    };
}
````

**Comment by SViradiya-MarutiTech** [comment]
@dj-nitehawk  Can you please review my comment?

**Comment by dj-nitehawk** [comment]
you're gonna have to be a bit patient buddy.
i have a day job to take care of first.
will check your issue when i get some free time.

**Comment by dj-nitehawk** [comment]
the following is how the mappers are typically used. you can also add any other mapping functions to the mapper class and access them through the `Map` property of the endpoint class in addition to the below.
```cs
public class AddPersonRequest
{
    public int PersonId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

public class AddPersonResponse
{
    public int PersonId { get; set; }
    public string Message { get; set; }
}

public class PersonDataModel
{
    public int Id { get; set; }
    public string FullName { get; set; }
}

public class RequestToDataModelMapper : Mapper<AddPersonRequest, AddPersonResponse, PersonDataModel>
{
    public override PersonDataModel ToEntity(AddPersonRequest r)
    {
        return new()
        {
            Id = r.PersonId,
            FullName = r.FirstName + " " + r.LastName
        };
    }

    public override AddPersonResponse FromEntity(PersonDataModel p)
    {
        return new()
        {
            Message = "Person sucessfully saved!",
            PersonId = p.Id
        };
    }
}

public class Endpoint : Endpoint<AddPersonRequest, AddPersonResponse, RequestToDataModelMapper>
{
    public override void Configure()
    {
        Post("add-person");
        AllowAnonymous();
    }

    public override async Task HandleAsync(AddPersonRequest r, CancellationToken c)
    {
        var personDataModel = Map.ToEntity(r);

        var response = Map.FromEntity(personDataModel);

        await SendAsync(response);
    }
}
```

**Comment by SViradiya-MarutiTech** [comment]
Thanks a lot... I am being curious to ask more questions, It would help me lot to integrate fastendpoints. and also clear doubts.

**Comment by dj-nitehawk** [comment]
sure no problem, as long as the questions are clear ;-)
i'll try to asnwer as soon as i have time available.
tc!

**Comment by dj-nitehawk** [comment]
also join our discord server. your questions may already be asnwered. also search old issues.
