### ISSUE TITLE
5.3.2 endpoints now have a capital letter

### ISSUE THREAD

**Issue by krjaction50** [FastEndpoints/FastEndpoints#330]
Just upgraded from 5.2.1 to 5.3.2 and now all my endpoints names in swagger have a capital letter on them.  I changed no code.   Is there something I have to set to get the endpoint names back to matching the endpoint definition? 

            Get("/addresses/{enterpriseId}");

Name shows as Addresses in Swagger.  Name used to be addresses.

**Comment by dj-nitehawk** [comment]
only the swagger groups/tags are capitalized right? 
not the individual operations right?

**Comment by krjaction50** [comment]
Correct

**Comment by dj-nitehawk** [comment]
somebody request them to be capitalized. that's why the default behavior was changed. guess I'll have to add a setting in the next version to let the user choose.

**Comment by krjaction50** [comment]
Yes, it's against our internal standards for some reason.

Thanks

**Comment by dj-nitehawk** [comment]
with `v5.3.2.12-beta` you can choose the tag naming strategy like so:
https://github.com/FastEndpoints/FastEndpoints/blob/b746669a0915d64c6fa0ff69824cb8ecd69efce6/Web/Program.cs#L19-L27
