### ISSUE TITLE
FastEndpoints.Swagger Version Conflict with EF Core 7.0

### ISSUE THREAD

**Issue by derekwelton** [FastEndpoints/FastEndpoints#335]
With the update to Net7.0, all the new packages for EF Core have been upgraded, which means at the moment if I wish to use Ef Core 7.0, I can't use FastEndpoints.Swagger. I know that 7.0 just came out, so I wasn't expecting FastEndpoints to be up to date yet :)

`Version conflict detected for Microsoft.Extensions.DependencyInjection.Abstractions. Install/reference Microsoft.Extensions.DependencyInjection.Abstractions 7.0.0 directly to project DRP.Api to resolve this issue. 
 DRP.Api -> Npgsql.EntityFrameworkCore.PostgreSQL 7.0.0 -> Microsoft.EntityFrameworkCore 7.0.0 -> Microsoft.Extensions.Logging 7.0.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 7.0.0) 
 DRP.Api -> FastEndpoints.Swagger 5.4.0 -> NSwag.AspNetCore 13.17.0 -> NSwag.Generation.AspNetCore 13.17.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 6.0.0 && < 7.0.0)`

![image](https://user-images.githubusercontent.com/31353783/201595697-372fe145-de46-42f6-84e7-fb149500697e.png)

**Comment by dj-nitehawk** [comment]
it's because nswag hasn't been updated for .net 7.0 yet.
i believe this can be worked around for the time being by adding the following to your csproj file:
```xml
<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="7.0.0" />
<PackageReference Include="Microsoft.Extensions.Options" Version="7.0.0" />
```
once nswag is updated, you can remove those.

**Comment by timbze** [comment]
For reference, it's waiting on this: https://github.com/RicoSuter/NSwag/pull/4220
