### ISSUE TITLE
Events setup with WaitForNone still waits for handlers to finish.

### ISSUE THREAD

**Issue by EthemAcar-Dev** [FastEndpoints/FastEndpoints#337]
I have a ProcessDataHandler setup as test for the Event approach. I expected Mode.WaitForNone to not wait for ProcessDataHandler's result and immediately return a result while the ProcessDataHandler finished his task in the background. Right now it just waits 10 seconds till the Handler finishes to return the request.

The code:

```
public class ProcessDataHandler : IEventHandler<ProcessDataEvent>
    {
        private readonly ILogger _logger;

        public ProcessDataHandler(ILogger<ProcessDataHandler> logger)
        {
            _logger = logger;
        }

        public Task HandleAsync(ProcessDataEvent eventModel, CancellationToken ct)
        {
            _logger.LogInformation($"order created event received:[{eventModel.ProcessId}]");
            Thread.Sleep(10000);
            _logger.LogInformation($"order [{eventModel.ProcessId}] finished.");

            return Task.CompletedTask;
        }
    }
```
```
public class ProcessDataEndpoint : EndpointWithoutRequest
    {
        public override void Configure()
        {
            Post("/ProcessData");
            AllowAnonymous();
        }

        public override async Task HandleAsync(CancellationToken ct)
        {
            PublishAsync(new ProcessDataEvent()
            {
                ProcessId = Guid.NewGuid().ToString(),
            }, Mode.WaitForNone);
        }
    }
```

**Comment by dj-nitehawk** [comment]
this is basically what waitfornone does:
https://github.com/FastEndpoints/FastEndpoints/blob/bd8acefb2c19d98ba07b98d92b718c99eacc2d0a/Src/Library/Messaging/Events/EventBus.cs#L49-L51

**Comment by EthemAcar-Dev** [comment]
> 

It was in DEBUG mode before, now i tested in Release mode with no debugger attached and got the same result. It waits for 10 seconds before returning the request. I'm trying to "Decouple Long-running Tasks from HTTP Request Processing". Events in FastEndpoint seemed like an answer for that.

**Comment by EthemAcar-Dev** [comment]
Interesting await Task.Delay(); Indeed works as expected. If Thread.Sleep blocks it like this that means all tasks are performed on the main thread right?

Working code:

```
   public async Task HandleAsync(ProcessDataEvent eventModel, CancellationToken ct)
        {
            _logger.LogInformation($"order created event received:[{eventModel.ProcessId}]");
             await Task.Delay(10000);
            _logger.LogInformation($"order [{eventModel.ProcessId}] finished.");
        }
```

**Comment by EthemAcar-Dev** [comment]
So my real world implementation gave the same problem. So I made a super simple test project which I want to share with you to help debugging the issue. The tests are performed on Release - Any CPU for me.

[FastEndpointsEvents.zip](https://github.com/FastEndpoints/FastEndpoints/files/10040634/FastEndpointsEvents.zip)

**Comment by dj-nitehawk** [comment]
should be sorted now in `v5.4.1.2-beta`
