### ISSUE TITLE
Consider using HttpContext.Response.StatusCode instead of defaulting to 200

### ISSUE THREAD

**Issue by kevbry** [FastEndpoints/FastEndpoints#338]
When using Endpoint<TReq,TResp> style endpoints, it seems to be impossible to return a status code other than 200 without throwing an exception or writing directly to the HttpResponse. If AutoSendResponse (https://github.com/FastEndpoints/FastEndpoints/blob/bd8acefb2c19d98ba07b98d92b718c99eacc2d0a/Src/Library/Endpoint/Endpoint.Static.cs#L45) used ctx.Response.StatusCode rather than hard-coding 200, it'd be possible to override the status code while still having the default be 200.

My use case is that I'm trying to convert a project to FastEndpoints that currently uses the OneOf library (https://github.com/mcintyre321/OneOf) to express endpoint response types as OneOf<SuccessResponse, ErrorTypeOne, ErrorTypeTwo>, etc. I'd like to be able to inspect the IProducesResponseTypeMetadata from the endpoint to automatically set the HTTP response code based on what actual type was returned from the terminal handler inside the OneOf<> container. I've done this by subclassing Endpoint<TRequest,TResponse>, but since AutoSendResponse is an extension method I can't override it. The only other option I see is to copy and reimplement Endpoint<TRequest, TResponse>, which would be a maintenance issue.

**Comment by dj-nitehawk** [comment]
done...
available in `v5.4.0.2-beta`

**Comment by kevbry** [comment]
That hit the spot. Thanks!
