### ISSUE TITLE
Minimal API Versioning - Endpoint not found

### ISSUE THREAD

**Issue by SViradiya-MarutiTech** [FastEndpoints/FastEndpoints#339]
As per description in https://fast-endpoints.com/docs/api-versioning#mark-endpoint-with-a-version, we tried to enable versioning in existing minimal API.

In Configuration we put 

```csharp
app.UseFastEndpoints(c =>
{
    c.Versioning.Prefix = "v";
    c.Versioning.DefaultVersion = 1;
});
```

And in Endpoint Configuration

```csharp
public override void Configure()
    {
       // Before Versioning
        Post("v1/accounts/{@id}/status", x => new {x.Id}); 
        // After Versioning
        Post("accounts/{@id}/status", x => new {x.Id}); 
        Version(1);
    }

```

After enabling Versioning, I get 404 when I hit
**POST** `http://localhost:5000/v1/accounts/1/status`

 I don't know where I am failing..

**Comment by SViradiya-MarutiTech** [comment]
If I remove versioning, Endpoint works.

**Comment by dj-nitehawk** [comment]
try POSTing to `http://localhost:5000/accounts/1/status/v1` because by default the version is appended to the url. you should setup swagger to see what the available endpoint URLs are.

**Comment by SViradiya-MarutiTech** [comment]
@dj-nitehawk   We want to use `http://localhost:5000/v1/accounts/1/status`  ,  we can not change our url...

**Comment by SViradiya-MarutiTech** [comment]
Is this possible? if it is not is should be there , as in  MVC Route we can set version in  route templete

**Comment by dj-nitehawk** [comment]
see `SuffixedVersion` at the bottom of the page you linked above.
