### ISSUE TITLE
Docs - search isn't working

### ISSUE THREAD

**Issue by JonHodgins** [FastEndpoints/FastEndpoints#340]
Regardless of what I type into the search, it returns "No results for..."

![image](https://user-images.githubusercontent.com/19355502/202607498-e5cceea8-dfbb-4750-8b34-b67df2c8a86e.png)

**Comment by dj-nitehawk** [comment]
yeah it's a known issue. 
algolia refuses to give us a free/open source account for some reason.
people are working on an alternative.
you can stay tuned for updates here: 
https://discord.com/channels/933662816458645504/999224616595750922
