### ISSUE TITLE
Endpoint group declaration with empty route

### ISSUE THREAD

**Issue by oamm** [FastEndpoints/FastEndpoints#341]
I realize Endpoint declaration needs to have a RoutePattern even when you associate a group with that endpoint.

First, i have this configuration for the base Group of my urls.
This configuration is going to give a url like "/api/credits"

```
public class CreditsGroup : Group
{
    public CreditsGroup()
    {
        Configure("credits", ep =>
        {
            ep.Description(x => x
                .Produces(401)
                .WithTags("Credits"));
        });
    }
}
```

Then i configure my endpoint, to receive the request, but i have to register a pattern route even when i just want to post directly to the base url given by the group, i mean the post request will be sent to "/api/credits",
So i think is a little redundant or unnecessary have to write a "empty RoutePattern", when i should only call Post() method without parameters

```
public class CreateCreditEndpoint : Endpoint<CreditRequest, CreditResponse>
{
    private readonly IMapper _mapper;
    private readonly IMediator _mediator;

    public CreateCreditEndpoint(IMapper mapper, IMediator mediator)
    {
        _mapper = mapper;
        _mediator = mediator;
    }

    public override void Configure()
    {
       //Here i have to add and empty string to the RoutePattern to avoid the exception 
        Post(string.Empty);
        AllowAnonymous();
        Group<CreditsGroup>();
    }

    public override async Task HandleAsync(CreditRequest request, CancellationToken c)
    {
        CreateCreditCommand command = _mapper.Map<CreateCreditCommand>(request);
        Credit credit = await _mediator.Send(command);
        await SendAsync(new CreditResponse()
        {
            
        }, cancellation: c);
    }
}
```

thanks

**Comment by dj-nitehawk** [comment]
will look in to it...

**Comment by oamm** [comment]
> will look in to it...

I'm thinking if you could give me some hint about how solve this issue I would try to fix it  just for start help you and start to know the project if you want,

**Comment by dj-nitehawk** [comment]
i think it makes more sense to just do `Post("/")` instead of `Post(string.Empty)` because it **is** the `root/base` route of that group. this way we don't need to change anything in the library code. `"/"` already works like so:
```cs
public class CreditsGroup : Group
{
    public CreditsGroup()
    {
        Configure("credits", ep =>
        {
            ep.Description(x => x
              .Produces(401)
              .WithTags("Credits"));
        });
    }
}

public class SalesGroup : Group
{
    public SalesGroup()
    {
        Configure("sales", ep =>
        {
            ep.Description(x => x
              .Produces(401)
              .WithTags("Sales"));
        });
    }
}

public class CreateCreditEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Post("/");
        Group<CreditsGroup>();
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync("hello from credits...");
    }
}

public class CreateSaleEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Post("/");
        Group<SalesGroup>();
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync("hello from sales...");
    }
}
```
anyhow, if you wanna learn what happens with the groups, this is where the route of the endpoint gets modified in a recursive manner:
https://github.com/FastEndpoints/FastEndpoints/blob/a0ee29ec3bf200738409b73b289f0d94cf93777d/Src/Library/Endpoint/Auxiliary/Group.cs#L17-L30
