### ISSUE TITLE
Request: FastEndpoints plugin for JetBrains Rider

### ISSUE THREAD

**Issue by JonHodgins** [FastEndpoints/FastEndpoints#345]
It would be great if there was a Rider plugin (extension) available that had similar functionality to the VS extension: https://marketplace.visualstudio.com/items?itemName=dj-nitehawk.FastEndpoints

PS: Thank you for building this library @dj-nitehawk! It's fantastic.

**Comment by dj-nitehawk** [comment]
@JonHodgins i don't use rider, so it's gonna have to be a community contribution. i'll leave this ticket open so somebody will look in to it hopefully.

@MichaelHochriegl was it you that interested in making a rider plugin?

**Comment by altmank** [comment]
Isn't this something that can be done with the existing Live Template system in Rider and then just exported/shared? Not have to be an entire plugin?

**Comment by MichaelHochriegl** [comment]
I haven't looked at the new 2023 version, but with the 2022 version you are not able to export the templates for dotnet, only for other languages you can properly export the templates.

If something changed in that regard it would be awesome!
