### ISSUE TITLE
testing: Factory.Create equivelant for pre/prost processors

### ISSUE THREAD

**Issue by jammehcow** [FastEndpoints/FastEndpoints#346]
Currently there is support for creating testable instances of endpoints without the use of a `WebApplicationFactory<>` by using the `Factory.Create<T>` method. However, there is no equivalent method for `IGlobalPre/PostProcessor` or `IPre/PostProcessor<T>` which prevents processors from being tested in the same way.

Ideally the `Factory.Create<>` method would support instantiating these processors without passing off the request to an endpoint to aid in unit testing.

**Comment by jammehcow** [comment]
I'm more than happy to look into implementing this if the approach of adding a `Factor.Create<>` overload seems reasonable.

**Comment by dj-nitehawk** [comment]
yeah another generic overload for factory.create sounds ok. go for it 😉

**Comment by jammehcow** [comment]
Originally I was wanting to functionally test behaviour of an `IGlobalPreProcessor` which depends on both an `ILogger<T>` and an `IConfiguration`. It didn't click that the `TryResolve` method was actually an extension method with static fields backing it - making it impossible to mock out. I've just noticed that the `Endpoint` classes also make use of the same static `IServiceProvider` - preventing parallelization of tests.

I'm going to close this issue off in favour of a new issue to cover this static `IServiceProvider` used by all implementations of `TryResolve` as I believe it's a hindrance for testing.
