### ISSUE TITLE
How to re-use validators in other classes

### ISSUE THREAD

**Issue by itsoli91** [FastEndpoints/FastEndpoints#347]
Hi,
Currently, I'm using` Validator<MyRequest>` to validate my request, however to prevent rewriting another validation to use in another classess rather than endpoints, I tried to access to `Validator<MyRequest>` or `IValidator<MyRequest>` from DI, but always i get service not register error from DI.
Is there anyway to re-use validators ?

```
    private readonly Validator<MyRequest> _myRequestValidator;
    // or private readonly IValidator<MyRequest> _myRequestValidator;

    public HostedService(
        Validator<MyRequest> myRequestValidator)
    {

        _myRequestValidator= searchNaturalPersonRequestValidator;

    }
```

**Comment by dj-nitehawk** [comment]
you can just register the validators in di yourself. 
fastendpoints doesn't register nor resolve them from di. only a single instance is cached and reused for every http request because benchmarking showed that validators are expensive to recreate per request.
