### ISSUE TITLE
System.Text.Json.JsonException only when making client-side request

### ISSUE THREAD

**Issue by Josh865** [FastEndpoints/FastEndpoints#349]
Thanks for the great library!

I have an endpoint that returns a paginated response. 

```
public override async Task HandleAsync(Request request, CancellationToken cancellationToken)
{
  var sponsors = await _context.Sponsors
    .OrderBy(s => s.Name)
    .PaginateAsync(request.Page, request.PerPage, cancellationToken);

  await SendOkAsync(sponsors, cancellationToken);
}
```

The `Request` class for the endpoint simply inherits from a `PaginatedRequest` class.

**Request.cs**
```
public class Request : PaginatedRequest { }
```

**PaginatedRequest.cs**
```
public abstract class PaginatedRequest : IPaginatedRequest
{
  public virtual int Page { get; set; } = 1;
  public virtual int PerPage { get; set; } = 20;
}
```

Everything works perfectly fine when accessing the corresponding URL with a browser. However, when I try to access the URL from the client (specifically, using the `fetch` API inside a React component), I receive the following error:

```
System.Text.Json.JsonException: The input does not contain any JSON tokens.
Expected the input to start with a valid JSON token, when isFinalBlock is true.
Path: $ | LineNumber: 0 | BytePositionInLine: 0.
```

I've quickly scaffolded an endpoint in `Program.cs` that accepts the same parameters and returns the same data, and it works fine regardless of how it's accessed (whether in the browser or via the `fetch` API):

```
app.MapGet("sponsors", async (int? page, int? perPage, ApplicationDbContext db) =>
{
  return await db.Sponsors.OrderBy(s => s.Name).PaginateAsync(page ?? 1, perPage ?? 20);
});
```

I'm happy to provide more context if it would be helpful, but I didn't want to create too much noise if the issue is something simple that I'm simply overlooking or not aware of.

**Comment by dj-nitehawk** [comment]
what does your configure method look like?
is it a get or post request? 
this error is typically thrown by STJ when you ask it to deserialize a json object or array but the incoming request doesn't have a valid json format. such as {} or [] etc. 

btw your minimal example is not really the same thing as the FE endpoint. if you update it to accept the request dto object instead of the individual parameters, it may throw the same exception.

**Comment by Josh865** [comment]
Thanks for the quick response! Here's the Configure method for the endpoint:

```
public override void Configure()
{
  Get("api/sponsors");
  AllowAnonymous();
  Description(b => b.WithTags("Sponsors"));
  Summary(s =>
  {
    s.Summary = "Returns a list of all sponsors.";
  });
}
```

Following your suggestion, I changed my minimal example to reference the same request DTO and it still works correctly (though the use of `[AsParameters]` attribute may mean this still isn't an exact apples-to-apples comparison).

```
app.MapGet("sponsors", async ([AsParameters] Api.Endpoints.Sponsors.GetSponsors.Request request, ApplicationDbContext db) =>
{
  return await db.Sponsors.OrderBy(s => s.Name).PaginateAsync(request.Page, request.PerPage);
});
```

I should have mentioned in my original comment that I'm using version 5.4.1 on .NET 7.

**Comment by dj-nitehawk** [comment]
and the parameters are being bound from query strings right? 

if this is a get request and it works from a browser that probably means that your react fetch request has an incorrect content type header which is causing STJ to try and deserialize a non-existent json request body. so check what content-type is being sent from the fetch client. if it has application/json content type, get rid of that.

**Comment by dj-nitehawk** [comment]
if that doesn't solve it, pls post the full class code I can copy paste and debug. will have a look at it tomorrow morning.

**Comment by Josh865** [comment]
You were right, it was the `Content-Type` header that was causing the issue. It was set to `application/json`, so by removing that and not setting a value for the `Content-Type` at all (at least for `get` requests), it works as expected.

Thanks for your help!
