### ISSUE TITLE
Validators doesn't return custom error messages or error codes

### ISSUE THREAD

**Issue by developer82** [FastEndpoints/FastEndpoints#350]
Following the documentation for validators:
https://fast-endpoints.com/docs/validation#request-dto-validation

Results ignores the `WithMessage` and instead displays a default message.
It also ignores the `WithErrorCode` property and again displays a default message.

This is my code:
```
public class RegistrationValidator : Validator<RegistrationRequest>
    {
        public RegistrationValidator()
        {
            RuleFor(x => x.Email)
                .NotEmpty()
                .WithErrorCode(ValidatorsErrorCodes.REQUIRED)
                .EmailAddress()
                .WithErrorCode(ValidatorsErrorCodes.INVALID_EMAIL);

            RuleFor(x => x.Password)
                .NotEmpty()
                .WithErrorCode(ValidatorsErrorCodes.REQUIRED)
                .MinimumLength(8)
                .WithErrorCode(ValidatorsErrorCodes.MIN_LENGTH)
                .MaximumLength(16)
                .WithErrorCode(ValidatorsErrorCodes.MAX_LENGTH)
                .Matches(@"[A-Z]+")
                .WithErrorCode(ValidatorsErrorCodes.PASSWORD_MUST_CONTAIN_UPPERCASE_LETTER)
                .Matches(@"[a-z]+")
                .WithErrorCode(ValidatorsErrorCodes.PASSWORD_MUST_CONTAIN_LOWERCASE_LETTER)
                .Matches(@"[0-9]+")
                .WithErrorCode(ValidatorsErrorCodes.PASSWORD_MUST_CONTAIN_NUMBER)
                .Matches(@"[\!\?\*\.]+")
                .WithErrorCode(ValidatorsErrorCodes.PASSWORD_MUST_CONTAIN_SPECIAL_CHARACTER);

            RuleFor(x => x.FullName)
                .NotEmpty()
                .WithErrorCode(ValidatorsErrorCodes.REQUIRED);
        }
    }
```

**Comment by dj-nitehawk** [comment]
i don't see you using `WithMessage` in your example above.
anyhow if you take a look at this [sample project](https://github.com/FastEndpoints/FastEndpoints/files/10096266/Repro.zip), it works and returns error messages like this:

![image](https://user-images.githubusercontent.com/7043768/204089722-0b06dd38-a604-45de-8f2a-52e675cd68f4.png)

as for the `WithErrorCode`, fastendpoints doesn't use this error code anywhere and has no use for it. if you use this method it will just be available in the `ValidationFailure` object if you wanna do something with that info, for example when doing your own custom error responses as described [here](https://fast-endpoints.com/docs/configuration-settings#customizing-error-responses).
