### ISSUE TITLE
testing: static-backed dependency resolution reduces endpoint/processor testability

### ISSUE THREAD

**Issue by jammehcow** [FastEndpoints/FastEndpoints#351]
As mentioned in my last comment in #346, endpoints & processors (`IGlobalPreProcessor` etc.) make use of a shared static `IServiceProvider` in `FastEndpoints.Config`. This was most likely introduced to ensure a single known service provider across an application's lifetime without getting mixed up with the ASP.NET types in ASP.NET's service provider (assumption). 

The use of a single static instance hinders unit test parallelization when using different dependency implementations and subsequently prevents per-test mocking of dependencies when running in parallel.

**Comment by dj-nitehawk** [comment]
parallel integration/WAF testing does work as can be seen [here](https://github.com/FastEndpoints/FastEndpoints/blob/main/Tests/IntegrationTests/FastEndpoints.IntegrationTests/WebTests/AdminTests.cs).

different test services are configured like so:
https://github.com/FastEndpoints/FastEndpoints/blob/4cab0fe73b2429edb4c30bc14e2c47dd712057b3/Test/Setup.cs#L14-L18

as for unit testing, you're not supposed to test the whole pipeline consiting of pre/post processors, validators, etc. in a unit test.
the purpose of a unit test is to test only the handler logic by supplying it a populated request dto and checking the result dto to see if the handler did it's job correctly producing the response. any other requirement calls for an integration test.

for example, if you need to test if a database entity was correctly set/updated by the endpoint handler, that's an integration test, and should be done with the help of the `WebApplicationFactory` and not `Factory.Create<TEndpoint>()`.

pipeline pieces such as validators, pre-processors, filters, etc. should be unit tested in isolation on their own. and yes you're correct that if you use the convenient `Resolve<TService>()` methods does not led well to unit testing. for the time being you'd just have to switch to using `HttpContext.RequestServices.GetService<TService>()` instead if you need to unit test processors. then you can just use a mock/default http context.
