### ISSUE TITLE
`Asp.Versioning.Http` package support

### ISSUE THREAD

**Issue by rsr-maersk** [FastEndpoints/FastEndpoints#352]
HI

Thanks for the awesome package. Its awesome.

we add versions to our Apis via api header:

```c#
services.AddApiVersioning(options =>
        {
            options.AssumeDefaultVersionWhenUnspecified = true;
            options.DefaultApiVersion = ApiVersion.Default;
            options.ReportApiVersions = true;
            options.ApiVersionReader = new HeaderApiVersionReader("api-version");
        });
```

The API versioning on https://fast-endpoints.com/docs/api-versioning#deprecate-an-endpoint uses a path for the versioning.
For fast endpoints we are also using the "Configure()" override. How can we utilize our version header for apis and using the Configure option. The "Version()" override does not appear to work :-/

Would be awesome if it fastendpoints could support https://github.com/dotnet/aspnet-api-versioning

Thanks again..

**Comment by dj-nitehawk** [comment]
`Asp.Versioning.Http` package is currently not supported. somebody who's familiar with the internal workings of that package would have to make a contribution.

as for our existing implementation of versioning, will look in to the possibility of adding header support as soon as i get a chance. if someone reading this wants to have a crack at adding header support to our versioning, please go ahead and submit a PR.

thanks!

**Comment by rsr-maersk** [comment]
The main point though is, that the versioning needs to support the HeaderApiVersionReader. 
It is just as normal for Api Versioning in the header, equally to a path prefix

**Comment by dj-nitehawk** [comment]
ideally we should look at providing header support for our existing versioning system instead of relying on a third-party which is not even maintained by microsoft anymore.

so if you wanna have crack at implenting that, do go ahead...
as for how, i have no idea. i need to sit down and study the versioning code again.
the amount of free time needed for this task is nowhere to be found anytime soon for me unfortunately 🫤

**Comment by dj-nitehawk** [comment]
okay soo... with `v5.9.0.1-beta` you can now do the following (if you really must) 😉
```cs
using Asp.Versioning;
using Asp.Versioning.Builder;
using Asp.Versioning.Conventions;
using FastEndpoints;
using FastEndpoints.Swagger;

var builder = WebApplication.CreateBuilder();

builder.Services
    .AddApiVersioning(o =>
    {
        o.DefaultApiVersion = new(1.0);
        o.AssumeDefaultVersionWhenUnspecified = true;
        o.ApiVersionReader = new HeaderApiVersionReader("x-api-version");
    })
    .AddApiExplorer(o => o.GroupNameFormat = "'v'VVV");

var versionSet = new ApiVersionSetBuilder(null)
    .HasApiVersion(1.0)
    .HasApiVersion(2.0)
    .Build();

builder.Services
    .AddSingleton(versionSet) //this is the only part that's specific to FastEndpoints
    .AddFastEndpoints()
    .AddSwaggerDoc(x =>
    {
        x.DocumentName = "version one";
        x.ApiGroupNames = new[] { "v1" }; //needs to conform to 'GroupNameFormat' above
    })
    .AddSwaggerDoc(x =>
    {
        x.DocumentName = "version two";
        x.ApiGroupNames = new[] { "v2" }; //needs to conform to 'GroupNameFormat' above
    });

var app = builder.Build();
app.UseAuthorization()
   .UseFastEndpoints()
   .UseSwaggerGen();
app.Run();

public class Endpoint_v1 : Endpoint<Request>
{
    public ApiVersionSet VersionSet { get; set; }

    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
        Options(x => x
            .WithApiVersionSet(VersionSet)
            .MapToApiVersion(1.0));
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        await SendAsync($"v1 - {r.Name}");
    }
}

public class Endpoint_v2 : Endpoint<Request>
{
    public ApiVersionSet VersionSet { get; set; }

    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
        Options(x => x
            .WithApiVersionSet(VersionSet)
            .MapToApiVersion(2.0));
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        await SendAsync($"v2 - {r.Name}");
    }
}

public sealed class Request
{
    public string Name { get; set; }
}
```

**Comment by zfchai** [comment]
about [okay soo... with you can now do the following (if you really must) v5.9.0.1-beta😉]

**Comment by zfchai** [comment]
# about [okay soo... with you can now do the following (if you really must) v5.9.0.1-beta😉] 

The code display at this location is abnormal, as shown below:

`.AddApiExplorer(o => o.GroupNameFormat = "'v'VVV"); `

Error message: The method did not display an overload of a parameter.

What should I do?

**Comment by dj-nitehawk** [comment]
@zfchai make sure you have the following in your csproj:
```xml
        <PackageReference Include="Asp.Versioning.Http" Version="7.0.0" />
        <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="7.0.0" />
```

**Comment by zfchai** [comment]
Does the version have to be 7.0. does net6.x not support it?

```
<PackageReference Include="Asp.Versioning.Http" Version="7.0.0" />
<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="7.0.0" />
```

**Comment by dj-nitehawk** [comment]
i think they only added minimal api support in v7. not 100% sure though.
try out v6 and see if it works and report back please.

**Comment by zfchai** [comment]
Suggest adjusting the HasApiVersion and MapToApiVersion parameters to string type instead of number type.

```csharp
var versionSet = new ApiVersionSetBuilder(null)
    .HasApiVersion(stirng)
    .HasApiVersion(string)
    .Build();

public override void Configure()
{
   ...
   Options(x => x.WithApiVersionSet(VersionSet).MapToApiVersion(string));
   ...
}
```

![image](https://user-images.githubusercontent.com/82487746/234209276-2147d747-bd7b-49ec-bbeb-ccf55882ef36.png)

**Comment by dj-nitehawk** [comment]
we have no control over it. 
all of those methods are from that package. 
you can lodge an issue with them.

**Comment by zfchai** [comment]
Since you are using your FastEndpoints framework, it is recommended that the nuget package for the solution should be fed back with the corresponding nuget package provider to promote each other, otherwise I have to feedback every muget package I use, which is not very scientific. From the user's point of view, I feel that the feedback suggestions are very fragmented and there is no unified system.

**Comment by dj-nitehawk** [comment]
well that's open source for ya 😉
basically it's a take it or leave it system 😜
there's no perfection in software development.
anyhow I don't have the time to reimplement what that package does since I don't personally have a need for it. hence the code above is simply meant to show people how to use it with FE. 

if you like you can contribute a PR and I'll gladly review it. however I believe the reason they're also using a double instead of a string is due to increased allocations that would have to be made when doing comparisons internally. so I would also not want any strings in the versioning code for the PR to be accepted. so I think you should just let go of the idea that endpoint versioning should be string based and just use either the built in FE versioning or use the third party package if the built in functionality is not sufficient for your use case. 

this will be my last reply regarding the matter as I'd like to keep this thread clean just for feedback on edge cases that might popup regarding the integration.

**Comment by zfchai** [comment]
https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/issues/51

**Comment by dj-nitehawk** [comment]
> [luoyunchong/IGeekFan.AspNetCore.Knife4jUI#51](https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/issues/51)

this works for me: https://github.com/FastEndpoints/FastEndpoints/issues/437#issuecomment-1518937470

also pls use the relevant thread. this gh issue is for `Asp.Versioning.Http` package integration only.

**Comment by candoumbe** [comment]
Good to see some work being done on this area !
I just forked the project and was about to ask where tests related to handling versions are (if any).

Well done !

**Comment by dj-nitehawk** [comment]
@candoumbe no tests yet. i'm trying to wrap up this functionality into a `FastEndpoints.AspVersioning` package for ease of use. let's see how that goes.

**Comment by candoumbe** [comment]
> @candoumbe no tests yet. i'm trying to wrap up this functionality into a `FastEndpoints.AspVersioning` package for ease of use. let's see how that goes.

Yeah of course, I was talking about tests for the "current" implementation of Versioning (and not the one in `WIP`).

**Comment by dj-nitehawk** [comment]
@candoumbe integration tests like these are dispersed throught 🤐

https://github.com/FastEndpoints/FastEndpoints/blob/fbe3c7ac872a2c1000f2c593e7656a116f2257c0/Tests/IntegrationTests/FastEndpoints.IntegrationTests/WebTests/AdminTests.cs#L65-

as well as swagger snapshot tests such as these:

https://github.com/FastEndpoints/FastEndpoints/blob/fbe3c7ac872a2c1000f2c593e7656a116f2257c0/Tests/IntegrationTests/FastEndpoints.Swagger.IntegrationTests/SwaggerDocTests.cs#L20-L66

**Comment by dj-nitehawk** [comment]
okay... i have some progress...
upgrade FE packages to `v5.9.0.2-beta` and install `FastEndpoints.AspVersioning` package also.
then test out the following:
```cs
using Asp.Versioning;
using Asp.Versioning.Conventions;
using FastEndpoints;
using FastEndpoints.AspVersioning;
using FastEndpoints.Swagger;

VersionSets.CreateApi(">>Orders<<", v => v
    .HasApiVersion(1.0)
    .HasApiVersion(2.0));

VersionSets.CreateApi(">>Inventory<<", v =>
{
    v.HasApiVersion(1.0);
    v.HasApiVersion(1.1);
});

var builder = WebApplication.CreateBuilder();
builder.Services
    .AddFastEndpoints()
    .AddVersioning(o =>
    {
        o.DefaultApiVersion = new(1.0);
        o.AssumeDefaultVersionWhenUnspecified = true;
        o.ApiVersionReader = new HeaderApiVersionReader("X-Api-Version");
    })
    .AddSwaggerDoc(x =>
    {
        x.DocumentName = "version one";
        x.ApiVersion(new(1.0));
    }, tagIndex: 0)
    .AddSwaggerDoc(x =>
    {
        x.DocumentName = "version one point one";
        x.ApiVersion(new(1.1));
    }, tagIndex: 0)
    .AddSwaggerDoc(x =>
    {
        x.DocumentName = "version two";
        x.ApiVersion(new(2.0));
    }, tagIndex: 0);

var app = builder.Build();
app.UseAuthorization()
   .UseFastEndpoints()
   .UseSwaggerGen();

app.Run();

public class GetInvoices_v1 : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("invoices");
        AllowAnonymous();
        Options(x => x
            .WithVersionSet(">>Orders<<")
            .MapToApiVersion(1.0));
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync("v1 - orders");
    }
}

public class GetInvoices_v2 : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("invoices");
        AllowAnonymous();
        Options(x => x
            .WithVersionSet(">>Orders<<")
            .MapToApiVersion(2.0));
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync("v2 - orders");
    }
}

public class GetStockItems_v1 : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("stock-items");
        AllowAnonymous();
        Options(x => x
            .WithVersionSet(">>Inventory<<")
            .MapToApiVersion(1.0));
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync("v1 - inventory");
    }
}

public class GetStockItems_v1_1 : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("stock-items");
        AllowAnonymous();
        Options(x => x
            .WithVersionSet(">>Inventory<<")
            .MapToApiVersion(1.1));
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync("v1.1 - inventory");
    }
}
```

**Comment by zfchai** [comment]
How does **FastEndpoints.Swagger** implement **API Group**? 

For example, there are two groups of API. 

- Group A: 
1 、 /api/user/create. 
2 、 /api/user/get. 

- Group B: 
1 、 /api/org/create. 
2 、 /api/org/get

Can you provide a specific demo?

**Comment by dj-nitehawk** [comment]
@zfchai read this: https://fast-endpoints.com/docs/swagger-support#swagger-operation-tags

please for the love of god create new issues for stuff that doesn't belong in existing issues.
or ideally join the discord server and create posts there.
thanks for understanding!

**Comment by zfchai** [comment]
Let's first take a look at two images, as follows:

- using FastEndpoints.Swagger;

![d6083dd70651c6d03e168f66f9d020a](https://user-images.githubusercontent.com/82487746/234493865-7e77437a-01fa-4ece-be97-ee985e26b36a.png)

- using IGeekFan.AspNetCore.Knife4jUI;

![ebdcd8c2d5e75e73d7aef09c75f13d3](https://user-images.githubusercontent.com/82487746/234493919-ef97cc9e-ee96-4d4c-a690-d4e6cda3ba62.png)

demo => [Solution1.zip](https://github.com/FastEndpoints/FastEndpoints/files/11329907/Solution1.zip)

The above API essentially only has three APIs, as shown below:

- /my/create
- /user/create
- /your/create

My belongs to Amin，The other two APIs belong to User。

After testing, it is clear that it does not meet expectations. Are you sure this is not a problem?

Do you understand what I mean, or should you tell me what to do?

**Comment by zfchai** [comment]
ok, create new issues.
