### ISSUE TITLE
Unit test can not access custom error body response?

### ISSUE THREAD

**Issue by timbze** [FastEndpoints/FastEndpoints#357]
I have this:
`Endpoint<GetApiRq, GetApiRs>`

I regularly return:
`await SendAsync(domainValue.MapToApi(), cancellation: ct);`

But on a certain authorization error I return:
`await SendStringAsync("Something did not work out", 403, cancellation: ct);`

In my unit test I try to access `ep.HttpContext.Response.Body` after running `HandleAsync`, but the response body is null. It seems I can't check for the error message when I call `SendStringAsync`. I am able to check status code 403 though.

Do you know if there is a way to check the custom response body in unit tests?

I am aware that I could test that in integration tests.

**Comment by dj-nitehawk** [comment]
you'd have to do something like this:
```cs
var ep = Factory.Create<Endpoint>(ctx =>
{
    ctx.Response.Body = new MemoryStream();
});

await ep.HandleAsync(default);
ep.HttpContext.Response.Body.Position = 0;
using var sr = new StreamReader(ep.HttpContext.Response.Body);
var res = await sr.ReadToEndAsync();
```
basically, you'd have to setup a stream for the body. and then rewind the stream position before reading the stream.

**Comment by timbze** [comment]
That works, thank you!
