### ISSUE TITLE
Supporting application/xml as an output format and return a 406 not acceptable if the content-type is not supported.

### ISSUE THREAD

**Issue by JudeAlquiza** [FastEndpoints/FastEndpoints#363]
Hi,

Not sure if I just can't find the documentation on this but is it possible to return a 406 not acceptable if the content-type is not supported ? 

Also how can we support application/xml as an output format ? Is there something that is out of the box, or do we need to custom built our own ? 

Thanks!
Jude Alquiza.

**Comment by dj-nitehawk** [comment]
here's an example of such an extension method for a custom send function: https://github.com/FastEndpoints/FastEndpoints/issues/234#issuecomment-1246380441
