### ISSUE TITLE
Tags are not available in EndpointFilter

### ISSUE THREAD

**Issue by salixzs** [FastEndpoints/FastEndpoints#364]
```csharp
// Setting up
builder.Services.AddSwaggerDoc(settings =>
{
    settings.EndpointFilter(EndpointDocumentationFilter);
},
tagIndex: 0);

private static bool EndpointDocumentationFilter(EndpointDefinition endpoint)
{
    if (endpoint.EndpointTags != null && endpoint.EndpointTags.Contains("MyTag"))
    {
        return false;
    }
    return true;
}

// And in endpoint:
public override void Configure()
{
    Get("/MyUrl");
    Options(opts => opts.WithTags("MyTag"));
}
```

During runtime `EndpointFilter` gets endpoint object where `EndpointTags` is null, however in Swagger Docs Tags are actually used.

Could be nice to have ignoring possibility on endpoint configure level, like with `[OpenApiIgnore]` attribute on classic Controller Action uses.

**Comment by dj-nitehawk** [comment]
the `EndpointTags` have nothing to do with swagger tags which you add using `WithTags()`.
an endpoint is tagged like so:
```cs
    public override void Configure()
    {
        Get("/MyUrl");
        Tags("MyTag");
    }
```
which would then be available in `EndpointTags` property.
