### ISSUE TITLE
SendErrors is restrictive when considering that not all errors are ValidationErrors - FluentResults

### ISSUE THREAD

**Issue by kcadduk** [FastEndpoints/FastEndpoints#365]
Given that an endpoint needs to handle both requests and responses, the current implementation of SendErrors is *heavily* weighted towards problems on the request.

Full Disclosure, I am (trying) to use FluentResults to manage the errors that occur in the Application, Domain or Infrastructure layer. Calls to services within these layers return `Result` or `Result<T>`. 

Throwing Exceptions is expensive, so I try to avoid throwing unnecessary exceptions such as when a record cannot be found in the database. Sure, I could return null, but in other circumstances, null could mean two or three things.  Therefore, the Result class allows me to record each type of error that has occurred (usually one) lower in the stack, and pass them back up to the endpoint, which has some pre-determined logic to decide what to do with specific error types, or if it can't give a more appropriate response (400, 403, 409 etc) then as a last resort it will return 500. Error messages and formats are standardised and even objects required by the errors are captured, for full information relating to the problem.

There are lots of things that can go wrong, are not exceptional, and other processes up the stack should know about before continuing.

On with the problem. SendErrors simply send the _validation_ errors to the client. Which to me, means validation on the input. Errors that happened in my other layers, once the request was received, understood and validated are simply lost. It would be great if we could return some other (non-typed) response in the body. That doesn't require me to throw an exception because something happened that I expected could happen.

Something like 
```
    protected Task SendErrorsAsync(object response, int statusCode = 400, CancellationToken cancellation = default)
    {
        return HttpContext.Response.SendErrorsAsync(response, statusCode, Definition.SerializerContext, cancellation);
    }
```

Happy to share some specific code or a demo-repo if needed.

**Comment by dj-nitehawk** [comment]
you do have the option to write your own `SendErrors()` as an extension method targetting `IEndpoint` interface.
the downside to that would be you'd have to preface your call with `this.SendErrors...`

you'd be able to avoid that by extending/subclassing `Endpoint<TRequest,TResponse>` classes and adding your overload there.

would that do it?

**Comment by kcadduk** [comment]
I've arrived at the same result through trial and error. Its a work around. (`this.SendResult()`) but the end result is the same.

Writing the Endpoint class extensions, is a fair chunk of work, given the different options, including the mapping endpoint classes too (which sub-class Endpoint, and implement an interface).

All of the "logic" to handle Results would probably need to be implemented multiple (identical) times in many ResultExtension<TReq, TRes> classes, and I hate repeating myself. Again Extension Methods might help to reduce the DRY, but its not straight forward.

Taking the FluentResults aspect away. Could we look at this from the point of view I have which is, **Not all errors are validation errors. Could some way of reporting non-validation errors be implemented?** 

Putting FR back into the frame, It might make it easier to bridge the gap between FluentResults and this Library if I were able to report Errors as a response, Not validation errors, and not the response that the endpoint *ususally* makes.

**Comment by dj-nitehawk** [comment]
so does adding the following overload to the endpoint base class enable you to do what you want?
```cs
protected Task SendErrorsAsync(object response, int statusCode = 400, CancellationToken cancellation = default) {}
```
if so, that's an easy fix...

**Comment by kcadduk** [comment]
I think so, I also think it'd need a mapping function ("Interceptor"?) which could be set when configuring the library to intercept those responses and change the result to a specific code and object.

```
public class EndpointDiscoveryOptions()
{
    public Task<Action<object>>? SendErrorsInterceptor { internal get; set }
}
```

which would be used like this 
```
        serviceCollection.AddFastEndpoints(opt =>
        {
            opt.SendErrorsInterceptor = o =>
            {
                if (o is ResultBase and { IsFailed: true } failedResult)
                    await SendErrorsAsync("Standardized Error Message - failedResult.Error", StatusCodes.Status400BadRequest);
            };
        });
```

Run the "interceptor", before you start returning a response, check after the interceptor has run, whether a response has started, if so, do nothing, else return the original SendErrors request.

This means, I can pass in any error result, I don't have to worry (in the endpoint) about what type of error response I should be sending. That can be set at the application level.

**Comment by kcadduk** [comment]
Sure, i'll have a go.

I had another thought, which occurred  to me last night. We could simply allow for an interceptor on SendAsync. Which would do the same thing, Without having to create or amend any overloads of Endpoint.

1. When processing SendAsync(), look in the configuration for an interceptor that can handle that type
2. If none found, skip to 4
3. If found, run the interceptor
4. Check to see if a response has been returned
5. If yes, skip 6
6. Send the default SendAsync response.

Could even type the interceptors and SendAsync, so that its all strongly typed. Let me have a go at a PR. We can go from there.

**Comment by kcadduk** [comment]
#366 Opened for your review

**Comment by dj-nitehawk** [comment]
`v5.6.0.3-beta` has been pushed to nuget with the PR.
would like to see your `HandleAsync()` and `IResponseInterceptor` code with this in action.
if you can do a small sample repo and throw it up on github, i can link it from the documentation as an example on how to use FE together with FluentResults library. no big deal... only if you have some free time ;-)
thanks for the PR.

**Comment by kcadduk** [comment]
Absolutely. Let me see what space I get tomorrow. :)

**Comment by kcadduk** [comment]
Just another note, on testing with my actual project, its working a treat. 

One thing that would be great, is the ability to access the `Endpoint.Send.cs` methods as you have to basically write all response logic again. You seem only to be accessing public properties of the endpoint (At first glance endpoint base), and the `HttpContext`, so I think its do-able.

If they were extension methods, rather than partial methods, we could really be winning, you'd access them through `HttpResponse` and have to pass in an `EndpointBase`, plus the response, code and canx token.

Let me know your thoughts, and if you think its a go, I'll raise a separate issue.

**Comment by dj-nitehawk** [comment]
such extension methods already exist: https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Library/Extensions/HttpResponseExtensions.cs

this is for sending the responses from within the interceptor right?

if so, we already have the ability to do a similar thing when shorcircuiting from within pre-processors: https://fast-endpoints.com/docs/pre-post-processors#short-circuiting-execution

**Comment by SpaceOgre** [comment]
@dj-nitehawk I found myself in the same boat as kcadduk in that I would like to send custom errors that are not validation problems.

The solution here is not ideal for me, since I have created my own Endpoint class which extends the normal one. In this, I would just like to do: 
```csharp
var myCustomErrors = new ApiErrorResponse();
SendErrors(myCustomErrors, 500);
```
And I want to avoid adding an extra pipeline for this since it is not obvious for my developers how it works, I prefer if we can just hit F12(Go to definition) and follow our flow. 

I looked at using the ExtensionMethod for HttpContext but then I don't have access to the SerializerContext since that is private.

I could look into creating a PR for this if you think an overload for SendErrors are okay?

**Comment by dj-nitehawk** [comment]
@SpaceOgre i believe the new [TypedResults](https://fast-endpoints.com/docs/get-started#union-type-returning-handler) support would work for you. that way you can send whatever shape/response you like as with typical minimal apis.

there's also the `SendResultAsync` method for sending any `IResult`:
```cs
sealed class ApiErrorResponse : IResult
{
    public string ErrorMsg { get; set; }

    public async Task ExecuteAsync(HttpContext ctx)
    {
        await ctx.Response.SendAsync(this, 500, ...); //can pass down SerializerContext also
    }
}

sealed class SomeEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("error");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        await SendResultAsync(new ApiErrorResponse { ErrorMsg = "blah blah" });
    }
}
```

**Comment by SpaceOgre** [comment]
@dj-nitehawk I tried to get it to work with TypedResults but did not get all the way.

But the SendResultAsync might be a nice way to do it.

How would I get hold of the SerializerContext? I have not been able to figure that out :(

**Comment by dj-nitehawk** [comment]
nothing special there

```cs
[JsonSerializable(typeof(ApiErrorResponse))]
public partial class ApiErrorResponseCtx : JsonSerializerContext { }
```

```cs
await ctx.Response.SendAsync(this, 500, ApiErrorResponseCtx.Default);
```

**Comment by SpaceOgre** [comment]
@dj-nitehawk thanks, yeah that was not that hard.
