### ISSUE TITLE
DateTime query parameter binding to local time

### ISSUE THREAD

**Issue by frasermclean** [FastEndpoints/FastEndpoints#367]
I have a request DTO with properties binding to DateTime objects. The query string is using ISO 8601 strings such as "2023-02-28T13:00:00Z" The dates bind correctly, but they are coming in as local time.

Is this expected behaviour?

**Comment by dj-nitehawk** [comment]
apparantly that is the default behavior of the `DateTime` class in .net when parsing strings like these.

you can customize this behavior by registering a custom value parsing func in FE like this:

```cs
app.UseFastEndpoints(o =>
{
    o.Binding.ValueParserFor<DateTime>(s => new(
        DateTime.TryParse(
            s.ToString(),
            CultureInfo.InvariantCulture,
            DateTimeStyles.RoundtripKind,
            out var result),
        result));
});
```

more info here: https://fast-endpoints.com/docs/model-binding#custom-value-parsers

**Comment by frasermclean** [comment]
Thanks for the info and the awesome framework!
