### ISSUE TITLE
Endpoint Was Excluded in The Swagger Document After Enabling Versioning

### ISSUE THREAD

**Issue by Vincent-Lz-Zhang** [FastEndpoints/FastEndpoints#376]
Hi There,

My Program.cs is

global using FastEndpoints;
using FastEndpoints.Swagger;

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();

builder.Services.AddSwaggerDoc(maxEndpointVersion: 1, settings: s =>
{
    s.DocumentName = "Release 1.0";
    s.Title = "My API Ver1";
    s.Version = "v1.0";
});
var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints(c =>
{
    c.Versioning.Prefix = "v";
});

app.UseSwaggerGen();
app.Run();`

And I have an Endpoint class

using SP.API.SmartPakPolicy.Domain.Models;

namespace Api;

public class SampleEndpoint : Endpoint<MyRequest>
{
    public override void Configure()
    {
        Post("/api/user/create");
        Version(1);
        AllowAnonymous();
    }
    public override async Task HandleAsync(MyRequest req, CancellationToken ct)
    {
        var response = new MyResponse()
        {
            FullName = req.FirstName + " " + req.LastName,
            IsOver18 = req.Age > 18
        };
        await SendAsync(response, cancellation: ct);
    }
}

According to the document, the endpoint's version (which is 1) is not greater than 1, so it should be included,  what did I miss? Thanks a lot.

**Comment by Vincent-Lz-Zhang** [comment]
Okie, I finally understand how it works. All good.

**Comment by rthanga1** [comment]
Hello @Vincent-Lz-Zhang How did you fix it? I have the same issue now. I enable versioning in the Program.cs and the swagger is not listin any of my end points.

`app.UseFastEndpoints(c =>
{
    c.Versioning.Prefix = "v";
    c.Versioning.PrependToRoute = true;
    c.Versioning.DefaultVersion = 1;
});`
