### ISSUE TITLE
[Question] Unit testing an endpoint that uses SendBytesAsync

### ISSUE THREAD

**Issue by idormenco** [FastEndpoints/FastEndpoints#379]
Hi,
I have the following question(s): 

- Should we write unit tests for Endpoints with SendBytesAsync and check the resulted byte array or this should be an Integration/e2e test
- If yes, how can we obtain byte array sent in an unit test.

we can use this endpoint as example
 ```
public class Endpoint : EndpointWithoutRequest
{
    private static readonly byte[] content = Encoding.UTF8.GetBytes("abcdefghijklmnopqwstuvwxyz");

    public override void Configure()
    {
        Get("/test-cases/range");
        AllowAnonymous();
    }

    public override Task HandleAsync(CancellationToken ct)
    {
        return SendBytesAsync(content, contentType: "text/plain");
    }
}
```
```
    [Fact]
    public async Task ShouldReturnCorrectBytes()
    {
        // Arrange
        var endpoint = Factory.Create<Endpoint>();
        
        //Act
        await endpoint.HandleAsync(CancellationToken.None);
        
        // Assert
        endpoint...
    }
```

Best regards
// Ion

**Comment by dj-nitehawk** [comment]
it would be integration tests such as these:
https://github.com/FastEndpoints/FastEndpoints/blob/c9834c6cfadf4cfefd17194e71353910ced92d2c/Tests/IntegrationTests/FastEndpoints.IntegrationTests/WebTests/MiscTestCases.cs#L680-L734
