### ISSUE TITLE
Swagger Generation does not handle route pattern with colon `:`

### ISSUE THREAD

**Issue by ricksu978** [FastEndpoints/FastEndpoints#380]
## Given
Configure route pattern to include colon `:`
```csharp
public override void Configure()
{
    Post("/entities/{id}:action");
}
```

## Actual
Swagger UI - missing colon in route pattern
![image](https://user-images.githubusercontent.com/35659961/218345356-92e0b378-d8ca-420c-a21d-53cbea76b07a.png)

## Expect
Swagger UI - expecting route pattern displayed with colon
![image](https://user-images.githubusercontent.com/35659961/218345474-875051f7-93fc-42c9-ae3c-0495cd171465.png)

Note: This is just Swagger Generation bug, the endpoint is registered **_correctly_** with `/entities/{id}:action`, I have no problem calling the API with colon action using Postman

**Comment by dj-nitehawk** [comment]
pls try `v5.7.1.1-beta`
this is now supported.
thanks for reporting...
