### ISSUE TITLE
can I integrate IndetityServer5 to a fastendpoints based API

### ISSUE THREAD

**Issue by mawarnes** [FastEndpoints/FastEndpoints#381]
has anyone managed this?

**Comment by mawarnes** [comment]
[https://duendesoftware.com/products/identityserver](url)

**Comment by dj-nitehawk** [comment]
there was a discussion on discord regarding duende BFF and came out with the following to get it working with FE: [DuendeBFF.zip](https://github.com/FastEndpoints/FastEndpoints/files/10751840/DuendeBFF.zip)

you might be able to get some clues as to what to do for a regular backend without serving a frontend.

if not, you'd have to supply an asp.net minimal api project which i can help translate to fastendpoints.

if you have trouble getting that sorted, you might try joining our discord and ask there. there's definitely people there using identity server with FE.

**Comment by mawarnes** [comment]
thank you very much for the information, I'll join the discord, and keep you posted on any progress
