### ISSUE TITLE
Unit Test FastEndpoints exception

### ISSUE THREAD

**Issue by bhuvan1980** [FastEndpoints/FastEndpoints#382]
I am getting the exception when trying to run the unit test case as below: (getting error in line 42)
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/125615481/219509768-9145ce01-8f0b-43f7-b9d8-6f9124dd1bc8.png">

Getting error when trying to make call SendCreatedAtAsync() in below screenshot:

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/125615481/219510089-50037404-0ad7-4a73-9873-311940a13311.png">

I only get error when trying SendCreatedAtAsync(). For SendAsync() or SendNotFoundAsync(), it works fine. Please help.

**Error description:**
Message: 
    System.InvalidOperationException : Service provider is null on the current HttpContext! Set it yourself for unit tests.

  Stack Trace: 
    HttpResponseExtensions.SendCreatedAtAsync(HttpResponse rsp, String endpointName, Object routeValues, Object responseBody, JsonSerializerContext jsonSerializerContext, Boolean generateAbsoluteUrl, CancellationToken cancellation)
    HttpResponseExtensions.SendCreatedAtAsync[TEndpoint](HttpResponse rsp, Object routeValues, Object responseBody, Nullable`1 verb, Nullable`1 routeNumber, JsonSerializerContext jsonSerializerContext, Boolean generateAbsoluteUrl, CancellationToken cancellation)
    Endpoint`2.SendCreatedAtAsync[TEndpoint](Object routeValues, TResponse responseBody, Nullable`1 verb, Nullable`1 routeNumber, Boolean generateAbsoluteUrl, CancellationToken cancellation)
    CreateCompany.HandleAsync(CreateCompanyRequest req, CancellationToken ct) line 27
    CreateCompanyTests.CreateCompany_GivenValidCompany_ReturnsCompany() line 43
    --- End of stack trace from previous location ---

**Comment by dj-nitehawk** [comment]
it's a bit tricky to unit test endpoints that use `SendCreatedAt` since it requires mocking out a `LinkGenerator` and as well as populating the http context correctly. a basic unit test however can be done as follows:

https://github.com/FastEndpoints/FastEndpoints/blob/9d983c2dadad9c9d0f6e114934f25a26725abec1/Tests/UnitTests/FastEndpoints.UnitTests/WebTests/UnitTests.cs#L128-L135

to be able to properly check if the correct `Location` header value is returned, you should turn it in to an integration test.

**Comment by bhuvan1980** [comment]
It still gives same error. My changed code is below:

 private readonly CreateCompany _createCompany;
    private readonly Mock<ICompanyService> _mockCompanyService;
    private readonly CancellationToken _ct;
    public CreateCompanyTests()
    {
        var linkgen = new Mock<LinkGenerator>();
        _mockCompanyService = new Mock<ICompanyService>();
        _createCompany = Factory.Create<CreateCompany>
            (ctx =>
            {
                var services = new ServiceCollection();
                services.AddSingleton(linkgen);
                ctx.RequestServices = services.BuildServiceProvider();
            },
            _mockCompanyService.Object
            );
    }

**Comment by dj-nitehawk** [comment]
just tried the following and it works:
```cs
var linkgen = new Mock<LinkGenerator>().Object;

var ep = Factory.Create<Endpoint>(ctx =>
{
    var services = new ServiceCollection();
    services.AddSingleton(linkgen);
    ctx.RequestServices = services.BuildServiceProvider();
    ctx.Response.Body = new MemoryStream();
});

await ep.HandleAsync(default);

ep.HttpContext.Response.Body.Position = 0;
var msg = new StreamReader(ep.HttpContext.Response.Body).ReadToEnd();

var pass = msg == "{\"msg\":\"hello\"}";

Console.WriteLine("test passed: " + pass);
Console.Read();

public class Endpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendCreatedAtAsync("/get-company", new { id = 1 }, new { msg = "hello" });
    }
}
```
