### ISSUE TITLE
Proposal for HttpClientExtensions

### ISSUE THREAD

**Issue by SStapfer-privat** [FastEndpoints/FastEndpoints#383]
https://github.com/FastEndpoints/FastEndpoints/blob/9d983c2dadad9c9d0f6e114934f25a26725abec1/Src/Library/Testing/HttpClientExtensions.cs#L33

In our use cases we throw Exceptions if e.g. a user does not exist and want to forward them to the client (as NotAuthorized response).
Using your implementation it will first try to deserialize the response content which of course throws a JsonExceptions as the content is not TResponse but a string.

We solved it by first checking if the response was successful, and if not to return the response without deserializing:

```
if (!res.IsSuccessStatusCode || typeof(TResponse) == EmptyResponse)
{
    if (res.Content.Headers.ContentType?.MediaType == "text/plain")
    {
        res.ReasonPhrase = await res.Content.ReadAsStringAsync();
    }

    return (res, default);
}

TResponse? body;

try
{
    body = await res.Content.ReadFromJsonAsync<TResponse>();
}
catch (JsonException)
{
    var reason = $"[{res.StatusCode}] {await res.Content.ReadAsStringAsync()}";
    throw new InvalidOperationException(
        $"Unable to deserialize the response body as [{typeof(TResponse).FullName}]. Reason: {reason}");
}

return (res, body);

```

What is your opinion about this?

**Comment by dj-nitehawk** [comment]
looks alright at first glance.
is there a potential for breaking existing tests for people is the question 🤔
if there's a chance it could break our users tests, we could make this into a new overload maybe?
or let's add an optional argument to all the methods:
```cs
public static async Task<(HttpResponseMessage? response, TResponse? result)>
        POSTAsync<TRequest, TResponse>(this HttpClient client, 
                                       string requestUri, 
                                       TRequest request, 
                                       bool neverThrow = false) //add it here at the end
```
