### ISSUE TITLE
Custom Http Errors 

### ISSUE THREAD

**Issue by gstrainovic** [FastEndpoints/FastEndpoints#386]
What is the best solution to implement a custom http error message globally as described here? https://www.realworld.how/docs/specs/backend-specs/error-handling ?

**Comment by dj-nitehawk** [comment]
for customizing 4XX errors, see here: https://fast-endpoints.com/docs/configuration-settings#customizing-error-responses
for 5XX: https://fast-endpoints.com/docs/exception-handler#unhandled-exception-handler
