### ISSUE TITLE
How do I set response models to not be optional as typescript is saying a value can be undefined when it can never be the case.

### ISSUE THREAD

**Issue by rubenmamo** [FastEndpoints/FastEndpoints#388]
I'm using fast endpoints with a typescript client automatically generated from the Open API specification generated by Fast Endpoints.

I have response models which I know they will always have a value, however, currently the response models are being created with all fields being marked as nullable, for example:
```
    id?: string;
    name?: string;
    headerImage?: string;
``` 

my understanding is that this is happening because the Open API definition is created as per the below:
```
    "schemas": {
      "Response": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "headerImage": {
            "type": "string"
          }
        }
      },
```

I'd like to generate this definition instead:
```
    "schemas": {
      "Response": {
        "type": "object",
        "required": [
          "id",
          "name",
        ],
        "additionalProperties": false,
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "headerImage": {
            "type": "string"
          }
        }
      },
```

Is it possible to create this OpenAPI definition?

**Comment by dj-nitehawk** [comment]
looks like this is a known issue with nswag+oas3+typescript: 
https://github.com/RicoSuter/NSwag/issues/3110

and the current workaround seems to be to use a custom schema processor to mark all non-nullable properties of the schema as required.

```cs
public class MarkNonNullablePropsAsRequired : ISchemaProcessor
{
    public void Process(SchemaProcessorContext context)
    {
        foreach (var (_, prop) in context.Schema.ActualProperties)
        {
            if (!prop.IsNullable(SchemaType.OpenApi3))
                prop.IsRequired = true;
        }
    }
}
```

which you can register like this:
```cs
builder.Services.AddSwaggerDoc(s =>
{
    s.SchemaProcessors.Add(new MarkNonNullablePropsAsRequired());
});
```

which seems to solve it for typescript client generation.

i'm wondering whether i should incorporate this into FE so it'll be on by default.
would there be some unforeseen issues? why doesn't nswag do this by default?
let me know your thoughts.

**Comment by rubenmamo** [comment]
Thanks for the update. I can confirm that the code above is a valid workaround, however, I think there will be some cases where this wouldn't work, particularly if you don't enable the nullable reference types feature of C#8.
From what I can gather, the IsNullable function listed above doesn't return true for arrays, strings or reference types which means that unless you enable nullable reference types this functionality will probably cause issues down the line in clients.
I will do some further investigation and will update the issue with any information.

**Comment by austins** [comment]
This works well for me too. I have nullable reference types enabled. I wonder if it would be better to include it in the library as a option that can be toggled.

**Comment by austins** [comment]
Yes, this is useful for me since I have nullable reference types enabled. The processor above allows the NSwag TS client generator to generate the correct required props. Perhaps it could be an option in the library to toggle.

**Comment by dziedrius** [comment]
Nice addition of `MarkNonNullablePropsAsRequired`, worth adding to documentation in my opinion :)

**Comment by dj-nitehawk** [comment]
@dziedrius 
[done...](https://dev.fastendpoints-doc-site.pages.dev/docs/swagger-support#non-nullable-properties-as-required)
