### ISSUE TITLE
Endpoint returns 404 for unauthorized user

### ISSUE THREAD

**Issue by Reikooters** [FastEndpoints/FastEndpoints#389]
Hi there,

I set up policies as per the documentaiton here: https://fast-endpoints.com/docs/security#endpoint-authorization

I'm using the latest beta version of FastEndpoints from Nuget.

I have a "User" and an "Admin" policy that looks like this

```csharp
// Authorization Policies
builder.Services.AddAuthorization(options =>
{
    options.AddPolicy("User", policy =>
    {
        policy.RequireAuthenticatedUser();

        // Check user role
        policy.RequireAssertion(c =>
        {
            return c.User.IsInRole("User") || c.User.IsInRole("Admin");
        });
    });

    options.AddPolicy("Admin", policy =>
    {
        policy.RequireAuthenticatedUser();

        // Check user role
        policy.RequireAssertion(c =>
        {
            return c.User.IsInRole("Admin");
        });
    });
});
```

And I have an example endpoint configured like this

```csharp
public sealed class MeEndpoint : EndpointWithoutRequest
{
    private readonly UsersRepository _usersRepository;

    public MeEndpoint(UsersRepository usersRepository)
    {
        _usersRepository = usersRepository;
    }

    public override void Configure()
    {
        Get("/user/me");
        SerializerContext(MeContext.Default);
        Policies("Admin");
    }

    ...

}
```

The endpoint works fine when the logged in user has the Admin role, however, when they don't, the endpoint returns 404 Not Found, when I kind of expected it to return 403 Forbidden.

This means when the user's session expires and they are logged out, the endpoint now returns 404.

How can I best determine the difference on the front-end, between a bug in the front-end code which is calling the wrong url resulting in a 404 which needs to be fixed, or that the user just needs to be redirected to the login screen so they can log back in to continue?

I don't think it should make a difference, but I'm using cookie authentication as per https://fast-endpoints.com/docs/security#cookie-based-authentication

**Comment by dj-nitehawk** [comment]
that is the default bahavior of the cookie middlware in asp.net.
it sends a redirect response automatically to the error page which in most api's wouldn't exist.
so you'd have to override that behavior with something like this:
```cs
builder.Services.AddCookieAuth(validFor: TimeSpan.FromMinutes(10), o =>
{
    o.Events = new CookieAuthenticationEvents()
    {
        OnRedirectToLogin = (ctx) =>
        {
            if (ctx.Request.Path.StartsWithSegments("/api") && ctx.Response.StatusCode == 200)
            {
                ctx.Response.StatusCode = 401;
            }
            return Task.CompletedTask;
        },
        OnRedirectToAccessDenied = (ctx) =>
        {
            if (ctx.Request.Path.StartsWithSegments("/api") && ctx.Response.StatusCode == 200)
            {
                ctx.Response.StatusCode = 403;
            }
            return Task.CompletedTask;
        }
    };
});
```

**Comment by Reikooters** [comment]
Thanks for explaining. And your code example works great. Thanks a lot for your help.

**Comment by irfankhanteo** [comment]
I was facing a 404 Not Found issue when accessing protected endpoints using Identity and JWT together with FastEndpoints.

Initially, I had only set:

options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
However, this alone wasn't enough. The issue was resolved when I also set:


options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
So the final working configuration became:

services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
});
