### ISSUE TITLE
An argument out of range exception is thrown when invalid JSON is passed to a FE endpoint.

### ISSUE THREAD

**Issue by hoxhaerin** [FastEndpoints/FastEndpoints#391]
This line here:
https://github.com/FastEndpoints/FastEndpoints/blob/baab0c41d1a6884e6cf2ff82a654fcfc7ad400dd/Src/Library/Endpoint/Endpoint.cs#L106
more specifically this part: [2..], throws an ArgumentOutOfRangeException | startIndex cannot be larger than length of string. (Parameter 'startIndex') when you add an extra comma at the end of the JSON request.

```
{
  "code": "A001",
  "name": "",
  "marketingName": "fsa",
}
```

I'd open a PR myself but I don't know why you have added that index there and how you'll want to handle it, so I'm just leaving this here.

![image](https://user-images.githubusercontent.com/29415274/221728191-a56f74df-138d-48db-b283-845fd815ebf2.png)

**Comment by dj-nitehawk** [comment]
fixed in `v5.7.2.8-beta`
thanks for reporting!
