### ISSUE TITLE
Any advice on how to test an endpoint that requires authentication

### ISSUE THREAD

**Issue by shawndewet** [FastEndpoints/FastEndpoints#392]
I've reviewed the documentation [here ](https://fast-endpoints.com/docs/integration-unit-testing#integration-testing) and have implemented my integration tests accordingly.  It works brilliantly.

However, I am now stuck on trying to implement my first integration test for an endpoint that does NOT have `AllowAnonynous()`.  The test fails with the error:
`System.InvalidOperationException : Unable to deserialize the response body as [MyResponseTypeHere]. Reason: [Unauthorized]`

Any advice as to how I can go about passing authentication info to such a test?

**Comment by dj-nitehawk** [comment]
you just need to emulate an authenticated user, for example for JWT auth,  by adding the auth header with the token to the http client like so:
https://github.com/FastEndpoints/FastEndpoints/blob/df18d69603f041225d25e3c32e0992631a58d5cc/Tests/IntegrationTests/IntegrationTests.Shared/Fixtures/EndToEndTestBase.cs#L49

you could also add the header per request, but that's gonna be a bit more verbose. so what i typically do is i create 1 http client per each type of user in my system, such as here:

https://github.com/FastEndpoints/FastEndpoints/blob/df18d69603f041225d25e3c32e0992631a58d5cc/Tests/IntegrationTests/IntegrationTests.Shared/Fixtures/EndToEndTestBase.cs#L23-L29

or a more simpler way here:
https://github.com/FastEndpoints/FastEndpoints/blob/4cab0fe73b2429edb4c30bc14e2c47dd712057b3/Test/Setup.cs#L20-L22

if you need further help, just send a small repro project through and i'll update it to add an authenticated http client (as it would depend on how you've setup your testing infrastructure).

**Comment by shawndewet** [comment]
Thanks a mil @dj-nitehawk!  Brilliant.
For those interested in another approach, I came across [this](https://khalidabuhakmeh.com/testing-aspnet-core-fastendpoints) post that injects a fake user directly into the http context.

**Comment by dj-nitehawk** [comment]
yeah that would work too. thanks for that!
