### ISSUE TITLE
Proposal for Claim's values validation

### ISSUE THREAD

**Issue by roddone** [FastEndpoints/FastEndpoints#393]
Hi, 

Checking th docs we found the methods [`Claims()` and `ClaimsAll()`](https://fast-endpoints.com/docs/security#claims-method) to ensure an endpoint is accessible only if the current user has the specified claims.

It works well, but in some scenarios we also need to check one of the claim's value and it does not seem possible with the current 'Claims' helpers.
Currently, we achieve that with Preprocessors (or middlewares, helpers, or whatever).

What would you think of adding new helpers (maybe "ClaimsValue()" and "ClaimsValueAll()") that allows to specify a claim AND a value to check ? The challenge would be to allow to check a static value or dynamically at runtime (via callback actions maybe ?)

If you find this relevant, I can try a PR to suit this need.

Regards,

Romain.

**Comment by dj-nitehawk** [comment]
in `v5.7.2.10-beta` you can now do stuff like this:
```cs
public override void Configure()
{
    Get("test");
    Policy(b => b
        .RequireUserName("Administrator")
        .RequireClaim("UserId", "001") //checking claim value
        .RequireAssertion(ctx =>
        {
            return ctx.User.ClaimValue("Email") == "admin@company.com";
        }));
}
```

**Comment by roddone** [comment]
Nice ! I'll give it a try, thanks ;)
