### ISSUE TITLE
More than one validator was found for the request dto [Project.Request]. Specify the exact validator to register using the `Validator()` method in endpoint configuration.

### ISSUE THREAD

**Issue by sandelirious7** [FastEndpoints/FastEndpoints#394]
Though I've explicitly mentioned the validator in my Endpoint, I still see this error in 5.7.0

CreateEndpoint.cs
`public override void Configure()
        {
            Verbs(Http.POST);
            Routes("/streaming");
            AllowAnonymous();
            Description(
                req =>
                req
                    .Accepts<Request>("application/json")
                    .Produces((int)HttpStatusCode.Accepted)
                    .Produces<ErrorResponse>((int)HttpStatusCode.BadRequest, "application/json+problem")
                    .Produces<ErrorResponse>((int)HttpStatusCode.NotFound, "application/json+problem"),
                    clearDefaults: true
            );
            Validator<CreateRequestValidator>();
        }`

UpdateEndpoint.cs
`public override void Configure()
        {
            Verbs(Http.PATCH);
            Routes("/streaming");
            AllowAnonymous();
            Description(
                req =>
                req
                    .Accepts<Request>("application/json")
                    .Produces((int)HttpStatusCode.Accepted)
                    .Produces<ErrorResponse>((int)HttpStatusCode.BadRequest, "application/json+problem")
                    .Produces<ErrorResponse>((int)HttpStatusCode.NotFound, "application/json+problem"),
                    clearDefaults: true
            );
            Validator<UpdateRequestValidator>();
        }`
        
`public class CreateStreamingDrupalAssetsRequestValidator : Validator<Request>
{
    public CreateRequestValidator()
    {
        RuleFor(req => req.Doc.Name)
            .NotNull()
            .NotEmpty()
            .WithMessage("Name is required");
    }
}

public class UpdateRequestValidator : CreateRequestValidator
{
    public UpdateStreamingDrupalAssetsRequestValidator() : base()
    {
        RuleFor(req => req.Doc.Uuid)
            .NotNull()
            .NotEmpty()
            .WithMessage("UUID is required");
    }
}`

**Comment by dj-nitehawk** [comment]
pls upgrade to `5.7.2.12-beta`
and do validator inheritance like shown below:
```cs
public class Update : Endpoint<Request>
{
    public override void Configure()
    {
        Post("/streaming");
        AllowAnonymous();
        Description(x => x
            .ProducesProblemFE(400)
            .ProducesProblemFE(404));
        Validator<UpdateRequestValidator>();
    }

    public override async Task HandleAsync(Request req, CancellationToken ct)
    {
        await SendAsync(req);
    }
}

public class CreateRequestValidator : Validator<Request>
{
    public CreateRequestValidator()
    {
        RuleFor(req => req.Doc.Name)
            .NotEmpty().WithMessage("Name is required");
    }
}

public class UpdateRequestValidator : Validator<Request>
{
    public UpdateRequestValidator()
    {
        Include(new CreateRequestValidator()); //this is how you inherit rules written in other validators
        RuleFor(req => req.Doc.Uuid)
            .NotEmpty().WithMessage("UUID is required");
    }
}
```
