### ISSUE TITLE
Bug with parallelism and multiple preprocessors

### ISSUE THREAD

**Issue by VictorioBerra** [FastEndpoints/FastEndpoints#395]
Reproduction - https://github.com/VictorioBerra/FastEndpoints-Possible-PreProcessors-XUnit-Bug

Short explanation:

When using XUnit with multiple test classes that inherit from `IClassFixture<CustomWebAppFac<Program>>`, some of the tests fail when multiple pre-processors have been configured on an endpoint.

I created a new project with `dotnet new fastendpoints --name MaybeBugFEXunit`. I replaced the test code with code that looks more like the [Microsoft](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0#customize-the-client-with-withwebhostbuilder) and [FE docs](https://fast-endpoints.com/docs/integration-unit-testing#route-less-testing) (XUnit, ITestFixture, WebAppFactory, etc.). Finally, I added a couple sample PreProcessors.

To Reproduce:

1. Clone my [project](https://github.com/VictorioBerra/FastEndpoints-Possible-PreProcessors-XUnit-Bug)
2. Click "Run All" in Visual Studio Test Explorer
3. See either `TestClass1` or `TestClass2` will be marked as failed.
4. Comment out or delete the PreProcessors in `IndexEndpoint/Endpoint`
5. Click "Run All" in Test Explorer
6. All tests pass!

**Comment by dj-nitehawk** [comment]
thanks for the repro. made my life so much easier ;-)
issue has been fixed in `5.7.2.13-beta`
pls give it a go and report back.
cheers!
