### ISSUE TITLE
Request: Extension for Visual Studio Code

### ISSUE THREAD

**Issue by stanspotts** [FastEndpoints/FastEndpoints#397]
Title kinda says it all :)

**Comment by drilko** [comment]
@stanspotts Hey :)
I've released a preview version of vs code extension.
Just search for FastEndpoints in the marketplace.
It's just snippets for now but I plan on adding code generation in upcoming versions.
I would love some feedback tho :)

**Comment by dj-nitehawk** [comment]
@drilko gave it a try. seems to be working great. i think it's safe to remove the `preview` flag from the vsix pkg. also linked to the marketplace from the scaffolding [doc page](https://fast-endpoints.com/docs/scaffolding#code-snippets) and credited you in the latest [release notes](https://github.com/FastEndpoints/FastEndpoints/releases/tag/v5.14). thanks again for your contribution mate!
