### ISSUE TITLE
How to support Cookie and Jwt authentication at the same time?

### ISSUE THREAD

**Issue by maurosampietro** [FastEndpoints/FastEndpoints#398]
I found examples on Microsoft documentation, 

builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(JwtBearerDefaults.AuthenticationScheme,
        options => builder.Configuration.Bind("JwtSettings", options))
    .AddCookie(CookieAuthenticationDefaults.AuthenticationScheme,
        options => builder.Configuration.Bind("CookieSettings", options));

But can’t find a way using fast endpoints extension methods. 

Can you please provide an example that shows how it’s done?

Thank you

**Comment by dj-nitehawk** [comment]
here you go:
```cs
var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddCookieAuth(validFor: TimeSpan.FromMinutes(60));
builder.Services.AddJWTBearerAuth("_TokenSigningKey_"); //this becomes the default scheme
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthentication();
app.UseAuthorization();
app.UseFastEndpoints();
app.UseSwaggerGen();
app.Run();

public class LoginEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Post("login");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        Action<UserPrivileges> privileges = p =>
        {
            p.Permissions.Add("some_permission");
            p.Roles.Add("some_role");
            p["some_claim"] = "claim_value";
        };

        await CookieAuth.SignInAsync(privileges);

        var jwtToken = JWTBearer.CreateToken(
                signingKey: "_TokenSigningKey_",
                expireAt: DateTime.UtcNow.AddDays(1),
                priviledges: privileges);

        await SendAsync(jwtToken);
    }
}

public class SecretEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("secret");
        Permissions("some_permission");
        Roles("some_role");
        Claims("some_claim");
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync(User.ClaimValue("some_claim")!);
    }
}
```

**Comment by dj-nitehawk** [comment]
updated my sample code above. now it works with the combined auth scheme like you want.

**Comment by Nodios** [comment]
For me, this example was not working, the default schema was not being used. So I had to update the `AddAuthentication` method like this:

```
builder.Services.AddAuthentication(o =>
{
    o.DefaultScheme = "JWT_OR_COOKIE";
    o.DefaultAuthenticateScheme = "JWT_OR_COOKIE";
})
.AddPolicyScheme(...)
```
Defining `DefaultAuthenticateScheme` seemed to do the trick. Another approach would be to define auth schema on endpoint level like this:

```
public override void Configure()
{
    // ...
    AuthSchemes("JWT_OR_COOKIE");
}
```

**Comment by maurosampietro** [comment]
Thanks i will try this out!The other suggested solutions did not work for me either. I had the impression they were not actually trying what they suggested and did not insist further On 1 Apr 2023, at 19:48, Dino Repac ***@***.***> wrote:﻿
For me, this example was not working, the default schema was not being used. So I had to update the AddAuthentication method like this:
builder.Services.AddAuthentication(o =>
{
    o.DefaultScheme = "JWT_OR_COOKIE";
    o.DefaultAuthenticateScheme = "JWT_OR_COOKIE";
})
.AddPolicyScheme(...)

Defining DefaultAuthenticateScheme seemed to do the trick. Another approach would be to define auth schema on endpoint level like this:
public override void Configure()
{
    // ...
    AuthSchemes("JWT_OR_COOKIE");
}

**Comment by dj-nitehawk** [comment]
updated the sample code in https://github.com/FastEndpoints/FastEndpoints/issues/398#issuecomment-1455387227
