### ISSUE TITLE
No service for type 'Microsoft.AspNetCore.Authentication.IAuthenticationService' has been registered.

### ISSUE THREAD

**Issue by iamtheprotocol** [FastEndpoints/FastEndpoints#399]
I am getting "No service for type 'Microsoft.AspNetCore.Authentication.IAuthenticationService' has been registered." when trying to use PreProcessAsync to do API Key Authentication through request header:

SecurityProcessor.cs :

using FluentValidation.Results;
public class SecurityProcessor<TRequest>: IPreProcessor<TRequest> 
{   
    public Task PreProcessAsync(TRequest req, HttpContext ctx, List<ValidationFailure> failures, CancellationToken ct)
    {
        var apiId = ctx.Request.Headers["x-api-key"].FirstOrDefault();

        if (apiId == null)
        {
            failures.Add(new("MissingHeaders", "The [x-api-key] header needs to be set!"));
            return ctx.Response.SendErrorsAsync(failures); //sending response here
        }

        if (apiId != "12345")
            return ctx.Response.SendForbiddenAsync(); //sending response here

        return Task.CompletedTask;
    }
}

Endpoint.cs :

public class MyRequest
{

}
public class MyResponse
{
    public string FullName { get; set; }

}

public class MyEndpoint : Endpoint<MyRequest>
{
    public override void Configure()
    {
        Get("/api/user");
        PreProcessors(new SecurityProcessor<MyRequest>());

    }

    public override async Task HandleAsync(MyRequest req, CancellationToken ct)
    {
        var response = new MyResponse()
        {
            FullName = "John Doe"
        };
        Console.WriteLine("inside");
        await SendAsync(response);
    }
}

Program.cs : 

global using FastEndpoints;

var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddAuthorization();

var app = builder.Build();
app.UseAuthorization();
app.UseAuthentication();
app.UseFastEndpoints();
app.Run();

**Comment by dj-nitehawk** [comment]
a pre-processor won't be a good fit for this purpose because they are not executed when the incoming request is not authenticated and the endpoind doesn't `AllowAnonymous()`.

the recommended approach to api key authentication is this: https://github.com/FastEndpoints/FastEndpoints/issues/83#issuecomment-1088794792

however you could make a pre-processor work by adding `AllowAnonymous()` to the endpoint if you really want.
