### ISSUE TITLE
Swagger includes [FromHeader] in Json Body for POS/PUT request

### ISSUE THREAD

**Issue by ureymutuale** [FastEndpoints/FastEndpoints#400]
is it possible to exclude the headers properties from the JSON body ?
I tried adding the [JsonIgnore] but then the property is not visible in the header nor in the body.

<img width="1458" alt="Screenshot 2023-03-08 at 12 18 40 AM" src="https://user-images.githubusercontent.com/3835222/223578057-43a46b3f-0290-4a84-8f35-83a53d8649e1.png">

```
public class Request
{
    [FromHeader("tenant-id", IsRequired = false)]
    public string TenantID { get; set; }

    public string OrderID { get; set; }

public string Reference { get; set; }
}

public class Response
{
    public string Message => "ok!";
}

public class Endpoint : Endpoint<Request, Response>
{
    public override void Configure()
    {
        Post("/sales/orders/retrieve/{@id}", r => new { r.OrderID });
        PreProcessors(new SecurityProcessor<Request>());
        AllowAnonymous();
        Tags("orders");
    }

    public override Task HandleAsync(Request r, CancellationToken c)
    {
        return SendAsync(Response);
    }
}
```

**Comment by dj-nitehawk** [comment]
there's a property on the attribute called `RemoveFromSchema`:
https://github.com/FastEndpoints/FastEndpoints/blob/82779c2a65355dcf9ce9676015ee3ce325ec31eb/Src/Attributes/Attributes/FromHeaderAttribute.cs#L19-L22

i believe that's what you're looking for.
