### ISSUE TITLE
Swagger generates empty request schemas

### ISSUE THREAD

**Issue by Shepardeon** [FastEndpoints/FastEndpoints#404]
Hi! 
When using FastEndpoint, I'm not able to get a non empty request schema with Swagger.
For example, if I create the following endpoint:
```cs
internal class MyRequest
{
    public int SomeId { get; set; }
}

internal class MyEndpoint : Endpoint<MyRequest>
{
    // Configure/HandleAsync ...
}
```

Swagger will produce an empty schema despite the expectation to have a schema with `SomeId` defined in it.
![image](https://user-images.githubusercontent.com/15271735/224297402-fa5a5229-7af8-4bd6-b0df-7d52ae47d9b7.png)

Is there any way to achieve the outcome I want? This is would be useful as I'm using NSwag, which relies on the schema to generate Typescript interfaces.

**Comment by dj-nitehawk** [comment]
i presume this is a GET endpoint?

if so, all request dto properties get transformed into query string parameters in the swagger document. so there is no request schema for that endpoint. yes by default there would be an empty `MyRequest` schema, which you can get rid of as mentioned here: https://fast-endpoints.com/docs/swagger-support#removing-empty-schema

if memory serves me right, this won't be an issue for client generation as `SomeId` would be generated as an `int` method argument in the generated client.

let me know if that doesn't do it and i'll look in to it further...

**Comment by Shepardeon** [comment]
Hi, can confirm, after enabling client class and interface generation with nswag I'm getting a `MyEndpoint(SomeId: number)` method, so I think this should workout.

I think I was weirded out by the fact I was expecting something that was looking more alike to the backend code with methods taking Request objects rather than every arguments of the request.
