### ISSUE TITLE
Request JsonPropertyName doesn't map to object property

### ISSUE THREAD

**Issue by developer82** [FastEndpoints/FastEndpoints#406]
I have a request object that I have mapped with a `JsonPropertyName` annotation.

```
public class LoginRequest
{
    public string? Username { get; set;}
    public string? Password { get; set;}
    public string? RefreshToken { get; set;}
    
    [JsonPropertyName("fp")]
    public string? Fingerprint { get; set; }
}
```

The issue is that when I send a request with a JSON body that contains the "fp" property it doesn't populate the value but if I send "fingerprint" then it does.

Is that a bug? If not, what am I missing?

**Comment by dj-nitehawk** [comment]
make sure the attribute is from system.text.json and not the one from
newtonsoft.

**Comment by developer82** [comment]
Checked now, it's from `System.Text.Json.Serialization`

I changed `JsonPropertyName` to `[BindFrom("fp")]` and it works.

What is the correct way to do this?

**Comment by dj-nitehawk** [comment]
it depends on what the source of the data is. see this page under
"mismatched property names" for each source.
https://fast-endpoints.com/docs/model-binding#mismatched-property-names

**Comment by developer82** [comment]
So according to the documentation what I did with `JsonPropertyName` should have worked...

**Comment by dj-nitehawk** [comment]
it does work: https://streamable.com/a6yv1b

`[BindFrom("fp")]` working for you sounds like you're trying to bind it from some other source (where [BindFrom] is supported) and not from the json body of the request.

if you're still having trouble pls send through a self isolated/minimalistic repro i can debug.

as far as i can tell, there's no problem.
