### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by yarseyah** [FastEndpoints/FastEndpoints#407]
Not an issue with FastEndpoints itself, but a query, is the Discord server closed? Everything seems to be in 'archive' status.

**Comment by dj-nitehawk** [comment]
all the old chatrooms/channels have been archived.

we only have a single forum on discord now.

https://discord.com/channels/933662816458645504/1071471869552771203

if it's not displaying for you, maybe your discord app needs an update.

**Comment by dj-nitehawk** [comment]
this is the new invite link if you can't get in with the old invite links:
https://discord.gg/ARGPxTukpr
