### ISSUE TITLE
No extension method available for HttpClient and file Upload (Integration Test)

### ISSUE THREAD

**Issue by DCP-JUNG** [FastEndpoints/FastEndpoints#409]
Hello,
Can you try and confirm or not the following situation ?

### 1. Describe the bug
Using file upload feature on my endpoint, then trying to run an integration test.
Extension method POSTAsync<TEndpoint, TRequest, TResponse> is returning 415 (related to wrong media-type).

![image](https://user-images.githubusercontent.com/71648841/225685596-fc338b05-78fa-4261-9df5-bad24944b386.png)

### 2. To Reproduce

In endpoint :

```
        Post("/mowers/execute");
        AllowFormData();
        AllowAnonymous();
        //Set anything you want here
```

Also Request and Response examples :

```
internal sealed record ExecuteFileRequest(IFormFile File);
internal sealed record ExecuteFileResponse(IReadOnlyList<string> Outputs);
```

Then in integration test, using WebApplicationFactory use
`await _client.POSTAsync<TEndoint, TRequest, TResponse>(youRequest);`

### 3. Expected behavior

In integration test, be able to access an extension method supporting media-type multipart/form-data

### 4. Actual behavior

There is no POSTAsync extension method to pass MultipartFormDataContent

### 5. Idea

```
internal static class HttpClientExtension
{
    internal static async Task<TestResult<TResponse>> POSTFileAsync<TEndpoint, TResponse>(this HttpClient client, MultipartFormDataContent file)
    {
        var ep = IEndpoint.TestURLFor<TEndpoint>();
        var rsp = await client.PostAsync(ep, file);

        try
        {
            var res = await rsp.Content.ReadFromJsonAsync<TResponse>(SerOpts.Options);
            return new TestResult<TResponse>(rsp, res!);
        }
        catch (JsonException)
        {
            var reason = $"[{rsp.StatusCode}] {await rsp.Content.ReadAsStringAsync()}";
            throw new InvalidOperationException($"Unable to deserialize the response body as [{typeof(TResponse).FullName}]. Reason: {reason}");
        }
    }
}
```

How to use :

```
           await using var fileStream = File.OpenRead(relativePath);
            using var streamContent = new StreamContent(fileStream);
            using var formData = new MultipartFormDataContent();
            formData.Add(streamContent, "file", Path.GetFileName(fileStream.Name));

            var (httpResponse, result) = await _client.POSTFileAsync<ExecuteFileEndpoint, ExecuteFileResponse>(formData);
```

### Other suggestion : 
=> Do not hide JsonException, and do not replace by InvalidOperationException with reason to increase devex and access full stack trace.
=> Add one more extension to upload file without response body (204 No content support)

7. Versions: 5.8.0

**Comment by dj-nitehawk** [comment]
checkout `5.8.0.4-beta`
took a slightly different approach and now you can do the following.
basically by saying `sendAsFormData: true`, the request dto gets automatically converted to a `MultipartFormDataContent`
https://github.com/FastEndpoints/FastEndpoints/blob/be153240f93696f321f416bd04291993c822615f/Tests/IntegrationTests/FastEndpoints.IntegrationTests/WebTests/MiscTestCases.cs#L704-L731
