### ISSUE TITLE
Ability to execute an `ICommand` non-concrete command type.

### ISSUE THREAD

**Issue by joakimjohanssn** [FastEndpoints/FastEndpoints#411]
Hi, I'm running into an issue when I'm not using a concrete type to call the `ExecuteAsync()` method on a command. Like this:
```
ICommand myCommand = new MyCommand(); // MyCommand : ICommand {}
await myCommand.ExecuteAsync();
// Throws InvalidCastException
```
An `InvalidCastException` is thrown, because of this cast in the `ExecuteAsync()` [extension method](https://github.com/FastEndpoints/FastEndpoints/blob/3f45f64dc25f409b0cd0cf279560bdbc6e46efe0/Src/Library/Messaging/Commands/CommandExtensions.cs#L22):
```
(ICommandHandler<TCommand>)handler
```
since the generic type parameter `TCommand` will have the value of `ICommand` and not the concrete command type that the handler is expecting.

What I want to be able to do is to parse a message and to map it to a command. Here's an example,  lets say we have a method `GetCommand(string commandType)` that instantiates a command based on the input paramter and returns an `ICommand`. Then this code,
```
var command = GetCommand("some-command");
await command.ExecuteAsync();
```
will not work. 

A workaround is to use `ICommand<TResult>` instead (and just discard the return value) since in this case the type of the command is not used as a type paramater to the extension method. However a similar situation arises if one uses a common base class for different return types.

I believe that a fix could be to implement the `ICommand.ExecuteAsync` method similar to how the `ExecuteAsync()` for `ICommand<TReturn>` is implemented, using `MakeGenericOf` and a `CommandHandlerExecutorOf1` type:
```
internal static readonly Type CommandHandlerExecutorOf1 = typeof(CommandHandlerExecutor<>);
```
Version 5.8.0.0

**Comment by dj-nitehawk** [comment]
> I believe that a fix could be to implement the `ICommand.ExecuteAsync` method similar to how the `ExecuteAsync()` for `ICommand<TReturn>` is implemented, using `MakeGenericOf` and a `CommandHandlerExecutorOf1` type

would you like to have a crack at a PR?
or you're gonna have to wait until i can find some free time to look in to this ;-)

**Comment by joakimjohanssn** [comment]
Thanks for your reply, I gave it a try here: https://github.com/FastEndpoints/FastEndpoints/pull/413
