### ISSUE TITLE
Request: ValidationFailure return also ErrorCode

### ISSUE THREAD

**Issue by Mewriick** [FastEndpoints/FastEndpoints#412]
Hi,

can you also add into response with validation errors property `ErrorCode`?

Thanks

**Comment by dj-nitehawk** [comment]
sorry your question doesn't make much sense.
pls explain further with some code if possible.
thanks!

**Comment by Mewriick** [comment]
Object `ValidationFailure` in [FluentValidation](https://github.com/FluentValidation/FluentValidation) package has property `ErrorCode`. https://github.com/FluentValidation/FluentValidation/blob/7604dc9114183aa302e1374e5a96dbfdb42a659d/src/FluentValidation/Results/ValidationFailure.cs#L81

But FastEndpoints does not include this property where some validation fails only `ErrorMessage` is present. Can `ErrorCode` property be also included in `BadRequest` response?

**Comment by dj-nitehawk** [comment]
you can customize the error response builder behavior with something like this if you want:
```cs
app.UseFastEndpoints(c =>
{
    c.Errors.ResponseBuilder = (failures, _, statusCode) =>
    {
        return new ErrorResponse()
        {
            StatusCode = statusCode,
            Errors = failures
                .GroupBy(f => f.PropertyName)
                .ToDictionary(
                    g => g.Key,
                    g => g.Select(f => $"Code: [{f.ErrorCode}] Message: [{f.ErrorMessage}]").ToList())
        };
    };
});
```
documented here: https://fast-endpoints.com/docs/configuration-settings#customizing-error-responses
