### ISSUE TITLE
415 Unsupported Media Type application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by ArcaneTSGK** [FastEndpoints/FastEndpoints#414]
FastEndpoints v5.8.0
.NET 6

When attempting to POST using `application/x-www-form-urlencoded` the request is not processed. 

Using AllowFormData() in the Configure() method allows for multipart/form-data but not `application/x-www-form-urlencoded`

It should be possible to accept requests containing form data as outlined in the fast endpoints documentation https://fast-endpoints.com/docs/model-binding#from-form-fields

I also tried a custom request binder but received the same result.

Here is an example DTO

```
public class DocumentTransactionRequest
{
  public string TransactionReference { get; init; } = default!;
  public string TransactionDate { get; init; } = default!;
}
```

Endpoint
```
public class TransactionCallback : Endpoint<DocumentTransactionRequest>
{
  public override void Configure()
  {
    Post($"/{ApiEndpoints.V1.Transaction.TransactionCallback}");
    AllowAnonymous();
  }
  // HandleAsync etc...
}
```

Service registration:

```
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddFastEndpoints();
//...
var app = builder.Build();
app.UseFastEndpoints().UseCors(defaultPolicyName);
```

Is there something I am missing in the configuration or is there a problem with the library.

Currently I can only access form data by using `EndpointWithoutRequest` and then mapping the values from `IFormCollectionData` to my DTO.

Thanks

**Comment by dj-nitehawk** [comment]
you need to do the following to allow url encoded form data:
```cs
public override void Configure()
{
    Description(x => x.Accepts<DocumentTransactionRequest>("application/x-www-form-urlencoded"));
}
```

this has been simplified in `v5.8.0.8-beta` where you can just do the following:
```cs
public override void Configure()
{
    AllowFormData(urlEncoded: true);
}
```
