### ISSUE TITLE
Assume latest version when version is omitted in URL

### ISSUE THREAD

**Issue by dustyroberts** [FastEndpoints/FastEndpoints#415]
I currently have a few endpoints:

/v1/Message/Send
/v2/Message/Send
/V1/Accounts/
/V1/Accounts/{accountid}

this versions are specified in the configure method of my endpoint with `Version(x)`.

I can access all these routes correctly, but is there a way to be able to ommit the version during the request and let the system automatically assume the latest version?

I've tried re-writing the request path, with some custom middleware:

```
public class VersionRedirectMiddleware
{
    private readonly RequestDelegate _next;
    private readonly string _latestVersion;

    public VersionRedirectMiddleware(RequestDelegate next, string latestVersion)
    {
        _next = next;
        _latestVersion = latestVersion;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        // Ignore URL rewriting for paths containing "swagger"
        if (!context.Request.Path.Value.Contains("swagger", StringComparison.OrdinalIgnoreCase))
        {
            // Check if the request URL contains any version prefix or suffix
            var hasVersion = Regex.IsMatch(context.Request.Path, @"v\d+");

            // If no version is specified, assume the latest version and rewrite the request URL
            if (!hasVersion)
            {
                // Modify the request path based on your versioning scheme (prefix or suffix)
                context.Request.Path = $"/v{_latestVersion}{context.Request.Path}";
            }
        }

        // Call the next middleware in the pipeline
        await _next(context);
    }
}
```
    
and i've registered this middleware in my program.cs

`app.UseMiddleware<VersionRedirectMiddleware>("2");`

It re-writes the path correctly, but for some reason does not hit the `v2` endpoint.

**Comment by dustyroberts** [comment]
I've found the issue, I am supposed to include the following:
`
app.UseMiddleware<VersionRedirectMiddleware>("2"); //<-- this is my middlware
app.UseRouting(); // <-- this was required
app.UseAuthorization(); //<-- this has to be between UserRouting and USeFastEndpoints
app.UseFastEndpoints(c =>
`
It would be nice to have this feature in fastendpoints as a setting `AssumeLatest = true/false`

**Comment by dj-nitehawk** [comment]
good to know that you have a working solution. 
however, in FE versioning, it's designed to assume "initial version" if there's no version number in the url.
will look in to adding that as a future feature.
