### ISSUE TITLE
Required header bindings in integration tests

### ISSUE THREAD

**Issue by MichaelNel** [FastEndpoints/FastEndpoints#416]
We have a required header for one of our endpoints and don't have a convenient way of passing the header in integration tests. We've fallen back to following what you guys do in your integration tests by adding [default headers to the http client](https://github.com/FastEndpoints/FastEndpoints/blob/main/Tests/IntegrationTests/IntegrationTests.Shared/Fixtures/EndToEndTestBase.cs#L52-L53). This isn't ideal since the headers are present on all requests on the client when we'd rather scope the header to a single request.

We'd be happy to contribute to support for required header bindings in integration tests but we'd like to hear if you have any suggestions for an approach, if you think this would be a useful addition.

**Comment by dj-nitehawk** [comment]
you can add per request headers as done here:
https://github.com/FastEndpoints/FastEndpoints/blob/0a6c187c3b04187033ec1b371cb2fbe4568663a2/Tests/IntegrationTests/FastEndpoints.IntegrationTests/WebTests/MiscTestCases.cs#L946

but you'd have to construct the httprequestmessage yourself, for which you can obtain the endpoint route and combine it with the base path like so:
https://github.com/FastEndpoints/FastEndpoints/blob/0a6c187c3b04187033ec1b371cb2fbe4568663a2/Tests/IntegrationTests/FastEndpoints.IntegrationTests/WebTests/MiscTestCases.cs#L70-L75
