### ISSUE TITLE
Separate Swagger Docs

### ISSUE THREAD

**Issue by altmank** [FastEndpoints/FastEndpoints#417]
I have a requirement where I need to take different endpoints and put them into different swagger docs. So say I have 3 API endpoints, 1 will be in one doc, and the other 2 will be in another doc. The swagger docs will get uploaded into another system and there is a (business) reason why they have to be created as two separate instances. Is there already a baked in method here to choose the swagger document an endpoint will go into/maintain multiple swagger documents (outside of versioning).

**Comment by dj-nitehawk** [comment]
you could achieve it with an endpoint filter and tagging endpoints as shown here: https://github.com/FastEndpoints/FastEndpoints/issues/252#issuecomment-1256188784
