### ISSUE TITLE
Variable Response based on user role/claims/permissions

### ISSUE THREAD

**Issue by desarrollo-ctme** [FastEndpoints/FastEndpoints#418]
Grettings:

First of all and as I said months ago, congratulations for this superb library that I have been using for a while now. After more than 150 endpoints implemented, today I had to add security into the api and encountered a problem I don't know how to resolve.

A bit of context first. I am programing an API that mostly do CRUD operations to an Angular frontend. In this frontend we have dozens of lists and then details for every entity we manage. For example, you access the employee list and then click on one of them to access his details. All data needed for the employee detail is sent to the frontend in one API call by just one endpoint, for example:

https://localhost:5001/employees/{id} 

with the following response:

```C#
public sealed record GetEmployeeResponse
{
    // Base Employee Data

    public string Code { get; init; }  
    public string Name { get; init; } 
    public string Surname { get; init; } 
    public string Email { get; init; }  
    public DateTime? BirthDate { get; init; }  

    // Much more stuff....  

   //Employee Bank Details

    public string BankName { get; init; } 
    public string BankAddress { get; init; } 
    public string BankAccount { get; init; } 

    // Much more stuff....

    public DateTime CreatedAt { get; init; }
    public DateTime? DeletedAt { get; init; }
    public DateTime? ArchivedAt { get; init; }
}
```

Entity's details can be very complex, and the frontend break down all that information into visual pieces like tabs, so the user can understand better how they are organized.

Now I have to implement a configurable security system over this already made endpoints and they want to filter parts of the GetEmployeeResponse based on Roles/claims/permissions, so a user with "Admin" role can see everything and another user with "Human Resources" role cannot see the bank details section. So now I have to change the response structure, data or both on users role, for example.

I dont see a way to do this without rewriting the existings endpoints and without making new endpoints every time a role is added which imho is cumbersome and time consuming. So the question is if this possible at all or what ways are there to get around this problem and meet the new security requirements. If I didn't explained the issue properly and need more information, feel free to ask.

Thanks for your time and response, kind regards.

**Comment by dj-nitehawk** [comment]
maybe something like this:
```cs
//assign individual permissions to each user type on login
public class UserLogin : EndpointWithoutRequest
{
    public override Task HandleAsync(CancellationToken ct)
    {
        var permissionCodes = new[] {
            Allow.User_Create,
            Allow.Account_Create,
            Allow.Account_View,
            Allow.Account_View_Balance
        };
        //admin login would have all permissions like so:
        //var permissionCodes = new Allow().AllCodes();

        var jwtToken = JWTBearer.CreateToken(
            signingKey: "secret token",
            permissions: permissionCodes);

        var permissionSet = new Allow().NamesFor(permissionCodes);

        Response = new
        {
            AccessToken = jwtToken,
            PermissionSet = permissionSet //ui can use these to show hide elements based on permissions
        };
    }
}

public class GetAccount : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("account/{id}");
        Permissions(
            Allow.Account_View,
            Allow.Account_View_Balance);
    }

    public override Task HandleAsync(CancellationToken ct)
    {
        //do stuff differently based on the permissions of the current user

        if (User.HasPermission(Allow.Account_View_Balance))
        {
            //retrieve account balance from db and set on response dto
        }

        //or do stuff based on a role
        if (User.IsInRole("Admin"))
        {
            //whatever
        }

        //these checks can also be auto bound to the request dto using [HasPermission(...)] attribute:
        //https://fast-endpoints.com/docs/model-binding#has-permissions
    }
}
```

**Comment by desarrollo-ctme** [comment]
Good to know that I was missing nothing and there is no way around this. I have to modify the endpoint's logic. Thanks for the response.
