### ISSUE TITLE
How to use FastEndpoints only for command bus?

### ISSUE THREAD

**Issue by gufigueiredo** [FastEndpoints/FastEndpoints#420]
I'm trying to use FastEndpoints only as a Command Bus, no endpoints here.
But when I try to build my webhost, I always get an error message saying that no endpoints were found.

Is there any way to fix this?

**Comment by dj-nitehawk** [comment]
it's not meant to be used as a standalone command bus.
you can however just register a dummy endpoint just to get FE to startup correctly.
