### ISSUE TITLE
Access to exception in IGlobalPostProcessor

### ISSUE THREAD

**Issue by disagol** [FastEndpoints/FastEndpoints#424]
First things first, love the lib very neat.
We have a global post processor for handling common issues regarding all eps. We also have a middleware to log exceptions the way we need. But now we need to get the exception in the post processor which is not a ValidationFailure one. How can we acomplish this? Any alternative?
Thanks in advance.

**Comment by dj-nitehawk** [comment]
it's not possible for a post-processor to "catch" exceptions with the current architecture.
your choices would be to either use the [IEntpointFilter introduced in .net 7](https://discord.com/channels/933662816458645504/1092452107199721542/1092452107199721542).
or you could do something like the following with the global post processors [with processor state](https://fast-endpoints.com/docs/pre-post-processors#sharing-state).
```cs
var builder = WebApplication.CreateBuilder();
builder.Services.AddFastEndpoints();
builder.Services.AddSwaggerDoc();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints(x => x.Endpoints.Configurator = ep =>
{
    ep.PostProcessors(Order.After, new MyPostProcessor());
});
app.UseSwaggerGen();
app.Run();

public class MyStateBag
{
    public List<Exception> Exceptions { get; set; } = new();
}

public class MyPostProcessor : IGlobalPostProcessor
{
    public Task PostProcessAsync(object req, object? res, HttpContext ctx, IReadOnlyCollection<ValidationFailure> failures, CancellationToken ct)
    {
        var logger = ctx.Resolve<ILogger<MyPostProcessor>>();
        var state = ctx.ProcessorState<MyStateBag>();

        foreach (var ex in state.Exceptions)
            logger.LogError("{msg}", ex.Message);

        return Task.CompletedTask;
    }
}

public class Endpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        try
        {
            throw new InvalidOperationException("blah blah blah");
        }
        catch (Exception x)
        {
            ProcessorState<MyStateBag>().Exceptions.Add(x);
            throw;
        }
    }
}
```

**Comment by disagol** [comment]
Oh I see, so Id need to decorate all my endpoints with try-catch blocks to make the exception available for the processor to handle it. I guess I wiill just move the code to the existing middleware, maybe in future releases this could become handy. Whats your thoughts on this?

Thanks!

**Comment by dj-nitehawk** [comment]
i don't see post-processors gaining the ability to catch exceptions anytime soon.
for that you can already use the `IEndpointFilter`s introduced in .net 7 (if that logic doesn't really belong in a middleware).

**Comment by tcortega** [comment]
I came across this aswell, I don't see why we would have this section in the documentation if we can't handle exceptions using `IGlobalPostProcessor`s

![image](https://github.com/FastEndpoints/FastEndpoints/assets/60912483/15d2e3cb-285c-4ddf-bad5-b4fc0ca871af)

**Comment by dj-nitehawk** [comment]
> I came across this aswell, I don't see why we would have this section in the documentation if we can't handle exceptions using `IGlobalPostProcessor`s
> 
> ![image](https://user-images.githubusercontent.com/60912483/279838347-15d2e3cb-285c-4ddf-bad5-b4fc0ca871af.png)

you cant catch them there but you have access to the validation failures for purposes such as logging them.

**Comment by tcortega** [comment]
> > I came across this aswell, I don't see why we would have this section in the documentation if we can't handle exceptions using `IGlobalPostProcessor`s
> > ![image](https://user-images.githubusercontent.com/60912483/279838347-15d2e3cb-285c-4ddf-bad5-b4fc0ca871af.png)
> 
> you cant catch them there but you have access to the validation failures for purposes such as logging them.

Sure, the bit we're talking about is just for when stuff doesn't pass validation. But in the screenshot I sent, it basically says, 
"You don't have to make your own middleware for catching exceptions; you could just set up a global post-processor instead...".

I don't think that the IGlobalPostProcessor should be in there, at least not put the way it currently is.

As for the `IGlobalPostProcessor`, isn't it better if you give it it's own Context, and inside it's context you could have properties such as the Request, the Response, the HttpContext and an optional `ExceptionDispatchInfo`.

**Comment by tcortega** [comment]
I suppose you'd have to provide a way for `PostProcessor`s to write to the Response.

**Comment by eulerchavez** [comment]
Hi @dj-nitehawk, first of all, I want to express my admiration for the work you've done with FE.

Like @tcortega, I'm encountering a similar challenge:

> provide a way for PostProcessors to write to the Response.

In my current project, I'm implementing the Result pattern in my services. The Result class is crucial as it indicates whether the operation was a success or if there was an error/exception, encapsulating these details.

I'm exploring the implementation of IGlobalPostProcessor to effectively evaluate the status of the Result class and accordingly craft a Response. For successful operations, I utilize the well-known SendAsync method to relay the actual value. Conversely, in case of exceptions, I'm considering creating a custom error result, inspired by issue #230.

This approach, I believe, could enhance the flexibility and error handling capabilities of FE. Could this be a feasible enhancement to Fast Endpoints? Are there any suggestions or guidelines you might have for this implementation?

Looking forward to your thoughts and guidance on this.

**Comment by dj-nitehawk** [comment]
@eulerchavez 
starting `v5.21.2.16-beta` post-processors can be put in charge of sending responses. see [example here](https://gist.github.com/dj-nitehawk/6e23842dcb7640b165fd80ba57967540). i'm sure you can easily translate that to a global processor.

btw, post-processors gained the [ability to handle exceptions](https://fast-endpoints.com/docs/pre-post-processors#handling-unhandled-exceptions-with-post-processors) recently and is available in the current release.

the [shape of error responses](https://fast-endpoints.com/docs/pre-post-processors#handling-unhandled-exceptions-with-post-processors) can also be customized.

if you have further questions, please create a new issue with code samples or a repro.
