### ISSUE TITLE
Update ISourceGenerator to IIncrementalGenerator

### ISSUE THREAD

**Issue by chIsmaeel** [FastEndpoints/FastEndpoints#426]
**Description:**
Currently, in the .NET project, the `ISourceGenerator` interface is used for generating source code during build-time. However, it has some limitations, such as regenerating all the source code even when only a small change is made. This can result in unnecessary overhead during the build process, especially in large projects.

I propose updating the `ISourceGenerator` interface to `IIncrementalGenerator` to enable incremental code generation, which will only regenerate the affected parts of the source code when changes are made, improving build performance and reducing unnecessary recompilations.

This change will require updating the `ISourceGenerator` interface definition and updating the existing source generators in the .NET ecosystem to implement the `IIncrementalGenerator` interface instead.

**Benefits:**

- Improved build performance in large projects with frequent code generation.
- Reduced unnecessary recompilations during the build process.
- Better support for incremental updates in source generators.

**Implementation plan:**

1. Update the `ISourceGenerator` interface definition to IIncrementalGenerator in the .NET source code.
2. Update the documentation and samples to reflect the changes.
3. Notify existing source generator authors to update their generators to implement the IIncrementalGenerator interface.
4. Update the .NET documentation and release notes to highlight the changes and benefits of using IIncrementalGenerator.
5. Provide backward compatibility support for existing source generators that still implement the ISourceGenerator interface.

I believe this change will greatly benefit the .NET ecosystem by improving build performance and reducing unnecessary recompilations. I'm open to discussions and feedback from the community and would be happy to contribute to the implementation of this proposal.

Thank you for considering this issue.

**Comment by dj-nitehawk** [comment]
good job and thank you for the contribution.
much appreciated 🙏
