### ISSUE TITLE
JsonSerialiser options

### ISSUE THREAD

**Issue by dustyroberts** [FastEndpoints/FastEndpoints#428]
Hi There,

I am using and specifying the default json serialiser in my Program.cs

           ```
            c.Serializer.RequestDeserializer = async (req, tDto, jCtx, ct) =>
            {
                using var reader = new StreamReader(req.Body);
                return Newtonsoft.Json.JsonConvert.DeserializeObject(await reader.ReadToEndAsync(), tDto);
            };

            c.Serializer.ResponseSerializer = (rsp, dto, cType, jCtx, ct) =>
            {
                rsp.ContentType = cType;
                return rsp.WriteAsync(Newtonsoft.Json.JsonConvert.SerializeObject(dto), ct);
            };
            ```

This works 100% until i need to start specifying different serialization options for various endpoints.

In one endpoint when returning an object `await SendAsync(responseModel, 200, ct);`  I need to be able to specify a set of JsonSerializerSettings and in another endpoint i need to specify a different set of JsonSerializerSettings

I do not see an overload in SendAsync that allows one to specify JsonSerializerSettings.

I can add one set of JsonSerializerSettings as a global configuration in my Program.cs:

```
                return rsp.WriteAsync(Newtonsoft.Json.JsonConvert.SerializeObject(dto, new JsonSerializerSettings
                {
                    NullValueHandling = NullValueHandling.Ignore,
                    Converters = new List<JsonConverter>
                    {
                        new StringEnumConverter()
                    }

                }), ct);
```

but this is now the default, and all endpoits use it, so i cannot change the JsonSerializerSettings on another endpoint.

I can achieve this by using WriteAsync, but it feels a bit hacky.

```
            var serializerSettings = new JsonSerializerSettings
            {
                NullValueHandling = NullValueHandling.Include,
                DefaultValueHandling = DefaultValueHandling.Include
            };

            var json = JsonConvert.SerializeObject(myObject, serializerSettings);

            HttpContext.Response.StatusCode = 200;
            HttpContext.Response.ContentType = "application/json";
            await HttpContext.Response.WriteAsync(json);
```

**Comment by dj-nitehawk** [comment]
the `RequestDeserializer` is global. you'd either have to do a switch statement inside it to check which type is currently being handled or you'd have to write your own custom response send methods like the following:

```cs
public static class EndpointExtensions
{
    public static Task SendCustom<TResult>(this IEndpoint ep, TResult result, int statusCode = 200, CancellationToken ct = default)
    {
        ep.HttpContext.MarkResponseStart();
        ep.HttpContext.Response.StatusCode = statusCode;
        ep.HttpContext.Response.ContentType = "application/json";
        return System.Text.Json.JsonSerializer.SerializeAsync(ep.HttpContext.Response.Body, result);
    }
}
```

usage like so:

```cs
public override async Task HandleAsync(CancellationToken ct)
{
    await this.SendCustom(new { ... });
}
```

there's currently no support for per endpoint serializer settings/options. 
won't be added anytime soon since it's such a niche use case.

also i'd recommend you move away from newtonsoft and embrace STJ if at all possible.
the performance difference between the two is quite major last i checked.

**Comment by diegosasw** [comment]
Where can I find the default System.Text `JsonSerializationOptions` that FastEndpoints uses by default?
I am seeing it's capable of deserializing strings into long or int, and I want to mimic the same serialization settings in my custom middleware not to have discrepancies between middleware and endpoint, but I can't find any documentation about it other than how to specify custom options.

**Comment by dj-nitehawk** [comment]
@diegosasw 
the following part from the docs should answer your question:

![Image](https://github.com/user-attachments/assets/81f77dda-582d-4e29-88aa-a4d4a98beb4c)

so for your need, do the options pattern.

**Comment by dustyroberts** [comment]
> the `RequestDeserializer` is global. you'd either have to do a switch statement inside it to check which type is currently being handled or you'd have to write your own custom response send methods like the following:
> 
> public static class EndpointExtensions
> {
>     public static Task SendCustom<TResult>(this IEndpoint ep, TResult result, int statusCode = 200, CancellationToken ct = default)
>     {
>         ep.HttpContext.MarkResponseStart();
>         ep.HttpContext.Response.StatusCode = statusCode;
>         ep.HttpContext.Response.ContentType = "application/json";
>         return System.Text.Json.JsonSerializer.SerializeAsync(ep.HttpContext.Response.Body, result);
>     }
> }
> usage like so:
> 
> public override async Task HandleAsync(CancellationToken ct)
> {
>     await this.SendCustom(new { ... });
> }
> there's currently no support for per endpoint serializer settings/options. won't be added anytime soon since it's such a niche use case.
> 
> also i'd recommend you move away from newtonsoft and embrace STJ if at all possible. the performance difference between the two is quite major last i checked.

This is definately a feasible alternative.

Thanx
