### ISSUE TITLE
Is it possible to apply policies only to associated authentication scheme?

### ISSUE THREAD

**Issue by zszepczynski** [FastEndpoints/FastEndpoints#429]
My setup:

```cs
 services
            .AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
            .AddJwtBearer(options =>
            {
              //setup
            })
            .AddJwtBearer(AuthenticationSchemeTypes.FileDownload, options =>
            {
                //setup
            });
```

Now I'm mapping policies to auth scheme

```cs
 services.AddAuthorization(options =>
        {
            options.AddPolicy(CustomPolicies.FileDownload, policy => policy
                .AddAuthenticationSchemes(AuthenticationSchemeTypes.FileDownload) <- only for this scheme
                .RequireAuthenticatedUser()
                .RequireClaim(JwtClaimTypes.Id));
            
            
            options.AddPolicy(CustomPolicies.SomeOtherPolicy, policy => policy
                .AddAuthenticationSchemes(JwtBearerDefaults.AuthenticationScheme)  <- only for this scheme
                .AddRequirements(new SomeOtherPolicy));
                ...
```

Now I want to protect all endpoints with SomeOtherPolicy that are using default authentication scheme. I set it globally like this:

```cs
 app.UseFastEndpoints(c =>
        {
            c.Versioning.Prefix = "v";
            c.Endpoints.ShortNames = true;
            c.Endpoints.Configurator = ep =>
            {
                    ep.Policies(CustomPolicies.SomeOtherPolicy);
         }

```
And my file download file endpoint config:

```cs
 public override void Configure()
    {
    //setup
        AuthSchemes(AuthenticationSchemeTypes.FileDownload);
        Policies(CustomPolicies.FileDownload);
    }
```

However when I execute download file endpoint, it validates all default authentication scheme policies and FileDownload.
Is it possible to map policies to a particular authentication scheme and set authentication scheme in endpoint?

**Comment by dj-nitehawk** [comment]
i believe something like the following should do the trick:
```cs
app.UseFastEndpoints(c =>
{
    c.Endpoints.Configurator = ep =>
    {
        if (ep.PreBuiltUserPolicies?.Contains(CustomPolicies.FileDownload) is not true)
            ep.Policies(CustomPolicies.SomeOtherPolicy);
    };
});
```
because otherwise, you're adding `SomeOtherPolicy` to every endpoint.

if that doesn't do it, pls attach a runnable minimalistic repro project and i'll look in to it further.

**Comment by zszepczynski** [comment]
This would do the job however I was thinking that associating authentication scheme with policy and settings auth scheme in the endpoint would do that automatically for me.

**Comment by dj-nitehawk** [comment]
all FE is doing is dynamically creating an `[Authorize]` attribute and setting it's `Policy`, `AuthenticationSchemes`, and `Roles` properties according to what methods were called in the endpoint `Configure()`.

other than that, all the auth behavior is dictated by how the asp.net middlware is configured.

in other words, calling the `AuthSchemes()`, `Policies()` and `Roles()` inside `Configure()` is exactly the same as decorating an mvc controller or minimal api endpoint with an `[Authorize(...)]` attribute. the rest is done by the middlware you configure.
