### ISSUE TITLE
Strongly-typed route values for SendCreatedAtAsync

### ISSUE THREAD

**Issue by austins** [FastEndpoints/FastEndpoints#430]
What do you think about having strongly-typed route values for SendCreatedAtAsync? It may be a bit of effort to infer the name of the parameter, but perhaps we could tie it into if we have defined [Strongly Typed Route Parameters](https://fast-endpoints.com/docs/misc-conveniences#strongly-typed-route-parameters) for a specific verb and can infer the name of potential route parameter names from that. Might need source generation.

So if you had something like:
```csharp
Put("/articles/{@param1}/{@param2}", x => new { x.Year, x.Name });`
```

Then you could do something like:
```csharp
await SendCreatedAtAsync<GetPageEndpoint, GetPageEndpointRouteParams>(new GetPageEndpointRouteParams { Year = article.Year, Name = article.Name }, article);
```

**Comment by dj-nitehawk** [comment]
just had a quick look at this and i'm not quite sure exactly what you're asking for here, since we can already just do this:
```cs
SendCreatedAtAsync<GetPageEndpoint>(new GetPageEndpointRouteParams { Year = article.Year, Name = article.Name }, article);
```
what's the point of having to type the second generic parameter?
```cs
SendCreatedAtAsync<GetPageEndpoint, GetPageEndpointRouteParams>
```

**Comment by austins** [comment]
That's better. Got side-tracked by the anonymous objects. 😅
