### ISSUE TITLE
Question about failure to process without body

### ISSUE THREAD

**Issue by disagol** [FastEndpoints/FastEndpoints#431]
Hi, its me once again. I apologize if this is in the docs or issue list did my best to find it.
So there is an ep with put VERB, defined it with a request because there are route params and header params which are binded to a common validator. So having a request is needed, the thing is this request has no body parameter so it fails with 

`The input does not contain any JSON tokens. Expected the input to start with a valid JSON token`

From rest client I need to add empty {} to pass the issue, like it is waiting a body param. I understand I can get the route params with the Route(), but then I need to get the header params too and run the validator by hand. Thats not the issue but maybe I am missing some config to allow an Endpoint to have a Request dto (with all header and route params) calling it with no body from the client.

Many thanks!

**Comment by dj-nitehawk** [comment]
this should do it:
```cs
public override void Configure()
{
    ...
    Description(x => x.Accepts<Request>("*/*"), clearDefaults: true);
}
```
and when submitting the request from the client, don't set the `Content-Type` header to `application/json` because if you do, FE will send it down the json serialization path.

when the endpoint itself accepts `"*/*"` your client doesn't need to even set a `Content-Type` header.

**Comment by disagol** [comment]
Thanks I ended up having a binder and populating the Request myself inheriting from Request Binder. But I like your solution as is just a one-linner config.
