### ISSUE TITLE
How can we integrate Custom Schema FIlters to use with SmartEnums

### ISSUE THREAD

**Issue by essuraj** [FastEndpoints/FastEndpoints#433]

**Comment by dj-nitehawk** [comment]
describe your problem pls.
what exactly do you wanna achieve?
is this about nswag shema filters or how to model bind smart enums?
maybe this would help: https://github.com/FastEndpoints/FastEndpoints/pull/288#issue-1414354228

**Comment by dj-nitehawk** [comment]
this is how you'd register custom schema filters/processors for nswag:

```cs
builder.Services.AddSwaggerDoc(s =>
{
    s.SchemaProcessors.Add(new SmartEnumSchemaFilter());
});

public class SmartEnumSchemaFilter : ISchemaProcessor
{
    public void Process(SchemaProcessorContext context)
    {

    }
}
```
as for the implementation for smart enums, i can't help you with that since i'm not familiar with that package.
you'd most likely be able to use the same logic that's used for swashbuckle.
