### ISSUE TITLE
`SendOkAsync` does not serialize the response when endpoint inherits from `EndpointWithoutRequest`

### ISSUE THREAD

**Issue by candoumbe** [FastEndpoints/FastEndpoints#435]
I wrote the following endpoint

```csharp
public class UploadEndpoint : EndpointWithoutRequest
{
    ///<inheritdoc/>
    public override void Configure()
    {
        Post("files");
        AllowFileUploads(true);
        AllowAnonymous();
    }

    ///<inheritdoc/>
    public override async Task HandleAsync(CancellationToken ct)
    {
        int sectionCount = 0;
        await foreach (FileMultipartSection section in FormFileSectionsAsync(ct))
        {
            if (section is not null)
            {
                using FileStream fs = File.Create(section.FileName);
                await section.Section.Body.CopyToAsync(fs, 1024 * 64, ct)
                                          .ConfigureAwait(false);

                sectionCount++;
            }
        }

        var result = new { sectionCount, Message = "Upload complete" };
        await SendOkAsync(result, ct).ConfigureAwait(false);
    }
}
```

and when testing this endpoint, I get an empty response but if I changed the endpoint to inherit from `EndpointWithoutRequest<UploadResponse>` and change the last two lines to

```csharp
UploadResponse result = new () { Count = sectionCount, Message = "Upload complete" };
await SendOkAsync(result, ct).ConfigureAwait(false);
```

Then in this case I get the response sent.

Is this normal ?

**Comment by dj-nitehawk** [comment]
just tried the following:
```cs
public class UploadEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Post("files");
        Description(x => x.Accepts<object>("*/*")); //just for testing without formdata
        AllowFileUploads(true);
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        var result = new { sectionCount = 10, Message = "Upload complete" };
        await SendOkAsync(result, ct);
    }
}
```
and i get this:
![image](https://user-images.githubusercontent.com/7043768/233635323-f91040b0-fbd0-45f8-9247-c36f972ed0b1.png)

unrelated question... why do you do `ConfigureAwait(false)`?
it's not necessery in asp.net 6 since it doesn't have a synchronization context anymore.

**Comment by candoumbe** [comment]
@dj-nitehawk 

I will be using a DTO anyway but I still don't get why it works on your side an not in mine (using 5.8.1.10-beta)

Regarding `ConfigureAwait`, most of the time I'm working on library and so I'm used to do `ConfigureAwait` there 😅

**Comment by dj-nitehawk** [comment]
can you create a new project and try to replicate it?
if successful attach it here.
if not, try debugging with loaded symbols and stepping into FE source to see what's happenning.

**Comment by candoumbe** [comment]
I'll try and will update this issue
