### ISSUE TITLE
About the display of Swagger DTO Model parameters

### ISSUE THREAD

**Issue by zfchai** [FastEndpoints/FastEndpoints#438]
Create 3 APIs as follows:

- MyEndpoint : Endpoint<MyRequest, MyResponse>，Get("/my/query");

The get request DTO model displays as expected on the swagger page.

![image](https://user-images.githubusercontent.com/82487746/234814835-c422ddd8-cb54-4c9f-9913-45c41e5f3253.png)

- UserEndpoint : Endpoint<UserRequest<UserReqDto>, UserResponse<UserInfo>>，Get("/user/query");

The generic DTO model requested by get does not display as expected on the swagger page.

![image](https://user-images.githubusercontent.com/82487746/234816331-1b81e756-73d7-40ad-886e-a891eb359023.png)

- YourEndpoint : Endpoint<YourRequest<YourReqDto>, YourResponse<YourInfo>>，Post("/your/create");

The general DTO model for POST requests is displayed as expected on the swagger page.

![image](https://user-images.githubusercontent.com/82487746/234816946-99171f79-e43a-4648-9cf3-9fa3765b05ad.png)

Strangely, none of the above DTO models display XML document annotation information. Is there any configuration error?

```xml
<PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
</PropertyGroup>
```

DTO model attributes all have XML document annotations. How to display them in the swagger? 

For more information, please refer to demo: MyWebApp 

Demo => [Solution1.zip](https://github.com/FastEndpoints/FastEndpoints/files/11342594/Solution1.zip)

ts!

**Comment by dj-nitehawk** [comment]
looks like you've attached the wrong zip file. there's no `Get("/user/query")` endpoint in this solution.
attach the correct one and i'll have a look at it.

**Comment by dj-nitehawk** [comment]
anyway i think you just need to provide the default value for `Args` property:
```cs
public class MyRequest
{
    [DefaultValue("{ \"FirstName\": \"test\", \"LastName\":  \"test\" }")]
    public Whatever Args { get; set; }
}
```

**Comment by zfchai** [comment]
Please carefully compare the endpoints in the demo as follows:

![image](https://user-images.githubusercontent.com/82487746/234841622-cbd2cb64-5768-43b1-b5a3-8ea7e3e32bdb.png)

Args is a generic, universal model, and only the specific Ednpoints used determine the specific DTO model. 
Therefore, [DefaultValue ("{" FirstName  ": " test  ", " LastName  ": " test  "}") cannot be marked on Args attributes.

Demo => [Solution1.zip](https://github.com/FastEndpoints/FastEndpoints/files/11342594/Solution1.zip)

**Comment by dj-nitehawk** [comment]
it's currently not possible to set an example/default value for a generic request dto such as `UserRequest<UserReqDto>`.
if it's not a generic dto but a straight up dto like `UserReqDto`  then you can set an example with the `[DefaultValue(...)]` attribute or an `/// <example> { ... }</example>` xml comment.

btw, your xml documentation is not working because you have invalid xml data such as:
```xml
/// <summary>
/// UserRequest<TRequest> 
/// </summary>
```
`<TRequest>` is invalid xml there. delete that and it works.

**Comment by dj-nitehawk** [comment]
also it's not recommended that you do GET requests with complex dto models. if the request data is complex, always put them in the body as json and make it a POST request, even if it's a data retrieval operation. query params with complex objects is a bad practice imho.

if you really must set examples/default values for complex/generic request dtos, you may be able to achieve that with a custom operation processor for nswag.

**Comment by zfchai** [comment]
I understand what you mean. XML documents can only be used to label the JSON data in the specific DTO model. However, whether it is a get or post request, the DTO model has many fields that require manual writing of JSON data as XML annotation tags. This workload is too much, and I want to use Swagger to complete this task, freeing up more effective time to do meaningful things.

**Comment by dj-nitehawk** [comment]
try something like this:
```cs
public class DefaultValueOperationProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext context)
    {
        foreach (var parameter in context.OperationDescription.Operation.Parameters.Where(p => p.Kind == OpenApiParameterKind.Query))
        {
            if (parameter.Schema.Default is null)
                parameter.Schema.Default = parameter.Schema.ActualTypeSchema.ToSampleJson();
        }
        return true;
    }
}
```
register the processor with the document
```cs
builder.Services.AddSwaggerDoc(doc =>
{
    doc.Title = "My API";
    doc.Version = "v1";
    doc.OperationProcessors.Add(new DefaultValueOperationProcessor());
}, tagIndex: 0);
```

**Comment by zfchai** [comment]
Feedback has been provided, please check here：https://github.com/luoyunchong/IGeekFan.AspNetCore.Knife4jUI/issues/52
