### ISSUE TITLE
Does it support EF database migration?

### ISSUE THREAD

**Issue by freeddser** [FastEndpoints/FastEndpoints#440]

**Comment by dj-nitehawk** [comment]
how do you usually run them?

**Comment by nefarius** [comment]
How is FE even remotely connected to EF migrations... 🤔

**Comment by dj-nitehawk** [comment]
@nefarius exactly my thought 🫤

**Comment by nefarius** [comment]
I think these types of issues should be closed sooner than later, with the project gaining popularity the management overhead with issues that are none will rise exponentially and only strain the already stretched time budget of yourself and the collaborators. My two cents 🙃

**Comment by dj-nitehawk** [comment]
agreed :-)
