### ISSUE TITLE
Adjust the correspondence between API interface and Schemas display in Swagger page

### ISSUE THREAD

**Issue by zfchai** [FastEndpoints/FastEndpoints#441]
Currently, the Schemas is concentrated together, and it is not easy to view each API. 

Can you modify and adjust it to the way shown in the figure below?

![54e02c82eb808930afebe9ad2c2e872](https://user-images.githubusercontent.com/82487746/236102204-6506376e-8b31-4016-b0ae-c69fedadce65.png)

**Comment by dj-nitehawk** [comment]
first question:
```cs
.UseSwaggerGen(uiConfig: c => c.DocExpansion = "full");
```
second question:
```cs
builder.Services.SwaggerDocument(o => o.EnableGetRequestsWithBody = true);

app.UseSwaggerGen(uiConfig: c =>
{
    c.DocExpansion = "full";
    c.EnableTryItOut = false;
});
```

**Comment by zfchai** [comment]
At present, it is not possible to display some commonly used verification information such as whether DTO model attributes are mandatory or length restrictions on Swagger.

**Comment by zfchai** [comment]
At present, it is not possible to display some commonly used verification information such as DTO model attributes required or length restrictions on Swagger.

**Comment by zfchai** [comment]
```csharp
c.EnableTryItOut = false;
```

Unable to debug without displaying the Execute button!

**Comment by zfchai** [comment]
Unfortunately, currently FastEndpoints.Swagger is based on NSwag packaging and does not substantially solve the workload of online API documentation. 

It is recommended to use the Swashbuck currently used in the asp.net core, which is much more convenient.

**Comment by dj-nitehawk** [comment]
> Unable to debug without displaying the Execute button!

with the latest beta, do this:

```cs
.UseSwaggerGen(uiConfig: c=>c.DeActivateTryItOut());
```

> It is recommended to use the Swashbuck

we had swashbuck support but it became a nightmare to maintain two different swagger packages. so now only nswag exists because of it's superior feature-set. and i don't agree that swashbuck is more convenient.

**Comment by zfchai** [comment]
Defects in Swagger:

Two or more Endpoint APIs in EF use the same DTO model, and regardless of whether the Endpoint API uses GET or POST requests, the schema information display is invalid.

**Comment by dj-nitehawk** [comment]
don't share dtos then.
put the common properties in a base class. and use schema flattenning: `.SwaggerDocument(o => o.FlattenSchema = true);`

example:

Person - base class with commin properties

CreatePerson : Person
UpdatePerson : Person

**Comment by zfchai** [comment]
Please take a look at the following example:

- UserLoginEndpoint 

```csharp
public class UserLoginEndpoint : Endpoint<Request<UserLoginDto>, Response<UserTokenInfoDto>>
{
  public override void Configure()
  {
    Post("/user/login");
    AllowAnonymous();
  }

  public override async Task HandleAsync(Request<UserLoginDto> req, CancellationToken c)
  {
    var dto = new UserTokenInfoDto()
    {
      //...
    };
    var resp = new Response<UserTokenInfoDto>.BuildResult(dto, 200, true, "ok")
    {
      //...
    };
    await SendAsync(resp);
  }
}
```

- Common DTO model

```csharp
public sealed class Request<TArgs> where TArgs : class
{
    /// <summary>
    /// 入参唯一ID（GUID32 & 雪花ID）
    /// </summary>
    public string RequestId { get; set; } = string.Empty;

    /// <summary>
    /// 租户ID
    /// </summary>
    public string TenantId { get; set; } = string.Empty;

    /// <summary>
    /// 当前用户id
    /// </summary>
    public string UserId { get; set; } = string.Empty;

    /// <summary>
    /// 入参函数、方法(FuncCode)
    /// </summary>
    public string ActionCode { get; set; } = string.Empty;

    /// <summary>
    /// 时间戳
    /// </summary>
    public long TimeStamp { get; set; }

    /// <summary>
    /// 接口描述
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// 泛型模型参数
    /// </summary>
    public TArgs? Args { get; set; }
}

public sealed class Response<TData>
{
    /// <summary>
    /// 响应代码
    /// </summary>
    public int Code { get; set; }

    /// <summary>
    /// 接口状态
    /// </summary>
    public bool Success { get; set; }

    /// <summary>
    /// 提示信息
    /// </summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// 数据体
    /// </summary>
    public TData? Data { get; set; }

    /// <summary>
    /// 格式化
    /// </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="data"></param>
    /// <param name="code"></param>
    /// <param name="success"></param>
    /// <param name="msg"></param>
    /// <returns></returns>
    public static Response<T> BuildResult<T>(T data, int code, bool success, string msg) where T : class
    {
        var result = new FastResponse<T>
        {
            Code = code,
            Success = success,
            Message = msg,
            Data = data
        };
        return result;
    }
}
```

- DTO of the current API interface

```csharp
public class UserLoginDto
{
    /// <summary>
    /// 账号
    /// </summary>
    public string LoginName { get; set; } = string.Empty;

    /// <summary>
    /// 密码
    /// </summary>
    public string Password { get; set; } = string.Empty;
}

public class UserLoginValidator : Validator<FastRequest<UserLoginDto>>
{
    public UserLoginValidator()
    {
        RuleFor(x => x.Args.LoginName).NotEmpty().WithMessage("登录账号不能为空！");

        RuleFor(x => x.Args.Password).NotEmpty().WithMessage("登录密码不能为空！");
    }
}

public class UserTokenInfoDto
{
    /// <summary>
    /// 用户信息
    /// </summary>
    public OrgUserInfo UserInfo { get; set; }

    /// <summary>
    /// 账号访问信息
    /// </summary>
    public OrgAccountTokenInfo AccountTokenInfo { get; set; }

    /// <summary>
    /// 用户角色
    /// </summary>
    public List<UserRoleInfo> UserRoles { get; set; }

    /// <summary>
    /// 用户权限
    /// </summary>
    public List<UserPrivsInfo> UserPrivies { get; set; }
}
```

Cannot use. SwaggerDocument (o=>o. FlattenSchema=true);

Because these parameters are non business related!

**Comment by zfchai** [comment]
In the demo above, there was an issue with the data parsing of the GET request URL Search Params on the Swagger, and the parameter format error is displayed as follows:

```
http://www.xxx.com/user/login?RequestId=a1&TenantId=1001&HospitalArea=a&UserId=86678006a50444609ba3278ed504269d&ActionCode=a&TimeStamp=1683355270&Id=86678006a50444609ba3278ed504269d}
```

- Normal parameter format:

```
http://www.xxx.com/user/login?RequestId=a1&TenantId=1001&HospitalArea=a&UserId=86678006a50444609ba3278ed504269d&ActionCode=a&TimeStamp=1683355270&Args={"Id": "86678006a50444609ba3278ed504269d"}
```

**Comment by dj-nitehawk** [comment]
your endpoint config says `Post("/user/login");`
so why are you talking about a GET request and query params?

**Comment by dj-nitehawk** [comment]
if you need further help, pls attach an absolute minimalistic repro project i can debug. the code snippets posted above are not complete and i can't compile it by copy pasting. also pls trim stuff down that's no related to the issue at hand. for example, nobody needs to see those xml commets to reproduce an issue right?

**Comment by zfchai** [comment]
Here is just an example, of course, this example is the use of Post requests, at that time similar to DTO get requests can also be ah, you can modify and debug, can the mind expand the open point?

**Comment by dj-nitehawk** [comment]
no minimal repro = no help from me

i don't have time to recreate your use cases. i'm doing this all for free sacrifising my free time while having a day job.
hope you can understand ;-)

so make it easy for me to help you.

thank you!

**Comment by zfchai** [comment]
- Args is a JSON object

```json
{
  "id": "string"
}
```

- but it was resolved by the swagger as "id=string"

```bash
curl -X 'GET' \
  'http://localhost:5010/api/Organization/UserManage/GetOrgUserRoles?RequestId=1&TenantId=1&HospitalArea=1&UserId=1&ActionCode=1&TimeStamp=111&Description=11&id=string' \
  -H 'accept: application/json'
```

![image](https://user-images.githubusercontent.com/82487746/236685385-dfa88daf-459d-4f40-98cb-c21ae5702a35.png)

![image](https://user-images.githubusercontent.com/82487746/236685550-7d498558-0034-4d94-af7a-8038b62adda0.png)

**Comment by dj-nitehawk** [comment]
it seems that swagger ui is not compatible with the setting `AllowReferencesWithProperties = true`
more info: https://github.com/RicoSuter/NSwag/issues/2986

i suggest you move away from GET requests with nested complex objects.
or since swagger ui doesn't really work well with GET requests with nested complex objects, just use `EnableGetRequestsWithBody = true` and put the complex objects in the request body.

**Comment by dj-nitehawk** [comment]
also i just remembered there's another option for you. FE has an undocumented attribute you can use for this scenario `[FromQueryParams]`

example: 
```cs
using FastEndpoints;
using FastEndpoints.Swagger;

var builder = WebApplication.CreateBuilder();
builder.Services
    .AddFastEndpoints()
    .SwaggerDocument(o => o.DocumentSettings = s => s.AllowReferencesWithProperties = true);

var app = builder.Build();
app.UseFastEndpoints()
   .UseSwaggerGen();

app.Run();

public class Arg
{
    public string Id { get; set; }
}

public class Request<T> where T : class
{
    public int MainId { get; set; }

    [FromQueryParams]
    public T Args { get; set; }
}

public class ExampleEndpoint : Endpoint<Request<Arg>>
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request<Arg> r, CancellationToken c)
    {
        await SendAsync(r);
    }
}
```
![image](https://user-images.githubusercontent.com/7043768/236758495-fc22acc3-1798-4a62-9a8f-f5c4c1941f42.png)

**Comment by zfchai** [comment]
- `Request<T>` is a universal DTO format

```
public class Request<T> where T : class
{
    public int MainId { get; set; }

    [FromQueryParams]
    public T Args { get; set; }
}
```

- Cannot directly annotate the `[FromQueryParams]` attribute in Args;

Because this DTO model will have `GET` or `POST` request methods.

- Possible bug

Now we have discovered a problem where the same DTO model is being used by both GET and POST request Endpoint methods, while the POST request Endpoint method has no corresponding display information on the Swagger page.

**Comment by zfchai** [comment]
Perhaps the best practice:

- When requesting GET, the DTO model can be serialized as a JSON object.
- When making a POST request, simply keep the Body parameter model unchanged.

```csharp
o.FlattenSchema = true;
```

This method will lose the native JSON format corresponding to the DTO model!

**Comment by zfchai** [comment]
The problem has reproduced, please check https://github.com/FastEndpoints/FastEndpoints/issues/444
