### ISSUE TITLE
Does it support dapr integration?

### ISSUE THREAD

**Issue by zfchai** [FastEndpoints/FastEndpoints#442]
- https://docs.dapr.io/

**Comment by IeuanWalker** [comment]
@zfchai most likely.

Just remember FE is just a really nice wrapper for minimal apis, so anything you can do with that you can likely do with FE.

I also recommend you at least try it out before raising an issue, not fair to the maintainers or collaborators to keep answering questions like this.

**Comment by dj-nitehawk** [comment]
@IeuanWalker thank you! i was looking for a nice way to say that but you beat me to it 😉

@zfchai i understand you may be a beginner/intermediate coder, but please understand that this is free and open source software and we don't really have the time to hold your hand throughout your learning process. so going forward, if you post stuff that's not properly described or has nothing to do with FE, or is being too demanding, or it looks like you haven't made a reasonable effort to figure it out yourself, i will be closing those issues without any response/warning. keep doing that, and you will be blocked from accessing this repo. even with your previous questions, i've had to explain the same things to you multiple times but you still don't seem to get it and keep circling back to the same point wasting my time.

having said that, you can join our [discord server](https://discord.gg/ARGPxTukpr) and go bananas with your questions. people (including myself) will answer when we have free time.
