### ISSUE TITLE
Authorization/authentication for the Command Bus.

### ISSUE THREAD

**Issue by aynur-safin** [FastEndpoints/FastEndpoints#443]
I'm using Blazor Server, and to further secure requests to the backend, I wanted to bind authorization/authentication for the Command Bus. I'm combining an Endpoint and an ICommandHandler implementation and have written an extension that checks the authorization for the current request if it's not a FastEndpoint call. To do this, I change the endpoint of the current request to FastEndpoint endpoint and call "httpContext.AuthenticateAsync()". Please see if this can be done better or easier? Below are code examples. Thank you!

Request and Response: 
```cs
public class Request : ICommand<Response>
{
    public Company? Company { get; set; }
}

public class Response : Get.Response {}
```

Endpoint Extension for Command:
```cs
public async static Task<bool> CommandAuthorizeAsync(this FastEndpoints.BaseEndpoint endpoint,
    HttpContext? httpContext,
    IEnumerable<EndpointDataSource> endpointSources)
{
    if (endpoint.Definition == null) // is not Endpoint == is Command
    {
        if (httpContext != null)
        {
            var origEndpoint = httpContext.GetEndpoint();

            // get test endpoint
            var testEndpoint = endpointSources.SelectMany(es => es.Endpoints)
                .OfType<RouteEndpoint>()
                .Where(e => e.Metadata.GetMetadata<EndpointDefinition>() != null
                && e.Metadata.GetMetadata<EndpointDefinition>()!.EndpointType.FullName == endpoint.GetType().FullName)
                .Where(e => origEndpoint == null
                    || origEndpoint.Metadata.GetMetadata<EndpointDefinition>() == null
                    || origEndpoint.Metadata.GetMetadata<EndpointDefinition>()!.EndpointType.FullName != e.Metadata.GetMetadata<EndpointDefinition>()!.EndpointType.FullName)
                .FirstOrDefault();

            if (testEndpoint != null)
            {
                try
                {
                    httpContext.SetEndpoint(testEndpoint);
                    var authenticateResult = await httpContext.AuthenticateAsync();
                    if (!authenticateResult.Succeeded)
                    {
                        if (!httpContext.Response.HasStarted) // is not blazor server connection
                            await httpContext.Response.SendForbiddenAsync();

                        throw new Exception("Forbidden");
                        //return false;
                    }
                }
                finally
                {
                    httpContext.SetEndpoint(origEndpoint);
                }
            }
        }
    }

    return true;
}
```

Endpoint implementation:
```cs
public class Endpoint : Endpoint<Request, Response>, ICommandHandler<Request, Response>
{
    public override void Configure()
    {
        Post("/company/create");
        //AllowAnonymous();
    }

    private readonly AppDbContext _db;
    private readonly IHttpContextAccessor _contextAccessor;
    private readonly IEnumerable<EndpointDataSource> _endpointSources;

    public Endpoint(AppDbContext db,
        IHttpContextAccessor contextAccessor,
        IEnumerable<EndpointDataSource> endpointSources)
    {
        _db = db;
        _contextAccessor = contextAccessor;
        _endpointSources = endpointSources;
    }

    public override async Task<Response> ExecuteAsync(Request req, CancellationToken ct)
    {
        await this.CommandAuthorizeAsync(_contextAccessor.HttpContext, _endpointSources);
           
        _ = req.Company ?? throw new ArgumentNullException(nameof(req.Company));

        _db.Entry(req.Company).State = EntityState.Added;
        await _db.SaveChangesAsync();

        return new Response {  Company = req.Company };
    }
}
```
Call from Blazor Razor Page:
`var res = await new CreateEndpoint.Request { Company = _company }.ExecuteAsync(CancellationToken);`

**Comment by dj-nitehawk** [comment]
> I'm combining an Endpoint and an ICommandHandler

why exactly are you doing this? do you also have a REST client making http calls to the FE endpoint as well?

**Comment by aynur-safin** [comment]
> > I'm combining an Endpoint and an ICommandHandler
> 
> why exactly are you doing this? do you also have a REST client making http calls to the FE endpoint as well?

I am using Blazor Server (not WebAssembly). Yes, I can use HttpClient and make calls to the local server through it, but it seems to me that this is an overhead compared to a direct function call, in addition, direct calls are more convenient - everything is typed, there is less chance of making a mistake. But I also want to have an API built by FastEndpoint for use with other API clients.

**Comment by dj-nitehawk** [comment]
> everything is typed, there is less chance of making a mistake

well you could just use a [generated api client](https://fast-endpoints.com/docs/swagger-support#api-client-generation).
that would be a much cleaner approach and you won't lose any functionality like auth/validation etc.

the command bus is intended to sit behind the endpoint/api layer and was never meant to run pipeline steps such as auth/validation/pre|post processors etc.

what you're doing might work with some limitations but doesn't look like a clean approach to me. it's gonna be hard for someone other than yourself reading/maintaining the code in the future also. certainly took me a while and a bit of head scratching to understand it ;-)

> seems to me that this is an overhead compared to a direct function call

true but since there's no network latency involved, it should perform sufficiently. blazor server doesn't scale too well anyway, so you'd be okay serving a few hundred requests per second.

so yeah... that would be my advise. use a generated client and place all your app logic behind the same FE api layer.
