### ISSUE TITLE
Security. How to disable issued access token?

### ISSUE THREAD

**Issue by XaspMe** [FastEndpoints/FastEndpoints#445]
Please tell me how can I turn off the valid authorization token that was issued to the user, what is the name of the token reading method on the endpoint call?
I studied the topic, in such cases a blacklist is used, but I do not understand how I can check token for existing in blacklist when calling the endpoint.
Any advice would be helpful, thanks for the help!

**Comment by dj-nitehawk** [comment]
i agree with what @aroman35 said.
and you could possibly do the blacklist check by setting an action for the `OnTokenValidated` jwt bearer event like so:
```cs
builder.Services
    .AddFastEndpoints()
    .AddJWTBearerAuth("signing_key", bearerEvents: x =>
    {
        x.OnTokenValidated = async context =>
        {
            var token = context.Request.Headers["Authorization"].FirstOrDefault()?.Replace("Bearer ", "");
            if (TokenIsRevoked(token))
            {
                context.Fail("Token Revoked!");
            }
        };
    })
```
