### ISSUE TITLE
Output Format(ter)s Other Than JSON

### ISSUE THREAD

**Issue by akurone** [FastEndpoints/FastEndpoints#446]
Hi there,
First of all thanks for this hard work. I am currently evaluating alternatives that potentially can replace MVC controllers used as API endpoints in our project; and hence exploring FastEndpoints. 
I have a use case utilizing MVC output formatters: We do provide MessagePack encoding option (if the client sets the accept header in the request, response is encoded accordingly; all we do is to register an output formatter in service config actually: like `.AddMvc(o => o.OutputFormatters.Add(new MessagePackOutputFormatter()))`). 
I could not find out how i can utilize output formatters with FastEndpoints and after a skim through the docs and the source (Send & friends, HttpResponseExtensions) I think that FastEndpoints is JSON only (with binary/stream/string abilities when necessary). 
I would like to know (if i am not terribly wrong with my wildly fast conclusion): is this a design decision / implementation constraint or do you have plans to utilize output formatters?

**Comment by dj-nitehawk** [comment]
there's no concept of output formatters in asp.net minimal apis. so FE doesn't have them either. and there's no plans to implement it.

one of the ways to achieve that would be to write your own `Send*Async()` methods either as extension methods targetting `IEndpoint` [like this](https://github.com/FastEndpoints/FastEndpoints/issues/234#issuecomment-1246380441) or by creating your own endpoint base classes with custom `Send*Async()` methods.

or you could even do this:

```cs
public class MsgPackResponseHeaderAdder : IGlobalPreProcessor
{
    public Task PreProcessAsync(object req, HttpContext ctx, List<ValidationFailure> failures, CancellationToken ct)
    {
        if (ctx.Request.Headers.Accept.Contains("application/msgpack"))
            ctx.Response.Headers.ContentType = "application/msgpack";
        return Task.CompletedTask;
    }
}

app.UseFastEndpoints(c =>
{
    c.Endpoints.Configurator = ep =>
    {
        ep.PreProcessors(Order.Before, new MsgPackResponseHeaderAdder()); //register the pre-processor
    };
    c.Serializer.ResponseSerializer = (rsp, dto, cType, jCtx, ct) =>
    {
        if (rsp.Headers.ContentType == "application/msgpack") //if it was added by the pre-processor
        {
            rsp.HttpContext.MarkResponseStart();
            rsp.StatusCode = 200;
            return SerializeMsgPackToResponseStream(rsp, dto, ct);
        }
        return rsp.WriteAsJsonAsync(dto, dto.GetType(), jCtx?.Options, cType, ct);
    };
});
```

**Comment by akurone** [comment]
Thanks for your quick response! Now i know my options; i will utilize custom base with appropriate method since not all of my endpoints need to support MPACK. 

Putting this as a side note for future reference; let me know if it's wrong or misleading.
If someday minimal apis introduces same/similar concept, FE will have the _feature_ since it can do anything else minimal apis can do.

**Comment by dj-nitehawk** [comment]
yes 90% chance it will just work out of the box.
for example, in .net7, they introduced endpoint filters and FE internals didn't have to change at all to support that.
hard to say what the future will bring, but most likely it shouldn't be too difficult to make FE support it, since FE is simply an abstraction over minimal apis.
