### ISSUE TITLE
Is it possible to filter a route from Swagger (not the whole endpoint)

### ISSUE THREAD

**Issue by jerriep** [FastEndpoints/FastEndpoints#451]
Hi,

I have an endpoint defined with two routes as follows:

```
public class FromGoogleDocsEndpoint : Endpoint<FromGoogleDocsEndpoint.Command, JobStatusModel>
{
    public override void Configure()
    {
        AllowFormData();
        Post("export/google-docs", "exports/google-docs");
        Version(2);
    }
}
```

The second route (`exports/google-docs`) is a legacy route that will be removed sometime in the future, and as such, I do not want it to appear in the Swagger docs. I know that one can filter the endpoints from the Swagger docs ([as per your docs](https://fast-endpoints.com/docs/swagger-support#filtering-endpoints)), but that filters the entire endpoint and is not what I want to do in this case. I want just the one route of the endpoint filtered from the Swagger docs.

Is there a way to achieve this?

BTW, thank you for a wonderful project! I made a one-time contribution to OpenCollective. As a solo, bootstrapped founder, that is the best I can do at the moment, but if my income increases, I hope I can do something on a recurring basis.

**Comment by dj-nitehawk** [comment]
thank you for the contribution. much appreciated 🙏

the easiest way to filter out a path from a multi-route endpoint would be with a swagger operation filter like the following:

```cs
builder.Services.SwaggerDocument(o =>
{
    o.DocumentSettings = s =>
    {
        s.AddOperationFilter(ctx => ctx.OperationDescription.Path != "/exports/google-docs");
    };
});
```

if there are a lot of those or you'd like to abstract that away from the program.cs, you can implement it as an `IOperationFilter` like so:

```cs
public class HideEndpointsProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext ctx)
    {
        return ctx.OperationDescription.Path != "/exports/google-docs";
    }
}
```

and register it like so:

```cs
builder.Services.SwaggerDocument(o =>
{
    o.DocumentSettings = s =>
    {
        s.OperationProcessors.Add(new HideEndpointsProcessor());
    };
});
```
