### ISSUE TITLE
Dual support for OpenApi (v3) and Swagger (v2) specifications

### ISSUE THREAD

**Issue by jansonjc** [FastEndpoints/FastEndpoints#453]
I have a need to be able to generate Swagger v2.0 spec in addition to the latest Open Api v3.0 spec. I believe this is supported by NSwag as per their [documentation](https://github.com/RicoSuter/NSwag/blob/master/src/NSwag.Sample.NETCore20/Startup.cs). But, I'm not able to figure out how to get it done with FastEndpoints. The [SwaggerDocument](https://github.com/FastEndpoints/FastEndpoints/blob/931a1189724f5f7896b5393e70a094cac6c0ceab/Src/Swagger/Extensions.cs#LL36C12-L36C12)extension method only allows Open Api v3.0.

**Comment by KateyBee** [comment]
Hello!

You can specify the Swagger spec version as follows:
```cs
builder.Services.SwaggerDocument(o =>
{
    o.DocumentSettings = s =>
    {
        s.SchemaType = SchemaType.Swagger2;
    };
});
```

Let me know if that's not what you're after.

Thanks!

**Comment by jansonjc** [comment]
Thank you @KateyBee. In order to generate both v2 and v3 of the spec, I made two invocations to the SwaggerDocument extension method. This seems to be working. Is the approach correct?

```
builder.Services.SwaggerDocument(o =>
{
    o.DocumentSettings = s =>
    {
        s.DocumentName = "openapi";
        s.SchemaType = SchemaType.OpenApi3;
    };
});


builder.Services.SwaggerDocument(o =>
{
    o.DocumentSettings = s =>
    {
        s.DocumentName = "swagger";
        s.SchemaType = SchemaType.Swagger2;
    };
});
```

Thanks!
