### ISSUE TITLE
When support signalr?

### ISSUE THREAD

**Issue by wj8400684** [FastEndpoints/FastEndpoints#454]

**Comment by dj-nitehawk** [comment]
there's nothing to support. FastEndpoints is for building REST APIs. SignalR has nothing to do with REST. just use the SignalR hubs as you normally do.

**Comment by wj8400684** [comment]
![image](https://github.com/FastEndpoints/FastEndpoints/assets/39239954/7d8e9282-6a84-4e9a-b3ff-f51af3635201)I just think FastEndpoints are more elegant!

**Comment by dj-nitehawk** [comment]
that's true but SignalR is not based on asp.net minimal apis (which FE is built on).
so it's not compatible with the routing model of asp.net

however, we're investigating how to integrate inter-process-communication using something like [netmq](https://netmq.readthedocs.io/en/latest/) for FE's event/command bus, which would allow you do basically do what SignalR does.

it's a pretty difficult task to achieve. let's see what happens ;-)

**Comment by dj-nitehawk** [comment]
fyi, we no have remote-procedure-call support via grpc.
more info here: https://discord.com/channels/933662816458645504/1115702061246447708
