### ISSUE TITLE
Route order in fastendpoints library

### ISSUE THREAD

**Issue by itsoli91** [FastEndpoints/FastEndpoints#456]
How can I fix the route order in fastendpoints library? I have two routes: `/onboarding/{OnboardingId}` and `/onboarding/restore`. But fastendpoints always goes to the first route because it thinks restore is also an OnboardingId.

**Comment by nefarius** [comment]
This is an ASP.NET Core Routing behaviour, not FE, you can not influence this easily without hacking in some custom middleware or similar, better to overthink your route design and maybe if you can not change it, let the EP that handles `/onboarding/{OnboardingId}` also process the special case of `restore`?

**Comment by itsoli91** [comment]
In asp.net core we can use  route-constraints, is it also possible  in FE?

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/routing?view=aspnetcore-7.0#route-constraints

**Comment by itsoli91** [comment]
This is interesting... 
if I put the restore method on top of another method `http://localhost:5019/onboarding/restore` now returns 200 ok

```
app.MapGet("/onboarding/restore",
        ([FromQuery] string? crmId) =>
        {
            return $"Hi from /onboarding/restore?crmId={crmId}";
        })
    .WithOpenApi();

app.MapGet("/onboarding/{onboardingId:minlength(10)}",
        (string onboardingId) =>
        {
            return $"Hi from /onboarding/{onboardingId}";
        })
    .WithOpenApi();
```

**Comment by dj-nitehawk** [comment]
just tried the following and it works as expected:
```cs
public class RestoreRequest
{
    [QueryParam]
    public string CrmId { get; set; }
}

public class RestoreEndpoint : Endpoint<RestoreRequest>
{
    public override void Configure()
    {
        Get("/onboarding/restore");
        AllowAnonymous();
    }

    public override async Task HandleAsync(RestoreRequest r, CancellationToken c)
    {
        await SendAsync($"Hi from /onboarding/restore?crmId={r.CrmId}");
    }
}

public class OnboardingEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("/onboarding/{onboardingId:minlength(10)}");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync($"Hi from /onboarding/{Route<string>("onboardingId")}");
    }
}
```
