### ISSUE TITLE
ExecuteAsync

### ISSUE THREAD

**Issue by sammontakoja** [FastEndpoints/FastEndpoints#461]
When using endpoint ExecuteAsync function then how cann you change response http status?Thanks!

**Comment by sammontakoja** [comment]
I read through docs and those examples show how it's done using HandleAsync function and not how to do it with ExecuteAsync. I prefer ExecuteAsync function bec it's is easier to unit test.

**Comment by KateyBee** [comment]
@sammontakoja You can just use the regular `Send*()` methods like this and at the end return your response DTO.

```cs
public class Endpoint : EndpointWithoutRequest<Response>
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task<Response> ExecuteAsync(CancellationToken ct)
    {
        var response = new Response
        {
            Msg = "hello!"
        };

        await SendAsync(response, 201);

        return response;
    }
}

public class Response
{
    public string Msg { get; set; }
}
```

However, do note, that you can only assert on the property values of the returned result DTO. You won't be able to assert on the HTTP status codes or anything else related to the HttpContext. For that you need to be doing integration tests.
