### ISSUE TITLE
Use another mapping in mapper.

### ISSUE THREAD

**Issue by ErenKrt** [FastEndpoints/FastEndpoints#462]
Hello guys, i have two object as "Role" and "Permissions". Im showing Permissions under the role and i need map in response.

This is my permission mapper.
```csharp
public class GetMapper : Mapper<GetRequest, PermissionDTO, Core.Entities.Permission>
    {
        public override PermissionDTO FromEntity(Core.Entities.Permission e)
        {
            return new PermissionDTO()
            {
                Name = e.Name,
                ID = e.ID,
                Description= e.Description
            };
        }
    }
```

And this is my role mapper. (i tried like that but not work)
```csharp
public class GetMapper : Mapper<GetRequest, RoleDTO, Core.Entities.Role>
    {
        public override RoleDTO FromEntity(Core.Entities.Role e)
        {
            
            var permMapper = Resolve<Permission.Get.GetMapper>();

            return new RoleDTO()
            {
                Name = e.Name,
                ID = e.ID,
                Permissions= e.Permissions.Select(x=> permMapper.FromEntity(x)).ToList()
            };
         }
    }
```

**Comment by KateyBee** [comment]
Hello!

I think your problem is `var permMapper = Resolve<Permission.Get.GetMapper>()` because Mappers are not registered in DI if you haven't done that yourself.

Can you try instantiating the permMapper instead of resolving it?

```cs
var permMapper = new Permission.Get.GetMapper();
```

Does that help?

**Comment by IeuanWalker** [comment]
@ErenKrt i personal rather keep my mapper as a single entity and not use external methods/ mappers.

So personally i would just set up the mapper for the permission inside the role mapper

 i.e. instead of -
```csharp
Permissions= e.Permissions.Select(x=> permMapper.FromEntity(x)).ToList()
```
Id just do -
```csharp
Permissions = e.Permissions.Select(x => new PermissionDTO()
{
	Name = e.Name,
	ID = e.ID,
	Description = e.Description
}).ToList()
```

**Comment by KateyBee** [comment]
I agree with @IeuanWalker specially if you're doing Vertical Slice Architecture and need to keep the v-slices independent of each other. It does feel iffy when a mapper has a reference to another mapper imho.
