### ISSUE TITLE
Log automatic 400 responses

### ISSUE THREAD

**Issue by jansonjc** [FastEndpoints/FastEndpoints#464]
How do I achieve [automated logging of 400 responses](https://learn.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-7.0#log-automatic-400-responses) in FastEndpoints?

I couldn't find an equivalent of ConfigureApiBehaviorOptions or InvalidModelStateResponseFactory delegate.

**Comment by dj-nitehawk** [comment]
you could do it either inside a custom error response builder func: https://fast-endpoints.com/docs/configuration-settings#customizing-error-responses

or using a global post-processor like this: https://fast-endpoints.com/docs/exception-handler#the-better-approach

let me know if that doesn't do it and i'll look in to it further.

**Comment by jansonjc** [comment]
Thank you! I added a global post-processor and works great. The documentation may need a change though.

1. PostProcessors method has a new parameter (**Order enum**)
2. PostProcessAsync method's second argument is nullable (**object? res**)

```
app.UseFastEndpoints(c =>
{
    c.Endpoints.Configurator = ep =>
    {
        ep.PostProcessors(Order.After, new ErrorLogger());
    };
});
```
```
public class ErrorLogger : IGlobalPostProcessor
{
    public Task PostProcessAsync(object req, object? res, HttpContext ctx, IReadOnlyCollection<ValidationFailure> failures, CancellationToken ct)
    {
        if (failures.Count > 0)
        {
            var logger = ctx.Resolve<ILogger<ErrorLogger>>();
            logger.LogWarning("Validation error count: {@count}", failures.Count);
        }
        return Task.CompletedTask;
    }
}
```

**Comment by jansonjc** [comment]
I agree that post-processor example may not be needed. Since it is mentioned in the [Exception Handler](https://fast-endpoints.com/docs/exception-handler#the-better-approach) section, I suggest we correct the documentation there as well.

![image](https://github.com/FastEndpoints/FastEndpoints/assets/20315731/c29c8497-460f-4006-85ab-c861cbf14d62)

**Comment by dj-nitehawk** [comment]
done...
