### ISSUE TITLE
FastEndpoint Does not allowing to use Custom Complex Dto in query string

### ISSUE THREAD

**Issue by Shweta-Gardiant** [FastEndpoints/FastEndpoints#469]
Actually I was trying to add one custom Dto which is little complex but Fast endpoint failing to bind it in query string.

**Comment by nefarius** [comment]
What DTO? With which query string? Code? Examples? Anything?

**Comment by Shweta-Gardiant** [comment]
![image](https://github.com/FastEndpoints/FastEndpoints/assets/140780608/13b8696d-482d-47b8-9bfc-471014becd75)
I have this request Dto Model and I want to use this in Get Request as a request parameter but model binding is failing and I am getting null Filters and Sort Criteria.
![image](https://github.com/FastEndpoints/FastEndpoints/assets/140780608/91ff1dd4-8845-4a14-9666-effee98dc67e)
You can find my controller here.

**Comment by nefarius** [comment]
Please paste code as actual text, not screenshots, so people can actually quite and correct it without wasting a day transcribing your code.

**Comment by KateyBee** [comment]
Yeah not enough information was provided for us to help you @Shweta-Gardiant 

The built-in model binder only "officially" supports the query string formats listed [here](https://fast-endpoints.com/docs/model-binding#from-query-parameters). So the recommended approach to send complex objects via query parameters is to send them as JSON.

What does the actual query string look like and what does the DTO being bound to look like?
We're going to need to see the nested complex types as well. At least a simplified version of it.

**Comment by Shweta-Gardiant** [comment]
` public class DocumentsRequestDto
    {

        public DocumentFilters Filters { get; set; }
        public SortCriteria SortCriteria { get; set; }
    }
 public class DocumentFilters
    {
        public bool ShowTrash { get; set; }
        public string SearchTerm { get; set; }
        public List<long> CreatedByIds { get; set; }
    }
public class SortCriteria
    {
        public int? Take { get; set; }
        public int? Skip { get; set; }
    }`

So I have this DTo file.


`  
        public override void Configure()
        {
            Post("/documents/filter");
            Group<ClaimGroup>();
        }

        public override async Task HandleAsync(DocumentsRequestDto request, CancellationToken ct)
        {
            var result = await _documentService.GetDocuments(request);
            await SendOkAsync(result);
        }`

When I am passing with this request , I am getting Filters and sortCriteria as null , unable to file way to bind the model with this complex dto.

**Comment by KateyBee** [comment]
You forgot to mention the query string data being sent in from the client.

**Comment by Shweta-Gardiant** [comment]
https://localhost:7030/documents?showTrash=true&searchTerm=shweta&createdByIds=0&take=0&skip=0
Here is my query string

**Comment by KateyBee** [comment]
The thing to note here is that, in Minimal APIs, binding complex DTOs from query parameters is not supported out of the box (most likely due to poor performance). 

You'd have to write your own static [TryParse](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/parameter-binding?view=aspnetcore-7.0#custom-binding) method to do the binding.

But in FE, you have the alternative option to send in the complex data as JSON, and here's how you'd do it:
```cs
using FastEndpoints;
using FastEndpoints.Swagger;
using System.ComponentModel;

var bld = WebApplication.CreateBuilder();
bld.Services
   .AddFastEndpoints()
   .SwaggerDocument();

var app = bld.Build();
app.UseAuthorization()
   .UseFastEndpoints(o => o.Serializer.Options.PropertyNamingPolicy = null)
   .UseSwaggerGen();
app.Run();

sealed class TestEndpoint : Endpoint<DocumentsRequestDto>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
        Description(x => x.Accepts<DocumentsRequestDto>()); //required only if all properties of the
                                                            //request DTO is marked with [QueryParam] attribute
    }

    public override async Task HandleAsync(DocumentsRequestDto req, CancellationToken ct)
    {
        await SendAsync(req);
    }
}

sealed class DocumentsRequestDto
{
    [QueryParam] //tells swagger to add it as a query parameter
    [DefaultValue("{\"ShowTrash\":true,\"SearchTerm\":\"term\",\"CreatedByIds\":[100,200]}")]
    public DocumentFilters Filters { get; set; }

    [QueryParam]
    [DefaultValue("{\"Take\":10,\"Skip\":0}")]
    public SortCriteria SortCriteria { get; set; }
}

sealed class DocumentFilters
{
    public bool ShowTrash { get; set; }
    public string SearchTerm { get; set; }
    public List<long> CreatedByIds { get; set; }
}

sealed class SortCriteria
{
    public int? Take { get; set; }
    public int? Skip { get; set; }
}
```
![image](https://github.com/FastEndpoints/FastEndpoints/assets/134909513/cfe3f0fc-e99a-4623-b2b5-81da9b85977c)
