### ISSUE TITLE
Possible Jwt related breakage starting with FE 5.14

### ISSUE THREAD

**Issue by havremunken** [FastEndpoints/FastEndpoints#470]
Hi,

I discovered a problem and discussed it in this thread on the Discord server:

https://discord.com/channels/933662816458645504/1140308053535764554

If we disregard the ReSharper stuff (which might be a red herring), I can 100% reproduce this problem:

By upgrading FastEndpoints (and .Security) from 5.13 to 5.14, my call to JWTBearer.CreateToken() lifted almost verbatim from the documentation (it just adds an issuer call and some specific claims/roles) will start giving the following exception:

```
System.NullReferenceException
Object reference not set to an instance of an object.
   at FastEndpoints.Security.JWTBearer.CreateToken(String signingKey, Nullable`1 expireAt, IEnumerable`1 permissions, IEnumerable`1 roles, IEnumerable`1 claims, String issuer, String audience, TokenSigningStyle signingStyle)
   at FastEndpoints.Security.JWTBearer.CreateToken(String signingKey, Action`1 priviledges, String issuer, String audience, Nullable`1 expireAt, TokenSigningStyle signingStyle)
```

It could of course be a problem with my code, but the problem does not appear in 5.13 or earlier versions of FastEndpoints, so something must have changed somewhere to break this behavior. 

I can reproduce the problem easily if needed for diagnostic purposes. Happy to help track this down - if it turns out that this is not just a "me" problem. :)

**Comment by havremunken** [comment]
I can also confirm that upgrading `System.IdentityModel.Tokens.Jwt` to 6.32.1 and `Microsoft.AspNetCore.Authentication.JwtBearer` to 7.0.10 does *not* cause any test failures, as long as I leave the FastEndpoint packages at 7.13.

**Comment by dj-nitehawk** [comment]
@havremunken we haven't been able to replicate this on our end. and there's no reports from any other users as well. if you're still encountering it, please send a repro project we could debug. i'll close this in the meantime. feel free to re-open with the repro. thanks!
