### ISSUE TITLE
Source generator does not discover endpoints in nested classes

### ISSUE THREAD

**Issue by ekspedycja** [FastEndpoints/FastEndpoints#471]
Hi,

I have been working my project that uses quite a lot of generated code. I am also using vertical-slices approach with class by feature approach. 

Long story short - my use case requires the endpoint class to be a nested class. Currently the code generated by the source generator does not see the class.  

I found a workaround for that if someone is interested.  

This also simplified the code a little bit - BTW is there a reason for so much workarounds and exclusions in current generator's code? 

Here is my approach for file: Src/Generator/EndpointsDiscoveryGenerator.cs

```CS
[Generator(LanguageNames.CSharp)]
public class EndpointsDiscoveryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeDeclarationSyntaxProvider = context.SyntaxProvider.CreateSyntaxProvider(
                (sn, _) => sn is TypeDeclarationSyntax,
                (c, _) => Transform(c))
            .Where(p => p is not null);

        var compilationAndClasses = context.CompilationProvider.Combine(typeDeclarationSyntaxProvider.Collect());

        context.RegisterSourceOutput(compilationAndClasses, (spc, source) => Execute(source.Left, source.Right, spc));
    }

    private void Execute(ImmutableArray<ITypeSymbol> typeSymbols, SourceProductionContext spc)
    {
        if (!typeSymbols.Any())
            return;
        var fileContent = GetContent(typeSymbols);
        spc.AddSource(
            "DiscoveredTypes.g.cs",
            SourceText.From(fileContent,
                Encoding.UTF8));
    }

    private ITypeSymbol? Transform(GeneratorSyntaxContext ctx)
    {
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node);
        if (symbol is not ITypeSymbol typeSymbol) return null;
        var isEndpoint = typeSymbol.AllInterfaces.Select(i => new TypeDescription(i)).Intersect(new[]
        {
            new TypeDescription("FastEndpoints.IEndpoint"),
            new TypeDescription("FastEndpoints.IEventHandler"),
            new TypeDescription("FastEndpoints.ICommandHandler"),
            new TypeDescription("FastEndpoints.ISummary"),
        }).Any() && typeSymbol is { IsAbstract: false, DeclaredAccessibility: Accessibility.Public };
        return isEndpoint ? typeSymbol : null;
    }

    private static string GetContent(IEnumerable<ITypeSymbol> filteredTypes)
    {
        var sb = new StringBuilder(@"
using System;
namespace FastEndpoints
{
    public static class DiscoveredTypes
    {
        public static readonly System.Type[] All = new System.Type[]
        {
");

        foreach (var discoveredType in filteredTypes)
        {
            sb.Append("            typeof(")
                .Append(discoveredType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).Append(@"),
");
        }

        sb.Append(@"        };
    }
}");
        return sb.ToString();
    }
}

**Comment by dj-nitehawk** [comment]
@nefarius would you like to take this one?

@ekspedycja can you pls send your changes in as PR so it's easy to what you've done pls?

**Comment by ekspedycja** [comment]
https://github.com/FastEndpoints/FastEndpoints/pull/472

**Comment by dj-nitehawk** [comment]
`5.15.0.22-beta` pushed to nuget if you guys wanna give it a test run.

**Comment by dj-nitehawk** [comment]
@ekspedycja @nefarius 
guys it's been reported that the new source generator does not discover types from referenced assemblies in the same solution.
i've put together a small [repro](https://github.com/FastEndpoints/FastEndpoints/files/12473299/SourceGenRepro.zip) showing what the issue is.

i have absolutely no clue on how to remedy this. any ideas?

thanks!

**Comment by KateyBee** [comment]
Issue solved with a minor breaking change to how we register the discovered types :-)

 The source generator no longer automatically discovers types from referenced assemblies/projects. 
 You now have to add the `FastEndpoints.Generator` package to each project you'd like to use type discovery with and register the discovered types per assembly like so: 
 ```cs 
 builder.Services.AddFastEndpoints(o => 
 { 
     o.SourceGeneratorDiscoveredTypes.AddRange(MyApplication.DiscoveredTypes.All); 
     o.SourceGeneratorDiscoveredTypes.AddRange(SomeClassLib.DiscoveredTypes.All); 
 }) 
 ```

**Comment by nefarius** [comment]
We should [add that to the documentation](https://fast-endpoints.com/docs/configuration-settings#source-generator-based-startup) as it's not immediately self-explanatory what's happening now, IMHO.
