### ISSUE TITLE
Summary does not use json converters registered with swagger or fastendpoints

### ISSUE THREAD

**Issue by rsr-maersk** [FastEndpoints/FastEndpoints#473]
Hi.
Awesome package thanks!

We have added converts to swagger and fast endpoint registration. But the "Summary" does not seam to use it for the example.

```c#
static void ConfigSerializer(JsonSerializerOptions options)
{
    options.PropertyNameCaseInsensitive = true;
    options.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
    options.Converters..Add(new ZonedDateTimeConverter.SystemTextJsonConverter(writeLocalTime));
    options.Converters.Add(new JsonStringEnumConverter());
    options.Converters.Add(NodaConverters.InstantConverter);
    options.Converters.Add(NodaConverters.OffsetDateTimeConverter);
    options.Converters.Add(NodaConverters.LocalDateTimeConverter);
    options.Converters.Add(NodaConverters.LocalDateConverter);
}
```
registration
```c#
builder.Services.SwaggerDocument(options =>
{
    options.DocumentSettings = s =>
    {
        s.Title = "SCP.Timestamp.Examples.PostgresWebApi";
        s.Version = "0.1";
    };
    options.SerializerSettings = (o) => ConfigSerializer(o);
}); //define a swagger document


App:
```c#
app.UseFastEndpoints(c =>
{
    ConfigSerializer(c.Serializer.Options);
});```

However the summary does not appear to call the converter for ZonedDateTime that is in ZonedDateTimeConverter. Any thoughts as to why?

```c#
public override void Configure()
    {
        Post("/api/transportleg/import");
        AllowAnonymous();
        Summary(s =>
        {
            s.Summary = "Example demonstrating how to ingest a date time when the client provides a timezone";
            s.ExampleRequest = new CreateTransportLegFromUiReq(new TransportLegFromUiDto()
            {
                PortOfDischargeCode = "Foo",
                PortOfLoadingCode = "Bar",
                DepartureTime = new ZonedDateTime(DateTime.UtcNow.Subtract(TimeSpan.FromDays(30)).ToInstant(),
                    DateTimeZoneProviders.Tzdb["America/New_York"]),
                ArrivalTime = new ZonedDateTime(DateTime.UtcNow.Subtract(TimeSpan.FromDays(7)).ToInstant(),
                    DateTimeZoneProviders.Tzdb["Asia/Kolkata"]),
            });
        });
    }
```

Looks like it is using ToString on the object and not the converters

**Comment by rsr-maersk** [comment]
@dj-nitehawk awesome. thanks!!!

**Comment by rsr-maersk** [comment]
no cigar with the 

```
.SwaggerDocument(o =>
{
   o.NewtonsoftSettings = s =>
   {
       s.Converters.Add(new ZonedDateTimeConverter());
   };
});
```

and package v5.15.0.19-beta didn't seam to do the trick. The custom converter wasn't being picked up

**Comment by dj-nitehawk** [comment]
can you try the following project?

[Example-Project.zip](https://github.com/FastEndpoints/FastEndpoints/files/12427220/Example-Project.zip)

the custom converter does get called:
![screen-record-1692865557](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/fc1ec34a-38e5-4739-b3ae-b37b07409ee2)

update the project and send back if you can reproduce the problem.

**Comment by rsr-maersk** [comment]
HI @dj-nitehawk Any update is the NSwag accepts the System.Json.Text SerializerSettings yet?

**Comment by dj-nitehawk** [comment]
@rsr-maersk sadly still the same. uses newtonsoft mostly. so you're gonna need to make newtonsoft versions of any custom converters.

**Comment by dj-nitehawk** [comment]
@rsr-maersk thought you might find this info interesting: https://discord.com/channels/933662816458645504/1255257287291834560/1255915229431332934

apparently, nswag doesn't have the ability to execute json converters when generating the swagger doc.
custom converters added to the swagger doc would only get picked up by the FE swagger processor when generating examples and default values. if those code paths are not hit, custom converters are not used by nswag itself.

solution is to register something nswag calls a "type mapper". details in the discord thread.

**Comment by dziedrius** [comment]
@dj-nitehawk trying to open mentioned discord thread fails, so can't see suggested solution, but still, wondering if this should come as fast endpoints feature, so that people would not need to mangle through several places to set it up cleanly.

**Comment by dj-nitehawk** [comment]
@dziedrius 
i believe you need to join the discord server first before being able to see posts there. use [this invite link](https://discord.gg/ARGPxTukpr) first and then click on the above link (which is still valid).

anyhow, this behavior is documented [here](https://fast-endpoints.com/docs/swagger-support#custom-converters).

> wondering if this should come as fast endpoints feature

there's a limit to what FE can offer as conveniences. unfortunately this is one of the cases we haven't figured out a nice solution which requires the user to take care of it with the suggested solution. if someone has any ideas, PRs are always welcome.
