### ISSUE TITLE
BuildSecurityPolicies method causing random InvalidOperationExceptions

### ISSUE THREAD

**Issue by savagja** [FastEndpoints/FastEndpoints#474]
I receive a transient (not always reproduceable) exception when using FastEndpoints. 

Its been my experience that when exceptions happen sometimes, but not always, they are almost always ASYNC related issues. The actual error I receive is: 

> An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll
> Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.

And the relevant stack trace is:

> at System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported() in /_/src/libraries/System.Private.CoreLib/src/System/ThrowHelper.cs:line 450
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:line 642
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value) in /_/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/Dictionary.cs:line 206
   at Microsoft.AspNetCore.Authorization.AuthorizationOptions.AddPolicy(String name, Action`1 configurePolicy)
   at FastEndpoints.MainExtensions.<BuildSecurityPoliciesForEndpoints>d__5.MoveNext()
   at FastEndpoints.MainExtensions.<>c__DisplayClass0_0.<<AddFastEndpoints>b__0>d.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state) in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:line 1917
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 979
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/ThreadPoolWorkQueue.cs:line 790
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/PortableThreadPool.WorkerThread.cs:line 63
   at System.Threading.Thread.StartCallback() in /_/src/coreclr/System.Private.CoreLib/src/System/Threading/Thread.CoreCLR.cs:line 106

The line that is actually adding to a standard dictionary is 
> Microsoft.AspNetCore.Authorization.AuthorizationOptions.AddPolicy(String name, Action`1 configurePolicy)

Which is being called by
> FastEndpoints.MainExtensions.<BuildSecurityPoliciesForEndpoints>d__5.MoveNext()

When googling for potential issues and solutions, I found an issue in the dotnet repo https://github.com/dotnet/aspnetcore/issues/7849

They essentially say that AuthorizationOptions aren't meant to be modified after startup. In theory, the AddFastEndpoints is startup code, however, after looking into your source code I found:

```
services.AddAuthorization(async o => await BuildSecurityPoliciesForEndpoints(o, services)); //this method doesn't block
```
This is line 32 of Src/Library/Main/MainExtensions.cs 

A couple of things pop in my head:
1. AddAuthorization takes an Action, which returns void, this implementation uses an async call on that, which now returns async void, which has been generally shown to cause havoc
2.  Since this is async, and not returning a task, it is running somewhere on its own, potentially AFTER startup, or at least still running AFTER startup...  sometimes - hence the error sometimes, but not always. 

Potential solutions:

1. I think the best approach is for the BuildSecurityPoliciesForEndpoints(AuthorizationOptions opts, IServiceCollection services) to NOT return a Task - this should be a void method and NOT async. The only reason its now an async task is because of the delay loop which by comment should not happen unless its called early - better to check and throw than to have a random async error
2. The other solution, if the async approach is deemed necessary - is to follow Microsoft's recommendation of implementing your own  custom options and authorization provider and using a concurrent dictionary . This is a lot more work, and potential for other problems, vs. removing an "async void" issue

**Comment by dj-nitehawk** [comment]
do you get the `InvalidOperationException` during regular app launch or during test runs?

**Comment by savagja** [comment]
During regular app runs. This occurs both locally in a dev environment and on a production server. 

The current work around is to keep restarting, it eventually starts, sometimes it takes no restarts, sometimes it takes several.

**Comment by dj-nitehawk** [comment]
alright... give the latest beta a try and report back pls :-)

**Comment by dj-nitehawk** [comment]
can you try `v5.15.0.20-beta` and let me know if you still get the transient exception?
i've gotten rid of the async void as you suggested.
thanks!

**Comment by savagja** [comment]
I'll check it out!

**Comment by savagja** [comment]
The system seems gets stuck in an infinite loop on the Thread.Sleep().

The call is waiting for ep.IsInitialized, however, that seems to get set from the EndPointDefinition.Initialize() extension method, which by default gets called via.... app.UseFastEndpoints() => MapFastEndpoints() => (line 78) ep.Initialize()

So the services.AddFastPoints() blocks waiting for initialized endpoints, but endpoints aren't initialized until the app is built and app.UseFastEndPoints() is called... which can never get there with Thread.Sleep()

I've at least confirmed that the Thread.Sleep is being hit as I replaced it with a throw and in fact am getting my thrown exception

**Comment by dj-nitehawk** [comment]
there are no blocking calls inside `AddFastPoints()` as you can see from this: https://streamable.com/ik2j2f
the `BuildSecurityPoliciesForEndpoints()` method is called last in the flow of execution.

in the rare occassion it's called before `UseFastEndpoints() => MapFastEndpoints() => ep.Initialize()`, it should NOT be blocking the `AddFastPoints()` call which returns immediately.

could it be something you're doing in your app's config/startup that's causing this behavior? if not how much thousands of other's using FE don't see this behavior.

and i myself for the life of me can't get the app to hit that `Thread.Sleep()` line no matter what sort of startup config i try.

can you modify the attached repro project to replicate the behavior you're seeing?
it has the FE source referenced so you can debug locally.

[Repro.zip](https://github.com/FastEndpoints/FastEndpoints/files/12424975/Repro.zip)

oh and don't forget to delete the `bin` and `obj` folders before zipping up the files again.

thanks!

**Comment by savagja** [comment]
I've added TestApp2 to the repo, it will hit the Thread.Sleep() if you stick a breakpoint there.

The difference is that in TestApp2 I also add and map controllers. 

[Repro-response.zip](https://github.com/FastEndpoints/FastEndpoints/files/12430688/Repro-response.zip)

**Comment by dj-nitehawk** [comment]
the solution is quite simple actually. just call `UseFastEndpoints()` before calling `MapControllers()`

```cs
app.UseHttpsRedirection();
app.UseStaticFiles();
app.UseRouting();
app.UseAuthorization();
app.UseFastEndpoints(); //call this before MapControllers
app.MapControllers();
app.Run();
```

`MapControllers()` is the culprit forcing the execution of `BuildSecurityPoliciesForEndpoints()`. when you switch the order around, the FE definitions are now already initialized.

i'll change the code so that it throws (instead of waiting) to warn the user about the potential ordering problem.

thank you very much for your help in identifying this edge case.
