### ISSUE TITLE
Job Queues: how to read stored command objects?

### ISSUE THREAD

**Issue by YandyZaldivar** [FastEndpoints/FastEndpoints#480]
I am using EF as the backend storage for Job Queues.

When you create an entity that implements the `IJobStorageRecord` interface there is not a nice way to deal with the `object` type of the `Command` property.

Everything would be much simpler just by changing the type from `object` to `string`, or add this as an alternative.

When saving to the database it is easy to serialize the object to a json string, but when reading it back you can't deserialize, because you don't know the type of command.

Finding a workaround is possible by storing the full object name and using reflection. But such complexity feels foreign to FastEndpoints.

A nice solution could be to provide an optional function converter like `TCommand From<TCommand>(string value)`.

Or be resilient enough to assume that in the following code `record.Command` could be a json string, and in that case instead of autocasting, you deserialize into a TCommand.

![image](https://github.com/FastEndpoints/FastEndpoints/assets/13922845/ced96f92-4486-4b25-a482-90b5b439d910)

**Comment by dj-nitehawk** [comment]
haven't used EF in almost over 10yrs.
wouldn't something like this work?
```cs
public class MyRecord : IJobStorageRecord
{
    [NotMapped]
    public object Command {
        get {
            return JsonSerializer.Deserialize(CmdString, CmdType);
        }
        set {
            CmdString = JsonSerializer.Serialize(value);
            CmdType = value.GetType();
        }
    }
    public string CmdString { get; set; }
    public Type CmdType { get; set; }

    public string QueueID { get; set; }
    public DateTime ExecuteAfter { get; set; }
    public DateTime ExpireOn { get; set; }
    public bool IsComplete { get; set; }
}
```
didn't try it myself.
if that doesn't work, you'll just have to use a nosql db such as mongodb, litedb, etc.

**Comment by YandyZaldivar** [comment]
Something like that could be the workaround I described, but more complicated. You cannot store the Type CmdType just like that, you need to represent it with a string, and yet more complications will follow, for example, my Job entities are defined in a different assembly than the Commands, so the Entities don't have access to the Command types.

This issue is not related to EF, it will affect other storages, and you are forced to use binary serialization, even with NoSQL, notice the BSON serializer in the MongoDB example:

![image](https://github.com/FastEndpoints/FastEndpoints/assets/13922845/98631609-ba75-458a-bb36-264ee24f1c55)

On top of that, even if a NoSQL db makes sense, why to force ppl into it.

In my opinion this is mostly a design issue. I see some possible solutions to improve this design, and all of them are backward compatible and won't introduce any breaking change to existing code:

1- Because Command is an object we can assign a json string to it. So when you are casting the `object` to the `Command` you can check if the type is a string and perform by convention a JSON deserialization. With that approach something like this will be enough:
```csharp
public class BaseJob : EntityRoot<Guid>, IJobStorageRecord
{
    public string QueueID { get; set; } = default!;
    public DateTime ExecuteAfter { get; set; }
    public DateTime ExpireOn { get; set; }
    public bool IsComplete { get; set; }
    public string? LastErrorMessage { get; set; }

    [NotMapped]
    public object Command { get; set; } = default!;

    [Column(nameof(Command))]
    public string MappedCommand
    {
        get => JsonSerializer.Serialize(Command);
        set => Command = value;
    }
}
```

2- Introduce an optional `CmdStr` field to the `IJobStorageRecord` interface, then if the `Command` field is not set you use the CmdStr field to create the Command object by json deserialization.

3- When casting from `IJobStorageRecord.Command` to the intended `Command` object, you present to the user a configuration function so the user can decide how to perform the mapping from one object to the other.

**Comment by dj-nitehawk** [comment]
couple of things:

- i don't wanna bake in json serialization into the library as it's the slowest.
- messagepack would be the ideal serializer but i don't want to add a reference to that package just for job serialization.

so, for EF users, here's my suggested approach with messagepack:

```cs
using FastEndpoints;
using MessagePack;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

public class JobRecord : IJobStorageRecord
{
    public Guid Id { get; set; }
    public string QueueID { get; set; }
    public object Command { get; set; }
    public DateTime ExecuteAfter { get; set; }
    public DateTime ExpireOn { get; set; }
    public bool IsComplete { get; set; }
}

public class MyDB : DbContext
{
    public DbSet<JobRecord> Jobs { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder o)
        => o.UseSqlite("Data Source=JobDatabase");

    protected override void OnModelCreating(ModelBuilder b)
    {
        MessagePackSerializer.DefaultOptions
            = MessagePack.Resolvers.ContractlessStandardResolver.Options;

        var converter = new ValueConverter<object, byte[]>(
            v => Serialize(v),
            v => Deserialize(v));

        b.Entity<JobRecord>()
            .Property(e => e.Command)
            .HasConversion(converter)
            .HasColumnType("BLOB"); //VARBINARY for sql server
    }

    static byte[] Serialize(object cmd) => MessagePackSerializer.Serialize(cmd);
    static object Deserialize(byte[] cmdBytes) => MessagePackSerializer.Deserialize<object>(cmdBytes);
}
```

the downside ofcourse would be that you lose the ability to look at/understand the stored command objects in the database.
but then again, if the need arises, you can just do a query with the job id and retrieve it via EF dbcontext.

**Comment by YandyZaldivar** [comment]
> * messagepack would be the ideal serializer but i don't want to add a reference to that package just for job serialization.

Me neither, even with your proposal working fine, I can't justify adding this dependency.

> * i don't wanna bake in json serialization into the library as it's the slowest.

That's why I proposed the option number 3. 
- Zero performance hit and behavior change for core library
- Zero breaking changes or weird assumptions
- High flexibility impact for FastEndpoints users

Here is a Pull request with the whole idea #481

**Comment by dj-nitehawk** [comment]
so with the new update, this is how you'd be using it?

```cs
public class JobRecord : IJobStorageRecord
{
    public Guid Id { get; set; }
    public string QueueID { get; set; }
    public string CommandJson { get; set; } //add this
    public DateTime ExecuteAfter { get; set; }
    public DateTime ExpireOn { get; set; }
    public bool IsComplete { get; set; }

    //add this
    TCommand IJobStorageRecord.GetCommand<TCommand>()
        => JsonSerializer.Deserialize<TCommand>(CommandJson) ?? throw new InvalidOperationException();

    [NotMapped] //add this
    public object Command { get; set; }
}
```

**Comment by dj-nitehawk** [comment]
in `v5.17.1.8-beta` added a set method as well. now it can be simplified like this:
```cs
public class JobRecord : IJobStorageRecord
{
    public Guid Id { get; set; }
    public string QueueID { get; set; }
    public DateTime ExecuteAfter { get; set; }
    public DateTime ExpireOn { get; set; }
    public bool IsComplete { get; set; }
    public string CommandJson { get; set; } //add this

    //add this
    TCommand IJobStorageRecord.GetCommand<TCommand>()
         => JsonSerializer.Deserialize<TCommand>(CommandJson)!;

    //add this
    void IJobStorageRecord.SetCommand<TCommand>(TCommand command)
         => CommandJson = JsonSerializer.Serialize(command);

    [NotMapped] //do this
    public object Command { get; set; }
}
```

**Comment by YandyZaldivar** [comment]
Thank you for considering the idea!

Yes, that is how it should be used, by implementing those methods when needed, and it works for any custom parsing and serialization method.

This removes a lot of complications, I need to dispose my current workaround and start using the new behavior, but I am confident this was all needed for the topic.
