### ISSUE TITLE
Injecting IAuthorizationService in Endpoints messes with FastEndpoints initialization

### ISSUE THREAD

**Issue by fredrik-forssen-cint** [FastEndpoints/FastEndpoints#482]
If you use imperative resource based authorization by injecting `IAuthorizationService` according to the [MSDN documentation](https://learn.microsoft.com/en-us/aspnet/core/security/authorization/resourcebased?view=aspnetcore-7.0) then FastEndpoints will throw the following exception when calling `UseFastEndpoints`:

```
System.InvalidOperationException
Endpoints are not initialized! This usually happens when 'app.UseFastEndpoints()' is placed after 'app.MapControllers()'. Try changing the middleware order.
```

I have verified that this is because of `IAuthorizationService` being constructor-injected into the endpoint. If I remove that dependency from the constructor _or_ if I replace it with injecting a `Func<IAuthorizationService>` instead that just resolves it from the DI container during runtime then things seem to work just fine. 

Injecting `IAuthorizationService` into endpoints did not throw this exception in FastEndpoints 5.14, so this is something that has changed since then.

**Comment by dj-nitehawk** [comment]
thanks for reporting.
fixed in `v5.17.1.12-beta`
