### ISSUE TITLE
Deprecated flag on the endpoints in Swagger documentation.

### ISSUE THREAD

**Issue by Rasmus715** [FastEndpoints/FastEndpoints#484]
Is there a way to mark an endpoint as "Deprecated" in API versioning article on Wiki there's an option to exclude the endpoint at some version, but I want to "gray out" some specific routes as on the screenshot below.
![image](https://github.com/FastEndpoints/FastEndpoints/assets/35352131/abc7128c-62e8-4446-b64e-e34192698d08)

This could be achieved by marking an Endpoint with deprecated parameter in the Swagger documentation, and the ASP.NET Core controllers support such functionality by using [Obsolete] attribute on the endpoint or the whole controller
https://github.com/swagger-api/swagger-ui/issues/6925

**Comment by GilesC9** [comment]
You can achieve this with just creating a custom operation processor. You can even hook it into the `Versioning(1, deprecatedAt: X`) functionality as well. Below is just an example that you can use as a starting point. Looking at the source this is probably easier than trying to mess with how the Versioning features work with FastEndpoints.

Define the operation processor
```csharp
public class DeprecatedOperationProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext context)
    {
        var operation = context.OperationDescription.Operation;
        var endpointDefinition = context.GetEndpointDefinition();
        
        // If version deprecatedAt has been set then mark the endpoint as deprecated
        // you can always add to it to do other stuff if you want.
        if (endpointDefinition?.Version.DeprecatedAt > 0) 
            operation.IsDeprecated = true;
        
        return true;
    }
}
```

Then add it within the SwaggerDocument definition.

```csharp
builder.Services
    .SwaggerDocument(o =>
    {
        o.MaxEndpointVersion = 1;
        o.DocumentSettings = s =>
        {
            s.DocumentName = "Release 1.0";
            s.Title = "my api";
            s.Version = "v1.0";
            
            // So we can mark endpoints as deprecated
            s.OperationProcessors.Add(new DeprecatedOperationProcessor());
        };
    });
```

![image](https://github.com/FastEndpoints/FastEndpoints/assets/4312453/7de7c5bc-1709-4447-ac78-97cd8302aed1)

You don't have to use `endpointDefinition.Version`, you can always base it on whether the class as an `Obsolete` attribute instead.

**Comment by KateyBee** [comment]
@Rasmus715 What @GilesC9 said would be the way to go about it.

But do you mean you want to grey out deprecated endpoints from the swagger doc instead of completely filtering it out?

If that's the case, we need to change the library to support that. Because right now, deprecated endpoints are removed from Swagger Docs that aren't supposed to have them.

**Comment by KateyBee** [comment]
Added support for showing deprecated versions of endpoints in Swagger in `v5.17.1.19-beta`.
[See here](https://gist.github.com/dj-nitehawk/c32e7f887389460c661b955d233b650d) for usage.

**Comment by Rasmus715** [comment]
> 



> @Rasmus715 What @GilesC9 said would be the way to go about it.
> 
> But do you mean you want to grey out deprecated endpoints from the swagger doc instead of completely filtering it out?
> 
> If that's the case, we need to change the library to support that. Because right now, deprecated endpoints are removed from Swagger Docs that aren't supposed to have them.

What I'm looking for is some sort of flag that will mark this endpoint as deprecated in Swagger schema. This functionality could be achieved by manually configuring every endpoint or based on the deprecated version (the approach which you introduced right above, thanks!)
```cs
    public class MyEndpoints : Endpoint<Request> 
    {
        public override void Configure()
        {
            Post("Cart/AddOrderToCart");
            AllowAnonymous();
           
            // Something like that
            Deprecated();

           // Or that 
            Tags("Obsolete", "Please use new version of this endpoint: POST \"/Cart/{id}/Orders"");    
          // And then the obsolete tag is getting processed by a filter to mark the endpoint as deprecated in a swagger.
        }
    }
```
