### ISSUE TITLE
Custom Column in JobRecord?

### ISSUE THREAD

**Issue by LeMigoA** [FastEndpoints/FastEndpoints#486]
Hi,

I got everything working with available documentation.

JobStorageProvider uses JobRecord model to manipulate the JobRecords table:

[Id],
[QueueId],
[CommandJson],
[ExecuteAfter],
[ExpireOn],
[IsComplete]

Now I'm trying to implement a [JobId] column/property in JobRecord to give back when the JobEndpoint is called.

JobEndpoint:
```      
            var jobId = Guid.NewGuid();
            await new JobCommand
            {
                JobRequest = req
            }.QueueJobAsync(ct: ct);
            
            await SendAsync(new JobResponse()
            {
                JobId = jobId
            }, cancellation: ct);
```    
The problem is; there is no way to save this endpoint generated jobId GUID inside [JobId] property of JobRecord.

How can i achieve what I'm trying?

**Comment by dj-nitehawk** [comment]
the storage record class implementing [IJobStorageRecord](https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Library/Messaging/Jobs/IJobStorageRecord.cs) is not meant to be exposed to your application/endpoint code.

whatever you need to access from the application layer, you shoud put on your command model itself.
so why not add a `JobId` property to your `JobCommand` class?

i'm not sure if i correctly understood your requirement.
if not, pls explain a bit more what you're trying to achieve.

**Comment by LeMigoA** [comment]
Hi thanks for helping.

When you add JobId to the JobCommand it get's correctly saved in to CommandJson column but to query that JobId I first need to parse the CommandJson. 

Let's say I have JobId xxx-xxx-xxx-xxx. I can't use LINQ to do .FirstOrDefault(m=>m.JobId == "xxx-xxx-xxx-xxx")

What i did now is making a JobRecordsView :

```
SELECT [Id],
	[QueueId],
	[CommandJson],
	JSON_VALUE(CommandJson, '$.JobId') AS JobId,
	[ExecuteAfter],
	[ExpireOn],
	[IsComplete],
FROM JobRecords
```

And use that for LINQ to do FirstOrDefault but JSON_VALUE has performance impact and its not the most elegant way.

**Comment by dj-nitehawk** [comment]
why exactly do you need to query the job storage record? just trying to understand your use case.

**Comment by LeMigoA** [comment]
I can explain my situation happily;

ProcessXMLEndpoint that returns 'JobId':
```

    public class ProcessXMLEndpoint : Endpoint<ProcessXMLRequest, ProcessXMLResponse>
    {
        public override void Configure()
        {
            Post("/process/xml");
            AllowAnonymous();
        }

        public override async Task HandleAsync(ProcessXMLRequest req, CancellationToken ct)
        {
            var jobId = Guid.NewGuid();
            await new ProcessXMLCommand
            {
                JobId = jobId,
                JobRequest = ProcessXMLRequest
            }.QueueJobAsync(ct: ct);
            
            await SendAsync(new ProcessXMLResponse()
            {
                JobId = jobId 
            }, cancellation: ct);
        }
    }
    
```

CommandHandler that does the Processing of XML

```
  public class ProcessXMLCommandHandler : ICommandHandler<ProcessXMLCommand>
    {
        public Task ExecuteAsync(ProcessXMLCommand, CancellationToken ct)
        {
            // This process takes a while. Every progress made is saved in the table JobProgress with relation to JobRecords tables JobId column.
        }
    }
```

Endpoint to get status of XML processing of a job by using JobId:

```
  public class StatusProcessXMLEndpoint : Endpoint<StatusProcessXMLRequest, StatusProcessXMLResponse>
    {
        public override void Configure()
        {
            Post("/status/xml");
            AllowAnonymous();
        }

        public override async Task HandleAsync(StatusProcessXMLRequest req, CancellationToken ct)
        {
        
            var statusOfJob = dbcontext.JobRecords.FirstOrDefault(m=>m.JobId == req.JobId);
            
            await SendAsync(new StatusProcessXMLResponse()
            {
                Status = statusOfJob.Status
            }, cancellation: ct);
        }
    }
```

**Comment by dj-nitehawk** [comment]
hehehe glad to be of service 😉

typically there's no need for the application code to interact with the job storage table. it's a somewhat "internal" thing of the library.

99% of the time, the command model will contain an Id of some other parent who owns the command. when the command handler executes, it updates the parent informing of command completion. the application queries the parent regarding status.

ex: create order endpoint is hit > order entity created & create invoice pdf command is queued > pdf generation command handler completes and updates the order entity with the url to the pdf.

any status checking is done against the order entity. i.e. if `PdfUrl` property is null, status is `pending`.

just a simple example if anybody else runs in to a similar situation 😉
