### ISSUE TITLE
ExecuteAsyncReturnsIResult

### ISSUE THREAD

**Issue by cphillips83** [FastEndpoints/FastEndpoints#487]
When you implement this system you lose the ability for auto wiring up 401, 403 and 400/validator detection.

```
            if (Definition.ExecuteAsyncReturnsIResult)
            {
#if NET7_0_OR_GREATER
                b.Add(eb => ProducesMetaForResultOfResponse.AddMetadata(eb, tResponse));
#endif
            }
            else
            {
                if (tResponse == Types.Object || tResponse == Types.EmptyResponse)
                    b.Produces<TResponse>(200, "text/plain", "application/json");
                else
                    b.Produces<TResponse>(200, "application/json");

                if (Definition.AnonymousVerbs?.Any() is not true)
                    b.Produces(401);

                if (Definition.RequiresAuthorization())
                    b.Produces(403);

                if (Conf.ErrOpts.ProducesMetadataType is not null && Definition.ValidatorType is not null)
                {
                    b.Produces(
                        Conf.ErrOpts.StatusCode,
                        Conf.ErrOpts.ProducesMetadataType,
                        "application/problem+json");
                }
            }
```
While I see why it does this, I still think there needs to be a better way to get this automatically rather than having to manually add these 3 result types to the Results generic (which doesn't even work because not all implement PopulateMetadata).

To bring back the 401, you have to either override configure and add Produces(401) or you need to implement your own version on an `Unauthorized : IResult, IEndPointMetadataProvider` so that it can be used as a result type. (Note: NotFound properly implements `IEndPointMetadataProvider`)

Furthermore, its not ideal to have to include these when they are handled outside of our ExecuteAsync method further up the pipeline.

I should note there are a few places where something such as Unauthorized could be included in the results and that would be on an Anonymous endpoint that is validating the inputs and doesn't want to leak data. For example, an oAuth endpoint could return Unauthorized to an anonymous endpoint when an invalid clientid or secret is passed.

**Comment by dj-nitehawk** [comment]
huh... wonder why not all result types returned by `TypedResults` static class implement `IEndPointMetadataProvider`. didn't realize that was the case. thanks for pointing that out. wonder why MS does it that way?

sooo... any ideas on how to improve the situation? a PR would be highly appreciated.
hopefully something that doesn't break existing swagger spec of people's projects ;-)

even though the current implementation is not ideal considering all scenarios, i think it's not a big deal since the user has [control over](https://fast-endpoints.com/docs/swagger-support#clearing-default-accepts-produces-metadata) what `Produces Metadata` is added to their endpoints.

**Comment by dj-nitehawk** [comment]
this seems to be MS's stance on the matter: https://github.com/dotnet/aspnetcore/issues/47705#issuecomment-1544808236

**Comment by dj-nitehawk** [comment]
@mehdihadeli did you ever figure out a clean solution to the issue of not all `TypedResults` implementing `IEndPointMetadataProvider`? or are we just stuck with MS's stubbornnes? 🤣

**Comment by mehdihadeli** [comment]
Hi, 
I think, they don't have a plan for that, maybe became it makes their apis dirty. I had to implement it my self for my apps [like this](https://github.com/mehdihadeli/ecommerce-microservices/blob/refactor/cqrs/src/BuildingBlocks/BuildingBlocks.Web/Problem/HttpResults/NotFoundHttpProblemResult.cs). I don't know doing this is a good design for fastendpoint or not?

**Comment by dj-nitehawk** [comment]
yeah i guess that would be the way forward unless they don't wanna offer a consistent experience :-(

**Comment by cphillips83** [comment]
I actually have a few ideas on this project that might be useful and would probably need a real discussion rather than over comments, I will try to jump on the discord server when I have time. 

I'm very interested in this project but feel that Endpoint.cs has far too much logic and too many things are coupled together rather than added on (like validation and the httpcontext for example).

As for this specific issue, I think the easiest way is to add an additional interface that works like UserConfigAction but is global and allows you to override the configuration for all endpoints. Something like this would then allow you to move all of the initial logic like `AllowAnonymous`, `ResponseCaching`, `EndpointSummary` out of the main code path and applied as configuration layers that could just be included by default.

**Comment by dj-nitehawk** [comment]
> but is global and allows you to override the configuration for all endpoints

we have that already: https://fast-endpoints.com/docs/configuration-settings#global-endpoint-options

ah sorry you've seen that now.

so we good for now? i'll close this issue for now. feel free to re-open or create a new one in case you wanna take it further.

thanks!
