### ISSUE TITLE
Vertical Slices Architecture and EF

### ISSUE THREAD

**Issue by nowakpaw** [FastEndpoints/FastEndpoints#489]
Hi. Is it possible to use FastEndpoints with VSA and EF? I can see in tutorials and in scaffolded files (with vs extension) that Data.cs is a static class, and static is not "context friendly":) I can set is as not static, but then I would have to register it in DI for each use case. I'm looking for an elegant replacement for VSA with MediatR and Minimal Api.

**Comment by dj-nitehawk** [comment]
> then I would have to register it in DI for each use

there's a source generator coming in `v5.17.1.20-beta` that can help with that.

first add the source generator to your project:
```cs
dotnet add package FastEndpoints.Generator --version 5.17.1.20-beta
```

decorate the data class with `[RegisterService]` attribute:
```cs
[RegisterService<Data>(LifeTime.Scoped)]
sealed class Data
{
    private readonly DbContext _db;

    public Data(DbContext dbContext)
    {
        _db = dbContext;
    }

    public async Task<bool> SomethingExistsAsync(Guid id)
    {
        var exists = await _db....
        return exists;
    }
}
```

use the source generated extension method to register all discovered services:

```cs
using YourAssemblyName; //the generated extension methods are in this namespace

builder.Services.RegisterServicesFrom{YourAssemblyName}()
```

inject (either property or ctor) the `Data` class in to your endpoint:
```cs
sealed class MyEndpoint : EndpointWithoutRequest
{
    public Data Data { get; set; }

    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        var res = await Data.SomethingExistsAsync(Guid.NewGuid());
        await SendAsync(res);
    }
}
````
how about that?

**Comment by nowakpaw** [comment]
Thank You very much for Your comprehensive reply.

To be honest I don't see much gain with generator - I can gather all Data in one extension method (with more control in my hands) and with one line add them to DI in Program.cs. 

For now I ended up with something like endpoint class with injected context which is passed as a parameter to ctor of Data. But I will think about something better:)

I also noticed a problem with the use of annotations: [RegisterService<Data>(LifeTime.Scoped)] - if the assembly has a dot in the name (we use the naming convention: SolutionName.SpecificProject - for example SolutionName.Api) the automatically generated code does not compile due to an error in the method name.

Overall I'm really impressed with Fast Endpoints and how elegant they are and I'm using them for a while. VSA is just my latest want-to-try thing:) Thank You for Your work.

**Comment by dj-nitehawk** [comment]
good catch! problem with dots in the assembly name has been fixed in beta 21. thanks!

how about writing the data methods as extensions like this:

```cs
static class Data
{
    public static async Task<bool> SomethingExistsAsync(this DbContext db, Guid id)
    {
        ...
    }
}
```

the extension methods will only show up for that particular feature/slice namespace.
won't show up for namespaces of other slices.

this way you don't need to register the data classes in DI.
