### ISSUE TITLE
Websockets within Fastendpoints

### ISSUE THREAD

**Issue by chukara1** [FastEndpoints/FastEndpoints#493]
Is it possible to implement some endpoints as websockets within FastEndpoints framework?

**Comment by dj-nitehawk** [comment]
there is no built-in support for websockets but...
if we go by [this example](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/websockets?view=aspnetcore-7.0#add-http2-websockets-support-for-existing-controllers) from microsoft, it would translate to fastendpoints like this:
```cs
sealed class WebSocketEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Verbs("CONNECT");
        Routes("/websocket");
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        if (HttpContext.WebSockets.IsWebSocketRequest)
        {
            using var webSocket = await HttpContext.WebSockets.AcceptWebSocketAsync();
            await Echo(webSocket);
        }
        else
        {
            HttpContext.Response.StatusCode = StatusCodes.Status400BadRequest;
        }
    }
}
```
didn't test it out though. theoretically should work.
give it a shot and let us know how it went ;-)

**Comment by chukara1** [comment]
Thanks. But unfortunately it did not work. I get an error on the server side 
**"[20:00:00 INF] Request starting HTTP/1.1 GET http://localhost:5105/websocket - -
[20:00:00 INF] Executing endpoint '405 HTTP Method Not Supported'
"**
And on the client side
 **"Error: Handshake status 405 Method Not Allowed"**

**Comment by dj-nitehawk** [comment]
ah... that would most likely be due to the default accpets metadata not allowing CONNECT requests. 

can you try clearing the defaults as mentioned here: https://fast-endpoints.com/docs/swagger-support#clearing-default-accepts-produces-metadata

if that doesn't do it, let me know I'll have a deeper look first thing in the morning.

**Comment by dj-nitehawk** [comment]
oh wait... you're making a GET request it seems. the MS docs says to do a CONNECT request right?

**Comment by chukara1** [comment]
Actually, the opposite is true. :) After some experimentation, I found that using Verbs("GET") makes it work. This is due to the inability of the Python library "websockets" to support WebSockets over HTTP/2. But then  I started googling, I became a bit perplexed ...results began with:

"HTTP/2 doesn't support WebSockets as HTTP did, making the protocols an either-or choice. A good workaround for this situation would be to use the gRPC protocol, which uses HTTP/2 under the hood."

However, the official Microsoft documentation states:

".NET 7 introduced support for WebSockets over HTTP/2 in Kestrel, the SignalR JavaScript client, and SignalR with Blazor WebAssembly. HTTP/2 WebSockets use CONNECT requests rather than GET. If you previously used [HttpGet("/path")] for your controller action method for WebSocket requests, you should update it to [Route("/path")] instead."

**Comment by chukara1** [comment]
Either way, now it works! many thanks!
