### ISSUE TITLE
How would you bind to a JWT claim with a dynamic name?

### ISSUE THREAD

**Issue by baynezy** [FastEndpoints/FastEndpoints#494]
So I am trying to populate my Request object with a property from that Auth JWT token passed in the `Authorization` header. The challenge I have is that the name of the property is different per environment.

The token the property looks like so:-

```"https://dev.my-domain.com/profileId": "a09d05bc-b07d-49f7-a166-b15789fe2a51"``` in my dev environment and it will have a different sub-domain in higher environments. Is there a way with FastEndpoints to populate my request model dynamically? Or do I need to roll my own custom model binder?

Cheers, and I love the framework by the way.

**Comment by dj-nitehawk** [comment]
there's nothing built-in (even in asp.net) that can do it.
is there any possibility to break that in to two different claims at all?
i.e. `domain` & `profileId`?
that would be the easiest way to solve it.

if not, you'll have to write a custom model binder using an appropriate method [explained here](https://fast-endpoints.com/docs/model-binding#diy-request-binding).

**Comment by dj-nitehawk** [comment]
something like this should work:
```cs
interface IHasProfileId
{
    string? ProfileId { get; set; }
}

sealed class MyRequest : IHasProfileId
{
    public string? ProfileId { get; set; }
}

static class CustomBinding
{
    public static void Modifier(object req, Type _, BinderContext ctx, CancellationToken __)
    {
        if (req is IHasProfileId r)
        {
            r.ProfileId = ctx.HttpContext.User.FindFirst(c => c.Type.EndsWith("/profileId"))?.Value;
        }
    }
}

app.UseFastEndpoints(c => c.Binding.Modifier = CustomBinding.Modifier)
```

didn't test that out though. let me know if it's not working.

**Comment by baynezy** [comment]
@dj-nitehawk - thanks so much for your swift response.

> is there any possibility to break that in to two different claims at all?

Sadly not. I am using Auth0 as my IdP, and to add custom claims in the auth token seems to require namespacing.

The good news is [your suggestion](https://github.com/FastEndpoints/FastEndpoints/issues/494#issuecomment-1744143311) worked perfectly. Thanks so much.

👍👍👍👍👍👍👍👍👍👍
