### ISSUE TITLE
Swagger.json in docker and nginx problem

### ISSUE THREAD

**Issue by ahmadlashgari** [FastEndpoints/FastEndpoints#495]
![Screenshot 2023-10-03 121731](https://github.com/FastEndpoints/FastEndpoints/assets/20770707/e41d91e7-4904-436b-9473-7024ebeb2358)

I used docker and nginx and got the above error. I also used a virtual path called "catalog". In this case, "swagger.json" does not exist. I tried all the options but I couldn't add the "catalog" to the beginning of the "swagger.json" creation URL. please guide me. Thankful

**Comment by nefarius** [comment]
Please provide your code and Nginx config (I assume you use it as a reverse proxy?) so we do not have to play guessing games, thanks.

**Comment by ahmadlashgari** [comment]
**Startup**

builder.Services
  .SwaggerDocument(o =>
  {
    o.ShortSchemaNames = true;
    o.MaxEndpointVersion = 1;
    o.DocumentSettings = s =>
    {
      s.DocumentName = "Release 1.0";
      s.Title = "Catalog API";
      s.Version = "v1.0";
    };
  });

app.UseFastEndpoints(config =>
{
  config.Versioning.Prefix = "v";
});

**Docker Compose:**

  reverse-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: reverse-proxy
    ports:
      - ${DEFAULT_HTTP_PORT}:80
      - ${DEFAULT_HTTPS_PORT}:443
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './shared/reverse-proxy/vhost.d:/etc/nginx/vhost.d'
      - './shared/reverse-proxy/certs:/etc/nginx/certs:ro'
      - './shared/reverse-proxy/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      proxy: null
      primarynetwork:
        aliases:
          - api.marketplace.local
    restart: always

  catalog.web:
    image: ${DOCKER_REGISTRY-}xyz
    container_name: xyz
    build:
      context: .
      dockerfile: src/Services/xyz/src/xyz/Dockerfile
    environment:
      - VIRTUAL_HOST=api.marketplace.local
      - VIRTUAL_PATH=/catalog/
      - VIRTUAL_DEST=/
      - VIRTUAL_PROTO=https
      - VIRTUAL_PORT=443
    networks:
      primarynetwork: null

**Comment by ahmadlashgari** [comment]
also added this in startup:

app.UseSwaggerGen(config =>
{
  config.PostProcess = (swaggerDoc, request) =>
  {
    OpenApiServer openApiServer = new OpenApiServer();
    DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(4, 3);
    defaultInterpolatedStringHandler.AppendFormatted(request.Scheme);
    defaultInterpolatedStringHandler.AppendLiteral("://");
    defaultInterpolatedStringHandler.AppendFormatted(request.Host);
    defaultInterpolatedStringHandler.AppendLiteral("/");
    defaultInterpolatedStringHandler.AppendFormatted("catalog");
    openApiServer.Url = defaultInterpolatedStringHandler.ToStringAndClear();
    swaggerDoc.Servers.Add(openApiServer);
  };
});

**Comment by KateyBee** [comment]
You can change the document path where SwaggerUI looks for the `swagger.json` file like this:
```cs
app.UseSwaggerGen(uiConfig: s => s.DocumentPath = "/catalog/swagger/{documentName}/swagger.json");
```

And please use markdown code formatting when posting code like this: 
![image](https://github.com/FastEndpoints/FastEndpoints/assets/134909513/8f13f380-f9a7-4a97-8a14-8b7f03aae72a)


Thanks!

**Comment by ahmadlashgari** [comment]
Thanks @KateyBee! it's work. but api call display not found. please help me.
![Screenshot 2023-10-03 133425](https://github.com/FastEndpoints/FastEndpoints/assets/20770707/338518d8-e534-420d-ab8c-3b0df1c5428b)

`public class List : Endpoint<BrandListRequest, BrandListResponse, BrandListMapper>
{
  private readonly IMediator _mediator;

  public List(IMediator mediator)
  {
    _mediator = mediator;
  }

  public override void Configure()
  {
    Get(BrandListRequest.Route);
    Version(1);
    AllowAnonymous();

    Description(e => e
        .Accepts<BrandListRequest>()
        .Produces<BrandListResponse>(200)
        .ProducesProblemFE()
        .ProducesProblemFE<InternalErrorResponse>(500),
    clearDefaults: true);

    Summary(e =>
    {
      e.Summary = "List all Brands.";
      e.Description = "returns a BrandListResponse containing the Brands.";
      e.ResponseExamples[200] = new BrandListResponse
      {
        Items = new List<BrandRecord>
        {
          new(1, "Microsoft", "About Microsoft company.", string.Concat("/brands/", Guid.NewGuid().ToString(), ".png"), "Microsoft co", "Microsoft Corporation is an American multinational technology corporation headquartered in Redmond, Washington.", "Microsoft", DateTime.Now.AddDays(-3))
        },
        Skip = 0,
        Take = 100,
        TotalCount = 500
      };
    });
  }

  public override async Task HandleAsync(BrandListRequest request, CancellationToken cancellationToken)
  {
    var result = await _mediator.Send(new ListBrandsQuery(request.Skip, request.Take));

    if (result.IsSuccess)
    {
      Response = Map.FromEntity(result.Value);
    }
  }
}`

**Comment by ahmadlashgari** [comment]
Thanks @KateyBee. It's worked! but api not found.

![Screenshot 2023-10-03 133425](https://github.com/FastEndpoints/FastEndpoints/assets/20770707/e669f509-0439-43ac-97fb-9308a0096c91)


```cs
public class List : Endpoint<BrandListRequest, BrandListResponse, BrandListMapper>
{
  private readonly IMediator _mediator;

  public List(IMediator mediator)
  {
    _mediator = mediator;
  }

  public override void Configure()
  {
    Get(BrandListRequest.Route);
    Version(1);
    AllowAnonymous();

    Description(e => e
        .Accepts<BrandListRequest>()
        .Produces<BrandListResponse>(200)
        .ProducesProblemFE()
        .ProducesProblemFE<InternalErrorResponse>(500),
    clearDefaults: true);

    Summary(e =>
    {
      e.Summary = "List all Brands.";
      e.Description = "returns a BrandListResponse containing the Brands.";
      e.ResponseExamples[200] = new BrandListResponse
      {
        Items = new List<BrandRecord>
        {
          new(1, "Microsoft", "About Microsoft company.", string.Concat("/brands/", Guid.NewGuid().ToString(), ".png"), "Microsoft co", "Microsoft Corporation is an American multinational technology corporation headquartered in Redmond, Washington.", "Microsoft", DateTime.Now.AddDays(-3))
        },
        Skip = 0,
        Take = 100,
        TotalCount = 500
      };
    });
  }

  public override async Task HandleAsync(BrandListRequest request, CancellationToken cancellationToken)
  {
    var result = await _mediator.Send(new ListBrandsQuery(request.Skip, request.Take));

    if (result.IsSuccess)
    {
      Response = Map.FromEntity(result.Value);
    }
  }
}
```

**Comment by KateyBee** [comment]
Waht's the value of `BrandListRequest.Route`?
Make sure it matches with what SwaggerUI is sending the request to:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/134909513/bc0d8b49-093a-4ef3-9bca-bf3ed5d349c0)

I'm assuming Kestrel is listening on `/brands` and not `/catalog/brands`

@nefarius Any ideas what's going on here?

**Comment by ahmadlashgari** [comment]
````cs
public const string Route = "/brand";

**Comment by ahmadlashgari** [comment]
also using this:

```cs
app.UseFastEndpoints(config =>
{
  config.Versioning.Prefix = "v";
  config.Endpoints.RoutePrefix = "catalog";
});

**Comment by nefarius** [comment]
> ```cs
> public const string Route = "/brand";
> ```

Try removing the slash.

**Comment by ahmadlashgari** [comment]
thanks all. i fixed this by code below:

````cs
// Fast Endpoints
app.UseFastEndpoints(config =>
{
  config.Versioning.Prefix = "v";
});

// Swagger
app.UseSwaggerGen(config =>
{
  config.PostProcess = (swaggerDoc, request) =>
  {
    OpenApiServer openApiServer = new OpenApiServer();
    DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(4, 3);
    defaultInterpolatedStringHandler.AppendFormatted(request.Scheme);
    defaultInterpolatedStringHandler.AppendLiteral("://");
    defaultInterpolatedStringHandler.AppendFormatted(request.Host);
    defaultInterpolatedStringHandler.AppendLiteral("/");
    defaultInterpolatedStringHandler.AppendFormatted("catalog");
    openApiServer.Url = defaultInterpolatedStringHandler.ToStringAndClear();
    swaggerDoc.Servers.Clear();
    swaggerDoc.Servers.Add(openApiServer);
  };
}, uiConfig: config =>
{
  config.DocumentPath = "/catalog/swagger/{documentName}/swagger.json";
});
