### ISSUE TITLE
Cannot override ApiClient name and Fastendpoints default namespace when generating CSharpClient.

### ISSUE THREAD

**Issue by binair-io** [FastEndpoints/FastEndpoints#496]
When generating a CSharp Client as detailed in the [documentation](https://fast-endpoints.com/docs/swagger-support#swagger-documentation), I cannot override the default namespace "FastEndpoints" and client name "ApiClient". 

<pre>o.DocumentSettings = s =>
{
    s.DocumentName = "v1";
    s.Title = "Decap.Api";
    s.Version = "v1.0";

    s.GenerateCSharpClient(
        settings: s => {
            s.ClassName = "MyClientName";
            s.CSharpGeneratorSettings.Namespace = "MyNamespace";
        },
        destination: "../MyLib.ApiClient"
    );
};</pre>

Above code still outputs the defaults as in the code base. 
https://github.com/FastEndpoints/FastEndpoints/blame/a13d44187f4d15d925c25254e39306a897e6a12b/Src/ClientGen/CSClientGenProcessor.cs#L15

**Comment by dj-nitehawk** [comment]
see attached sample project. works fine.
[ClientGenSample.zip](https://github.com/FastEndpoints/FastEndpoints/files/12813061/ClientGenSample.zip)

the generated `client.cs` file looks like this:
![screen-record-1696487986](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/dbbccf47-58be-49ca-b5b2-19a9409d99f7)
