### ISSUE TITLE
Adding Summary to an endpoint will lose the response output

### ISSUE THREAD

**Issue by EelcoLos** [FastEndpoints/FastEndpoints#497]
## Expected Behavior
Adding a Summary to the Endpoint won't break the current flow of Endpoint

## Actual Behavior
When added, the description will be generated for the response types you're providing. However, the content section of the swagger document is completely removed

## Steps to Reproduce the Problem
1. As package, use FastEndpoints latest version
1. Write an Endpoint with a request/response
1. Write a Summary with response types you expect, like below:
``` csharp
public class GetDocumentsEndpointSummary : Summary<GetDocumentsEndpoint>
{
	public GetDocumentsEndpointSummary()
	{
		Summary = "Get all documents";
		Response(StatusCodes.Status200OK, "A list of documents.");
		Response(StatusCodes.Status400BadRequest, "Something went wrong, the details can be found in the ErrorMessage");
	}
}
```
4. Check the swagger document or use a generator to see a translation to another language
5. You see the content endpoint output rewritten with your summary, but no content
![image](https://github.com/FastEndpoints/FastEndpoints/assets/5102501/2befda11-c2a9-43aa-adb8-bf755037270a)

## Workaround
There _is_ a 'workaround'. In the `Configure` section, you can add the `Produces` part to get it back
```csharp
Description(x =>
		{
			x.Produces<IEnumerable<GetDocumentsResponse>>();
		});
```
However, this does not seem intuitive to me.

**Comment by dj-nitehawk** [comment]
this is documented behavior of the `Response()` method in the `Summary<T>` class.

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/405d4070-abe1-4d65-9631-cb4575bc56fd)

the remedy is to do the following:
```cs
public class GetDocumentsEndpointSummary : Summary<GetDocumentsEndpoint>
{
	public GetDocumentsEndpointSummary()
	{
		Summary = "Get all documents";
		Response<IEnumerable<GetDocumentsResponse>>(StatusCodes.Status200OK, "A list of documents.");
		Response(StatusCodes.Status400BadRequest, "Something went wrong...");
	}
}
```
wish this quirk didn't exist but if i remember correctly, there was some internal technical block to get rid of it.

do let me know if the above suggestion doesn't work out as i didn't actually test it :-)

**Comment by EelcoLos** [comment]
ah, that's very good to know, i missed that specific part between those 2 differences 😅. Thanks for your documentation 👍
