### ISSUE TITLE
Question: Swagger - Optional query parameters

### ISSUE THREAD

**Issue by MiddleKerb** [FastEndpoints/FastEndpoints#498]
## Question

The API has two optional parameters which will be pass as query string, i wanted to make `CustomerNumber` as optional parameter on swagger.

## Additional Information

```c sharp
public override void Configure()
{
    Get("/customers");
    Roles("ADMINISTRATOR", "VIEWER");
    Summary(s =>
    {
        s.Summary = "Get customer information API";
        s.Description = "This API endpoint retrieves current customers.";
        s.ExampleRequest = new GetCustomerRequest { OrgCode = "JK1", CustomerNumber = "100191" };
        s.RequestParam(r => r.OrgCode, "The branch code for the requested customer.");
        s.RequestParam(r => r.CustomerNumber, "The client ID for the requested customer.");
    });
    AuthSchemes(JwtBearerDefaults.AuthenticationScheme);
}
```

![image](https://github.com/FastEndpoints/FastEndpoints/assets/45553961/20d25108-f556-4eea-aa62-915aa4f7ecb7)

**Comment by dj-nitehawk** [comment]
making the property nullable on the request dto should do the trick.

**Comment by MiddleKerb** [comment]
> making the property nullable on the request dto should do the trick.

Thank you
