### ISSUE TITLE
Returning 204 content behavious differently when also producing 200 ok (typescript client generation)

### ISSUE THREAD

**Issue by delasource** [FastEndpoints/FastEndpoints#503]
i have an endpoint that i describe with
```c#
Description(b => b.Accepts<PostStatsRequest>("application/json")
                  .Produces(204)
);
```
and nothing else (ok just AllowAnonymous and POST-Verbs). 
Then, the typescript client generates this:
```ts
...
    protected processPostStats(response: Response): Promise<any> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
                result200 = resultData200 !== undefined ? resultData200 : <any>null;
    
            return result200;
            });
        } else if (status === 204) {
            return response.text().then((_responseText) => {
            return throwException("No Content", status, _responseText, _headers);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<any>(null as any);
    }
```

which throws an ugly exception. But if i just add the line "Produces(200)" like
```c#
Description(b => b.Accepts<PostStatsRequest>("application/json")
                  .Produces(200)
                  .Produces(204)
);
```
then the generated output looks like this:
```ts
    protected processPostsStats(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 204) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
```

which does not throw, it is just happy. Thats perfect. But why does it only behave like that if i specify Produces(200) ? I never return 200 because i dont need to return any content.

**Comment by dj-nitehawk** [comment]
can you try [clearing the default 200 produces metadata](https://fast-endpoints.com/docs/swagger-support#clearing-only-produces-metadata) like this:
```cs
Description(b => b.Accepts<PostStatsRequest>("application/json")
                               .ClearDefaultProduces(200)
                               .Produces(204)
);
```
see if that makes any difference.

also can you check (and post here) the generated `swagger.json` related to this endpoint? if the correct spec is generated but the typescript code is not correct, then that's an NSwag client generation issue that we need to talk to them about.

because FE only has control over the swagger spec and not TS code generation. if the swagger spec generated is not correct (after clearing the default 200 like above), then i will dig deeper in to this.

in which case, please attach a full repro that includes a bare minimum request dto + endpoint code that shows the problem.

thanks!

**Comment by delasource** [comment]
The .ClearDefaultProduces(200) indeed keeps the happy code. Thank you. 
But strangely why are there these 3 cases then? 
- defining ClearDefaultProduces -> 204 is happy
- specifying 200 -> 200 and 204 are happy
- not specifying 200 -> tries to parse any 200 response and breaks the 204 response

🤔

**Comment by dj-nitehawk** [comment]
might be a bug in nswag's TS generation.
from the perspective of FE, all we can do is generate the correct `swagger.json` spec and hope nswag spits out the right TS code.
