### ISSUE TITLE
It's time to experience . New features in NET8

### ISSUE THREAD

**Issue by vipwan** [FastEndpoints/FastEndpoints#504]
.NET8 will release the RTM version next month !
FrozenDictionary & GeneratedRegexAttribute & .... can intuitively improve performance 
It's time to experience ~

https://devblogs.microsoft.com/dotnet/performance-improvements-in-aspnet-core-8/

**Comment by dj-nitehawk** [comment]
will look in to what can be done when .net 8 is released. can't really use the current stable release of rider anyway. so will have to wait until rider supports .net 8 properly.

will close this ticket for now and re-open when we start working on .net 8 support.
