### ISSUE TITLE
Problem with unit testing after upgrading from 5.11 to any upper version

### ISSUE THREAD

**Issue by itsoli91** [FastEndpoints/FastEndpoints#510]
Hi
Currently we are using fast FastEndpoints Version="5.11.0".
I was trying to update to latest version, but after updating some of our unit tests starts to fail.

```
public class GetOnboardingEndpointTests
{
    private GetOnboardingEndpoint _getOnboardingEndpoint;

    public GetOnboardingEndpointTests()
    {
        _getOnboardingEndpoint =
            Factory.Create<GetOnboardingEndpoint>(
                ctx => { ctx.Request.RouteValues.Add("OnboardingId", _onboardingId); }, OnboardingService);
    }

    [Fact]
    public async Task GetOnboarding_Returns_Expected_OnboardingResult()
    {
        await _getOnboardingEndpoint.HandleAsync(new EmptyRequest(), default);
      
         // rest of code
    }

}
```

The above test fails with below error:

```
System.InvalidOperationException
No service for type 'Microsoft.AspNetCore.Http.IHttpContextAccessor' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at FastEndpoints.ServiceResolver.Resolve[TService]()
   at FastEndpoints.Factory.AddTestServices(HttpContext ctx, Action`1 s)
   at FastEndpoints.Factory.Create[TEndpoint](DefaultHttpContext httpContext, Object[] ctorDependencies)
   at FastEndpoints.Factory.Create[TEndpoint](Action`1 httpContext, Object[] ctorDependencies)
```

To make it a bit more clear, it starts failing when I update from 5.11 to 5.12, so maybe some changes on version 12 is causing this issue.

**Comment by dj-nitehawk** [comment]
update to the latest version and move the `Factory.Create` call out of the constructor into the actual test methods.

if i remember correctly, the `Factory` started using an `AsyncLocal` internally and calling it in the ctor might be messing things up. you should be able to use a static async function instead of the constructor if you really need to abstract out the creation of the endpoint/sut.

if that doesn't sort it out, i'm gonna need a repro project to debug. you can quickly scaffold one out using our `dotnet new` template.

```sh
dotnet new install FastEndpoints.TemplatePack
dotnet new feproj -n MyAwesomeProject
```

**Comment by itsoli91** [comment]
Sorry for very late response but still I am facing this issue, 
I have found something strange:
When I mock two endpoint at the same time this exception is always thrown for the second endpoint` Factory.Create`

Example:

```
   public class SomeEndpointTests 
   {
        private readonly EndpointA _a;
        private readonly EndpointB _B;

        public SomeEndpointTests(){

            _a = Factory.Create<EndpointA>(
              ctx => { ctx.Request.RouteValues.Add("FunnelSessionId", _funnelSessionId); },
              _someOtherMockedService); 

           _b = Factory.Create<EndpointB>(
              ctx => { ctx.Request.RouteValues.Add("FunnelSessionId", _funnelSessionId); },
              _someOtherMockedService); // error is thrown here
        }
   }
```

In above example if I remove  `_b = Factory.Create<EndpointB>...` then the error is gone. It is also not related to endpoint a or b, because I tried to call  `_b = Factory.Create<EndpointB>..` first then the error was thrown for  _`a = Factory.Create<EndpointA>

`

**Comment by dj-nitehawk** [comment]
i believe you're using the `Factory.Create()` method incorrectly.
it's designed to be called only once per test method.
i.e. test each endpoint independantly. don't create more than one endpoint instance within a single test method.
have  a look at these tests [here](https://github.com/FastEndpoints/FastEndpoints/blob/main/Tests/UnitTests/FastEndpoints/WebTests.cs). that is how it's supposed to be used.

**Comment by dj-nitehawk** [comment]
if you want, you can share mocked services (and other stuff) among different test methods, but `Factory.Create()` must be called inside each test method once.

if you attach a debuggable a repro project with a couple of tests, i can try to fix it up for ya ;-)

**Comment by itsoli91** [comment]
Thank you for fast response.
It is like I have to call some other endpoints to be prepared for testing my sut. But it seems it is not the correct way to do it, I have to internally change states rather than calling the endpoints.

**Comment by dj-nitehawk** [comment]
yeah if your unit tests can't be simple, that's an indication you ought to be doing integration tests instead. i myself rarely write unit tests for endpoints. i typically only write unit tests for simple units of business logic as a secondary layer of protection in addition to integration tests.

**Comment by itsoli91** [comment]
Yeah I totally agree, we are considering moving/converting them into intergration tests.
