### ISSUE TITLE
Summary ResponseParam doesn't work with JsonPropertyName

### ISSUE THREAD

**Issue by rage4** [FastEndpoints/FastEndpoints#511]
Hi. First of all, thanks for the awesome framework. At Rage4, we are moving most of our codebase to the FE. 
We are not sure if it is a bug or not, but we have noticed the following behaviour:
1. Create a response record (SampleResponse) with, let's say, an IsActive property (boolean)
2. Add the JsonPropertyName attribute to be serialized to 'is_active'.
3. Add the Summary with s.ResponseParam<SampleResponse>(o => o.IsActive, "Entity status");

I would expect that the Swagger would have the correct description. Unfortunately, it's empty.
Is there any workaround? Something similar to s.Params, so it would accept the dictionary?

Thanks. Piotr

**Comment by KateyBee** [comment]
Thanks for reporting this.
It has been fixed in `v5.18.0.7-beta`.
Hoping to do a final release around 3rd of November.
