### ISSUE TITLE
Endpoint returns "Error: response status is 415"

### ISSUE THREAD

**Issue by WeismanGitHub** [FastEndpoints/FastEndpoints#512]
I'd greatly appreciate some help in resolving this. I want to to have `RequestID` as a route parameter, but when I POST `/1234123213/accept/` I get "Error: response status is 415". It works perfectly fine when I add a random property to `Request` though.

```cs
public class Endpoint : Endpoint<Request> {
    public override void Configure() {
        Post("/{RequestID}/accept");
    }

    public override async Task HandleAsync(Request req, CancellationToken cancellationToken) {
        Console.WriteLine(req.RequestID);
    }
}
```
```cs
public class Request {
        [From(Claim.AccountID, IsRequired = true)]
        public string AccountID { get; set; }
        public string RequestID { get; set; }
}
```

**Comment by dj-nitehawk** [comment]
as mentioned [here](https://fast-endpoints.com/docs/swagger-support#clearing-default-accepts-produces-metadata), clear/redefine the default accepts metadata by doing this:
```cs
Description(x => x.Accepts<Request>());
```
let me know if that doesn't do it.
