### ISSUE TITLE
Binding based on interfaces' attributes

### ISSUE THREAD

**Issue by Seramis** [FastEndpoints/FastEndpoints#513]
First of all, thanks for this great library. It really helps to organize code better compared to MVC and pure minimal API approaches.

# Idea
When request models use interface for some common fields, it would be great, if I would be able to define the source for binding (headers, body, etc.) inside the interface and not worry about it in every request model.

## Current situation
Every request model must have all the binding attributes in itself. It can not inherit attribute information from interfaces.

## How it would look like after improvement
I would have an interface like this:
```csharp
internal interface IPagedRequest
{
    [FromHeader(IsRequired = false)]
    public int? Offset;

    [FromHeader(IsRequired = false)]
    public int? Limit;
}
```

With that being present, I can create Request models just with the fields:
```csharp
internal class ListUsersRequest : IPagedRequest
{
    // ... all "real fields" i would need to work with


    public int? Offset;

    public int? Limit;
}
```
... and I can have many different request models like this and I would not need to redefine the binding source every time I create a new model. This way, the binding source would be **defined in one place** and it would **apply to every case universally**.

### Additional comments
What is really being tried to be done here is and idea of "componentization". Multiple inheritance doesn't exist in C# in any form or way except partially as interfaces. There are many "universal components" that a request model may be composed of. One example is pagination as shown. Another might be result ordering for example as a separate component.
Maybe there are other ways to achieve similar results. If so, please let me know! :)

### Versions
.Net 7
FastEndpoints 5.18.0

**Comment by Seramis** [comment]
1. Not necessarily. When such interface exists for pagination, the next step is that you have an extension method on `IQueryable<T>` that can receive a request DTO based on interface. So in the end one could do something like this in their endpoint code:
```csharp
var results = await myDbCtx.Users.WithPagination(myRequestDto).ToListAsync();
```
A common interface would, of course, lead to common usage pattern.

2. Can't comment that too deeply. Code generation and caching of property metadata might help. (Maybe already been used by FastEndpoints, not sure) Similar concerns are well addressed with different ORM-like libraries (linq2db being my first choice) and somehow they have done it in acceptable way.

**Comment by dj-nitehawk** [comment]
if more people are interested in this, will look in to implementing it.
i'll keep this issue open for a few weeks so that others can chip in.
if anyone seeing this is keen on doing a PR, please go ahead.

**Comment by vipwan** [comment]
This is a matter of programming specifications, and you can't annotate properties inside the interface to be implemented, 
You can use **abstract classes** to achieve the effect you want

**Comment by vipwan** [comment]
> > This is a matter of programming specifications, and you can't annotate properties inside the interface to be implemented, You can use **abstract classes** to achieve the effect you want
> 
> Unfortunately no. One can not inherit from multiple abstract classes, therefore making this suggestion invalid.

Of course, there's a way to do this, and that's to use **source generation**, but that's a solution that has nothing to do with code specifications 

source generation automatically helps you annotate to the properties of the implementation class

**Comment by vipwan** [comment]
> > This is a matter of programming specifications, and you can't annotate properties inside the interface to be implemented, You can use **abstract classes** to achieve the effect you want
>  
> Unfortunately no. One can not inherit from multiple abstract classes, therefore making this suggestion invalid.

A solution using SG is provided https://github.com/vipwan/Biwen.AutoClassGen  :)

**Comment by dj-nitehawk** [comment]
@vipwan that's beautiful.... good stuff mate!

@joonatanu-birkle-it problem solved ;-)

**Comment by dj-nitehawk** [comment]
@vipwan people would find the lib more enticing if the readme was in english ;-)
just a thought...

**Comment by vipwan** [comment]
> @vipwan people would find the lib more enticing if the readme was in english ;-) just a thought...

Well, I'll translate into English 😃
