### ISSUE TITLE
User Secrets aren't working with tests.

### ISSUE THREAD

**Issue by WeismanGitHub** [FastEndpoints/FastEndpoints#514]
I want to test the endpoints in my `API` project from my `Tests` project, but the tests don't recognizing my user secrets. Running the API regularly works fine, as does putting my secrets directly into `appsettings.json`. I've attempted to set the user secrets in both `Tests` and `API`, but it still only reads from `appsettings.json`.

**Comment by dj-nitehawk** [comment]
if you use our [FastEndpoints.Testing](https://fast-endpoints.com/docs/integration-unit-testing#fastendpoints-testing-package) package, secrets overrides for `Testing` environment is automatically picked up from the `Appsettings.Testing.json` file.

see [this example project](https://github.com/FastEndpoints/FastEndpoints/files/13194760/Secrets.zip).

if you are talking about loading user secrets stored by .net under the current users data directory, i don't think that's possible with even regular asp.net.

the standard practice is to put testing related config in a `AppSettings.XXXX.json` file like how it's being done in the attached project.

**Comment by WeismanGitHub** [comment]
Yes, I'm using your testing package, and I tried adding my secrets in `appsettings.Testing.json`, but it still only reads data from `appsettings.json`. I'm pretty sure there aren't any differences between your example project and [my project](https://github.com/WeismanGitHub/Chat-Site-v2), but maybe I missed something. If it matters, I'm running the tests with Visual Studio.
![image](https://github.com/FastEndpoints/FastEndpoints/assets/102398620/021331cd-27ef-42e5-93eb-a1dd01688a30)


Also, how do you test an API that uses `CookieAuth` for auth? In an endpoint I've got `await CookieAuth.SignInAsync(u => u["AccountID"] = account.ID);`, and I'm not sure how to emulate that in a test.

Thank you for the help. I appreciate it a lot. 💜

**Comment by dj-nitehawk** [comment]
i also spent countless hours trying to figure that out :p

the fix is easy:

```cs
var builder = WebApplication.CreateBuilder(args);
```

you need to pass the `args` to `CreateBuilder()` method.

this is where i got the solution from: https://github.com/dotnet/aspnetcore/issues/37680#issuecomment-1738735331

will get back to you on the cookie auth matter when i get some free time later today.

**Comment by WeismanGitHub** [comment]
Passing in `args` fixed it. Thanks!

No rush with the cookie auth stuff. I've got plenty of time haha.

**Comment by dj-nitehawk** [comment]
check this sample: [CookieMonster.zip](https://github.com/FastEndpoints/FastEndpoints/files/13198214/CookieMonster.zip)

you need to hit the login endpoint so that the auth cookie is received by the http client.

**Comment by WeismanGitHub** [comment]
Ok I've got that working too now! Thank you so much for your help.

**Comment by dj-nitehawk** [comment]
there's also the alternative approach of using a [mock authentication](https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-7.0#mock-authentication) scheme/handler.

but i personally like to stay as close as possible to how the system will be used in production. also it's less work/code to maintain ;-)

**Comment by JoshuaNitschke** [comment]
Since I stumbled on this thread while trying to troubleshoot this same issue, I figured I'd contribute how I solved it.

```
public class MyApp :  FastEndpoints.Testing.AppFixture<Program>
{
    ...
    protected override IHost ConfigureAppHost(IHostBuilder a)
    {
        a.ConfigureHostConfiguration(c => c.AddUserSecrets<Program>()); // if you want to use specific secrets for test project change the Class referenced here
        var host = a.Build();
        host.Start();
        return host;
    }
    ...
}
```
