### ISSUE TITLE
Configure Swagger to ignore property on model

### ISSUE THREAD

**Issue by krzysztofseroka-vitessepsp** [FastEndpoints/FastEndpoints#515]
I would like to filter out property on request model (dynamically injected from auth claim, should not be passed in request Body). 
There is a solution for that using `Swashbuckle.AspNetCore.SwaggerGen.ISchemaFilter` (see below) but it does not work with FastEndpoints (it's not possible to configure `SchemaFilters`). Is there an alternative solution?

Solution using `ISchemaFilter`:
```
    [AttributeUsage(AttributeTargets.Property)]
    public class SwaggerExcludeAttribute : Attribute
    {
    }

    public class SwaggerExcludeFilter : ISchemaFilter
    {
        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
        {
            if (schema.Properties == null)
                return;

            var excludedProperties = context.Type.GetProperties()
                .Where(t =>
                    t.GetCustomAttribute<SwaggerExcludeAttribute>()
                    != null);

            foreach (var excludedProperty in excludedProperties)
            {
                if (schema.Properties.ContainsKey(excludedProperty.Name))
                    schema.Properties.Remove(excludedProperty.Name);
            }
        }
    }
```
(based on https://stackoverflow.com/questions/41005730/how-to-configure-swashbuckle-to-ignore-property-on-model)

**Comment by krzysztofseroka-vitessepsp** [comment]
Actually the property is ignored automatically when decorated with `[FromClaim]` attribute, nothing else is needed to remove it from `swagger.json`. The package works exactly how it should - great work!

**Comment by ninety7** [comment]
I am using this library for the first time and am loving it so far!

Actually, I implemented a custom authorization handler that uses different query string parameters, and that I use as input in some endpoint requests. As this info is already entered on the swagger authorization section, it would be very nice if we could make swagger gen ignore request properties at-will; either by creating a new attribute, or by adding a new parameter to the current attributes such as `FromHeaderAttribute(..)".

Would this be possible @dj-nitehawk ?

**Comment by dj-nitehawk** [comment]
@ninety7 you can achive that by decorating the property to be ignored with `[JsonIgnore]` from STJ, or `[HideFromDocs]` from fastendpoints.

fe's nswag operation processor removes those properties like so:
https://github.com/FastEndpoints/FastEndpoints/blob/1e364d6e0058418097fb3af45e2947c781bf361d/Src/Swagger/OperationProcessor.cs#L263-L275

**Comment by ninety7** [comment]
This is really nice. I have not noticed this in the docs (yet) so thank you so much for pointing me to what I was looking for!

**Comment by dj-nitehawk** [comment]
you are most welcome...
looks like we forgot to document it 🤦‍♂️
will update soon 😉
