### ISSUE TITLE
Source generator help

### ISSUE THREAD

**Issue by IeuanWalker** [FastEndpoints/FastEndpoints#516]
Hi, this isn't directly related to fast endpoints, just wondering if anyone can help.

I'm trying to build my first source generator, and i've used the ['ServiceRegistrationGenerator'](https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Generator/ServiceRegistrationGenerator.cs) in this project as a starting point.

The source generator is designed to register hangfire recurring jobs and a basic version is working similar to the 'ServiceRegistrationGenerator'. You can see this on the [master branch in this project](https://github.com/IeuanWalker/Hangfire.RecurringJob.Generator/blob/master/Scr/Attributes/RecurringJobAttribute.cs)

Idea is, user add an attribute too the recurring job class - 
```csharp
[RecurringJob("DeleteOldReportsAtMidnight", "* *678 * *")]
public class DeleteOldReports
{
    public void Execute()
    {
    }
}
```
The source generator automatically generates -
```csharp
namespace TestSolution;

// <auto-generated/>

using Hangfire;
using Microsoft.Extensions.DependencyInjection;

public static class ServiceRegistrationExtensions
{
    public static IServiceCollection RegisterServicesFromTestSolution(this IServiceCollection sc)
    {
		RecurringJob.AddOrUpdate<TestSolution.DeleteOldReports>("DeleteOldReportsAtMidnight", x => x.Execute(), "* *678 * *");
                return sc;
    }
}
```
And all the user has too do is call the registration method at start up `ServiceRegistrationExtensions.RegisterServicesFromTestSolution(services)`

_____

The bit im struggling with now is using more advanced attribute with optional parameters. You can see my [desired attribute here on a different branch](https://github.com/IeuanWalker/Hangfire.RecurringJob.Generator/blob/MoreAdvancedAttribute/Scr/Attributes/RecurringJobAttribute.cs)

The current implementation on the dev branch works the same as 'ServiceRegistrationGenerator' where it uses the argument list to get the properties, and uses them directly. As the more advanced attribute has more fields/ default optional field, i'm trying to pull the values from the properties, but cant find anyway of achieving this.

Any help would be appreciated

**Comment by dj-nitehawk** [comment]
sorry mate! don't have the capacity right now to look in to your problem in detail.
does the syntax tree visualizer in VS not help? rider should also have something similar.

sidenote, we have an "off topic" chatroom on discord. maybe post there and people will respond.

cheers!
