### ISSUE TITLE
Enhancement: Update IPostProcessor for Exception Handling

### ISSUE THREAD

**Issue by tcortega** [FastEndpoints/FastEndpoints#517]
I'd like to propose an enhancement to the `IPostProcessor` interface to include exception handling capabilities. As we continue to expand and refine our system, the ability to gracefully manage and respond to exceptions within post-processing operations becomes increasingly critical.

Currently, post-processors are quite limited as for its capabilities, they are simply pipeline behaviours that runs after an endpoint is done.

I am open to suggestions on the best practices for implementing this and would appreciate any input or discussion on the matter.

**Comment by tcortega** [comment]
I've drafted a PR about it, let me know if there is anything wrong with it @dj-nitehawk

**Comment by dj-nitehawk** [comment]
PR looks alright at first glance.
to take this further can you pls do the following:

1. let's keep things consistent and introduce a `IPreProcessorContext` as well for the pre-processors.
2. PR isn't currently compiling. fix these errors and make PR ready for review.
3. update any tests that need to be refactored to accomodate the breaking change.

sounds good?

**Comment by tcortega** [comment]
> PR looks alright at first glance. to take this further can you pls do the following:
> 
> 1. let's keep things consistent and introduce a `IPreProcessorContext` as well for the pre-processors.
> 2. PR  branch isn't currently compiling. fix these errors and make PR ready for review.
> 3. update any tests that need to be refactored to accomodate the breaking change.
> 
> sounds good?

Okay, understood. It seems reasonable to include it in the preprocessor for the sake of consistency. I will update the branch as soon as possible.

**Comment by tcortega** [comment]
@dj-nitehawk, I believe I've completed it; could you please review the pull request? Additionally, it appears you may have overlooked setting up the requirement for pull requests to receive approvals from yourself or other contributors, as I currently have the option to merge them without any reviews.
