### ISSUE TITLE
Global error handler reason

### ISSUE THREAD

**Issue by IeuanWalker** [FastEndpoints/FastEndpoints#519]
Hi, looking at the code for the global error handler, looks like the exception message is always returned - https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Library/Extensions/ExceptionHandlerExtensions.cs

For security reasons, we generally return a generic message for unhandled exception, unless in debug mode.
Returning the exception message could end up leaking info about the internals of the app that can help with an attack.

Would it be ok if i did a PR that add a parameter to `UseDefaultExceptionHandler` return a generic reason.

Proposed changes is just - 

- New parameter `bool UseGenericReason = false`
- Update the return `Reason = UseGenericReason ? "Something unexpected has happened" : error`

**Comment by dj-nitehawk** [comment]
sounds good. go ahead :-)

**Comment by dj-nitehawk** [comment]
`v5.19.0.4-beta` has been pushed to nuget
