### ISSUE TITLE
Improve InternalErrorResponse swagger example

### ISSUE THREAD

**Issue by IeuanWalker** [FastEndpoints/FastEndpoints#521]
Currently, in the swagger summary i am doing this - 
```csharp
Response<InternalErrorResponse>((int)HttpStatusCode.InternalServerError, "Unhandled error", example: new InternalErrorResponse
{
	Status = "Internal Server Error!",
	Code = 500,
	Reason = "Something unexpected has happened",
	Note = "See application log for stack trace."
});
```

If i add the `DefaultValue` attribute to the `InternalErrorResponse` class properties, i can just do this -
```csharp
Response<InternalErrorResponse>((int)HttpStatusCode.InternalServerError, "Unhandled error");
```

Ok for me to do a PR?

**Comment by dj-nitehawk** [comment]
if doing that, i think we should add the `DefaultValue` attribute to other DTOs such as `ErrorResponse` and `ProblemDetails` to keep the behavior consistent right?

**Comment by dj-nitehawk** [comment]
alright then... go ahead with the PR...

**Comment by dj-nitehawk** [comment]
`v5.19.0.5-beta` pushed to nuget.
thanks again ;-)
