### ISSUE TITLE
[Proposal] Alter default JWT Bearer Options

### ISSUE THREAD

**Issue by rudiv** [FastEndpoints/FastEndpoints#526]
When using `AddJWTBearerAuth` from FE, it's almost guaranteed that the consumer is using `JWTBearer.CreateToken`. It's then reasonable to expect that what you create is what you'll get back, however ASP.NET Core's default behaviour is to map inbound claims.

For example, a `sub` claim will become `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/nameidentifier`.

A test case is available here: https://gist.github.com/rudiv/ee386f4532fc8fa94932a939893dd819

This is fixed in 1 of 2 ways.

1. Globally remove the inbound claim mappings using `JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();`. This is advice from [this article about OpenId Connect](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/claims?view=aspnetcore-8.0#claims-namespaces-default-namespaces).

There are issues with this however. 1: it doesn't work with .NET 8 (preview 7 and above). 2: It GLOBALLY disrupts the claim mapping, meaning for other schemes (think Identity/Cookies if used, not the FE ones) claims will not map correctly without also updating the Identity/UserManager configuration (as some internals are using `ClaimTypes.NameIdentifier` in the case of the "sub" claim, for example).

For 1, the new code is actually `JsonWebTokenHandler.DefaultInboundClaimTypeMap.Clear()` as a new handler has been added as of preview 7. 2 still applies, however. Note that the link above, despite being 8.0 documentation does not reflect the change yet (a separate issue was logged for this).

2. Use the more modern method of setting `MapInboundClaims = false` on the `JWTBearerOptions`.

This is available since .NET 5 and works by setting the instance property on the handler of the specific authentication scheme.

This proposal thus proposes 1 of 2 options.

1; Expose the full `JWTBearerOptions`, rather than the more inner properties of `TokenValidationParameters` and `JwtBearerEvents`.

This means that the API would change from:
```cs
.AddJWTBearerAuth(Keys.SignKey,
        tokenValidation: o => o.ValidateIssuer = true,
        bearerEvents: o => o.OnTokenValidated = context => ..)
```

to this:
```cs
.AddJWTBearerAuth(Keys.SignKey, options: o =>
{
    o.TokenValidationParameters.ValidateIssuer = true;
    o.Events.OnTokenValidated = context => ..;

    o.MapInboundClaims = false; // Added to disable the mapping
});
```

The benefits of this is less maintenance on the API in case something else was added to `JwtBearerOptions` that might be relevant to developers. Drawback is that it would change the signature of the method and thus be a breaking change (unless it was done as an overload).

2. Within `AddJWTBearerAuth`, set the `MapInboundClaims = false` directly thus making it the default behaviour to not map.

Whilst not adding as much flexibility as the first option, it does provide the expected behaviour to developers that are creating their own signed tokens within the app and expect them to be consistent.

-----

A bonus 3rd option would be to do both, provide a sensible default for the FE specific scheme that could be overridden by the action provided by option 1.

**Comment by dj-nitehawk** [comment]
sounds good.
can we keep the existing method and add a new overload? 
if so, go ahead and send in a PR. 
cheers!
