### ISSUE TITLE
[Enhancement] Default force authentication on all endpoints

### ISSUE THREAD

**Issue by IeuanWalker** [FastEndpoints/FastEndpoints#529]
In our current MVC api project we force authentication on all endpoints automatically by default, by doing this -
```csharp
services.AddControllers(opt =>
{
    AuthorizationPolicy policy = new AuthorizationPolicyBuilder()
        .RequireAuthenticatedUser()
        .Build();
    opt.Filters.Add(new AuthorizeFilter(policy));
})
```

We do this just in case someone forgets to add a role/ policy to an api _(and its not picked up in  PR)_. It also means someone has to explicitly add the `AllowAnonymous` attribute to open up an API.

Wondering if a new property can be added to the `UseEndpoints` config, `bool AuthenticateAllEndpionts` that would replicate the same behaviour

**Comment by rudiv** [comment]
As it stands currently all FE endpoints are already secure by default and have the behaviour that you're expecting.

From the documentation:

> Securing Endpoints
>
> Endpoints are secure by default and you'd have to call AllowAnonymous() in the configuration if you'd like to allow unauthenticated users to access a particular endpoint.

`UseEndpoints()` is for mapping ASP.NET endpoints.

**Comment by IeuanWalker** [comment]
@rudiv ahh thanks, that's great, missed that from the docs
