### ISSUE TITLE
HTTP Verb tampering

### ISSUE THREAD

**Issue by IeuanWalker** [FastEndpoints/FastEndpoints#530]
A while ago when our MVC Web api was web inspected, one of the security risks that came back from the report was [HTTP Verb Tampering](https://owasp.org/www-project-web-security-testing-guide/v41/4-Web_Application_Security_Testing/07-Input_Validation_Testing/03-Testing_for_HTTP_Verb_Tampering)

Im not sure how much of a security issue this is in .net applications but to fix the issue raised from the web inspect i wrote this middleware (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405) - 
```csharp
public class HttpVerbsMiddleware
{
    private readonly RequestDelegate _next;
    private string[] VerbsToInclude = { "GET", "POST", "DELETE", "PUT" };
    public HttpVerbsMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task Invoke(HttpContext context)
    {
        if (!VerbsToInclude.Contains(context.Request.Method))
        {
            context.Response.StatusCode = 405;
            await context.Response.WriteAsync("Method Not Allowed").ConfigureAwait(false);
        }

        await _next.Invoke(context);
    }
}
```

Wondering if something could be added to do this automatically based on the endpoints found/ registered.

Some new options added to `UseFastEndpoints` - 
```csharp
public class HttpVerbBlockingOptions
{
    public bool Block { get; set; } = true;
    public string[]? AdditionalVerbs { get; set; } // incase people are using endpoints/ settings outside of fastEndpoints
}
```

**Comment by dj-nitehawk** [comment]
i don't see why you need an additional middleware because the asp.net routing middleware blocks any http verb that the endpoint is not configured/listening for.

for example, if you do a POST to the following PUT endpoint, you will get a 405 - method not allowed automatically.

```cs
sealed class PutEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Put("put-test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync($"method: {HttpMethod}");
    }
}
```
