### ISSUE TITLE
Binding query params without attributes

### ISSUE THREAD

**Issue by Arcalise08** [FastEndpoints/FastEndpoints#531]
I cant seem to get query params to populate correctly on swagger.

```csharp
public record GetUsersBySomethingQuery(
        string Something,
        CursorPaging Paging
    );
```

![image](https://github.com/FastEndpoints/FastEndpoints/assets/61042848/c229c97f-f4e7-4168-96a6-d1d4c5cf3281)

We follow clean architecture principles in our project so we cant use attributes in our contracts. Is there anyway to get this working correctly without attributes?

**Comment by dj-nitehawk** [comment]
attribute annotation is how the nswag operation processor identifies which dto properties are bound from query params. 

if unable to use attributes, the only other option left for you is to to write your own operation processor and replicate what the built in operation processor does by looking for attribute annotations. 

what that alternative is, I have no clue. maybe looking for xml comments?

so yeah this is CA specific problem. FE was designed for VSA so I'm not sure there's any elegant solution we can provide for CA.

**Comment by dj-nitehawk** [comment]
here's what the built in op processor does: 
https://github.com/FastEndpoints/FastEndpoints/blob/c60b83fb4edcef6cfc905ef90f123b1fbbf42de0/Src/Swagger/OperationProcessor.cs#L298

**Comment by Arcalise08** [comment]
Well i should say, I dont mean we cant use attributes in general. Our lower level libraries just cant have references to external sources. So i can make my own attribute which does the same thing. With that in mind, is an operation processor still the only way to go?

**Comment by dj-nitehawk** [comment]
yeah an operation processor is the only way I'm aware of in nswag that let's us modify the swagger generation.
