### ISSUE TITLE
OpenTelemetry Instrumentation with .AddAspNetCoreInstrumentation() covering all FastEndpoints cases?

### ISSUE THREAD

**Issue by christophwille** [FastEndpoints/FastEndpoints#533]
https://opentelemetry.io/docs/instrumentation/net/manual/

specifically

```
builder.Services.AddOpenTelemetry()
  .WithTracing(b =>
  {
      b
      .AddSource(serviceName)
      .ConfigureResource(resource =>
          resource.AddService(
            serviceName: serviceName,
            serviceVersion: serviceVersion))
      .AddAspNetCoreInstrumentation()
      .AddConsoleExporter();
  });
```

Question is does AddAspNetCoreInstrumentation() cover all bases for FastEndpoints too, or eg might it be useful to mark running an endpoint specifically, or some other "added value" for FastEndpoints that is not in that "general" ASP.NET tracing instrumentation?

**Comment by dj-nitehawk** [comment]
haven't tried it myself but theoretically it should as fastendpoints is doing those minimal api endpoint registrations such as `app.MapGet(...)` internally.

if `.AddAspNetCoreInstrumentation()` doesn't seem to work for you, please provide a minimalistic repro project we can debug and get to the bottom of why it's not detecting the minimal api endpoints mapped by fastendpoints. i don't see a reason why it shouldn't.

if anybody seeing this who's already using open-telemetry with FE, please chip in.

cheers!
