### ISSUE TITLE
.NET 8.0 support

### ISSUE THREAD

**Issue by YandyZaldivar** [FastEndpoints/FastEndpoints#536]
Are any of you already using FE in the stable .NEt 8.0 version?

I am experiencing the following issue when trying to migrate my projects using FE to .NET 8.0:

https://github.com/RicoSuter/NSwag/issues/4583

This is not directly related to FE, but it stops the early adoption of .NET 8.0.

In that thread there is a suggested workaround of using a preview version of NSwag, yet not sure if feasible or a good idea.

In any case, let's keep this issue open to track FE readiness for .NET 8.0

`[.NET 8.0 preview versions are not affected by this]`

**Comment by dj-nitehawk** [comment]
latest FE beta `v5.19.0.10-beta` is .net 8 ready.

see the first item in the [FE changelog](https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Library/changelog.md) for a temporary workaround until NSwag gets updated.

**Comment by YandyZaldivar** [comment]
Thanks for the update!
I'll definitely try out the pre-release of FE while the final version is being cooked.

**Comment by KateyBee** [comment]
`v5.20.0-rc1` has been published to Nuget.
This will most likely be the final build which is going to be published as `v5.20` in two weeks or so.
The RC is production ready if you're in a rush to use .NET 8 in production.
Finalized changelog can be found [here](https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Library/changelog.md).

**Comment by russharding** [comment]
Getting an error with NSwag. They don't support .NET 8 until version 14 which is in preview. The error suggests directly referencing Microsoft.Extensions.DependencyInjection.Abstractions, but NSawg prevents that upgrade.

The two packages giving me the error and refusing to update are:

- FastEndpoints.AspVersioning
- FastEndpoints.Testing


Jumping to version 14 should resolve the problem, but that unfortunately puts a dependency on another preview release.

https://www.nuget.org/packages/NSwag.Generation.AspNetCore/14.0.0-preview010

```
Error	NU1107	Version conflict detected for Microsoft.Extensions.DependencyInjection.Abstractions. Install/reference Microsoft.Extensions.DependencyInjection.Abstractions 8.0.0 directly to project Api to resolve this issue. 
 Api -> Microsoft.Extensions.Http.Polly 8.0.0 -> Microsoft.Extensions.Http 8.0.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 8.0.0) 
 Api -> FastEndpoints.AspVersioning 5.20.0-rc1 -> NSwag.Generation.AspNetCore 13.20.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 7.0.0 && < 8.0.0).
```

**Comment by dj-nitehawk** [comment]
@russharding 

update to FE `v5.20.0-rc1` and put the following in your `.csproj` until the other libraries start supporting .net 8:

```xml
<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
```

**Comment by russharding** [comment]
@dj-nitehawk , I didn't submit the comment until after I had tried the work around.

"I did try the work around in the release notes, but the solution refuses to build. One item of note, I am using ManagePackageVersionsCentrally set to true."

**Comment by dj-nitehawk** [comment]
@russharding that must be why it's not working. i'm not familiar with central package management.
maybe a [version override](https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management#overriding-package-versions) would work?

**Comment by ardalis** [comment]
I'm also using central package management and was having the same problem. @russharding can you show where you put the versionoverride for your solution? Also, not happy about having to turn off warnings as errors... hopefully NSwag publishes their full version this week.

**Comment by russharding** [comment]
@ardalis I put the overrides in the two projects that were impacted for me. My API and Integration test csproj files.

For example, from my test project:

```
<ItemGroup>
	<PackageReference Include="AsyncAwaitBestPractices" />
	<PackageReference Include="FastEndpoints.Testing" />
	<PackageReference Include="JetBrains.DotMemoryUnit" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" />
	<PackageReference Include="TestEnvironment.Docker.Containers.Elasticsearch" />
	**<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" VersionOverride="8.0.0" />
	<PackageReference Include="Microsoft.Extensions.Options" VersionOverride="8.0.0" />**
	<PackageReference Include="xunit" />
	<PackageReference Include="xunit.runner.visualstudio">
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>
	<PackageReference Include="coverlet.collector">
		<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>
</ItemGroup>
```

**Comment by ardalis** [comment]
Thanks!

**Comment by fluto7** [comment]
I've been developing a Web API using .NET 8 and am currently testing with FastEndpoints.Swagger v5.20.0-rc1 and NSwag v14 preview. I came across a potential compatibility issue related to recent changes in NSwag.

In the NSwag v14 preview version, it appears that the **UseSwaggerUi3** method has been removed, leaving only the **UseSwaggerUi** method for setting up Swagger UI. This change is highlighted in the commit message "remove legacy swagger ui (keep only UseSwaggerUi() with latest version)," which I found in the NSwag GitHub repo. Here's the specific commit: [NSwag Commit](https://github.com/RicoSuter/NSwag/commit/512eb654b1be5714c7923b74d22e2049d56b5622)

Given this change, there might be a compatibility issue with the current RC version of FastEndpoints.Swagger, which still includes calls to UseSwaggerUi3. This could affect users working with the latest versions of both libraries.

Could we consider the following actions to address this?

Review and Adapt to NSwag's Latest Changes: It would be beneficial to review these changes in NSwag and reflect them in the upcoming RC version of FastEndpoints.Swagger.

Update Method Calls for Compatibility: In the UseSwaggerGen extension method of FastEndpoints.Swagger, replacing the call to UseSwaggerUi3 with UseSwaggerUi might be a suitable solution.

This update will enhance the development experience for those of us working with .NET 8 and these libraries. Looking forward to any updates on this.

Thanks for the great work on FastEndpoints!

**Comment by KateyBee** [comment]
`v5.20.0-rc2` has been published to Nuget.
It has been updated to use `NSwag v14 RC1` and there's no apparent API changes needed for FE users.
There has been a lot of changes under the hood of NSwag as well as some breaking changes to their public API. So there is a small chance of some issues cropping up due to weird edge cases. We should test this build out before doing the final `v5.20` FE release.

Starting FE `v5.20.0-rc2` onwards there's no need for the following workaround in your `.csproj` files. You can delete these lines if you added them in `v5.20.0-rc1`:
```xml
<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.0" />
<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.0" />
```

**Comment by dj-nitehawk** [comment]
`v5.20` has been released
