### ISSUE TITLE
Endpoints Explorer Support

### ISSUE THREAD

**Issue by ardalis** [FastEndpoints/FastEndpoints#539]
By default Fast Endpoints endpoints don't appear to be automatically discovered by VS 2022's Endpoints Explorer. I'm not sure if there's anything we can do or if we need to relay on Visual Studio to address this but we should track it.

**Comment by ardalis** [comment]
If nothing else it should pick up requests from .http files but it doesn't do that, either. You can apparently create .http files from Endpoints Explorer but not the other way around. So far (because I always use endpoints) I haven't found Endpoints Explorer to be at all useful...

**Comment by dj-nitehawk** [comment]
yeah even in rider I don't find myself using the endpoint explorer ever. just like to work with .http files or swagger ui for quick testing of endpoints. postman doesnt even get much action from me anymore 😋

anyway let's keep this issue open and implement it as a "nice to have" feature if we can figure something out without having to invest too much energy in to it.

**Comment by ardalis** [comment]
Right. I'm hoping we can get the Visual Studio team to figure out how to detect our endpoints.

**Comment by dj-nitehawk** [comment]
yeah that would be great...
know anyone on the VS team we could talk to?
otherwise, i'm not even sure where to go for logging a feature request.

**Comment by ardalis** [comment]
There are already some open VS feature requests linked from this similar issue:
https://github.com/ardalis/ApiEndpoints/issues/196

Feel free to upvote them, everyone!

**Comment by ardalis** [comment]
See: https://developercommunity.visualstudio.com/t/Detect-Fast-Endpointscom-Endpoints-in-E/10535339?port=1025&fsid=5f6dc153-7fd0-4649-9ad7-37273c8a6ecf

**Comment by dj-nitehawk** [comment]
> See: https://developercommunity.visualstudio.com/t/Detect-Fast-Endpointscom-Endpoints-in-E/10535339?port=1025&fsid=5f6dc153-7fd0-4649-9ad7-37273c8a6ecf

everyone who's interested in seeing FE endpoints in VS endpoints explorer, please go vote/comment [on this issue](https://developercommunity.visualstudio.com/t/Detect-Fast-Endpointscom-Endpoints-in-E/10535339).

**Comment by frasermclean** [comment]
Not sure if it's related, but Rider also cannot detect any Fast Endpoints endpoints

**Comment by dj-nitehawk** [comment]
@frasermclean rider does pick up `swagger.json` files if you drop it in the project directory.
you can [export the swagger.json files](https://fast-endpoints.com/docs/swagger-support#exporting-swagger-json-files) with a cli command.

**Comment by dj-nitehawk** [comment]
closing due to no viable solutions.

**Comment by alexalok** [comment]
As a note, it semi-works on 17.11 thanks to [Discover dynamic Web API routes](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#endpointsexplorerdynamicdiscovery). It does detect the URL and the endpoint's name correctly, but the rest is of no-good use. It also can't navigate to the endpoint class, at least it didn't work for me.

![image](https://github.com/user-attachments/assets/e8ef6fb8-a25c-4c4b-98be-3a07927bbfee)
