### ISSUE TITLE
Error trying to run tests on .Net 8.0

### ISSUE THREAD

**Issue by wgrs** [FastEndpoints/FastEndpoints#540]
On Linux 23.10, .Net 8.0

Trying to run a test project and I am getting this error:

Error Message:
   System.AggregateException : One or more errors occurred. (Can't find '/home/xxx/Dev/Projects/FSBO/tests/bin/Debug/net8.0/testhost.deps.json'.

There is a file test.deps.json in that directory

**Comment by dj-nitehawk** [comment]
have you tried `v5.20.0-rc1` which is the .net 8 ready release candidate of FE? 

if you're still getting the same error, we're going to need a small repro project that replicates the issue.

**Comment by wgrs** [comment]
OK - thanks. Seems to be OK now.
