### ISSUE TITLE
FastEndpoints.Swagger 5.20.0-rc1 still not working with .net 8

### ISSUE THREAD

**Issue by tmakaro** [FastEndpoints/FastEndpoints#541]
FastEndpoints.Swagger 5.20.0-rc1 -> NSwag.AspNetCore 13.20.0 -> NSwag.Generation.AspNetCore 13.20.0 -> Microsoft.Extensions.Options (>= 7.0.0 && < 8.0.0)

**Comment by ardalis** [comment]
NSwag needs to get their stuff working, I think

**Comment by dj-nitehawk** [comment]
@tmakaro did you see this part from the [changelog]

(https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Library/changelog.md)?
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/2a52502b-bcf8-4a4e-8082-c982a39dd984)

doing that has worked for every project i upgraded. even though there will still be a compiler warning, it doesn't prevent the project from compiling.

**Comment by tmakaro** [comment]
Adding the package references to Microsoft.extensions worked.
