### ISSUE TITLE
Cookie AuthN - 404 instead of unauthorized

### ISSUE THREAD

**Issue by christophwille** [FastEndpoints/FastEndpoints#543]
[404Sample.zip](https://github.com/FastEndpoints/FastEndpoints/files/13440714/404Sample.zip)

See the sample (working via swagger and the default request objects works out of the box) - when you call /debugauthn/demo, you get a 404. If you call /debugauthn/login and then again /debugauthn/demo it works (authenticated). Why am I seeing 404 when not authenticated? That is strange.

**Comment by dj-nitehawk** [comment]
will have a look at your sample as soon i get a chance.
in the meantime, please see if this is related to the following: https://github.com/FastEndpoints/FastEndpoints/issues/389#issuecomment-1445249592

**Comment by christophwille** [comment]
That is exactly the behavior, and yes, the linked fix does work (404 is now 401)

**Comment by dj-nitehawk** [comment]
alrighty then :-)
