### ISSUE TITLE
FastEndpoints ver 5.20.0-rc1 model binding not working

### ISSUE THREAD

**Issue by wgrs** [FastEndpoints/FastEndpoints#544]
I upgraded FE to 5.20.0-rc1 yesterday. I am running .NET 8 on Ubuntu.

I have setup CRUD endpoints but when posting, the model binding is not working and there are no errors. So all string properties are shown as "" and int properties are showing 0;

Is this a known issue?

**Comment by dj-nitehawk** [comment]
there's no such known issues.
can you attach a small repro project pls?

**Comment by wgrs** [comment]
Created a new project and it works now
