### ISSUE TITLE
Memory Bleeding 

### ISSUE THREAD

**Issue by delasource** [FastEndpoints/FastEndpoints#546]
hi there, 
i have an endpoint that accepts a larger request payload (1MB of json). Everything is working, but memory usage keeps growing the more requests i receive. Garbage Collection does happen, but it seems like not everything is cleaned. I excluded the source within my code, by removing every code from the Handle/Execute function and constructor. So the endpoint basically just serializes/binds the request object (and has authorization).

I.e. when i hit the endpoint with 1000 requests (each being around 1MB of json), the server's memory raises up to 2GB usage (and more), which is a. much more then a binary representation of that data should be and b. does not get cleaned up by garbage collection.

It's a rather complex request dto (i.e. a list of objects with a list of objects) and i noticed that when i remove the endpoints Request-type (meaning no serialization/binding happens) then the memory usage does not raise.

**Comment by delasource** [comment]
indeed the same behaviour. but far less. it settles around 1.2GB. (probably because of missing auth and other middleware).

ok then why is that, and what can we do about it?

**Comment by dj-nitehawk** [comment]
i believe it's just how STJ or any other serializer works. if you try it with newtonsoft, the damage would be far worse.
afaik deserialization of that much json data is expensive work. don't quote me on that though.
maybe you should create an issue with STJ team/ microsoft and see what they have to say.

i mean it seems fair right... how many individual instaces of nested objects needs to be created and kept in memory recursively until the whole operation is complete. and then afterwards it would take some time for the gc to kick in. thousands of those operations in a short span of time is bound to consume that much memory.

so i think the best bet for you to is to figure out how to break apart the operation/request in to small chunks.
but in practicality, are you expecting thousands of clients to be submitting 1mb worth of json concurrently?
