### ISSUE TITLE
Generated Operation Id should follow nswag conventions

### ISSUE THREAD

**Issue by dsolteszopyn** [FastEndpoints/FastEndpoints#549]
in nswag.config you can set the property
"operationGenerationMode": "MultipleClientsFromOperationId"

for this to work the operationId in your swagger.json need to have groupings defined by '<group>_<name>'
"operationId": "MyGroup1_Enpoint1"
"operationId": "MyGroup1_Enpoint2"
"operationId": "MyGroup2_Enpoint1"
"operationId": "MyGroup2_Enpoint2"

this will then create two generated clients IMyGroup1 and IMyGroup2

If you specific tags for your endpoints, it groups them in swagger ui but the swagger.json either has the full namespace or short name for the operationId and doesn't apply the convention needed for nswag to support the MultipleClientsFromOperationId

**Comment by KateyBee** [comment]
Starting with `v5.20.0.1-beta` you can do the following:

```cs
//enable the setting
app.UseFastEndpoints(c => c.Endpoints.PrefixNameWithFirstTag = true)

//specify a tag for the endpoint
sealed class SayHelloEndpoint : Endpoint<Request, Response>
{
    public override void Configure()
    {
        Post("/api/hello");
        Tags("MyTag");
    }
}
```

The Swagger Operation Id would then be in the desired format:
```json
"paths": {
    "/api/hello": {
        "post": {               
            "operationId": "MyTag_SayHelloEndpoint",                
        }
    }
}
```

The other alternative would be to manually specify the Endpoint Name (Operaiton Id) [like this](https://fast-endpoints.com/docs/swagger-support#custom-endpoint-names).

**Comment by dsolteszopyn** [comment]
Exactly what I was looking for, thanks for the response.

**Comment by KateyBee** [comment]
The following looks to be generating multiple clients but they are all put into a single file. I have not been able to figure out how to get NSwag to spit out the clients into separate files. Not sure if it's even supported by NSwag.

```cs
await app.GenerateClientsAndExitAsync(
    documentName: "v1",
    destinationPath: bld.Environment.WebRootPath,
    csSettings: c =>
    {
        //this seems to be the default setting anyway
        c.OperationNameGenerator = new MultipleClientsFromOperationIdOperationNameGenerator();
    },
    tsSettings: null);
```
