### ISSUE TITLE
Error with .NET 8.0, after upgrading packages.

### ISSUE THREAD

**Issue by KrunalParmar85** [FastEndpoints/FastEndpoints#550]
We have upgraded our project to .NET 8.0, to use new improvement in EF Core 8.0

But after upgrading all fast endpoint packages to latest version we started getting conflict reference error.

Version conflict detected for Microsoft.Extensions.DependencyInjection.Abstractions. Install/reference Microsoft.Extensions.DependencyInjection.Abstractions 8.0.0 directly to project V2.FastEndPoints to resolve this issue. 
 V2.FastEndPoints -> V2.Queries -> Microsoft.EntityFrameworkCore 8.0.0 -> Microsoft.Extensions.Logging 8.0.0 -> Microsoft.Extensions.Options 8.0.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 8.0.0) 
 V2.FastEndPoints -> FastEndpoints.Swagger 5.20.0-rc1 -> NSwag.AspNetCore 13.20.0 -> NSwag.Generation.AspNetCore 13.20.0 -> Microsoft.Extensions.DependencyInjection.Abstractions (>= 7.0.0 && < 8.0.0).	V2.FastEndPoints	

Looks like some of Transitive packages are not upgraded to .NET 8.0.

Can you help me with this issue or let me know when it will be updated.

**Comment by dj-nitehawk** [comment]
if that's not the case, find the projects that's still referring to `FastEndpoints.Swagger 5.20.0-rc1` and upgrade to the latest release.

**Comment by AymericB305** [comment]
I had this issue using FastEndpoints.Swagger 5.19 with EF core 8. This is not the case anymore with FE 5.20

**Comment by KrunalParmar85** [comment]
thanks @dj-nitehawk  

I was using rc1 version for FastEndpoint.Swagger package, didn't realize when it released. 
Also, I was using asp.net core swagger app.UseSwaggerUi3 intead of a..UseSwaggerGen().

It would be much better, if swagger can group API by their name or some other way to group them by API path, instead of everything showing under common API (since all routes starts with api/). 

I would still want separate group for api/product and api/user routes, so it become easy to find those apis.

**Comment by dj-nitehawk** [comment]
> It would be much better, if swagger can group API by their name or some other way to group them by API path

it's possible. see here: https://fast-endpoints.com/docs/swagger-support#swagger-operation-tags
