### ISSUE TITLE
How to change interval for GetNextBatchAsync?

### ISSUE THREAD

**Issue by LeMigoA** [FastEndpoints/FastEndpoints#553]
I noticed that it takes some time that GetNextBatchAsync gets called so the Queue processing does not start instantly like i want it to be.
How can i set the interval to something lower for GetNextBatchAsync to be called?

**Comment by dj-nitehawk** [comment]
check [this sample](https://github.com/FastEndpoints/FastEndpoints/files/13545627/JobRepro.zip). works as expected.
make sure the db is ready before the command is executed.
update the sample and send back if you can reproduce the issue there.

**Comment by LeMigoA** [comment]
Thank you following your example if fixed my code, looks like it executes incoming queue item instantly now.
