### ISSUE TITLE
Cannot use RequiredScope from "Microsoft.Identity.Web"

### ISSUE THREAD

**Issue by DrXSsive** [FastEndpoints/FastEndpoints#556]
Hey guys,

I am using FastEndpoints for my new project but the issue I am have is to use RequiredScope attribute in my methods. I tired to explore the documentation but could not find anything. Can anyone please help me here?

**Comment by dj-nitehawk** [comment]
you can add any attribute as metadata to an endpoint like shown here: https://github.com/FastEndpoints/FastEndpoints/issues/342#issuecomment-1321543276
