### ISSUE TITLE
How to check a user's permissions when accessing API resources?

### ISSUE THREAD

**Issue by ngoquoctoandev** [FastEndpoints/FastEndpoints#557]
I want to authorize only users with a specified permission to use API resources.
According to the FastEndpoints documentation instructions, I set up claims about the user, role, and permissions to create a token to send to the user. If that person has some access to the resource then it seems reasonable. But if a user has several hundred permissions, the following problems will occur:
1. Bearer token in the request header will be very heavy.
2. May lead to security leaks.
Is there a way to secure the token, and check whether a user's access permission is valid or not, without relying on the token?
My idea is to write a service like IUserService to check whether the userId in the incoming request has that permission or not? If so, continue processing in the Handle method, otherwise return an unauthenticated error.

```
public class CreateNumerologyMapEndpoint(INumerologyService numerologyService, IStringLocalizer<CreateNumerologyMapEndpoint> localizer) : Endpoint<CreateNumerologyMapRequest, ApiResponse<NumerologyMapResponse>>
{
    private readonly IStringLocalizer _s = localizer;

    public override void Configure()
    {
        Post(EndpointConstants.Numerology);
        Permissions("Permissions.Numerology.Create");
    }

    public override async Task HandleAsync(CreateNumerologyMapRequest req, CancellationToken ct)
    {
        // handle logic here
    }
}
```

This is a sample JWT Token
```
{
  "id": "69537306-8c44-4d05-914c-2f5d810f8dc1",
  "emailaddress": "admin@root.com",
  "givenname": "root",
  "surname": "Admin",
  "imageUrl": "",
  "phone_number": "",
  "username": "admin@root.com",
  "type": "Pro",
  "tenant": "root",
  "permissions": [
    "Permissions.Dashboard.View",
    "Permissions.Hangfire.View",
    "Permissions.Users.View",
    "Permissions.Users.Search",
    "Permissions.Users.Create",
    "Permissions.Users.Update",
    "Permissions.Users.Delete",
    "Permissions.Users.Export",
    "Permissions.UserRoles.View",
    "Permissions.UserRoles.Update",
    "Permissions.Roles.View",
    "Permissions.Roles.Create",
    "Permissions.Roles.Update",
    "Permissions.Roles.Delete",
    "Permissions.RoleClaims.View",
    "Permissions.RoleClaims.Update",
    "Permissions.Numerology.View",
    "Permissions.Numerology.Search",
    "Permissions.Numerology.Create",
    "Permissions.Numerology.Update",
    "Permissions.Numerology.Delete",
    "Permissions.Numerology.Export",
    "Permissions.Tenants.View",
    "Permissions.Tenants.Create",
    "Permissions.Tenants.Update",
    ...
    ...
    ...
    "Permissions.Tenants.UpgradeSubscription"
  ],
  "role": "Admin",
  "aud": "https://helloworld.com",
  "iss": "HelloApi",
  "exp": 1701790286,
  "iat": 1701786686,
  "nbf": 1701786686
}
```

**Comment by dj-nitehawk** [comment]
first try the [source generated permissions/access control feature](https://fast-endpoints.com/docs/security#source-generated-access-control-lists). the 3 digit generated permission codes might be able to reduce the size of the jwt payload.

if that's still too big, you can write a session based authentication handler [like this](https://gist.github.com/dj-nitehawk/ef60db792a56afc23537238e79257d13), where the client will be sending just a session id and the auth handler will be looking up the users roles/claims/permissions on every incoming request.

**Comment by ngoquoctoandev** [comment]
Your idea of creating permissions with 3 characters is also great, but perhaps there should still be other options that do not assign permissions to tokens. Is there any other method like what I do below?
In which I have a service IUserService to check whether the user has the specified permission or not?
Previously when using Controller. I write a class like this:

```
public class MustHavePermissionAttribute(string action, string resource) : AuthorizeAttribute, IAuthorizationRequirement, IAuthorizationRequirementData
{
    public string Permission { get; } = FSHPermission.NameFor(action, resource);

    public IEnumerable<IAuthorizationRequirement> GetRequirements()
    {
        yield return this;
    }
}

internal class PermissionAuthorizationHandler(IUserService userService) : AuthorizationHandler<MustHavePermissionAttribute>
{
    protected override async Task HandleRequirementAsync(AuthorizationHandlerContext context, MustHavePermissionAttribute requirement)
    {
        if (context.User?.GetUserId() is { Length: > 0 } userId &&
            await userService.HasPermissionAsync(userId, requirement.Permission))
            context.Succeed(requirement);
    }
}
```
In any method in the Controller, I want users to have a specified permission to access the API as follows:

```
[HttpGet("/test")]
[MustHavePermission("Test", "View")]
public IActionResult Test()
{
    return Ok("Hello world!");
}
```

**Comment by IeuanWalker** [comment]
@ngoquoctoandev you could potentially look at creating a pre processor to handle it.
Not used them my self, but quick glance it should work - https://fast-endpoints.com/docs/pre-post-processors#short-circuiting-execution

**Comment by dj-nitehawk** [comment]
@ngoquoctoandev a pre-processor would work like @IeuanWalker mentioned.

however the way we attach custom attributes to endpoints in FE is like this:
```cs
public override void Configure()
{
    ...        
    Options(x=>x.WithMetadata(new MustHavePermission("Test", "View")));
}
```

just doing that should work. if it doesn't, attach a small repro project with your approach and i'll look in to it.

the other, much cleaner alternative would be to retrieve the current user's permissions from the database and stick them in the user principal using a [custom claims transformation](https://gunnarpeipman.com/aspnet-core-adding-claims-to-existing-identity/).

that way you can simply do the `Permissions(...)` call in endpoint config and everything will work according to the design of FE.

**Comment by dj-nitehawk** [comment]
@ngoquoctoandev created an example for you: https://gist.github.com/dj-nitehawk/220363f14e649a2cb850d61f9bd793b5
