### ISSUE TITLE
Override the default return codes on HandleAsync()

### ISSUE THREAD

**Issue by DrXSsive** [FastEndpoints/FastEndpoints#561]
Hey Guys,

I am having a problem with the return status codes from HandleAsync() method. I am implementing Google authentication in my api and when I tried to return the Challenge result, usually what happens is, api returns the 302 status code so it is redirected to Google Auth page, but in my case it is returning 204 no content status code and browser is not redirecting to the Google.
```cs
sealed class Handler(SignInManager<ApplicationUser> signInManager) : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("auth/google");
        AllowAnonymous();
    }

    public override async Task<ActionResult> HandleAsync(CancellationToken c)
    {
        var redirectUrl = "/google-callback-handler";
        var properties = signInManager.ConfigureExternalAuthenticationProperties("Google", redirectUrl);
        
        return new ChallengeResult("Google", properties);
    }
}
```

I am using the above code. In normal apis, it works fine, but I am having issue with FastEndpoints. Any help will be highly appriciated.

D

**Comment by dj-nitehawk** [comment]
`HandleAsync()` method cannot return any result type. it only supports `Send*Async()` methods for sending responses.

you have to override `ExecuteAsync()` if you want to return.

see an example [here](https://fast-endpoints.com/docs/get-started#union-type-returning-handler).

also `ChallengeResult` is from MVC. it's not used in minimal apis nor FE.

use `TypedResults.Challenge()` instead.

if you don't wanna use the union type `Results<>` something like the following would work:

```cs
sealed class Handler(SignInManager<ApplicationUser> signInManager) : EndpointWithoutRequest<IResult>
{
    ...
        
    public override async Task<IResult> ExecuteAsync(CancellationToken ct)
    {
        ...
        return Results.Challenge(properties, schemes);
    }
}
```
