### ISSUE TITLE
FastEndpoints.Generator - Auth.Allow not exist 

### ISSUE THREAD

**Issue by kevinvenclovas** [FastEndpoints/FastEndpoints#562]
I tried to auto generate the Auth.Allow static file but without any success: https://fast-endpoints.com/docs/security#auto-generating-the-permission-list

I installed https://www.nuget.org/packages/FastEndpoints.Generator : 
` <PackageReference Include="FastEndpoints.Generator" Version="5.20.1" PrivateAssets="all" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />`

I installed the SDK on VS
`https://github.com/FastEndpoints/FastEndpoints/issues/117#issuecomment-1136891324`

Is there any other to do?

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7681603/29f515ac-20d8-41bb-8e75-58d8e0119f06)

**Comment by kevinvenclovas** [comment]
Installed all VSS Updates did the job! Thank you

**Comment by kevinvenclovas** [comment]
@dj-nitehawk One more question is there an option to add a description to the permissions? I would like to generate a json with all permissions and a description
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7681603/f5b84779-1818-4197-a20f-80489a9d46b2)

**Comment by dj-nitehawk** [comment]
when you say "description", do you mean you want to add something to the `<summary>` xml doc comments?
if so, no such feature exists yet. will look in to that.

if that's not what you meant, pls explain a bit more.

thanks!

**Comment by kevinvenclovas** [comment]
It would be cool if we can descript the permission like this :
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7681603/d903803f-8e81-490d-a3e7-92ed0ab4e99c)

In the Allow file there will be generate a Dictionary like this:

```
#nullable enable

namespace AlfaTools.Auth;

public static partial class Allow
{

#region ACL_ITEMS
    /// <summary><see cref="AlfaTools.Controllers.Authentication.LoginEndpoint"/></summary>
    public const string Authentication_Login = "LQL";
#endregion

#region GROUPS
    public static IEnumerable<string> User => _user;
    private static void AddToUser(string permissionCode) => _user.Add(permissionCode);
    private static readonly List<string> _user = new()
    {
        Authentication_Login,
    };
#endregion

#region DESCRIPTIONS
    Dictionary<string, string> _description = new Dictionary<string, string>(){
     { "LQL","User can login as a admin" }
 };
#endregion
}
```

With all this Information we can generate a json to display all available permission without descripe all permission manually in a extra file:

```
{[
   permissionKey : "LQL"
   description : "User can login as a admin"
   group: "User "
]}
```

Frontend can be like this:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7681603/f8821019-c80d-498f-b920-3e904c55878c)
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7681603/507c49fb-afc1-48c7-b94c-b6127f5ed137)

**Comment by dj-nitehawk** [comment]
it's not possible to change the current method signatures in a non-breaking way. so i implemented an alternative.
starting `v5.20.1.6-beta` you can do either:

https://github.com/FastEndpoints/FastEndpoints/blob/0e613fbfdbf2e8772f0cccb27f1775c614170c98/Web/%5BFeatures%5D/Customers/Create/Endpoint.cs#L40-L44

where you specify the description as a single line comment. it has to follow the same format though. i.e. comment should appear straight after the openning bracket of the `AccessControl` method.

or you can specify all the descriptions in one place with your own partial `Allow` class like this:

https://github.com/FastEndpoints/FastEndpoints/blob/0e613fbfdbf2e8772f0cccb27f1775c614170c98/Web/Auth/Allow.cs#L14-L19

and when you need to consume the descriptions, simply access it via the generated `Allow.Descriptions` dictionary.

give it a try and let me know your thoughts.

**Comment by kevinvenclovas** [comment]
@dj-nitehawk Love it <3 Thank you
