### ISSUE TITLE
FromClaim or HideFromDocs attributes do not remove member from swagger docs if Json naming convention is changed from default

### ISSUE THREAD

**Issue by flamedmg** [FastEndpoints/FastEndpoints#563]
Good morning!
Consider this request:
```
public class GetOrCreateCartRequest
{
  public const string Route = "/cart";

  [FromClaim(IsRequired = false, ClaimType = "sid", RemoveFromSchema = true)]
  [HideFromDocs]
  public Guid? UserId { get;  set; }

  ///  <summary>
  ///    The cart id to retrieve or create.
  /// </summary>
  public Guid? CartId { get; set; }
}

```
And FastEndpoints configuration
```
app.UseFastEndpoints(c =>
  {
    c.Serializer.Options.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;
  })
  .UseAuthentication()
  .UseAuthorization();
```

UserId is still in request body documentation and in example. My suspicion is that RemovePropFromRequestBodyContent that is supposed to remove props can't find property that is in snake case in my example.

If i remove this line ` c.Serializer.Options.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;` then prop is properly removed.

**Comment by KateyBee** [comment]
Thanks for reporting. 
`v5.20.1.7-beta` correctly supports `JsonNamingPolicy.SnakeCase*` now.
With the fix, you don't need to use `[HideFromDocs]` or `RemoveFromSchema = true`

**Comment by flamedmg** [comment]
Thank you very much @KateyBee for supporting this great project! and reacting soooo quick!
