### ISSUE TITLE
[ToHeader] tag for response DTOs just like [FromHeader] exists for request DTOs

### ISSUE THREAD

**Issue by Seramis** [FastEndpoints/FastEndpoints#564]
The current implementation provides certain attributes for request data models to direct where the data is retrieved from inside the http request. (`QueryParam`, `FromHeader`, `FromBody` and a set of attributes related to auth and claims)

It would be great if the library would allow to easily respond with a single model and the model can define some properties to belong to response headers instead of serialized body of the response. For that i would suggest to introduce `ToHeader(string? name = null)` attribute for response models that will be ignored by the json serializer and would be instead put into the header of the response. Default name in the header would be property name itself.

A quick and simple use-case would be an endpoint that responds with list of items and allows pagination.
In general, it is discouraged to use "enveloping" to add additional data like total item count along with the set of items themselves. Instead, additional header values in response are recommended to be used to convey such information and the serialized payload would consist of only the list of items.

**Comment by dj-nitehawk** [comment]
well... the first roadblock to doing something like that would be the `JsonIgnoreAttribute` itself and the fact that [it is sealed](https://source.dot.net/#System.Text.Json/System/Text/Json/Serialization/Attributes/JsonIgnoreAttribute.cs,10). so we can't simply inherit it to make our own `ToHeaderAttribute`. the alternative would be to write a generic `JsonConverter` but it would then have to use reflection which will negatively impact performance. also it would be an unnecessary maintenance burden for FE. so, i don't think it's possible to bake this in to the library unfortunately.

let me however interest you in an undocumented feature that may help you with this requirement.
```cs
public sealed class MyResponse
{
    public int Id { get; set; }

    [JsonIgnore] // so that STJ will not serialize this property
    public string AddMeAsHeader { get; set; }
}

//implement a response interceptor
sealed class AddHeadersInterceptor : IResponseInterceptor 
{
    public Task InterceptResponseAsync(object response,
                                       int statusCode,
                                       HttpContext ctx,
                                       IReadOnlyCollection<ValidationFailure> failures,
                                       CancellationToken ct)
    {
        foreach (var p in response.GetType().GetProperties().Where(p => p.IsDefined(typeof(JsonAttribute), true)))
            ctx.Response.Headers.Append("x-custom-something", p.GetValue(response)?.ToString());

        return Task.CompletedTask;
    }
}

sealed class MyEndpoint : EndpointWithoutRequest<MyResponse>
{
    public override void Configure()
    {
        ...
        ResponseInterceptor(new AddHeadersInterceptor()); // register the interceptor
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        var response = new MyResponse
        {
            Id = 100,
            AddMeAsHeader = "blah blah"
        };
        await SendInterceptedAsync(response);
    }
}
```

**Comment by Seramis** [comment]
There would be no need for extending `JsonIgnoreAttribute`.
In JSON contract, appropriate modifiers can be introduced.

So it would be easy to introduce `ToHeaderAttribute` that makes property being ignored while serializing object. Then only appropriate hydration should be built to take those same properties and put them into the response's headers.

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/custom-contracts

**Comment by dj-nitehawk** [comment]
that link to custom contracts helped a lot and this feature has now been implemented.
checkout `v5.21.2.11-beta` with which, you can now do the following:

```cs
sealed class Response
{
    public int Id { get; set; }

    [ToHeader("x-age")]
    public int Age { get; set; }
}

sealed class MyEndpoint : EndpointWithoutRequest<Response>
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
        Summary( //this has to be done for swagger documentation
            x =>
            {
                x.ResponseHeaders.Add(
                    new(200, "x-age")
                    {
                        Description = "this is a description",
                        Example = 10
                    });
            });
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        var res = new Response { Id = 1, Age = 123 };

        await SendAsync(res);
    }
}
```

there are a couple of limitations to note:
- only works with `Send*Async()` methods that accept a response dto instance (obviously).
- swagger documentation for response headers must be done manually like above using endpoint summary.
- not compatible with `IResult` response types. i.e. doesn't work with `Results` / `TypedResults`.

**Comment by KateyBee** [comment]
@joonatanu-birkle-it 

Your code gave me an idea and I went a slightly different route.
Starting `v5.21.2.13-beta`, Swagger response headers are added automatically, and there's no need to do it manually via `Summary()` unless you want to.

XML summary and example tags are also picked up.
```cs
sealed class Response
{
    /// <summary>
    /// blah blah blah
    /// </summary>
    /// <example>100</example>
    [ToHeader("x-age")]
    public int Age { get; set; }
}
```
