### ISSUE TITLE
Output caching (.Net 7)   not working for me in .Net 8

### ISSUE THREAD

**Issue by wgrs** [FastEndpoints/FastEndpoints#567]
I tried various combinations of configs and none worked. Can you please let me know what config is required and if the Configure method is correct.

I aslo followed the docs example and that did not work either.

Program.cs
-----------------
/*   FASTENDPOINTS  */
builder.Services.AddFastEndpoints().AddResponseCaching();

/*   CACHING   */
//builder.Services.AddOutputCache();

/* FASTENDPOINTS   */
app.UseFastEndpoints().UseResponseCaching();

/*   CACHING   */
// app.UseOutputCache();

-------

 public override void Configure()
    {
        Get("/listings/town/{town}");
        Options(x => x.CacheOutput(p => p.Expire(TimeSpan.FromSeconds(60))));
    }

**Comment by dj-nitehawk** [comment]
check [this sample](https://github.com/FastEndpoints/FastEndpoints/files/13759833/CacheRepro.zip). works as expected.

**Comment by wgrs** [comment]
> check [this sample](https://github.com/FastEndpoints/FastEndpoints/files/13759833/CacheRepro.zip). works as expected.

OK, my config was wrong - the docs arent clear that AddOutput cache should repleace AddResponseCache.

I updated the config but the code breakpoints are still being hit inside HandleAsync. I assume your code snippet is tested in .Net 8? What version of the fastendpoints are you using?

**Comment by wgrs** [comment]
I used the following code from the docs - my config must be correct now because your earlier sample run fine. But the following response does not get cached:

public class MyEndpoint : Endpoint<MyRequest, MyResponse>
{
    public override void Configure()
    {
        Post("api/user/create");
        AllowAnonymous();
        Options(x => x.CacheOutput(p => p.Expire(TimeSpan.FromSeconds(60))));
    }

    public override async Task HandleAsync(MyRequest req, CancellationToken ct)
    {
        await SendAsync(new()
        {
            FullName = req.FirstName + " " + req.LastName,
            IsOver18 = req.Age > 18
        });
    }
}

public class MyRequest
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int Age { get; set; }
}


public class MyResponse
{
    public string FullName { get; set; }
    public bool IsOver18 { get; set; }
}

**Comment by dj-nitehawk** [comment]
you'll see that if you turn the endpoint into a GET endpoint, it works. 
that's because the default caching policy doesn't work for POST requests.
[see here](https://learn.microsoft.com/en-us/aspnet/core/performance/caching/output?view=aspnetcore-8.0#default-output-caching-policy) how to override the default policy.
