### ISSUE TITLE
Factory.Create no longer runs Configure on the Endpoint

### ISSUE THREAD

**Issue by Jmaharman** [FastEndpoints/FastEndpoints#569]
Firstly thank you for this excellent library, we started using it about a year ago and love it's simplicity and power.

We're currently updating from 5.2.1 to the latest and we noticed that Configure is no longer called on the Endpoint when using Factory.Create.

I've looked at the source code and it seems to have been introduced from the following commit:

dependency resolving support for endpoint Configure() method - 77d656ed56310307913a71e04371253b3f2098dc

![image](https://github.com/FastEndpoints/FastEndpoints/assets/215359/a3afa1ce-4ec7-4890-8941-43aebef01ff0)

the crux of it is that ImplementsConfigure and EndpointAttributes are no longer set. I was going to PR my change which gets it workin, seen below on lines 32 and 33, but I imagine that's now how you want to implement it.

![image](https://github.com/FastEndpoints/FastEndpoints/assets/215359/321a02b5-82e5-45be-934a-6675f1502b78)

Test added:

```c#
public class FactoryCreateTests
{
    [Fact]
    public async Task ConfigureIsExecuted()
    {
        var ep = Factory.Create<ConfigureEndpoint>();

        ep.Definition.Routes.Should().ContainSingle("configure/test");
    }
}
``` 

```c#
public class ConfigureEndpoint : Endpoint<Request, Response>
{

    public override void Configure()
    {
        Verbs(Http.GET);
        Routes("configure/test");
    }

    public override Task HandleAsync(Request r, CancellationToken ct)
    {
        return SendErrorsAsync();
    }
}
```

**Comment by Jmaharman** [comment]
wow, thanks so much for the quick turn around. We're testing it now.

**Comment by dj-nitehawk** [comment]
you're most welcome. it was fast because you found the exact cause :-)
a patch release `v5.21.2` has been pushed to nuget.
should be live in a few minutes.

**Comment by Jmaharman** [comment]
It worked perfectly by the way, thanks again!
