### ISSUE TITLE
Location header in the Response is not set properly

### ISSUE THREAD

**Issue by KwizaKaneria** [FastEndpoints/FastEndpoints#570]
In my POST API to create a resource I wanted to set the **LocationHeader** that contains the location from where the resource can be retrieved.  I used the `SendCreatedAtAsync` method in my code to send the **201 - Created**.  But I am getting the incorrect details in the response header, i.e. `/v1/user-company-connections?Length=87`. FYI, I am using the FastEndpoints version **5.7.0** and .NET Framework version **7.0.2**

Can you please guide me on this issue?

![image](https://github.com/FastEndpoints/FastEndpoints/assets/93565720/1bf5c32f-3058-4442-ab09-2b9d6183a518)

**Comment by nefarius** [comment]
And show your endpoint code, please.

**Comment by KateyBee** [comment]
Most likely a user error. I just tried [this code](https://github.com/FastEndpoints/FastEndpoints/issues/15#issuecomment-1008248092) with v5.7.0 and got the correct response header:

![image](https://github.com/FastEndpoints/FastEndpoints/assets/134909513/416c5633-8893-4272-93d5-b35603afe2a4)
