### ISSUE TITLE
Serializer.ResponseSerializer not being used for endpoints returning Results<,> union

### ISSUE THREAD

**Issue by alexalok** [FastEndpoints/FastEndpoints#572]
I have a custom `Serializer.ResponseSerializer` implementation and have noticed that it is not called for my endpoints if I use typed results in them. I would like to know whether this is a bug or an indented behavior. 

Please see a small repro here: https://github.com/alexalok/FastEndpointsResponseSerializerTest
Notice that when you call `GoodEndpoint`, the `Serializer.ResponseSerializer` is being called (and replaces the return value) but when calling `BadEndpoint` this is not the case.

**Comment by dj-nitehawk** [comment]
that is correct. it's not a bug but an unavoidable technical limitation of using `Results` or `TypedResults`.
the `IResult` types from minimal apis is in charge of serializing and writing to the response stream and they haven't exposed a way to customize that behavior.

so the FE response serializer functionality is only available when you use the `Send*Async()` methods in FE.

you can see under the hood difference between the two here:
https://github.com/FastEndpoints/FastEndpoints/blob/ca11936d154d49f1932d5a69ea7d366580d2b0e3/Src/Library/Extensions/HttpResponseExtensions.cs#L14-L48

**Comment by alexalok** [comment]
@dj-nitehawk, thank you for a great explanation. 

For everyone who might stumble upon this issue in the future, the limitation itself is being discussed in https://github.com/dotnet/aspnetcore/issues/39585 for cases of setting custom http headers.

**Comment by dj-nitehawk** [comment]
you're most welcome.
added a note to documentation as well.

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/e02a9c72-7a7a-48c8-9f3b-221966ec92a0)
