### ISSUE TITLE
Partial classes break `FastEndpoints.Generator`

### ISSUE THREAD

**Issue by ShawnTheBeachy** [FastEndpoints/FastEndpoints#574]
In the case of a partial class endpoint, e.g.

```c#
public sealed partial class MyEndpoint : IEndpoint<TIn, TOut> { }
public sealed partial class MyEndpoint { }
```

the `FastEndpoints.Generator` source generator will add two registrations for the class, resulting in a duplicate route exception being thrown on startup.

**Comment by KateyBee** [comment]
Good catch!
Fixed in `v5.21.2.7-beta`
Thanks for reporting.
