### ISSUE TITLE
Dependency Injection support for primary constructors

### ISSUE THREAD

**Issue by joaquinrovira** [FastEndpoints/FastEndpoints#575]
Right now there is support for Dependency Injection via Property [[1]](https://fast-endpoints.com/docs/dependency-injection#property-injection) and Constructor [[2]](https://fast-endpoints.com/docs/dependency-injection#constructor-injection) injection.

C# 12 introduced the concept of Primary Constructors [[3]](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/instance-constructors#primary-constructors). I have tried implementing an Endpoint that uses primary constructors but dependency injection fails.

The following code works as expected, returning 200 OK:

```C#
public class Redirector : EndpointWithoutRequest<Ok>
{
    private readonly IServiceProvider Svc;

    public Redirector(IServiceProvider svc)
    {
        Svc = svc
    }

    public override void Configure()
    {
        Get("/");
        AllowAnonymous();
    }

    public override async Task<Ok> ExecuteAsync(CancellationToken ct)
    {
        if (svc is null) throw new Exception("DI Failed!");
        await Task.CompletedTask;
        return TypedResults.Ok(); // Succeeds
    }
}
```

When using primary constructors, it fails:

```C#
public class Redirector(IServiceProvider Svc) : EndpointWithoutRequest<Ok>
{
    public override void Configure()
    {
        Get("/");
        AllowAnonymous();
    }

    public override async Task<Ok> ExecuteAsync(CancellationToken ct)
    {
        if (svc is null) throw new Exception("DI Failed!"); // Throws 
        await Task.CompletedTask;
        return TypedResults.Ok();
    }
}
```

**Comment by KateyBee** [comment]
Primary constructors is supported out of the box if your project is .NET 8.
I just tried your example and [it works without any problem](https://streamable.com/p7dzyl).
If you're still having trouble, please attach a small repro project and I'll look in to it further.
