### ISSUE TITLE
Overriding paramer type in Swagger document

### ISSUE THREAD

**Issue by jerriep** [FastEndpoints/FastEndpoints#577]
I have the following query class that I use to bind the query string parameters for an endpoint:

```cs
public class Query
{
    public ConnectionKind? Kind { get; set; }

    public string? Type { get; set; }
}
```

Where `ConnectionKind` is defined as follows:

```
public enum ConnectionKind
{
    Source = 0,
    Destination = 1
}
```

When I generate the Swagger document, the documentation for the `Kind` property is generated correctly as an enum

```json
"parameters": [
  {
    "name": "Kind",
    "in": "query",
    "description": "The kind of connection to filter by. Cannot be used in conjunction with Type.\n            ",
    "schema": {
      "nullable": true,
      "oneOf": [
        {
          "$ref": "#/components/schemas/ConnectionKind"
        }
      ]
    }
  },
  ...
]
```

With `ConnectionKind` declared as follows:

```json
"ConnectionKind": {
  "type": "string",
  "description": "",
  "x-enumNames": ["Source", "Destination"],
  "enum": ["source", "destination"]
},
```

So far everything is good. My issue comes in with the `Type` property on my `Query` class. As you can see, on the C# side this is a string. So, in the Swagger document it is declared as follows:

```json
{
  "name": "Type",
  "in": "query",
  "description": "The type of connection to filter by. One of:\n- CONTENTFUL\n- KENTICO\n- NOTION\n- SANITY\n- WEBFLOW\n- WORDPRESS\nCannot be used in conjunction with Kind.\n            ",
  "schema": {
    "type": "string",
    "nullable": true
  }
}
```

Strictly speaking, this is correct. However, it can be a limited set of values. So, as far as the Swagger document is concerned, I don't want the schema type simply declared as "string". I want to override the type for the Swagger document and also generate it as an enum - same as the case for the `Kind` property.

Is this possible?

**Comment by dj-nitehawk** [comment]
maybe in conjunction with [a schema processor](https://github.com/RicoSuter/NJsonSchema/issues/1125#issuecomment-1735825908), you might be able to optimize the above operation processor.

**Comment by dj-nitehawk** [comment]
@jerriep i updated the op processor above and it seems to get the job done. no need for a schema processor as i suggested before.
