### ISSUE TITLE
Validator not running in unit test

### ISSUE THREAD

**Issue by GChannonLondon** [FastEndpoints/FastEndpoints#581]
Hi,

Have you seen an issue with the Validator<> never calling in unit tests when using Factory.Create?

Code below:

`public class TestValidator : Validator<TestRequest>
{
    public TestValidator()
    {
        RuleFor(x => x.Id).GreaterThanOrEqualTo(0);
        //RuleFor(x => x.StartDateTime).LessThan(x => x.EndDateTime);
    }
}`

`public class TestEndpoint : Endpoint<TestRequest, IEnumerable<TestResponse>>
{
    public TestEndpoint(ITestManager tradeManager, AutoMapper.IMapper mapper)
    {
        _tradeManager = tradeManager;
        _mapper = mapper;
    }

    private readonly ITradeManager _tradeManager;
    private readonly AutoMapper.IMapper _mapper;
    
    public override void Configure()
    {
        Verbs(Http.GET);
        Routes("/trades");
        Version(1);
        
        Summary(s => {
            s.Summary = "Trades";
            s.Description = "Query trades";
        });

        AllowAnonymous();
    }

    public override async Task HandleAsync(TestRequest testRequest, CancellationToken cancellationToken)
    {
        var trades = _tradeManager
            .TestData
            .ProjectTo<TestResponse>(_mapper.ConfigurationProvider);
        
        await SendAsync(trades, cancellation: cancellationToken);
    }
}`

`using Microsoft.Extensions.DependencyInjection;
using FluentValidation;

namespace Adapter.Api.Tests.Trade;

[TestFixture]
public class TestEndpointTest
{
    [SetUp]
    public void Setup()
    {
        _fixture = new Fixture();
        _fixture.Customize(new AutoMoqCustomization());
    
        //Test contains legs of Tests which is an acceptable circular reference
        _fixture.Behaviors.OfType<ThrowingRecursionBehavior>().ToList()
            .ForEach(b => _fixture.Behaviors.Remove(b));
        _fixture.Behaviors.Add(new OmitOnRecursionBehavior());
    
        _Tests = _fixture.Build<Core.TestManager.Test>()
            .CreateMany(20).ToList();
    
        _TestManagerMock = _fixture.Freeze<Mock<ITestManager>>();
        _TestManagerMock.Setup(x => x.Tests).Returns(_Tests.AsQueryable());
        
        //_fixture.Inject(new TestValidator());
    
        var TestValidator = new TestValidator();
    
        var mappingConfig = new MapperConfiguration(cfg =>
            cfg.AddProfile(new MappingProfile()));
    
        var automapperMock = _fixture.Freeze<Mock<AutoMapper.IMapper>>();
        automapperMock.Setup(x => x.ConfigurationProvider).Returns(mappingConfig.CreateMapper().ConfigurationProvider);
    
       _TestEndpoint = Factory.Create<TestEndpoint>(
            _TestManagerMock.Object,
            automapperMock.Object);

       _TestEndpoint.Configure();
    }

    [Test]
    public async Task Test_Response_Is_Error_When_Negative_TestId()
    {
        var TestId = _Tests.First().Id;
    
        var TestRequest = new TestRequest
        {
            Id = -1
        };
    
        _TestEndpoint!.Definition.Validator<TestValidator>();
    
        await _TestEndpoint!.HandleAsync(TestRequest, default);
    
        _TestEndpoint!.ValidationFailed.Should().BeTrue();
    
    
    }
}`

**Comment by dj-nitehawk** [comment]
validators are not meant to be executed during a "unit test". model binding, validation, pre/post processors, etc. are part of the pipeline and are not meant to be executed during a unit test. that's what an integration test is for.
the purpose of a unit test is simply to accept a fully populated (and already validated) request dto run the handler logic and return the response. nothing else.

**Comment by dj-nitehawk** [comment]
examples of unit tests: https://github.com/FastEndpoints/FastEndpoints/blob/main/Tests/UnitTests/FastEndpoints/WebTests.cs

examples of integration tests: https://github.com/FastEndpoints/FastEndpoints/blob/main/Tests/IntegrationTests/FastEndpoints/WebTests/AdminTests.cs

**Comment by GChannonLondon** [comment]
Have you got any examples of integration tests with nunit?

**Comment by dj-nitehawk** [comment]
sorry no. we only use xunit.

**Comment by GChannonLondon** [comment]
Have you got any unit test examples for validators?

**Comment by GChannonLondon** [comment]
Why is it that the tests in this test class fail validation if it doesn't call validators? 

https://github.com/FastEndpoints/FastEndpoints/blob/main/Tests/UnitTests/FastEndpoints/WebTests.cs

**Comment by dj-nitehawk** [comment]
> Have you got any unit test examples for validators?

unit testing fluent validators can be done just like you would any other class.
unless your validator needs some service registrations [as described here](https://fast-endpoints.com/docs/integration-unit-testing#service-registration).

**Comment by GChannonLondon** [comment]
Thanks for your help.
