### ISSUE TITLE
Service resolver is null! Have you done the unit test setup correctly?

### ISSUE THREAD

**Issue by baynezy** [FastEndpoints/FastEndpoints#582]
I am trying to follow your advice on how to unit-test endpoints that use `SendCreatedAtAsync` #382:

https://github.com/FastEndpoints/FastEndpoints/blob/9d983c2dadad9c9d0f6e114934f25a26725abec1/Tests/UnitTests/FastEndpoints.UnitTests/WebTests/UnitTests.cs#L128-L135

Here is my version:

```csharp
[Fact]
public async Task WhenCreateDocumentEndpointIsCalled_ThenItShouldReturnCreatedStatusCode()
{
    // arrange
    var linkGenerator = Substitute.For<LinkGenerator>();
    var sut = Factory.Create<CreateDocumentEndpoint>(ctx =>
    {
        var services = new ServiceCollection();
        services.AddSingleton(linkGenerator);
        ctx.RequestServices = services.BuildServiceProvider();
    });

    // act
    await sut.HandleAsync(new CreateDocumentRequest(), CancellationToken.None);
    var statusCode = sut.HttpContext.Response.StatusCode;

    // assert
    statusCode.Should().Be(201);
}
```

When I try this I get an error:

```
System.InvalidOperationException
Service resolver is null! Have you done the unit test setup correctly?
```

What am I doing wrong?

**Comment by dj-nitehawk** [comment]
what you have linked above is an out-dated code snippet.
pls try the current way and report back if it helps or not:

https://github.com/FastEndpoints/FastEndpoints/blob/8c1d03b4cbbf55eb9d47eb7bcf21884ce28fba52/Tests/UnitTests/FastEndpoints/WebTests.cs#L205-L226

**Comment by dj-nitehawk** [comment]
here's a working [sample project](https://github.com/FastEndpoints/FastEndpoints/files/14066636/CreatedAtRepro.zip).

**Comment by freetison** [comment]
I like FastEndpoints, but it's really hard to test. What if you want to use NUnit instead of XUnit in a real endpoint with some dependencies and a PublishAsync() inside.  There is no example test for a real life one. 
In my case, this does not work.

 var serviceA = A.Fake<IServiceA>();
 var serviceB = A.Fake<IServiceB>();
  Factory.RegisterTestServices(s =>
  {
      s.AddSingleton(serviceA);
      s.AddSingleton(serviceB);
  });
            
var ep = Factory.Create<MyEndpoint>();

**Comment by dj-nitehawk** [comment]
@freetison 
it's easy: [NUnitExample.zip](https://github.com/user-attachments/files/16490407/NUnitExample.zip)

**Comment by freetison** [comment]
I'll try, but last night doing that way I received:
System.InvalidOperationException : You cannot add services to this http context because it's not empty!
   at FastEndpoints.Factory.AddTestServices(ServiceA ctx, Action`1 s)
   
   At the end I did it, but the way you are given to me is more clear and elegant .. Thanks a lot .

**Comment by freetison** [comment]
@dj-nitehawk unfortunately I'm receiving the same error using your solution. 
[Test]
        public async Task Configure_Should_Setup_Endpoint_Correctly()
        {
          
            var ep = Factory.Create<MyEndpoint>(
                ctx =>
                {
                    ctx.AddTestServices(s => s.AddTransient<IFoodProcessor, FoodProcessor>());
                    ctx.AddTestServices(s => s.AddTransient<IApiService, ApiService>());
                });

            await ep.ExecuteAsync(_request, _cancellationToken);

            Assert.That(ep.Response.StatusCode, Is.EqualTo(StatusCodes.Status200OK));
        }


System.InvalidOperationException : You cannot add services to this http context because it's not empty!
   at FastEndpoints.Factory.AddTestServices(HttpContext ctx, Action`1 s)

**Comment by dj-nitehawk** [comment]
@freetison 
can you update the attached solution to replicate the issue and attach it here pls?

**Comment by freetison** [comment]
https://github.com/freetison/doctor-booking-demo.git

**Comment by dj-nitehawk** [comment]
@freetison 
ah i see...
you're doing multiple `ctx.AddTestServices()` calls. there should only be one like so:
```cs
var ep = Factory.Create<GetWeeklyAvailabilityEndpoint>(
    ctx =>
    {
        ctx.AddTestServices(
            s =>
            {
                s.AddTransient<IFreeSlotProcessor>(_ => fakeFreeSlotProcessor);
                s.AddTransient<IDocPlannerApiService>(_ => fakeDocPlannerApiService);
            });
    });
```
