### ISSUE TITLE
OAuth2 for FastEndpoints

### ISSUE THREAD

**Issue by d4rkm0nkey** [FastEndpoints/FastEndpoints#584]
Is it currently possible to add OAuth2 Authentication to Swagger?
To me it seems that AddSecurity() is not exposed and can not be called.

I would like to have something like this:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/19959176/39ae9d0b-e51d-4e94-be9d-663e0829ef3c)

**Comment by dj-nitehawk** [comment]
yes it's possible. 
see following discord thread for an example: https://discord.com/channels/933662816458645504/1196371477407223928/1196416310939238430

**Comment by d4rkm0nkey** [comment]
Thank you!
