### ISSUE TITLE
Job Cancellation Support

### ISSUE THREAD

**Issue by d4rkm0nkey** [FastEndpoints/FastEndpoints#587]
When I add a Job to a JobQueue, I want to be able to cancel the job afterwards.

This is how I would imagine it to be:
QueueJobAsync could return a reference to the created job, which features a Cancel method.
When this method is called, the job is removed from the JobStorageProvider and if the JobQueue is already running it cancels the CancelationToken from the Command.

**Comment by dj-nitehawk** [comment]
had a brief look at implementing this but can't seem to find a way do it without introducing a major breaking change.
most likely this will be done with the next major version jump of FE (for which there's no plan atm).
until then, i'll leave this issue open for the community in case somebody can figure out a way without breaking changes.

---

in the meantime, i'd like to understand a bit more why exactly do you need this?
i.e what is the use case where you need to cancel the job early?
is simply setting a job expiry/execution limit not sufficient?

**Comment by d4rkm0nkey** [comment]
I would like to have Jobs that take a long time e.g. 4h. The jobs can be started manually, but sometimes it might be called with wrong parameters or during development, you might not want to wait until the job has finished. So it would be convenient to cancel a job that is already running.

**Comment by Woodman9** [comment]
I'm wondering if one of you maybe know how to fix an issue with JobStorageProvider. I created a mongodb-atlas account, got the connection string and put it in the Fastendpoints solution. When I run the app I get: System.ArgumentException: ''mongodb://:@olaxxwh.mongodb.net/?authSource=admin:27017' is not a valid end point. (Parameter 'value')'. The bizarre thing is how the init function stuffed the port number in the connection string. Can someone point me to information on how to get mongodb provider to work in the Fastendpoints solution??

**Comment by dj-nitehawk** [comment]
@Woodman9 the FE storage provider is db engine agnostic. so there's really no special handling you need to do for FE.

by the looks of it, something has mangled up your connection string. afaik, the mongo connection string looks something like this:

```
mongodb://{username}:{password}@{hostname}:{port}/?authSource=admin
```

can't give you exact steps for the official driver + atlas as i have not played with atlas in a long time.

you might have some luck with my [mongo library](https://mongodb-entities.com/wiki/Get-Started.html#using-a-connection-string). and here's a [sample job storage provider](https://github.com/FastEndpoints/Template-Pack/blob/main/templates/integrated/Source/Services/JobStorageProvider.cs) written for that lib.

**Comment by Woodman9** [comment]
I so much appreciate your help!! The string you posted is actually exactly what I have. It would be helpful to have an example implementation of Mongo because I simply cannot understand how you guys make this work. The "InitDatabase(DbName)" in program.cs fails with the above message I posted. It's like Mongo is detecting environment and stuffing 27017 port into the connection string. I have no idea how to control that. I'm going to keep digging, but some sample code or comments would be helpful in the project template. Again, you reply is very much appreciated.

**Comment by dj-nitehawk** [comment]
@Woodman9 if you join our discord server and create a post with a repro project, I can look in to it for you.

**Comment by Woodman9** [comment]
I will do that! I would like to become a contributor

**Comment by dj-nitehawk** [comment]
@broomfn 
the goal of the project is to supply all tools necessary for building a typical backend/api server (in a non-distributed setting) without the need for any additional dependencies/infrastructure such as message brokers/job schedulers/etc. when it's time for people to graduate their apps to distributed infrastructure, then they can reach for the big boy pants. until then FE will get you up and running in no time.

speaking of job queus, i'm yet to develop a backend app without the need to at least send a notification email in the background. job queing functionality is a perfect fit for getting things done in the background in an extremely convenient manner. can't remember the last time i wrote an `IHostedService ` 😉

@d4rkm0nkey 
i've already implemented cancellation support in a minimally disruptive manner. just need to write the tests before the next beta can be published. will keep you posted on the progress.

**Comment by dj-nitehawk** [comment]
job cancellation support is now complete.
here's how to use it, until the documentation is updated:

https://github.com/FastEndpoints/Job-Queue-Demo/blob/958970b0ff723faab88f5a71bf0c1d9756eff7ac/src/Program.cs#L55-L72
