### ISSUE TITLE
Cannot reference Generated Permission List

### ISSUE THREAD

**Issue by binair-io** [FastEndpoints/FastEndpoints#589]
[Auto-generated permission list](https://fast-endpoints.com/docs/security#auto-generating-the-permission-list) is an amazing feature. For real.

The only downside I am experiencing is when I try to reference the generated constants in the API project itself. Makes sense that at build time, the class is not yet available and thus generates build errors.

What is the recommended use / place for the generator? A separate lib? How can I use the Allow.MyConstantPermission in the API project itself?

**Comment by dj-nitehawk** [comment]
we've tested it in multi project solutions and haven't seen what you're describing. 

could you possibly throw together a small repro and attach here pls? 

it's possible I'm not fully comprehending your use case.

thanks!

**Comment by binair-io** [comment]
Will do, currently prepping a release, will have one up by end of week. Thanks for your quick reply

**Comment by dj-nitehawk** [comment]
in the meantime, give [this project](https://github.com/dj-nitehawk/MiniDevTo/tree/main) a go. 
if it's giving you the same sort of build errors, it could mean something has gone wrong in your dev environment.

**Comment by dj-nitehawk** [comment]
i'll close this for now. feel free to reopen with a repro.
thanks!

**Comment by binair-io** [comment]
Your demo-project pointed me in the right direction. All seems to be working now. Thanks!
