### ISSUE TITLE
Should FastEndpoints inner Validater support both DataAnnotation OR FluentValidation

### ISSUE THREAD

**Issue by buyuanne** [FastEndpoints/FastEndpoints#590]
```cs
public class Test : Endpoint<TestRequest>
{
  public override void Configure()
  {
    Get("test");
    AllowAnonymous();
  }

  public override async Task HandleAsync(TestRequest req, CancellationToken ct)
  {
    await SendOkAsync(req, ct);
  }
}

public class TestRequest
{
  [MaxLength(5)]
  public string Name { get; set; }
}

public class TestRequestValidator : Validator<TestRequest>
{
  public TestRequestValidator()
  {
    RuleFor(s => s.Name).MinimumLength(3);
  }
}
```

This code runs smoothly, but when changed to

```cs
public class TestRequest
{
  [Length(3,5)]
  public string Name { get; set; }
}

//public class TestRequestValidator : Validator<TestRequest>
//{
//  public TestRequestValidator()
//  {
//    RuleFor(s => s.Name).MinimumLength(3);
//  }
//}
```

and comment out the TestRequestValidator
no verification will be conducted

In some simple scenarios, it may be similar to requiring Length under only one DataAnnotations

Should FastEndpoints inner Validater support both DataAnnotation OR FluentValidation #499 

Sorry, these English are from Google Translate, my English level is not good

**Comment by buyuanne** [comment]
This code is valid when FastEndpoints is not used, but it is invalid when FastEndpoints is used

`builder.Services.Configure<ApiBehaviorOptions>(options =>
{
  options.InvalidModelStateResponseFactory = (context) =>
  {
   
  };
});`

Perhaps there is an issue with my configuration?

**Comment by dj-nitehawk** [comment]
`DataAnnotations` is an undocumented feature and it requires a `Validator` class for the endpoint to work. however, the validator can be empty (without any rules in it) like below:
```cs
app.UseFastEndpoints(o => o.Validation.EnableDataAnnotationsSupport = true)

public class TestRequest
{
    [Length(3, 5)]
    public string Name { get; set; }
}

public class TestRequestValidator : Validator<TestRequest>; //can be an empty validator without any rules. but is required.

public class Test : Endpoint<TestRequest>
{
    public override void Configure()
    {
        Get("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(TestRequest req, CancellationToken ct)
    {
        await SendOkAsync(req, ct);
    }
}
```

**Comment by buyuanne** [comment]
Okay, Thank you very much. FastEndpoints is great and I have received a lot of help  🍻

**Comment by kcvarun12** [comment]
I have added an empty validator and I have set this as true.
 `app.UseFastEndpoints(o => o.Validation.EnableDataAnnotationsSupport = true)`
 Still the child level validations are not working properly.
 Can you please suggest any workarounds or solutions for this issue?

**Comment by dj-nitehawk** [comment]
@kcvarun12 
data annotations can't do nested/child validators.
use fluentvalidation only for this purpose.
use the `SetValidator()` method as explained in the [fv docs](https://docs.fluentvalidation.net/en/latest/start.html#complex-properties).
