### ISSUE TITLE
AddJWTBearerAuth with Keycloak issue

### ISSUE THREAD

**Issue by fcantenot** [FastEndpoints/FastEndpoints#592]
Hi,

I tried to use FastEnpoints with Keycloak.
I added on my program.cs file following code

```
builder.Services.AddFastEndpoints()
    .AddAuthorization()
    .AddJWTBearerAuth("UZDmbNxWmV4TlpaCRcju6pMRsyuV3er1", JWTBearer.TokenSigningStyle.Symmetric,
        options =>
        {
            options.Audience = "account";
            options.MetadataAddress = "http://myapp-idp:8080/auth/realms/myapp/.well-know/openid-configuration";
            options.RequireHttpsMetadata = false;
            options.TokenValidationParameters.ValidIssuer = "http://myapp-idp:8080/auth/realms/myapp";
        });
```

When I use an endpoint with AllowAnonymous(), there is no problem.
But when I use an enpoint without AllowAnonymous() I have an error :

> IDX10204: Unable to validate issuer. validationParameters.ValidIssuer is null or whitespace AND validationParameters.ValidIssuers is null or empty.

I took a look inside "AddJWTBearerAuth" and I see the following line : 
`o.TokenValidationParameters.ValidIssuer = null;`

Is it a bug or do I not use correctly the framework please ?

Thanks

**Comment by nefarius** [comment]
What exactly are you trying to achieve here? If you plan to use Keycloak as the IDP for FE, use OpenIdConnect, not this.

**Comment by fcantenot** [comment]
I currently follow the training of Milan Jovanovic on Programatic Clean Architecure. I prefer FastEndpoint to MinimalApi or controllers. I tried to use Keycloak with FastEndpoint to authenticate user with a token and after to add roles management and so on.

**Comment by fcantenot** [comment]
Thanks for your answer.

yes it is taught in the course, but I can't make it work with FE. Maybe I made a mistake somewhere. The error in the log when I call my endpoint is 

> DX10204: Unable to validate issuer. validationParameters.ValidIssuer is null or whitespace AND validationParameters.ValidIssuers is null or empty

That's why I asked the question. 

I already read your example (I search by myself before ask a question), that's why I tried to use the code in Program.cs like above.

I can try to provide a minimal project with a minimal api. Not easy because the course covers many concepts.

**Comment by dj-nitehawk** [comment]
yeah most likely caused by a misconfiguration of the `Authentication` middleware.
btw, `AddJWTBearerAuth()` method is not meant to be used when using an external IDP.
it's only meant to be used for plain JWT bearer auth where you're the one who's issuing the jwt tokens.

---

@nefarius do you by any chance have any projects on github where you're using an IDP?
we're currently missing a sample of how to configure FE for OAuth2 together with swagger/ui.

**Comment by nefarius** [comment]
> @nefarius do you by any chance have any projects on github where you're using an IDP?
> we're currently missing a sample of how to configure FE for OAuth2 together with swagger/ui.

I have a closed source customer project where I could extract the relevant configuration and port it into its own little demo app, until then here's the meat of the logic:

### `Program.cs`

```cs
/*
 * Store session info in cookie and authenticate against Keycloak (OpenID)
 */
services.AddAuthentication(options =>
    {
        options.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
        options.DefaultChallengeScheme = OpenIdConnectDefaults.AuthenticationScheme;
    })
    .AddCookie( /* TODO: configure expiry time? */)
    .AddOpenIdConnect(o =>
        {
            KeycloakSettings keycloak = keycloakSection.Get<KeycloakSettings>();

            o.RequireHttpsMetadata = keycloak.RequireHttpsMetadata;
            o.ClientId = keycloak.ClientId;
            o.Authority = keycloak.Authority;
            o.AuthenticationMethod = OpenIdConnectRedirectBehavior.RedirectGet;
            o.ResponseType = OpenIdConnectResponseType.Code;
            o.ResponseMode = OpenIdConnectResponseMode.Query;
            o.GetClaimsFromUserInfoEndpoint = true;
            o.CorrelationCookie = new CookieBuilder();
            o.ProtocolValidator = new OpenIdConnectProtocolValidator { RequireState = false, RequireNonce = false };
            o.GetClaimsFromUserInfoEndpoint = true;

            // replace internal redirect URL with public one
            o.Events.OnRedirectToIdentityProvider = async n =>
            {
                n.ProtocolMessage.RedirectUri = keycloak.RedirectUri;
                await Task.FromResult(0);
            };

            // request scope including groups
            o.Scope.Add("microprofile-jwt");

            // convert Keycloak roles into ASP.NET roles
            o.Events.OnTokenValidated += context =>
            {
                ClaimsPrincipal principal = context.Principal;

                if (principal is null)
                {
                    Log.Logger.Warning("Principal was null");
                    return Task.CompletedTask;
                }

                ClaimsIdentity roles = new();

                foreach (Claim claim in principal.Claims.Where(c => Equals(c.Type, "groups")))
                {
                    Log.Logger.Information("Mapping role/group {Role}", claim.Value);
                    roles.AddClaim(new Claim(ClaimTypes.Role, claim.Value));
                }

                context.Principal!.AddIdentity(roles);

                return Task.CompletedTask;
            };
        }
    );

services.AddAuthorization(options =>
{
    //
    // Force authentication all the time
    // 
    options.FallbackPolicy = new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build();
});
```

### `appsettings.json`

```json
{
  // Identity Provider Settings
  "Keycloak": {
    // client ID configured in Keycloak
    "ClientId": "client-app",
    // this is fine because container to container communication is unencrypted
    "RequireHttpsMetadata": false,
    // internal URL to Keycloak container
    "Authority": "http://keycloak:8080/realms/DEMOREALM",
    // public URL of the protected site
    "RedirectUri": "https://example.com/signin-oidc",
    // logout endpoint
    "LogoutUri": "https://example.com/realms/DEMOREALM/protocol/openid-connect/logout"
  }
}
```

This will allow you also to have Keycloak roles available as groups to use via built-in ASP.NET authorization mechanisms.

**Comment by dj-nitehawk** [comment]
@nefarius thanks mate!
that should come in handy for someone wanting to configure oidc.
