### ISSUE TITLE
Q: How to handle Auth Roles & Permissions from database?

### ISSUE THREAD

**Issue by binair-io** [FastEndpoints/FastEndpoints#594]
When using Permissions in an endpoint configuration, how can one resolve the authorization when the Roles and Permissions are linked in database? 

The user token contains the Role and linked Permissions need to be fetched from database. I have tried using [HeimGuard](https://github.com/pdevito3/HeimGuard?tab=readme-ov-file), but it doesn't load up the data. Probably since FastEndpoints uses its own principle for endpoint authorization? 

How would you recommend I implement this? Using a pre-processor, or is there another way to fetch the data and set in user Claims, or even another approach?

**Allow.cs**
<pre>
public static partial class Allow
{
    public const string Team_Read = "Team_Read";
}
</pre>

**Endpoint Config:**
<pre>public class ListTeamsEndpoint : ApiEndpoint<ListTeams.Query, ListTeams.Response>
{
    public override void Configure()
    {
        Get("teams");
        AuthSchemes(JwtBearerDefaults.AuthenticationScheme);
        Permissions(Allow.Team_Read);
    }

    public override async Task HandleAsync(ListTeams.Query query, CancellationToken ct) => await SendAsync(query, ct);
}</pre>

**User Claims**
<pre>
privileges: u =>
{
    u.Claims.Add(new("Id", userAuthResponse.Payload.Id.ToString()));
    u.Roles.AddRange(new string[]{"admin", "user"}); // <<-- Simplified, actually comes from database query
});
</pre>

**Simplified database schema**
<pre>
| UserId | RoleName | PermissionKey |
|--------|----------|---------------|
| guid   | admin    | Team_Read     |
</pre>

**Comment by dj-nitehawk** [comment]
any dynamic (per request) claim loading can be facilitated by an [IClaimTransformation](https://gist.github.com/dj-nitehawk/220363f14e649a2cb850d61f9bd793b5). this is standard asp.net pipeline stuff and not specific to FE.

FE authorization enforcement works off of the current user principals claims.
so when the actual claims are not embedded in the jwt token itself, you can use an `IClaimTransformation` to hydrate the user principal's claims however you wish.

let me know if you have further questions.

**Comment by binair-io** [comment]
Managed to implement it with your example. Works like a charm. Thank you so much for your support! You're a beast for answering these tickets so fast.
