### ISSUE TITLE
JWT token

### ISSUE THREAD

**Issue by GChannon** [FastEndpoints/FastEndpoints#596]
Hi,

How do I get access to the JWT token payload within in an endpoint?

Thanks

**Comment by dj-nitehawk** [comment]
endpoints have a `User` property which is the `ClaimsPricipal` with all the claims already loaded. 
however if you wish to decode the token yourself, you can do that too like so:
```cs
var authHeader = HttpContext.Request.Headers.Authorization.ToString();
var parts = authHeader.Split(' ');
var accessToken = parts[1];
var handler = new JwtSecurityTokenHandler();
var token = handler.ReadJwtToken(accessToken);
var payload = token.Payload;
```

**Comment by GChannon** [comment]
Thanks.

Are you aware of any logging middleware that will allow us to monitor the number of requests for each user where we can identify a user by claim?

For example, Auth0 has a claim user_id which is an identifier for a user and wants to log how many requests from the user.

**Comment by dj-nitehawk** [comment]
sorry can't remember anything like that off the top of my head.

**Comment by nefarius** [comment]
Write one yourself, that's like what, 5 lines of code? 😜
