### ISSUE TITLE
Swagger and Route Parameters

### ISSUE THREAD

**Issue by iamtheprotocol** [FastEndpoints/FastEndpoints#598]
Greetings,

Consider the following endpoint:

``` cs
public class Request
{
    public int id { get; set; }
}
public class Response
{
    public string message { get; set; }
}

public class TestEndpoint : Endpoint<Request,Response>
{
    public override void Configure()
    {
        Get("/test/{id}"); 
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request req, CancellationToken ct)
    {
        await SendAsync(new()
        {
            message = $"Id is {req.id}"
        });
    }
}
```
My swagger endpoint looks like this 

![image](https://github.com/FastEndpoints/FastEndpoints/assets/33227160/7a82ac16-1cb4-4be6-9a2d-c8de4ff787a9)

Instead of /test/{id} , and its also saying that the request body is required. 

This is the program.cs 
``` cs
global using FastEndpoints;

using NSwag;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddFastEndpoints();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddOpenApiDocument(settings =>
{
    settings.DocumentName = "v1";
    settings.Title = "My API";
    settings.Version = "v1.0";

});

builder.Services.AddAuthorization();

var app = builder.Build();
app.UseAuthorization();
app.UseFastEndpoints();

app.UseOpenApi();
app.UseSwaggerUi(settings => 
{
    settings.DocumentTitle = "Test";
});

app.Run();
```
What am I doing wrong?

**Comment by dj-nitehawk** [comment]
where in the world did you get that swagger configuration from? 😜
[this is how](https://fast-endpoints.com/docs/swagger-support#enable-swagger) it's done with FE.

**Comment by dj-nitehawk** [comment]
this is what it looks like if you do the config right...
pls use the documentation ;-)

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/e8e5fccc-6c32-4638-939f-31d7b6b63c64)

**Comment by iamtheprotocol** [comment]
Hey thanks for your quick response. I will pay closer attention to the documentation next time  XD
