### ISSUE TITLE
JWT Scopes

### ISSUE THREAD

**Issue by GChannonLondon** [FastEndpoints/FastEndpoints#603]
Hi,

Why is it that fastendpoints only works with claims and permissions on a token?

It doesn't seem to work with scopes. Any idea how I can it working with scopes?

PermissionsAll(SCOPE_NAME);

**Comment by GChannonLondon** [comment]
Create a policy.

**Comment by dj-nitehawk** [comment]
you can change the claim type by setting this property via startup config: https://github.com/FastEndpoints/FastEndpoints/blob/78ba7dd3685ce904dba0113d6a912eab2f7037b1/Src/Library/Config/SecurityOptions.cs#L23

**Comment by ahmadlashgari** [comment]
can you show how to set this option?

**Comment by dj-nitehawk** [comment]
@ahmadlashgari 
```cs
app.UseFastEndpoints(c => c.Security.PermissionsClaimType = "scopes")
```
