### ISSUE TITLE
Blank response when combining `required` and `[JsonIgnore]`

### ISSUE THREAD

**Issue by MrGrinst** [FastEndpoints/FastEndpoints#604]
When combining `required` and `[JsonIgnore]` in a response class, the serialization silently fails and a blank response is returned (with a 200).

Example:
```
public class Response {
    [JsonIgnore]
    public required int Id { get; set; }

    public int CalculatedId => SomeCalculation(Id);
}
```

Expected: The ignored property should be ignored and other properties serialized.

Actual: Empty response is returned.

**Comment by dj-nitehawk** [comment]
when i try the following code with the latest version of FE, i see the below exception being thrown by STJ:

```cs
public class Response
{
    [JsonIgnore]
    public required int Id { get; set; }

    public int CalculatedId => Id;
}

sealed class MyEndpoint : EndpointWithoutRequest<Response>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        await SendAsync(new() { Id = 123 });
    }
}
```

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/0ba3dff1-1d7b-4cb9-ba6a-4af315ad1802)

so it seems like a restriction in STJ, where you can't put `JsonIgnore` on `required` properties.
getting rid of the `required` keyword fixes the problem.

possibly related [issue](https://github.com/dotnet/runtime/issues/82879).
