### ISSUE TITLE
Remove class constraint from Validator

### ISSUE THREAD

**Issue by Coda17** [FastEndpoints/FastEndpoints#605]
`FastEndpoints.Validator` currently has a constraint requiring the generic parameter is a class. I don't know why this requirement exists, when `FluentValidation.AbstractValidator` does not have this constraint. Removing the constraint allows for structs to be used as requests.

**Comment by dj-nitehawk** [comment]
it's done in `v5.22.0.4-beta`.
we used to have a `class` requirement for all request DTOs. it was eventually removed but looks like we missed the validator class when removing the contraints.
should be all good now.

thanks!
