### ISSUE TITLE
DisposeAsync in TestFixture disposes of HttpClient before running TearDownAsync

### ISSUE THREAD

**Issue by terryjbutler** [FastEndpoints/FastEndpoints#606]
Hi there,

I'd like to say that this is an amazing project and I'm enjoying using it a lot!

I was working with `FastEndpoints.Testing` in order to create some integration tests and wanted to use the `TearDownAsync` function to hit some endpoints to clean up some resources at the end of my tests. I ran into the following error:

```
[Test Class Cleanup Failure (...)]: System.ObjectDisposedException : Cannot access a disposed object.
Object name: 'System.Net.Http.HttpClient'.
```

This is due to the following code in `TestFixture`:

```csharp
public virtual Task DisposeAsync()
{
	Client.Dispose();
	return TearDownAsync();
}
```

An override in my test fixture seems okay for me as a side note:

```csharp
public async override Task DisposeAsync()
{
	await TearDownAsync();
	Client.Dispose();
}
```

I'd be interested to know if others have encountered the issue and how much of a breaking change it would be to alter it as I've done?

**Comment by dj-nitehawk** [comment]
i've changed the order around in `v5.22.0.5-beta`. that should do the trick 😉

https://github.com/FastEndpoints/FastEndpoints/blob/69819e7e91dda1d83d355a13f6c46bd0669eb68b/Src/Testing/TestFixture.cs#L155-L159

**Comment by terryjbutler** [comment]
Amazing, thank you!
