### ISSUE TITLE
Route parameter data type

### ISSUE THREAD

**Issue by AMW93** [FastEndpoints/FastEndpoints#610]
I cannot find a way to make my use case possible but I know this has to exist.

I have an endpoint such as this:

```
internal sealed class GetSomeEndpoint(ISomeService SomeService) : EndpointWithoutRequest<SomeDto>
{
    public override void Configure()
    {
        Get("/{SomeId}");
        Group<SomeEndpointGroup>();
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        var SomeId = Route<Guid>("SomeId");
        await SendAsync(someResultFromARedactedService, cancellation: ct);
    }
}
```

SomeId should be a Guid when using the GenerateClientsAndExitAsync method to generate the client file. Here is what my generate client method call looks like:

```
await app.GenerateClientsAndExitAsync(
    documentName: "..",
    destinationPath: "..",
    csSettings: c =>
    {
        c.ClassName = "..";
        c.DisposeHttpClient = true;
        c.AdditionalNamespaceUsages = AssemblyReferences.SomeNamespaces;
        c.CSharpGeneratorSettings.ClassStyle = CSharpClassStyle.Record;
        c.CSharpGeneratorSettings.JsonLibrary = CSharpJsonLibrary.SystemTextJson;
        c.CSharpGeneratorSettings.GenerateJsonMethods = true;
        c.CSharpGeneratorSettings.GenerateOptionalPropertiesAsNullable = true;
        c.CSharpGeneratorSettings.GenerateNativeRecords = true;
        c.CSharpGeneratorSettings.GenerateNullableReferenceTypes = true;
        c.CSharpGeneratorSettings.Namespace = "..";
        c.CodeGeneratorSettings.SchemaType = NJsonSchema.SchemaType.JsonSchema;
        c.ExposeJsonSerializerSettings = true;
        c.CodeGeneratorSettings.InlineNamedAny = false;
        c.GenerateDtoTypes = false;
    },
tsSettings: null
);
```

The resulting client generates method calls that are for a string? parameter type. What could I be doing wrong? Is there something I'm missing? I found this issue addressing my scenario from a couple of years ago https://github.com/meysamhadeli/FastEndpoints/commit/1c208ded054d3639c2f6e77bcdc51087a2a68caa but it doesn't seem to work that way anymore. Any help is greatly appreciated!

Edit: I noticed my question might be a bit incomplete. I understand why FE generates the route parameter as a string? but how can I force it to generate at a Guid instead?

**Comment by dj-nitehawk** [comment]
the correct client generation depends on the correct generation of the swagger document (swagger.json).
in order to define the correct type for route parameters, you're gonna have to use a request dto like this:
```cs
sealed class RequestDto
{
    public Guid SomeId { get; set; } //swagger will use the correct type now
}

sealed class ResponseDto
{
    public string Id { get; set; }
}

sealed class GetSomeEndpoint : Endpoint<RequestDto, ResponseDto>
{
    public override void Configure()
    {
        Get("something/{SomeId}");
        AllowAnonymous();
    }

    public override async Task HandleAsync(RequestDto r, CancellationToken ct)
    {
        await SendAsync(new() { Id = r.SomeId.ToString() });
    }
}
```
the generated swagger.json will be:
![screen-record-1708061735](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/6651c093-ad3e-4c3d-9a83-74124fa97950)
which defines the correct type, which should lead to the correct client generation.

as a sidenote, i see you're using nswag based client generation. we now have [kiota based client generation](https://fast-endpoints.com/docs/swagger-support#api-client-generation) in case you haven't seen that.
