### ISSUE TITLE
Support for Basic Authentication in Swagger

### ISSUE THREAD

**Issue by edmolko** [FastEndpoints/FastEndpoints#617]
I found this article for allowing Swagger to use BasicAuthentication:  [https://www.thecodebuzz.com/nswag-basic-authentication-openapi-documentation-asp-net-core/](url)

But when I add the **AddOpenApiDocument** extension to Program.cs I got an error from swagger: 

_"The OpenAPI/Swagger document 'v1' registered multiple times: Explicitly set the DocumentName property in AddSwaggerDocument() or AddOpenApiDocument()."_

How can I enable Swagger to use BasicAuthentication along with FastEndpoints?

**Comment by dj-nitehawk** [comment]
[here you go](https://gist.github.com/dj-nitehawk/ef1adfb23f248d936da6fea0ba025f09)
