### ISSUE TITLE
Endpoint role based authorization

### ISSUE THREAD

**Issue by xvsvg** [FastEndpoints/FastEndpoints#619]
Hi there ! I faced an issue, where the properly [configured with attributes](https://fast-endpoints.com/docs/get-started#configuring-with-attributes) endpoint does not seem to have a provided authorize attribute. However, if Im using `Configure()` method in order to reach all the same desired puproses , it works just as [documented](https://fast-endpoints.com/docs/security#endpoint-authorization)

## How to reproduce
.NET 7, FE 5.20.1
```csharp

[AuthorizeFeature(FeatureScopeName, FeatureName)]
internal class ProtectedEndpoint: Endpoint<Request, Response>
{
    private const string FeatureName = "ProtectedEndpointFeatureName";
    private const string FeatureScopeName = ""ProtectedEndpointsScope"";

    public override void Configure()
    {
        Patch("api/secret");
    }

    public override async Task HandleAsync(Request, CancellationToken ct)
    {
        await SendOkAsync(new Response("Secret reached"));
    }
}

public sealed class AuthorizeFeatureAttribute : AuthorizeAttribute
{
    public const string Prefix = "Feature_";

    public AuthorizeFeatureAttribute(string scope, string feature)
        : base($"{Prefix}{scope}:{feature}")
    {
        Scope = scope;
        Feature = feature;
    }

    public string Scope { get; }

    public string Feature { get; }
}


```
Going through the request pipeline I hit `Invoke()` method on default `AuthorizationMiddleware`, that will make an attempt to create policies 'on the flight', authorize attribute has no data though, that leads the case to be using something like `AllowAllPolicy`
![image](https://github.com/FastEndpoints/FastEndpoints/assets/89912995/b16db47b-a3b4-43b5-9521-39f24dad287e)

However, if get back inside my endpoint and configure it in the same fashion like so:
```csharp
internal class ProtectedEndpoint: Endpoint<Request, Response>
{
    private const string FeatureName = "ProtectedEndpointFeatureName";
    private const string FeatureScopeName = ""ProtectedEndpointsScope"";

    public override void Configure()
    {
        Patch("api/secret");
        Policies($"{AuthorizeFeatureAttribute.Prefix}{FeatureScopeName}:{FeatureName}");
    }

    public override async Task HandleAsync(Request, CancellationToken ct)
    {
        await SendOkAsync(new Response("Secret reached"));
    }
}
```
## Question

Im wondering, if such cases are not being properly documented or I just came across minor misconception.
Feel free to ask me for additional information.

**Comment by dj-nitehawk** [comment]
attribute forwarding was introduced in v5.21
https://github.com/FastEndpoints/FastEndpoints/releases/tag/v5.21

can you try with 5.21 and see if it work?

if not, I'll look in to this first thing tomorrow morning.

**Comment by xvsvg** [comment]
hm, looks like it's not, `AuthorizeAttribute` still has null values.
would be great, if you take a look

**Comment by dj-nitehawk** [comment]
initially i missed that you're using both attributes + Configure() to setup the endpoint.
which is not supported. even for attribute forwarding. it's an either/or deal. we don't want people to mix the two strategies because it adds congnitive load to a person reading the code.
documentation will be updated to clarify this.

if you do the following it works:
```cs
[HttpPatch("api/patch")]
[AuthorizeFeature(FeatureScopeName, FeatureName)]
class ProtectedEndpoint : EndpointWithoutRequest
{
    ...
}
```
