### ISSUE TITLE
[Question] Example Request in Swagger affected by implementing Validator<T>

### ISSUE THREAD

**Issue by zagoskin** [FastEndpoints/FastEndpoints#621]
I've noticed that as soon as I implement a `Validator<TRequest>` for one of my requests, the example value generated in the swagger documentation is affected by whatever validation I did. 
 
My question is, is there any quick away to turn off this behaviour? I know I can provide custom example values using the `Summary()` method and setting the `s.ExampleRequest<TRequest>` property to create an example. But I feel I would just prefer to do this whenever we believe a custom example is actually required.

**Comment by dj-nitehawk** [comment]
do you mean if you do this:
```cs
RuleFor(r => r.Id).GreaterThan(10);
```
this gets generated:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/f7df2c49-2553-4187-94eb-7d5c4f63419b)

so you want the validation rule to not change the default `0` in the example?

**Comment by zagoskin** [comment]
> so you want the validation rule to not change the default `0` in the example?

Exactly! But, like a way to globally configure that behaviour instead of having to provide a specific example for each request. In my case, I'm using the
```cs
RuleFor(r => r.Email).EmailAdress()
```
Which generates a totally unreadable string in the swagger. For this specific case, I'm willing to generate a proper custom example but then started to wonder about how future validations would affect the generated swagger, because I'm not always manually checking how each request is being shown in the example.

**Comment by dj-nitehawk** [comment]
the weird email string issue has been fixed in the latest beta. final relase will be first week of march.

**Comment by dj-nitehawk** [comment]
soo... this looks like a swagger ui thing. FE is not generating an example based on the rules.
FE is generating the correct swagger spec like this:
```json
            "MyRequest": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "id": {
                        "type": "integer",
                        "format": "int32",
                        "minimum": 10,
                        "exclusiveMinimum": true
                    }
                }
            }
```
it's swagger ui that's making the request example based on the spec.
so if you need a config option for that, you'll have to ask the swagger ui people.

**Comment by zagoskin** [comment]
> it's swagger ui that's making the request example based on the spec. so if you need a config option for that, you'll have to ask the swagger ui people.

Thanks for the reply! Will go bother them with the same question then.
