### ISSUE TITLE
Using Auth0 account

### ISSUE THREAD

**Issue by GChannon** [FastEndpoints/FastEndpoints#626]
Hi,

I have changed Fast Endpoints to the use scope section of a JWT token, but it doesn't work when the scope contains more than one scope.

app.UseFastEndpoints(c => c.Security.PermissionsClaimType = "scopes")

Scope: “scope1 scope2 scope3”

Is it possible for fastendpoints to work with 2+ scopes without me writing a custom policy?

**Comment by dj-nitehawk** [comment]
you can add a claim transformation to the pipeline which will split the scopes by space and add them as separate permission claims to the user principal. that should get the job done. 

here's and example transformer: https://gist.github.com/dj-nitehawk/220363f14e649a2cb850d61f9bd793b5

if that doesnt work, can you provide a sample jwt token and I'll look further into it.
