### ISSUE TITLE
Unable to disable problem details standard (rfc7807)

### ISSUE THREAD

**Issue by MattPress** [FastEndpoints/FastEndpoints#627]
Issue: I am unable to set content media type for non-success responses to `application/json`

Since updating to 5.23.0 I've noticed that i am unable to disable non-success responses from having the content media type of `application/problem+json`. In our platform we have not adopted problem details and have an internal central error model. This is never exposed to the client so there is currently no need to adopt the problem details standard. I took a look through the Fast Endpoints code base and it looks like `application/problem+json` is hard coded and cannot be disabled. Is this the case? If so, are there any plans for this to be made customizable so that it can be disabled?

**Comment by dj-nitehawk** [comment]
how were you disabling it in previous versions?

try the following:
```cs
app.UseFastEndpoints(
       c =>
       {
           c.Serializer.ResponseSerializer =
               (rsp, dto, cType, jCtx, ct) =>
               {
                   if (rsp.StatusCode == 400)
                       cType = "application/json"; //override the content-type

                   return dto is null
                              ? Task.CompletedTask
                              : rsp.WriteAsJsonAsync(
                                  value: dto,
                                  type: dto.GetType(),
                                  options: jCtx?.Options ?? c.Serializer.Options,
                                  contentType: cType,
                                  cancellationToken: ct);
               };

           c.Endpoints.Configurator =
               ep =>
               {
                   ep.Description(b => b.Produces<ErrorResponse>(400, "application/json"));
               };
       })
```

will add a config option in the next version.
