### ISSUE TITLE
Extend documentation about Query-Attributes

### ISSUE THREAD

**Issue by delasource** [FastEndpoints/FastEndpoints#628]
in https://fast-endpoints.com/docs/model-binding#from-query-parameters you say that annotating queries is not necessary.
however i had build a POST request today, that has a query param as well as a body. Swagger was not listing the query param until i annotated it in the DTO with `[QueryParam]`. Without it, it does not show on swagger

My Request DTO:

```
public class IncomingShopSaleRequest
{
    // This
    [QueryParam]
    public string Shop { get; set; } = "";

    [FromBody]
    public List<Order> Orders { get; set; } = new();

    [FromHeader("X-WC-Webhook-Signature")]
    public string XWcWebhookSignature { get; set; } = "";
}
```

My recommendation: add "[QueryParam]" to the documentation, because i spent 2 hours looking for that attribute ☠️

**Comment by dj-nitehawk** [comment]
it is documented on the swagger page here: https://fast-endpoints.com/docs/swagger-support#adding-query-params-to-swagger
