### ISSUE TITLE
JWT Token generation - still get 401's

### ISSUE THREAD

**Issue by nhwilly** [FastEndpoints/FastEndpoints#629]
First of all, fabulous package.  Just found it thanks to @ardalis and I'm moving my project to it.  

This post will hopefully be helpful.  I have a workaround in place and there is no urgency to this issue.

---
I am having some problems with security.  The tokens are generated just fine and the claims are there, but when I use the bearer token to access an endpoint, it always comes back with a 401.

Using www.jwt.io I also noticed that it would not verify the signature unless I specified the HS256 algorithm specifically during token creation.

I am pulling the signing key from the same spot in the config for both aspects, I've stripped the code down until there's almost nothing going on.

What's interesting is the sample code from Steve's Modular Monolith course is identical to mine and works in his project that I downloaded to my machine.

When I copy the code to my project it fails.

For the life of me I can't find the problem.  It has been all day, so I had to move on.  I am successfully issuing tokens and protecting endpoints with the standard asp.net core shown below.

I only leave this here in case someone else has the same problem and you need more information on it.  Feel free to reach out if I can help.

```csharp
builder.Services.AddAuthentication(options =>
{
  options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
  options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
  options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(o =>
{
  o.TokenValidationParameters = new TokenValidationParameters
  {
    ValidIssuer = authOptions.Issuer,
    ValidAudience = authOptions.Audience,
    IssuerSigningKey = new SymmetricSecurityKey
      (Encoding.UTF8.GetBytes(authOptions.JwtSecret)),
    ValidateIssuer = true,
    ValidateAudience = true,
    ValidateLifetime = true,
    ValidateIssuerSigningKey = true
  };
});
builder.Services
  .AddAuthorization()
  .AddFastEndpoints()
  .SwaggerDocument();
```
And for token generation:
```csharp
  private static string BuildJwtToken(AuthOptions options, IEnumerable<Claim> claims)
  {
    var key = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(options.JwtSecret));
    var creds = new SigningCredentials(key, SecurityAlgorithms.HmacSha256);
    var issuer = options.Issuer;
    var audience = options.Audience;
    var jwtValidity = DateTime.Now.AddMinutes(Convert.ToDouble(options.AccessTokenExpiresMinutes));
    var token = new JwtSecurityToken(issuer, audience, expires: jwtValidity, claims: claims, signingCredentials: creds);
    return new JwtSecurityTokenHandler().WriteToken(token);
  }
```

I am using an `AuthOptions` class like this:
```csharp
public class AuthOptions()
{
  [Required]
  public required string JwtSecret { get; init; }
  public required double AccessTokenExpiresMinutes { get; init; } = 60;
  public required double RefreshTokenLifetimeDays { get; init; } = 365;
  public required double RefreshTokenExpiresHours { get; init; } = 24;
  public required string Issuer { get; init; } = "https://www.coolstuff.io";  
  public required string Audience { get; init; } = "https://www.coolstuff.io";
}
```

**Comment by dj-nitehawk** [comment]
thanks for the info. as well as the monthly sponsorship. greatly appreciated 🙏

FE provides "easier on the eye" abstractions for both setting up the middleware and creating jwt auth.

```cs
bld.Services.AddAuthenticationJwtBearer(
       s =>
       {
           s.SigningKey = "signing key";
           s.SigningStyle = TokenSigningStyle.Symmetric; //not necessary as it's the default value
       },
       b =>
       {
           b.TokenValidationParameters.ValidIssuer = "issuer";
           b.TokenValidationParameters.ValidAudience = "audience";
       })
```
```cs
var token = JwtBearer.CreateToken(
    o =>
    {
        o.SigningKey = "signing key";
        o.SigningStyle = TokenSigningStyle.Symmetric;            //not necessary as it's the default value
        o.SymmetricKeyAlgorithm = SecurityAlgorithms.HmacSha256; //not necessary as it's the default value
        o.Issuer = "issue";
        o.Audience = "audience";
        o.ExpireAt = DateTime.UtcNow.AddDays(1);
        o.User.Claims.Add(("Claim Type", "Claim Value"));
        o.User.Permissions.Add("Perm1", "Perm2", "Perm3");
        o.User.Roles.Add("Role1", "Role2");
    });
```

and it sets up the right [default values](https://github.com/FastEndpoints/FastEndpoints/blob/10afd354beb48edbb01014bd1616015c8da286b0/Src/Security/AuthExtensions.cs#L62-L81) which you can override if needed.

**Comment by dj-nitehawk** [comment]
if you still have issues after trying the FE provided methods above, pls attach a small repro project and i'll look in to it.
