### ISSUE TITLE
Error 500 with formdata binding

### ISSUE THREAD

**Issue by delasource** [FastEndpoints/FastEndpoints#631]
I have configured my app to allow to re-read the body stream with

```
app.Use((c, next) =>
{
    c.Request.EnableBuffering();
    return next();
});

```

and i have an endpoint, that allows `application/json` and `application/x-www-form-urlencoded` requests (having both at the same endpoint is weird/bad i know). i.e.

```
Description(b => b
                         .Accepts<MyRequest>(isOptional: true,
                             "application/json",
                             "application/x-www-form-urlencoded")
                         .Produces<EmptyResponse>());
```

The application throws a 500 error and Exception `Cannot access a disposed object.` when it tries to bind the x-www-form-urlencoded payload. Json Payload works. Without "EnableBuffering" both work as expected.

I don't even want to serialize anything, as i am using an IPlainTextRequest

**Comment by KateyBee** [comment]
I have added support for this scenario in `v5.23.0.3-beta`.
The following now works:
```cs
app.UseAuthentication()
   .Use(
       (c, next) =>
       {
           c.Request.EnableBuffering();

           return next();
       })
```
```cs
sealed class MyEndpoint : Endpoint<MyRequest>
{
    public override void Configure()
    {
        Post("test");
        Description(
        Description(
            b => b.Accepts<MyRequest>(
                true,
                "application/json",
                "application/x-www-form-urlencoded"));
        AllowAnonymous();
    }

    public override async Task HandleAsync(MyRequest r, CancellationToken c)
    {
        await SendAsync(
            new
            {
                content = r.Content,
                formField = r.FormField
            });
    }
}
```
![screen-record-1709640845](https://github.com/FastEndpoints/FastEndpoints/assets/134909513/c4c86f9f-df60-4965-959c-a7ff9367e744)
![screen-record-1709640864](https://github.com/FastEndpoints/FastEndpoints/assets/134909513/ed0199b3-df2a-4f37-bf74-29e89c4a9f78)
