### ISSUE TITLE
[Bug] Route Parameter with v5.19+, newtonsoft camelcasing and cleardefaults breaks model binding

### ISSUE THREAD

**Issue by EelcoLos** [FastEndpoints/FastEndpoints#633]
### Current Behavior
When I'm trying to update from v5.18 to anything higher, NSwag will be updated to v14. 
On this upgrade, the camelcasing strategy has moved to a different implementation.

When I have an endpoint with a description `clearDefaults` and a different casing on my Route (ie: `/api/users/{Id}`), the request **will** be translated, **but the route will not**.
```cs
public override void Configure()
{
	Verbs("GET");
	Routes("/api/users/{Id}");
	Description(x => { x.WithName("getUser"); }, clearDefaults: true); // <-------- clearDefaults here breaks the newtonsoft CamelCaseNamingStrategy
}
```

### Expected Behavior

When having routing that clears the default with camelcase naming strategy, both the route and request need to be named on the correct strategy.
If not, derived projects (ie: nswag conversion), will bind this incorrectly too.

### GitHub Repo

the repo in v5.18: https://github.com/EelcoLos/FastEndpoints.CamelCase
the repo in v5.23: https://github.com/EelcoLos/FastEndpoints.CamelCase/tree/v5.23

On the repo, I made a `specification.json`, which is the output of the swagger document: https://github.com/EelcoLos/FastEndpoints.CamelCase/blob/v5.23/specification.json

### Steps to Reproduce

1. Have a FastEndpoint with a route not bound to the strategy (see example above)
1. add the `Description` with `clearDefaults: true`
1. look at the swagger.json

The incorrect route version path will show.

### Additional Information

Probably, this can be remedied for now with removing the `clearDefaults`, if that is possible in your situation

**Comment by dj-nitehawk** [comment]
there's a setting you can turn off to get back the old behavior:
```cs
builder.Services.SwaggerDocument(
   p =>
   {
       p.UsePropertyNamingPolicy = false;
   });
```
which will prevent the naming policy from being applied to the route param and keep it exactly as you've defined it in the route pattern. this setting should help you not have to update the route patterns you've already written in your endpoint classes.

going forward (in projects), the advise would be to turn the setting on and write the route patterns in the endpoints that actually do match up with the actual naming policy/casing you've configured at startup.

the deeper issue here is that when you just `clearDefaults` and not define the correct request dto type, the swagger operation processor is unable to determine the dto properties correctly, which results in this behavior.

if you simply define the accepts metadata like so, there is no problem:
```cs
Description(
    x =>
    {
        x.Accepts<GetUserRequest>(); //doing this allows swagger processor to infer props correctly
    },
    clearDefaults: true);
```

**Comment by dj-nitehawk** [comment]
btw, this is just a swagger ui related issue, because swagger ui will issue the request to a wrong url such as `http://localhost:5165/api/users/{Id}` which contains the route placeholder. swagger ui is case sensitive and it will only replace route segments if the casing is exactly the same.

**Comment by EelcoLos** [comment]
but the specification of swagger is also changed, as I showed on the specification

Btw, I also had this exact problem, using your second suggestion:
```cs
			x.Accepts<PutAccessIdentityEndpointRequestBody>(MediaTypeNames.Application.Json);
```
this also made the same issue happen

**Comment by EelcoLos** [comment]
I tried it on the repo with `clearDefaults`. Than this works yes, checking if `.Accepts` _without_ `clearDefaults` works too

**Comment by dj-nitehawk** [comment]
try this stripped down, fixed project.

[fe-camelcase.zip](https://github.com/FastEndpoints/FastEndpoints/files/14541056/fe-camelcase.zip)

**Comment by EelcoLos** [comment]
cheers, I see the boundaries now... removing the `clearDefaults` for my works repo did most of the work. Then, when using `Accepts<T>`, actually **using** the `clearDefaults` solves the camelcasing too

**Comment by EelcoLos** [comment]
My opinion is that in general, using `clearDefaults` shouldn't be needed at all. Using summaries will get you there most of the way.

**Comment by EelcoLos** [comment]
> going forward (in projects), the advise would be to turn the setting on and write the route patterns in the endpoints that actually do match up with the actual naming policy/casing you've configured at startup.

On that note: it _is_ kind of strange yes. Though the policy at work seems that `dotnet` environment properties are all capitalized at start, and front-end should be camelcase... so sadly, not my call :'(
