### ISSUE TITLE
ProblemDetails is not extensible

### ISSUE THREAD

**Issue by CSharpBender** [FastEndpoints/FastEndpoints#637]
Is there a reason for making the class ProblemDetails sealed and not defining a setter for the Title property?
I need to return ProblemDetails for any unsuccessful HTTP status code.
My issue is that I cannot change the Title for each type of error and I have to define my own class from scratch.

**Comment by dj-nitehawk** [comment]
[title can be set](https://fast-endpoints.com/docs/configuration-settings#rfc7807-compatible-problem-details) but it's a global setting and cannot be set per instance/response. because there's currently no way to specify per response titles with any of the error response sending methods provided out of the box.

the class itself is sealed because you're not supposed to instantiate it yourself. and it has internal implementation details we'd like to change in the future without breaking consumer code.

if you need to do per instance titles, you can achieve it like so:

```cs
app.UseFastEndpoints(
       c =>
       {
           c.Errors.ProducesMetadataType = typeof(ValidationProblemDetails);
           c.Errors.ResponseBuilder =
               (failures, ctx, statusCode) =>
               {
                   return new ValidationProblemDetails(
                       failures.GroupBy(f => f.PropertyName)
                               .ToDictionary(
                                   keySelector: e => e.Key,
                                   elementSelector: e => e.Select(m => m.ErrorMessage).ToArray()))
                   {
                       Type = "https://tools.ietf.org/html/rfc7231#section-6.5.1",
                       Title = ctx.Items["_ERR_TITLE_"]?.ToString() ?? "One or more validation errors occurred.",
                       Status = statusCode,
                       Instance = ctx.Request.Path,
                       Extensions = { { "traceId", ctx.TraceIdentifier } }
                   };
               };
       })
```

```cs
static class SendMethodExtensions
{
    internal static Task SendProblemDetails(this IEndpoint ep, string title, List<ValidationFailure> failures)
    {
        ep.HttpContext.Items["_ERR_TITLE_"] = title;

        return ep.HttpContext.Response.SendErrorsAsync(failures);
    }
}
```

```cs
sealed class MyEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("errors");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        AddError("blah blah");
        await this.SendProblemDetails("my error title", ValidationFailures);
    }
}
```

**Comment by CSharpBender** [comment]
I've seen the ValidationProblemDetails example but I wanted a ProblemDetails which contains traceId and error code.
Very ugly solution: copy-pasted your class, used reflection to read the `internal ` static config for name conversion, added a setter to the Title property, and updated the ResponseBuilder to set the title based on the HTTP status code.
What I wanted: create a ProblemDetails and set the Title based on statusCode.

**Comment by KateyBee** [comment]
Starting with `v5.23.0.7-beta` you can specify a "Title Transformer" function like this:
```cs
ProblemDetails.TitleTransformer =
    p =>
    {
        return p.Status switch
        {
            400 => "Validation Error",
            404 => "Not Found",
            _ => "One or more errors occurred!"
        };
    };
```
Example usage:
```cs
sealed class Endpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        switch (r.Id)
        {
            case 400:
                ThrowError("blah blah", 400);

                break;
            case 404:
                ThrowError("resource not found", 404);

                break;
        }
        await SendOkAsync();
    }
}
```

**Comment by CSharpBender** [comment]
Wow, already implemented? 
I have only one small issue regarding the generated schema example.
I'm using `ProducesProblemFE<ProblemDetails>(StatusCodes.Status404NotFound, "application/json+problem")` which generates an example with status 400.
![image_2024_03_14T10_17_49_795Z](https://github.com/FastEndpoints/FastEndpoints/assets/42767528/7d5b274e-b9eb-4dc7-a2fd-d13eb02d6e06)
What should I do to have 404 and (maybe) change the title in the example?

**Comment by KateyBee** [comment]
You can [set the swagger response example](https://fast-endpoints.com/docs/swagger-support#swagger-documentation) like so:
```cs
public override void Configure()
{
    Get("test");
    Description(x => x.ProducesProblemFE<ProblemDetails>(404));
    Summary(
        s => s.ResponseExamples[404] = new ProblemDetails
        {
            Status = 404,
            Instance = "string",
            TraceId = "string",
            Detail = "string",
            Errors =
            [
                new()
                {
                    Name = "string",
                    Code = "string",
                    Reason = "string",
                    Severity = "string"
                }
            ]
        });
}
```
It will automatically set the correct title according to your "Title Transformer".
The above generated this:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/134909513/ff972b25-5b02-428c-935e-13f1a901cf5e)

**Comment by KateyBee** [comment]
If you find yourself repeating the same example instances, just pre-populate and store them in a static constants class, to keep things dry.
