### ISSUE TITLE
Can`t register CommandHandlerRegistry without endpoints

### ISSUE THREAD

**Issue by d4rkm0nkey** [FastEndpoints/FastEndpoints#640]
I have a project where I would like to use the CommandHandlers, EventHandlers and JobQueues, but where I don't have any FastEndpoints. If I register the CommandHandlerRegistry with `services.AddFastEndpoints()`, I get the exception, that no endpoint is found. Unfortunately I cant register the CommandHandlerRegistry myself, because the class is internal.

**Comment by dj-nitehawk** [comment]
yeah those features were designed to be bonus features of FE and is currently deeply integrated to FE's configuration code. so you can't use them independently without bringing in FE.

what you can do however is simply add a dummy endpoint to your project such as this:
```cs
[HttpGet("/")]
sealed class DummyEndpoint : EndpointWithoutRequest
{
    public override Task HandleAsync(CancellationToken ct)
        => throw new NotImplementedException();
}
```

**Comment by dj-nitehawk** [comment]
alternatively look in to libraries such as masstransit, wolverine, hangfire, etc.

**Comment by d4rkm0nkey** [comment]
Thank you. I like how simple this implementation is in comparison to Wolverine, that's why I hoped it would be supported.

**Comment by dj-nitehawk** [comment]
yes that api surface simplicity is what makes it difficult to pull these features out into its own independent library.
