### ISSUE TITLE
sealed EmptyResult

### ISSUE THREAD

**Issue by mxmissile** [FastEndpoints/FastEndpoints#641]
Enhancement Request, can you please un-seal `EmptyResult`, I want to be able to use marker classes:

`public class HelloRequest : EmptyRequest{}`

```
public class HelloEndpoint : Endpoint<HelloRequest, HelloResponse>
{
...

    public override async Task HandleAsync(HelloRequest req, CancellationToken ct)
     {
          await PublishAsync(req);
     
          await SendAsync(new HelloResponse { Result = "hello"}, 200, ct);
     }
}
```

Even better, allow us to use records: 

`public record HelloRequest;`

**Comment by KateyBee** [comment]
`EmptyRequest` is a struct and structs cannot be inherited in c#.
Won't be changing it to a class/record as we've benchmarked struct vs. class and struct had better performance.
You can however turn off the warning/exception that is thrown if your request DTO has no properties, starting `v5.23.0.9-beta` like so:
```cs
app.UseFastEndpoints(c => c.Endpoints.AllowEmptyRequestDtos = true)
```
You can then use an empty record:
```cs
sealed record HelloRequest;

sealed class MyEndpoint : Endpoint<HelloRequest>
{
    public override void Configure()
    {
        Post("test");
        Description(x => x.ClearDefaultAccepts()); //this will be needed for POST requests
        AllowAnonymous();
    }
}
```
