### ISSUE TITLE
Integrating Hashids with FastEndpoints + Swagger

### ISSUE THREAD

**Issue by emanuelvarga** [FastEndpoints/FastEndpoints#642]
I've been trying to find a clean way to integrate Hashids generation with FastEndpoints for a cleaner solution.

I've managed to get around the binding issues by adding `[ModelBinder(typeof(HashidsModelBinder))]` (route) or `[JsonConverter(typeof(HashidsJsonConverter))]` (body) to all the hashed properties with using the following setup

```
app.UseFastEndpoints(c =>
{
    c.Serializer.Options.Converters.Add(new DependencyInjectionJsonConverter(app.Services.GetService<IHttpContextAccessor>(), app.Services.GetService<IServiceProvider>()));
    c.Binding.ValueParserWhen(prop =>
    {
        var att = prop.GetCustomAttributes(typeof(ModelBinderAttribute), true).FirstOrDefault() as ModelBinderAttribute;
        if (att?.BinderType == typeof(HashidsModelBinder))
            return true;

        return false;
    }, (obj, type) =>
    {
        var serviceProvider = app.Services.GetService<IServiceProvider>()!.GetService(typeof(IServiceProvider)) as IServiceProvider;
        var service = serviceProvider!.GetService<IHashids>();
        return new ParseResult(service != null, service?.Decode(obj!.ToString()).FirstOrDefault());
    });
});
```

Not the cleanest, not the worse, at least I can use an attribute to mark the properties that needs a custom converter. 
Any suggestions on how to make this cleaner?

BUT the main issue is with the swagger generation:

```
app.UseSwaggerGen(openApiConfig =>
{
    openApiConfig.PostProcess = (document, request) =>
    {
        foreach (var operation in document.Operations)
        {
            var operationParameters = operation.Operation.Parameters
                .Where(_ => _.Name.EndsWith("Id", StringComparison.InvariantCultureIgnoreCase) && _.ActualSchema.Type == JsonObjectType.Integer);
            foreach (var parameter in operationParameters)
            {
                parameter.ActualSchema.Format = string.Empty;
                parameter.ActualSchema.Type = JsonObjectType.String;
            }
        }

        foreach (var definition in document.Definitions)
        {
            var schema = definition.Value;
            var idProperties = schema.Properties.Values.Where(_ => _.Name.EndsWith("Id", StringComparison.InvariantCultureIgnoreCase) && _.Type == JsonObjectType.Integer);
            foreach (var jsonSchemaProperty in idProperties)
            {
                jsonSchemaProperty.Format = string.Empty;
                jsonSchemaProperty.Type = JsonObjectType.String;
            }
        }
    };
}, _ => {});
```

There is no way to check for attributes at this point. Is there something else I can use to accomplish this in a cleaner way?

For the controllers, the clean approach would be
`services.AddSwaggerGen(c => c.OperationFilter<HashidsOperationFilter>())`
and

```
public class HashidsOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        var hashids = context
            .ApiDescription
            .ParameterDescriptions
            .Where(x => x.ModelMetadata.BinderType == typeof(HashidsModelBinder))
            .ToDictionary(d => d.Name, d => d);

        foreach (var parameter in operation.Parameters)
        {
            if (hashids.ContainsKey(parameter.Name))
            {
                parameter.Schema.Format = string.Empty;
                parameter.Schema.Type = "string";
            }
        }

        foreach (var schema in context.SchemaRepository.Schemas.Values)
        {
            foreach (var property in schema.Properties)
            {
                if (hashids.ContainsKey(property.Key))
                {
                    property.Value.Format = string.Empty;
                    property.Value.Type = "string";
                }
            }
        }
    }
}
```

Is there something similar that I've missed in the swagger library built to support FastEndpoints?

**Comment by emanuelvarga** [comment]
Also, when using `c.Binding.ValueParserWhen` even though the full PropertyInfo is used as a parameter, the converter is cached per `propInfo.PropertyType`, not per `PropertyInfo`, thus rendering this useless, this might optimize the binding part a bit, but its very error prone and misleading

**Comment by KateyBee** [comment]
I think your best bet would be to create a custom type that encapsulates a `HashId`, something like the following:
```cs
readonly struct HashId
{
    static readonly Hashids _hid = new("salt");

    readonly int _int;
    readonly string _hash;

    internal HashId(int value)
    {
        _int = value;
        _hash = _hid.Encode(value);
    }

    internal HashId(string hash)
    {
        _hash = hash;
        _int = _hid.DecodeSingle(hash);
    }

    public static implicit operator int(HashId hashId)
        => hashId._int;

    public static implicit operator HashId(int value)
        => new(value);

    public static implicit operator HashId(string hash)
        => new(hash);

    public static implicit operator string(HashId hashId)
        => hashId._hash;
}
```
That way you don't need to mess around with `.Binding.ValueParserWhen` which btw is an undocumented method with a warning: 
https://github.com/FastEndpoints/FastEndpoints/blob/015ede860e1a4e74fcb4f478b4701ec18e62f307/Src/Library/Config/BindingOptions.cs#L131-L139

This way, you can just add a [TryParse() method](https://fast-endpoints.com/docs/model-binding#supported-dto-property-types) to the struct in order to support binding from route/query params, as well as write a `HashIdConverter : JsonConverter<HashId>` for STJ support.

For swagger support, you can write a [custom operation processor](https://gist.github.com/dj-nitehawk/d172140b1f7d576e632a0d15e9682f54) to cover your custom struct type as well.

Obviously there should be mapping to and from DTOs to data entities when there's a mismatch between the two worlds like this.
