### ISSUE TITLE
The property of the request body is not getting validated correctly

### ISSUE THREAD

**Issue by aakashbandhara-maruti** [FastEndpoints/FastEndpoints#644]
I have created a POST API endpoint with the request body as below:
```cs
public class CreateUserCompanyConnectionRequestDto 
{
    public string Email { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public int CompanyId { get; set; }
    public string Role { get; set; }
}
```

I have created the validator for all the properties. For now please consider the validation for FirstName. The validation is FirstName is required and the max length should be 40.
```cs
        RuleFor(c => c.FirstName)
            .NotEmpty()
            .WithErrorCode(ErrorResponsesProvider.InvalidFirstName.InternalCode)
            .MaximumLength(40)
            .WithErrorCode(ErrorResponsesProvider.FirstNameExceedsMaxLength.InternalCode);
```

Now when I make a request with the FirstName: null then I get the proper response as below
![image](https://github.com/FastEndpoints/FastEndpoints/assets/129277316/e5bb224c-e605-485a-a686-cf7762138467)

When I make a request with the FirstName length greater than 40 then also I get the proper response as below
![image](https://github.com/FastEndpoints/FastEndpoints/assets/129277316/ab9e2a93-6e58-446e-8f19-b52d6bdcee8b)

But when I make a request with the invalid data type ("first_name": 123) then I am not able handle the exception.
![image](https://github.com/FastEndpoints/FastEndpoints/assets/129277316/60a98b54-1e7d-4ec8-93c7-1533f047e162)

Suggest how we can handle the invalid datatype validation in FastEndpoints.

Note: the version of the FastEndpoints that I am using is 5.22.0

**Comment by dj-nitehawk** [comment]
i tried to replicate your issue with the following:
```cs
sealed class Request
{
    public string FirstName { get; set; }
    public int CompanyId { get; set; }
}

sealed class Validator : Validator<Request>
{
    public Validator()
    {
        RuleFor(c => c.FirstName)
            .NotEmpty().WithErrorCode("InvalidFirstName")
            .MaximumLength(40).WithErrorCode("FirstNameExceedsMaxLength");
    }
}

sealed class Endpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request r, CancellationToken c)
    {
        await SendAsync(r);
    }
}
```
this is what i get:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/f6b23e44-3ddb-4dbc-97ad-829b192c3bc5)

so it works as intended. 

your stack trace indicates this is some sort of custom middleware issue, and not caused by FE.

if you need further help, i'm going to need a repro project to debug. just copy/paste my code above to a new project and update it so that it produces the error, and attach a zip file here.
