### ISSUE TITLE
Decorating a member in Request with the [FromBody] attribute causes the "FluentValidation.Testing" library to stop working

### ISSUE THREAD

**Issue by martin-tnc** [FastEndpoints/FastEndpoints#645]
I have provided a modified E2EWalkthrough solution that illustrates the problem. All tests will turn green if you comment [FromBody] on the Request.  

This has not been implemented, as the HttpClient extension SENDAsync ignores attributes and serializes the entire request. Are there any plans to implement this?

I discovered this while setting up E2E tests for our project; it was a half-day detour :)

By the way, it's a great library. Keep up the excellent work.

Best regards,
Martin

[E2EWalkthrough.zip](https://github.com/FastEndpoints/FastEndpoints/files/14642039/E2EWalkthrough.zip)

**Comment by KateyBee** [comment]
This has been implemented in `v5.23.0.10-beta`.
Thanks for bringing it to our attention.

**Comment by martin-tnc** [comment]
As a side note, We also plan to use [FromHeader] and [FromQuery] in our request models. Do these work as well?

**Comment by KateyBee** [comment]
You're most welcome and yes it should.

**Comment by dj-nitehawk** [comment]
@martin-tnc 
thanks for the donation. greatly appreciate the support 🙏🙏🙏

also, i'd like to add a bit of clarity to what really goes on when you do a "routeless/strongly typed" integration test using the `HttpClient` extension methods such as `POSTAsyn()`. 

in such an integration test, you're basically skipping all the boilerplate code needed to construct a `HttpRequestMessage` with the applicable headers/route params/query params etc. instead you are constructing the actual request dto that the endpoint is looking for, to be able to do it's work. 

you're not really crafting the exact sort of http request that a real client/browser would be sending to the endpoint. so, these tests can't be called "true e2e/ integration tests" but this is perfectly fine as it's not your responsibility to test whether the library does it's binding correctly. all that really matters to you is that the endpoint handler receives the right (or wrong) data populated in the request dto.

if you really must get your hands dirty with the nitty gritty details of crafting a "true" http request, there's nothing stopping you from doing so using the regular methods on the http client such as `PostAsync()` or even the FE supplied `SENDAsync()` method. but it would be completely unnecessary in 99% of the cases, where a request dto is involved.

cheers!

**Comment by martin-tnc** [comment]
Thanks for clarifying. That's exactly what I thought was why this integration testing library had been created.
I just got confused, as it did not work as I thought, and I had to debug in the extension layer :)

I've upgraded to v5.23.0.10-beta in my feature branch, implemented a chain of tests, and all work flawlessly so far with the FromBody attribute. Thanks again for the awesome speed.
