### ISSUE TITLE
Adding multiple Validation Failures, only serialises the first

### ISSUE THREAD

**Issue by man-dh** [FastEndpoints/FastEndpoints#649]
Hello

I am trying to add multiple validation failures in my response, using ProblemDetails, but only the first one is serialised:

![Screenshot 2024-03-21 at 9 14 35 AM](https://github.com/FastEndpoints/FastEndpoints/assets/58421983/13288e3b-6c36-48fc-baa1-16677406f23d)

![Screenshot 2024-03-21 at 9 18 02 AM](https://github.com/FastEndpoints/FastEndpoints/assets/58421983/aae1a5e7-c7f7-4c58-9de0-92195411b1b1)

![Screenshot 2024-03-21 at 9 15 06 AM](https://github.com/FastEndpoints/FastEndpoints/assets/58421983/9c02d5b3-b6ec-4cf7-9b1e-abb153bc5899)

![Screenshot 2024-03-21 at 9 15 36 AM](https://github.com/FastEndpoints/FastEndpoints/assets/58421983/c7237970-cfae-4ea8-bea3-e187a4272d44)

**Comment by dj-nitehawk** [comment]
the default setting prevents duplicate errors for the same key name.
you can allow duplicates just by setting the following static property somewhere in your startup code:
```cs
ProblemDetails.AllowDuplicates = true;
```
[documented here](https://fast-endpoints.com/docs/configuration-settings#rfc7807-compatible-problem-details).

**Comment by man-dh** [comment]
Works, thanks
