### ISSUE TITLE
Could not find the JSON path of a referenced schema: Manually referenced schemas must be added to the 'Definitions' of a parent schema

### ISSUE THREAD

**Issue by JohnGalt1717** [FastEndpoints/FastEndpoints#651]
I'm getting this error in our project and I have no idea how do debug it and there is absolutely no information at all as to what is actually the issue. Right before this I get the following info, which is why I'm reporting it here and not in the nswag repository:

```
No action descriptors found. This may indicate an incorrectly configured application or missing application parts.
```
This would seem to indicate that there is no openapi definitions loaded, but the endpoints all work in fast-endpoints as you'd expect.

What does all of this mean with the swagger (other than it doesn't work) and how do I go about diagnosing it?

I can't find anything other than 2 open issues in nswag and nsjonschema with no information on how to find this and address it.

Thanks!

PS: I might be doing something wrong because this is confusing me in the docs:

Program.cs
Copy code
```cs
using FastEndpoints;
using FastEndpoints.Swagger; //add this

var bld = WebApplication.CreateBuilder();
bld.Services
   .AddFastEndpoints()
   .SwaggerDocument(); //define a swagger document

var app = bld.Build();
app.UseFastEndpoints()
   .UseSwaggerGen(); //add this
app.Run();
You can then visit /swagger or /swagger/v1/swagger.json to see the generated Swagger document.
```
[Configuration](https://fast-endpoints.com/docs/swagger-support#configuration)
Swagger generation/document settings can be configured by providing an action to SwaggerDocument():

```cs
Program.cs
bld.Services.SwaggerDocument(o =>
{
    o.DocumentSettings = s =>
    {
        s.Title = "My API";
        s.Version = "v1";
    };
});
```

Note that in the first section it references AddFastEndpoints().AddSwaggerDocument() and then in the second builder.Services.SwaggerDocument. If you do both, I get an error telling me that there's a duplicate. And some of the options to do with RemoveEmptyRequestSchema etc. (which I've tried not touching) don't show up in the AddFastEndpoints().AddSwaggerDocument() so it appears I need to use the later?

**Comment by dj-nitehawk** [comment]
> No action descriptors found. This may indicate an incorrectly configured application or missing application parts.

that you can safely ignore or suppress the log message as it's output by nswag because they're not aware of FE.

as for the other issue, i tried to replicate it but did not succeed.
could you possibly attach a small repro project so i can have a look?

btw, `AddSwaggerDocument()` is not something from FE. only `.Services.SwaggerDocument(...)` should be used.

**Comment by JohnGalt1717** [comment]
> > No action descriptors found. This may indicate an incorrectly configured application or missing application parts.
> 
> that you can safely ignore or suppress the log message as it's output by nswag because they're not aware of FE.
OK.

> as for the other issue, i tried to replicate it but did not succeed. could you possibly attach a small repro project so i can have a look?

The problem is that I have no way to start making an Repo because nswag is giving me no information at all to work from.  I can tell you that Swashbuckle works fine without error.


> btw, `AddSwaggerDocument()` is not something from FE. only `.Services.SwaggerDocument(...)` should be used.

Ok, well the FE docs reference it. Might want to fix.

Also of note, on app.ExportSwaggerJsonAndExitAsync it would be nice to supply the file name. I.e. we like to put ours in /help/v1/openapi.json but the document name is v1 so this right now forces /help.v1.json instead.

**Comment by dj-nitehawk** [comment]
> on app.ExportSwaggerJsonAndExitAsync it would be nice to supply the file name.

`v5.23.0.13-beta` can do this. thanks for the suggestion.

**Comment by JohnGalt1717** [comment]
> > No action descriptors found. This may indicate an incorrectly configured application or missing application parts.
> 
> that you can safely ignore or suppress the log message as it's output by nswag because they're not aware of FE.
> 
> as for the other issue, i tried to replicate it but did not succeed. could you possibly attach a small repro project so i can have a look?
> 
> btw, `AddSwaggerDocument()` is not something from FE. only `.Services.SwaggerDocument(...)` should be used.

https://fast-endpoints.com/docs/swagger-support

The first section and then second section. It may be the same thing, but it's very confusing.

I still can't figure out any way to identify why nswag is having an issue. If you have any insight, I'd greatly appreciate it.

**Comment by dj-nitehawk** [comment]
here's a [freshly scaffolded project](https://fast-endpoints.com/docs/scaffolding#project-scaffolding) with a working swagger/nswag setup. run it and check.

[SwaggerRepro.zip](https://github.com/FastEndpoints/FastEndpoints/files/14740440/SwaggerRepro.zip)

if you can reproduce the issue there with your own endpoint(s), send back the updated project and i'll look in to it.

**Comment by JohnGalt1717** [comment]
I found the issue. NSwag doesn't yet support Generics and throws without telling you what it's throwing on when it encounters a generic. (OpenApi 3.1 supports generics)
