### ISSUE TITLE
Unable to find any endpoint declarations when endpoints are in a different assembly

### ISSUE THREAD

**Issue by russharding** [FastEndpoints/FastEndpoints#653]
If I have all my endpoints in their own assembly, when calling builder.Services.AddFastEndpoints(), I get the error "System.InvalidOperationException: 'FastEndpoints was unable to find any endpoint declarations!'"

If I have other classes in the same assembly that get referenced before fast-endpoints, then I don't get this error. For example, if I have some services that I reference through DI, the error doesn't happen.

This feels like a quirk with how .NET loads assemblies and subsequently can find classes through reflection, like  Assembly.GetEntryAssembly()?.GetReferencedAssemblies();

[fastendpoint-error.zip](https://github.com/FastEndpoints/FastEndpoints/files/14748421/fastendpoint-error.zip)

**Comment by russharding** [comment]
This fixes the issue in my code, and more generically without the ".Where" clause, may be a good fall back for this type of use case.

```
 options.DisableAutoDiscovery = true;

              var assemblies = DependencyContext.Default?
                  .RuntimeLibraries
                  .Where(a => a.Name.Contains("PartOfMyNameSpace", StringComparison.InvariantCultureIgnoreCase))
                  .Select(a => Assembly.Load(a.Name))
                  .ToList();

              options.Assemblies = assemblies;
```

**Comment by dj-nitehawk** [comment]
yes you need specify additional assemblies for type discovery.
https://gist.github.com/dj-nitehawk/b3615fad393beabefe929e3f81af6822
