### ISSUE TITLE
Json Serializer Settings Ignored while unit testing endpoints 

### ISSUE THREAD

**Issue by rcreynolds53** [FastEndpoints/FastEndpoints#655]
Json Serializer settings are not respecting JsonSerializer settings for ignoring cycles

**This only seems to be happening when calling `SendAsync()` in the endpoint 
Setting `Response = ...` in the endpoint does seem to work as a workaround but is inadequate if I want to check status codes.
```cs
app.UseFastEndpoints(c =>
{
    .Endpoints.RoutePrefix = "api";
    c.Serializer.Options.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles;
});
```

In the test itself I have even tried to configure the Json Options 

```cs
var endpoint = Factory.Create<Endpoint>(ctx =>
  {
    ctx.AddTestServices(s => s.ConfigureHttpJsonOptions(opts => opts.SerializerOptions.ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles));
   }, _context, A.Fake<IOutputCacheStore>());
```

![image](https://github.com/FastEndpoints/FastEndpoints/assets/26964362/1dc59064-5626-4acf-9edb-967bdd990ede)

**Comment by KateyBee** [comment]
This should now work starting `v5.23.0.15-beta`.
Thanks for reporting.
