### ISSUE TITLE
options changed in `AddAuthenticationCookie` does not work even placed after `AddIdentity`

### ISSUE THREAD

**Issue by luxl** [FastEndpoints/FastEndpoints#656]
In my project, I need to use AddIdentity, and I want the api to return 401 if not authorized, so in `AddAuthenticationCookie` I did some configurations as discribed in #389, but it does not working, still using the default cookie autientication schema. But if I don't use `AddAuthenticationCookie` and use `ConfigureApplicationCookie`, then it works:
```
builder.Services.ConfigureApplicationCookie(options =>
{
    options.Cookie.Name = "xxx;
    options.Cookie.HttpOnly = true;
    options.LoginPath = new PathString("/xxxxxx");
    options.Events = new CookieAuthenticationEvents
    {
        OnRedirectToLogin = ctx =>
        {
            ctx.Response.StatusCode = 401;
                    
            return Task.CompletedTask;
        },
        OnRedirectToAccessDenied = ctx =>
        {
            ctx.Response.StatusCode = 403;
                    
            return Task.CompletedTask;
        },
        OnRedirectToReturnUrl = context =>
        {
            context.Response.StatusCode = StatusCodes.Status401Unauthorized;
            return Task.CompletedTask;
        }
    };

    options.SlidingExpiration = true;
});
```
Is the behavior expected or can be improved?

**Comment by dj-nitehawk** [comment]
`AddAuthenticationCookie()` is simply a wrapper method for quickly configuring basic cookie authentication. it's not meant to be used with identity, as identity sets cookies up in a different manner. so just configure identity as you [typically do](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/identity-configuration?view=aspnetcore-8.0).
