### ISSUE TITLE
Allow Commands/Events to be executed outside of an HTTP request without the need for IServiceScopeFactory 

### ISSUE THREAD

**Issue by gianbasagre** [FastEndpoints/FastEndpoints#657]
We use an event bus messaging in our project (NServiceBus) and we sometimes have the need to execute the Commands in an NServiceBus Handler as well as in Endpoints. I'm aware you can use `IServiceScopeFactory` but having the dependencies in the constructor is cleaner in my opinion.

**Comment by dj-nitehawk** [comment]
we've looked in to supporting this but it's just not possible due to the way the built-in command/event busses work.
it's the price we've decided to pay for convenience and performance.
cheers!
