### ISSUE TITLE
Route parameter property type not correctly set with swagger

### ISSUE THREAD

**Issue by Kingside88** [FastEndpoints/FastEndpoints#658]
Hi,

this issue is referencing to #99 Route parameter property type not correctly set with swagger

In my case the issue is not solved with the newest Version 5.24.0

my example Endpoint:
```csharp
    sealed class GetUserEndpoint : EndpointWithoutRequest
    {
        public override void Configure()
        {
            Get("/users/{UserId}");
            Options(x => x.WithTags("Test"));
            AllowAnonymous();
        }

        public override async Task HandleAsync(CancellationToken cancellationToken)
        {
            var logger = Resolve<ILogger<GetUserEndpoint>>();

            int userId = Route<int>("UserId");

            var user = new
            {
                UserId = userId,
                FirstName = "John",
                LastName = "Doe",
            };

            if (user is null)
            {
                await SendNotFoundAsync(cancellationToken);
                return;
            }

            await SendAsync(user, cancellation: cancellationToken);
        }
    }
```
Swagger: ***No parameters***
<img width="1088" alt="FastEndopoint_NoRouteParameter" src="https://github.com/FastEndpoints/FastEndpoints/assets/7474465/6c7e6910-6240-4eae-87bc-0378c5fc8d97">

Program.cs:
```csharp
...
services.AddFastEndpoints()
.SwaggerDocument();

...
app.UseFastEndpoints(config =>
{
    config.Errors.UseProblemDetails();
})
.UseSwaggerGen(); 

```

Thank you all, great package

**Comment by dj-nitehawk** [comment]
this is because the latest FE version applies the JSON property naming policy to swagger route parameters. you can turn that off like this:
```cs
.SwaggerDocument(x => x.UsePropertyNamingPolicy = false);
```
or you can just make sure the route parameter and the swagger parameter name matches, in which case it would just work without changing the above setting.
```cs
Get("/users/{userId}"); //should match below
var userId = Route<int>("userId"); //should match above
```

**Comment by Kingside88** [comment]
Thank you for the quick reply. Unfortunately that does not solve the problem
My code above the route Parameter is declared in PascalCase and the Route method tries to retrieve it in Uppercase.
Changing both to camelCase does not solve the problem.
`.SwaggerDocument(x => x.UsePropertyNamingPolicy = false);
`
has also no effect.

**Comment by dj-nitehawk** [comment]
works just fine either way.
have a look here: https://streamable.com/91aiup
if you want me to have a further look, please attach a small repro project i can debug.

**Comment by KateyBee** [comment]
@Kingside88 I'm not sure if this applies to your case, but reading route parameter type from route constraints is currently not implemented for FE's Swagger Processor.

For example, if you expect to see an `int` swagger path/route param just by defining a route constraint like this:
```cs
"/users/{UserId:int}"
```
It will not work out of the box. You need to be binding that to a request DTO to get that going like this:
```cs
sealed class MyRequest
{
    public int UserId { get; set; } // this int property will correctly make the swagger param int32
}

sealed class GetUserEndpoint : Endpoint<MyRequest>
{
    public override void Configure()
    {
        Get("/users/{UserId}");
        AllowAnonymous();
    }

    public override async Task HandleAsync(MyRequest req, CancellationToken cancellationToken)
    {
        var userId = req.UserId;

        await SendAsync(userId);
    }
}
```

**Comment by dj-nitehawk** [comment]
oh i see... this is about swagger param type, not about case mismatch.
my apologies @Kingside88 i missed this part in your initial question:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/a7e00c15-ef96-46fb-985d-454de6148ced)
i was thrown off by not seeing a route constraint in your route pattern 🤦‍♂️

**Comment by Kingside88** [comment]
It's all good :-) 
The solution from @KateyBee expects the parameter in the body.
```csharp
    sealed class MyRequest
    {
        public int UserId { get; set; } // this int property will correctly make the swagger param int32
    }

    sealed class GetUserEndpoint : Endpoint<MyRequest>
    {
        public override void Configure()
        {
            Get("/users/{UserId}");

            Options(x => x.WithTags("Test"));
            AllowAnonymous();
        }

        public override async Task HandleAsync(MyRequest request, CancellationToken cancellationToken)
        {
            var logger = Resolve<ILogger<GetUserEndpoint>>();

            //var userId = Route<int>("userId");
            int userId = request.UserId;

            var user = new
            {
                UserId = userId,
                FirstName = "John",
                LastName = "Doe",
            };

            if (user is null)
            {
                await SendNotFoundAsync(cancellationToken);
                return;
            }

            await SendAsync(user, cancellation: cancellationToken);
        }
    }
```
![Uploading FastEndopoint_NoRouteParameter_2.png…]()

**Comment by KateyBee** [comment]
Ummm... This is what I get:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/134909513/fae55237-d3c8-4bf5-bee4-37fd1f0b6059)

**Comment by Kingside88** [comment]
let me create an example repo for you...

**Comment by KateyBee** [comment]
You can just zip it up and attach here.

**Comment by Kingside88** [comment]
I created one but I can't even start it there :-(
https://github.com/Kingside88/FastEndpoints_RouteParameterIssue
When 
```csharp
services.AddFastEndpoints()
.SwaggerDocument();
```
is called, I retrieve the exception
`**System.InvalidOperationException:**'FastEndpoints was unable to find any endpoint declarations!'
`
But there is one endpoint in the folder Features

**Comment by KateyBee** [comment]
Let me check that and get back to ya...

**Comment by KateyBee** [comment]
Here you go... All fixed up.
Your startup config was a hot mess.
Seems like you haven't taken the time to go through FE's docs and just brute forced it ;-)
[RouteParameterIssue.zip](https://github.com/FastEndpoints/FastEndpoints/files/14903905/RouteParameterIssue.zip)

**Comment by KateyBee** [comment]
Btw, this is why your endpoint was not automatically discovered in this project:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/134909513/97bbdabe-636a-44ac-843f-a30ff2870325)

**Comment by dj-nitehawk** [comment]
aaaand we don't do swashbuckle over here. that project is now dead and we gave up on it long time ago 😉

**Comment by Kingside88** [comment]
Thank you. I will look to the differences. Even EndpointWithoutRequest is now correct. So I do not need a special Request class
