### ISSUE TITLE
Please reopen: Route parameter property type not correctly set with swagger

### ISSUE THREAD

**Issue by Kingside88** [FastEndpoints/FastEndpoints#659]
Sorry for being annoying, but this issue is not solved but is marked as closed:

#658

**Comment by dj-nitehawk** [comment]
we usually close issues when there's no work to be performed from our point of view. but that doesn't mean we will stop helping you resolve the issue, if you're still having trouble. pls allow at least 48 hours for a response. we're usually slow to response during weekends ;-)
