### ISSUE TITLE
Endpoint Validators not loading

### ISSUE THREAD

**Issue by davebowler** [FastEndpoints/FastEndpoints#663]
Validators for an endpoint do not seem to load correctly when the endpoint and validators are stored in a referenced class library instead of the AspNet core application itself. The endpoints are all recognized, but hitting the endpoint immediately returns a 500 error:

System.InvalidOperationException: Cannot resolve scoped service '<my validator class>' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(ServiceCallSite callSite, IServiceScope scope, IServiceScope rootScope)

If I move the endpoint, request and validator class into the API project, everything works fine, its only when attempting to load from a class library that is referenced.

Explicitly adding the validator as a Singleton allows it to resolve and run.

**Comment by dj-nitehawk** [comment]
you have to register additional assemblies (where validators are located) like so: https://gist.github.com/dj-nitehawk/b3615fad393beabefe929e3f81af6822

that should do the trick.

**Comment by davebowler** [comment]
services.AddFastEndpoints(
		o => o.Assemblies = new[]
		{
				typeof(ContributorByIdValidator).Assembly
		});

Error in trying to hit the endpoint:

System.InvalidOperationException: Cannot resolve scoped service 'XXXXXXX.ContributorByIdValidator' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(ServiceCallSite callSite, IServiceScope scope, IServiceScope rootScope)

**Comment by davebowler** [comment]
As I mentioned, the endpoint in other library loads and if I remove the validator, everything works, but having the validator there causes the above error unless I explicity add it into the service collection. However the Assembly loads into DI, it does not seem to load validators when they are in a different library than the Startup setting up FastEndPoints.

**Comment by dj-nitehawk** [comment]
hard to tell what exactly is going on there.
would it be possible to get a minimalistic/standalone repro project we can debug?
you can attach a zip file here.

**Comment by davebowler** [comment]
I will see what I might be able to put together. As an aside, I also tried:

`services.AddFastEndpoints(o =>
{
	var test = ExpenseTemplate.DiscoveredTypes.All;
	o.SourceGeneratorDiscoveredTypes.AddRange(ExpenseTemplate.DiscoveredTypes.All);
});`

And that did not work either even though I SEE the validator in a watch window in "test" variable above... And clearly the frameworks know what validator to look for because its complaining that it cannot find the fully qualified and correct name of the validator:
`System.InvalidOperationException: Cannot resolve scoped service 'FT.Expense.ExpenseTemplate.Endpoints.Contributor.ContributorByIdValidator' from root provider.`

**Comment by dj-nitehawk** [comment]
are you subclassing `AbstractValidator<T>` or `Validator<T>` when defining your validator classes?
if doing abstract validators, try:
```cs
.AddFastEndpoints(o => o.IncludeAbstractValidators = true)
```

**Comment by dj-nitehawk** [comment]
also are you trying to inject a validator by yourself into some endpoint?
if so, that may explain what's happenning. have a quick [read here](https://fast-endpoints.com/docs/dependency-injection#validator-dependencies).
FE doesn't actually register discovered validators in the DI container. it just creates it during startup and caches it as a singleton in the `EndpointDefinition`. that cached instance is re-used per every http request for a particular endpoint type.

shooting in the dark here really. need to see the exact usage in a repro to be certain.

**Comment by davebowler** [comment]
The Validator is inherited from the FEP Validator, not Fluent Abstract. I am injecting nothing into it.
`public class ContributorByIdValidator : Validator<ContributorByIdRequest>
{
	public ContributorByIdValidator()
	{
		RuleFor(x => x.ContributorId)
		  .NotEmpty();
	}
}`

That having been said, I just made as simple a version as I could without any other features focused ONLY on this endpoint to upload... But it WORKS!
So, there must be something else happening in my application that is somehow messing with the injection. I am going to add a second endpoint to my little test app and see if 2 validators work still, just in case, but as of now it seems like my problem has something to do with the interaction of FEP and something I have written... If two endpoints work in my test, then this is not a FEP issue.

**Comment by davebowler** [comment]
I can now replicate the issue. Basically, if I ALSO have Fluent Validation for my command handlers in the library, the endpoint validators seem to disappear when:
`services.AddValidatorsFromAssembly(typeof(CreateContributorHandler).Assembly);`

is called. I have tried using the "IncludeAbstractValidators" flag instead of the Fluent extension above and my command validators do not work.

**Comment by davebowler** [comment]
[FastEndpointTest.zip](https://github.com/FastEndpoints/FastEndpoints/files/15099226/FastEndpointTest.zip)

**Comment by dj-nitehawk** [comment]
you just need to filter out FE validators from being auto registered by `AddValidatorsFromAssembly`.
```cs
public static IServiceCollection AddTestEndPointDependencies(this IServiceCollection services)
{
	return services.AddValidatorsFromAssembly(
		typeof(MyFluentValidator).Assembly,
		filter: x => x.ValidatorType.BaseType?.GetGenericTypeDefinition() != typeof(FastEndpoints.Validator<>)); //filter out FE validators
}
```
the underlying cause is that `AddValidatorsFromAssembly` auto registers all validators as scoped, which is not what FE is looking for. also might pay to exclude non-FE validators from being scanned by FE:
```cs
builder.Services.AddFastEndpoints(o =>
{
	o.IncludeAbstractValidators = false; //make FE ignore abstract validators
});
```

**Comment by davebowler** [comment]
Works great! Thank you!
