### ISSUE TITLE
Problem with paralell testing with TestContainers. (Maybe Set WAF cache as optional?)

### ISSUE THREAD

**Issue by Luisetepe** [FastEndpoints/FastEndpoints#668]
Hi!,

I'm encountering a potential problem (or maybe I'm doing something wrong here) when trying to use TestContainers librry in order to set up a container for each test class. My fixture is something like this:
```csharp
public class IntegrationTestFixture : AppFixture<Program>
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:16-alpine")
        .WithDatabase("webapp_template_test")
        .Build();

    protected override async Task SetupAsync()
    {
        // place one-time setup code here for every test class

        await _postgres.StartAsync();

        //-----------THIS IS WHERE THE PROBLEM HAPPENS-----------------------//
        await using var scope = Services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<WebAppDbContext>();

        await Tools.Modules.Seeding.SeedingModule.Run(db);
        //------------------------------------------------------------------//
    }

    protected override void ConfigureServices(IServiceCollection services)
    {
        // replace the real database with a test database
        services.RemoveAll<DbContextOptions<WebAppDbContext>>();
        services.RemoveAll<WebAppDbContext>();
        services.AddDbContext<WebAppDbContext>(
            (options) =>
            {
                options.UseNpgsql(_postgres.GetConnectionString());
                options.UseSnakeCaseNamingConvention();
            }
        );
    }

    protected override async Task TearDownAsync()
    {
        // do cleanups here for every test class

        await _postgres.DisposeAsync();
    }

    public WebAppDbContext GetDbContext()
    {
        return Services.GetRequiredService<WebAppDbContext>();
    }

    public IUniqueIdentifierService GetUniqueIdentifierService()
    {
        return Services.GetRequiredService<IUniqueIdentifierService>();
    }
}
```

The problem here is that even if I disable any kind of concurrency in the xunit.runner.json, because its reuses the same WebApplicationFactory, I end up having the same dbContext for different test classes. This obviously leads to the tests that had the container where the DbContext points to succeeding, but any other test fails at seeding the database, complaining about the database not existing or not being able to connect to it.

The only thing that I can think of (that I did before the Appfixture rewrite some versions ago) is copy-pasting your helper TestFunctions and disable de WAF cache line, but I dont want to do this anything changes again.

Would you think this could be a sensible change to add an option to opt out of reusing the WebApplicationFactory?

Thank you very much!

**Comment by dj-nitehawk** [comment]
can you have a look at the [upcoming changelog](https://github.com/FastEndpoints/FastEndpoints/blob/5106bf6b31cc6a85920464428ce95d2dbd28388c/Src/Library/changelog.md), second item under "breaking changes" section?

see if [instantiating the testcontainer one time](https://gist.github.com/dj-nitehawk/04a78cea10f2239eb81c958c52ec84e0) inside the `PreSetupAsync()` method solves your issue.

the new behavior is available in [the latest beta](https://www.nuget.org/packages/FastEndpoints/5.24.0.9-beta).

i didn't analyze your issue too much assuming the new change would be the solution. if that doesn't seem to do it, let me know and i'll look in to it a bit deeper.

cheers!

**Comment by Luisetepe** [comment]
hi! thank you for your quick response. I've tried the new PreSetUpAsync() behaviour, and if you disable any concurrency in xunit, it works now. But the moment you enable any parallelism, it fails as before, 1 test class succeed, the rest does not because it can't fin the database.

Maybe this is a problem speciffically when using in combination EFCore(that I inject as a scoped dependency in the WAF) + TestContainers + Parallelism. The only thing that I can think of you enable this scenario is creating a WAF per test class, which would have its own Container + WAF, enabling this parallelism.

The beta version works right now if you want to use a SINGLE container for all the tests, which to some use cases could be problematic if you are testing modifications of the database.

**Comment by Luisetepe** [comment]
I think for now disabling parallelism and reseeding the database in SetupAsync() for every test class It's a good approach for my scenario. Maybe considering disable cache at the expense of using more resources for speed could be an option, but the current beta works well.

**Comment by dj-nitehawk** [comment]
the `AppFixture` is designed to only boot up one instance of your app/sut, cache and [reuse it for all test-classes](https://fast-endpoints.com/docs/integration-unit-testing#app-fixture) that depend on the derived app fixture.

the internal cache key is the the `System.Type` of your derived AppFixture. so if the goal is to have a sut/app per test-class, you can achieve that by creating a separate derived app fixture for each of the test-classes. that will boot up a separate sub per each test-class.

a shortcut you can use to reduce the amount of derived app fixtures is to create one generic app fixture:
```cs
public class MyAppFixture<TTestClass> : AppFixture<Program> { ... }
```
and then use that generic fixture in test-classes like this:
```cs
public class Tests(MyAppFixture<Tests> App) : TestBase<MyAppFixture<Tests>> { ... }

public class OtherTests(MyAppFixture<OtherTests> App) : TestBase<MyAppFixture<OtherTests>> { ... }
```

this will obviously slow down the test suit due to the number of suts being booted up but it should allow you to have a sut per test-class.

**Comment by Luisetepe** [comment]
Hi!
You were totally right, I read the code but did not realize a generic class with different type parameter would create another key for the WAF cache. This solution works perfectly for my use case.
