### ISSUE TITLE
Overriding EndpointSummary at endpoints level not possible when using Group

### ISSUE THREAD

**Issue by thenihalsingh** [FastEndpoints/FastEndpoints#675]
Hi,

### Problem Statement 

Currently, there is no way to override the summary at the endpoint level if the configuration is being provided from a group. This limitation prevents users from customizing the summary for specific endpoints when using groups.

### Expected Behaviour

Users should be able to override the summary at the endpoint level even when using a group. This would allow for more flexibility in customizing the endpoint summary based on specific requirements.

### Current Implementation

The current implementation does not allow for overriding the summary at the endpoint level when using a configuration group. The `EndpointSummary` attribute, which is typically used to override the summary, is not allowed in this scenario.

### Reproduction Steps

1. Create a configuration group.
2. Attempt to override the summary at the endpoint level using the `EndpointSummary` attribute.
3. Observe that the summary cannot be overridden and remains unchanged.

### Code Snippet
```
public class MyEndpointGroup: Group
{
    public MyEndpointGroup()
    {
        Configure("workordercenterwidget", ep =>
        {
           ep.Summary(s =>
          {
             s.Summary = "My endpoint Summary";
          });
       });
    }
}

[EndpointSummary("Overriding the summary at endpoint level")]   //<---------- This is not allowed right now
public class MyEndpoint : Endpoint<MyRequest, MyResponse>
{
    public override async Task HandleAsync(MyRequest req, CancellationToken ct)
    {
        await SendAsync(new()
        {
            FullName = req.FirstName + " " + req.LastName,
            IsOver18 = req.Age > 18
        });
    }
}
```
### Environment Details

- FastEndpoint Version: 5.25.0
- TargetFramework: net8.0

**Comment by thenihalsingh** [comment]
Found a solution. We can do this by overring the configure method at the endpoint level and adding a Summary over there.
```
public override void Configure()
{
    Post(MyRequest.Route);
    AllowAnonymous();
    Group<MyEndpointGroup>();
    Summary(s =>
    {
        s.Summary = "Overriding the summary at endpoint level";
    });
}
```

**Comment by dj-nitehawk** [comment]
that is correct.
we don't use the `[EndpointSummary]` attribute in FE.
