### ISSUE TITLE
Source Generator errors on FE projects

### ISSUE THREAD

**Issue by RivenSkaye** [FastEndpoints/FastEndpoints#676]
So on a new project I was getting a CS8785 error from the Razor source gen. Somewhat confused, I figured I'd spin up a fresh template (`dotnet new feproj`) and there were no errors or warnings _up until a reboot_. There it was, erroring on the template project as well.

FE version(s): 5.23, 5.24, 5.25
dotnet version: 8.0.204 (I'll see about updating that as well, but would be surprised if that fixed it)
env: Windows 10 pro, VSCode, dotnet CLI tools.

Repro steps:
from a CLI: `dotnet new feproj -n ReproTest -o ReproTest`. You _probably_ don't need to reboot, just pop open a fresh IDE session and it should present the error.

The most surprising part of this is the fact that the listed project SDK on the template is `Microsoft.NET.Sdk.Web` rather than `Microsoft.NET.Sdk.Razor` so I didn't expect Razor to be involved at all considering [the SDKs available currently](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview#available-sdks)

Error message:
```
Generator 'RazorSourceGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'MethodAccessException' with message 'Attempt by method 'Microsoft.AspNetCore.Razor.Language.RazorProjectEngineBuilder.Build()' to access method 'Microsoft.AspNetCore.Razor.PooledObjects.PooledArrayBuilder`1<System.__Canon>..ctor(System.Nullable`1<Int32>)' failed.'.
System.MethodAccessException: Attempt by method 'Microsoft.AspNetCore.Razor.Language.RazorProjectEngineBuilder.Build()' to access method 'Microsoft.AspNetCore.Razor.PooledObjects.PooledArrayBuilder`1<System.__Canon>..ctor(System.Nullable`1<Int32>)' failed.
   at Microsoft.AspNetCore.Razor.Language.RazorProjectEngineBuilder.Build()
   at Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator.GetStaticTagHelperFeature(Compilation compilation)
   at Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator.<>c.<Initialize>b__6_8(ValueTuple`2 pair, CancellationToken _)
   at Microsoft.CodeAnalysis.TransformNode`2.<>c__DisplayClass6_0.<.ctor>b__0(TInput i, CancellationToken token) in /_/src/Compilers/Core/Portable/SourceGeneration/Nodes/TransformNode.cs:line 27
   at Microsoft.CodeAnalysis.TransformNode`2.UpdateStateTable(Builder builder, NodeStateTable`1 previousTable, CancellationToken cancellationToken) in /_/src/Compilers/Core/Portable/SourceGeneration/Nodes/TransformNode.cs:line 83
-----
```

**Comment by dj-nitehawk** [comment]
just tried `dotnet new feproj -n ReproTest` and restarting rider.
everything's in order. don't have visual studio installed though.
can you zip up the project you scaffolded? let's see if i can run it on my machine.
most likely, something has gone haywire in your environment/ide.

**Comment by RivenSkaye** [comment]
Sorry for taking a while to get back to this; it seems like it's either a sporadic issue, or it just magically vanished after going off on vacation. Only difference between then and now is updating dotnet, so I'm going to wager it was an issue on that end instead
