### ISSUE TITLE
Route parameter property without DTO does not show up in Swagger

### ISSUE THREAD

**Issue by Iceeman76** [FastEndpoints/FastEndpoints#681]
Is there any known limitations about this?
When using a route parameter without a DTO like this: public override void Configure() => Get("/article/{ArticleID}");
And then accesing it like this: int articleID = Route<int>("ArticleID");
Works fine, but the parmeter is not shown in Swagger.

**Comment by dj-nitehawk** [comment]
works out of the box like so:
```cs
var bld = WebApplication.CreateBuilder(args);
bld.Services
   .AddFastEndpoints()
   .SwaggerDocument();

var app = bld.Build();
app.UseFastEndpoints()
   .UseSwaggerGen();
app.Run();

sealed class MyEndpoint : EndpointWithoutRequest
{
    public override void Configure()
    {
        Get("/article/{articleId:int}");
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken c)
    {
        await SendAsync(Route<int>("articleId"));
    }
}
```
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/be509bd0-3c0d-4cd2-aacc-fa1f6984a1e6)
