### ISSUE TITLE
Swagger: Treat GUID as UUID

### ISSUE THREAD

**Issue by Iceeman76** [FastEndpoints/FastEndpoints#682]
Hello!

Is there any way to tell SwaggerGen to treat GUID-types as UUID?
When generating an ApiClient with Kiota all guid:s are treated as strings, but if I change guid ti uuid in the swagger.json Kiota generates the correct type.

**Comment by dj-nitehawk** [comment]
i believe registering a [TypeMapper](https://github.com/RicoSuter/NJsonSchema/wiki/Type-Mappers) for nswag would get the job done.
```cs
.SwaggerDocument(
   o => o.DocumentSettings =
            s => s.SchemaSettings.TypeMappers.Add(
                new PrimitiveTypeMapper(
                    typeof(Guid),
                    schema =>
                    {
                        schema.Type = JsonObjectType.String;
                        schema.Format = "uuid";
                    })));
```
![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/2e29a5fb-3b32-490c-bc4a-6a4cd3cfcb21)
