### ISSUE TITLE
[Bug] Unit tests don't support multiple Factory.Create calls

### ISSUE THREAD

**Issue by d-avko** [FastEndpoints/FastEndpoints#687]
To reproduce: 
Create two endpoints, could be as simple as that:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/39842703/ce3c4821-ea66-4b76-8e0f-1986c6798554)

Then, create two of those inside ONE unit test:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/39842703/71ceb24d-b264-4f05-bae3-5d63c914bc6b)

The error occurs when I run the second HandleAsync:
![image](https://github.com/FastEndpoints/FastEndpoints/assets/39842703/e551a243-06c0-4304-b868-ea34847ba17d)

Could be related to Fastendpoint.Config ServiceProvider.

I guess simplest available solution for now is to decompose tests, and run them in order using NUnit's [Order] but I think this still needs fixing.

**Comment by dj-nitehawk** [comment]
that is not supported. pls see this [discord thread](https://discord.com/channels/933662816458645504/1223846876676362250) as to why. there's not much that can be done about it, other than converting to an integration test.

**Comment by d-avko** [comment]
got it - all good will use Order in that case.
