### ISSUE TITLE
JsonStringEnumConverter not doing anything

### ISSUE THREAD

**Issue by d4rkm0nkey** [FastEndpoints/FastEndpoints#689]
I configured FastEndpoints like this:
```csharp
.UseFastEndpoints(c =>
{
    c.Serializer.Options.Converters.Add(new JsonStringEnumConverter());
    c.Endpoints.RoutePrefix = "api";
})
```
This is my response model:
```csharp
public record MyResponse
{
    public required ResponseData ResponseData { get; set; }
}

public record ResponseData
{
    public required Address Address { get; init; }
}
public record Address
{
    public AddressType AddressType { get; init; }
}

public enum AddressType
{
    Type1,
    Type2,
    Type3
}
```
In swagger the preview looks correct:
```
"responseData": {
   "address": {
      "addressType": "Type1"
      }
}
```
But when I run the request, the endpoint returns:
```
"responseData": {
   "address": {
      "addressType": 0
      }
}
```
I am using:
FastEndpoints: 5.25.0
Microsoft.Extensions.Options: 8.0.2

**Comment by d4rkm0nkey** [comment]
Could be related to this: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2293#issuecomment-1283935011

**Comment by dj-nitehawk** [comment]
just tried it and works fine:

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/c83914f4-d47c-4909-a6a1-4df53989d1ca)

repro project?

**Comment by d4rkm0nkey** [comment]
I had to add `[JsonConverter(typeof(JsonStringEnumConverter))]` directly to my enum and now it is working for me as well. When I remove it, it returns 0 again.

**Comment by dj-nitehawk** [comment]
just doing this:
```cs
c.Serializer.Options.Converters.Add(new JsonStringEnumConverter());
```
works...
make sure it's the right one from STJ and not the one from newtonsoft.

**Comment by d4rkm0nkey** [comment]
I have  System.Text.Json.Serialization.JsonStringEnumConverter

**Comment by dj-nitehawk** [comment]
i just copy pasted your code above and created a test endpoint. works fine...

**Comment by dj-nitehawk** [comment]
```xml
<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.4"/>
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
```
don't need those. specially FE has no support for swashbuckle.
if removing those don't do it, attach a small repro project and i'll look in to it.

**Comment by d4rkm0nkey** [comment]
You are right. I removed them, but that didn't change the enum behaviour. I am fine though with adding the attribute to my enums.

If I can reproduce the problem with a small project, I will let you know.

**Comment by guillaume86** [comment]
Same issue here @d4rkm0nkey , did you find the cullprit?
