### ISSUE TITLE
Not sure where to leave this, exactly.

### ISSUE THREAD

**Issue by nhwilly** [FastEndpoints/FastEndpoints#696]
Your documentation is so good.  It helped me solve a problem I would *never* have been able to solve on my own.

It has made everything so easy to set up.  This particular case involved supporting two authentication schemes for my endpoints.  Now I can have native apps and my web apps call the same API endpoints with which authentication method is best.

I increased my monthly contribution after I noticed how much of my app now uses this package.  

Really outstanding.  Thank you.

**Comment by dj-nitehawk** [comment]
lovely...
greatly appreciate the feedback and the continued financial support.
may i sugget joining our [discord server](https://discord.gg/ARGPxTukpr)? there's plenty of casual/technical discussions going on over there which might be sometimes beneficial.
if you ever wanna have a chat privatey, just PM me or @KateyBee on discord. sponsors get preferential treatment😉
