### ISSUE TITLE
Nullable enum's

### ISSUE THREAD

**Issue by kevinvenclovas** [FastEndpoints/FastEndpoints#699]
Hi,

on my api i use a QueryParm enum value

```
 public class Request
 {
     /// <summary>
     /// Status of the user to filter result
     /// </summary>
     [QueryParam]
     public Status Status { get; set; }
 }
```

with this kind of code following dropdown is showing up on swagger:

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7681603/220697db-95cb-4142-ab7e-cc9bf10db475)

When i change the enum value to nullable, the dropdown disappear and the input converted to a string field

`public Status? Status { get; set; }`

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7681603/710188e0-e31a-4a04-b27e-7735f7527176)

Someone had a solution to keep the dropdown on nullable enum values?

**Comment by dj-nitehawk** [comment]
it's a bug in nswag. implemented a workaround in `v5.25.0.15-beta`.
that should correctly render a dropdown that's not required.
thanks for reporting 🙏
