### ISSUE TITLE
Swagger - conditional visibility

### ISSUE THREAD

**Issue by bojankostic81** [FastEndpoints/FastEndpoints#700]
Hi, is there a way to hide property in Swagger depending on the endpoint?

Instead of having two classes MyClassRequest and MyClassResponse

```
public class MyClassRequest
{
    public string Name { get; set; }
    public string Description { get; set; }
    // Other properties
}
```
and

```
public class MyClassResponse
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    // Other properties
}
```

I would like to have a single class:

```
public class MyClassModel
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    // Other properties
}
```
Is there a way to hide property in Swagger documentation based on a request in Endpoint? For example, if I have endpoints for updating and fetching entities this property should be visible in Swagger documentation, and if I have an endpoint for creating a new entity it shouldn't be displayed in Swagger documentation.

**Comment by IeuanWalker** [comment]
I don't believe there is, i also don't like the idea.

Each endpoint should have their own classes _(separation of concern)_. Otherwise your code will turn into a spaghetti mess and make your code hard to manage as it will be hard to track what a change could affect.

**Comment by dj-nitehawk** [comment]
agree 100% with @IeuanWalker 
there's a reason why REPR pattern exists.
however, you're free to create any sort of abomination you like by implementing a custom [operation processor](https://gist.github.com/dj-nitehawk/d172140b1f7d576e632a0d15e9682f54) for nswag and manipulating the schema.
