### ISSUE TITLE
The result displayed by Swagger is inconsistent with the actual return

### ISSUE THREAD

**Issue by buyuanne** [FastEndpoints/FastEndpoints#701]
```
    public override async Task HandleAsync(CancellationToken ct)
    {
        var res = new List<LabelValueModel>() {
                            new(){
                                 Label="item1",
                                 Value=1796959067866017792,
                                 Items=[]
                            }
        };

        await SendOkAsync(res);
    }
}

public class LabelValueModel
{
    public string Label { get; set; } = string.Empty;
    public long Value { get; set; }

    public List<LabelValueModel> Items { get; set; } = [];
}
```
swagger result
![3](https://github.com/FastEndpoints/FastEndpoints/assets/47813250/43a9a679-8401-46e7-8605-eb2fdbeac6f4)

reality
![4](https://github.com/FastEndpoints/FastEndpoints/assets/47813250/1e578a17-e80a-4c1e-870f-d4ad2f89a925)

type long 
value inconsistent

Perhaps it's still an issue with nswag?

**Comment by dj-nitehawk** [comment]
this is a swagger ui javascript thing. in js, the `Number` type is based on the IEEE 754 double-precision floating-point format, which can accurately represent integers up to `9,007,199,254,740,991`. the value `1,796,959,067,866,017,792` exceeds this limit, meaning it cannot be precisely represented as a javascript `Number`.

try this...
paste the following in the browser's js console and hit enter.
```js
var n = 1796959067866017792;
console.log(n);
```
you will see `1796959067866017800`
