### ISSUE TITLE
Inconsistent Endpoint Generation with Private Setters in Request Classes

### ISSUE THREAD

**Issue by JKamsker** [FastEndpoints/FastEndpoints#707]
### Description

When using private setters in a request class, the OpenAPI generator creates two different endpoints instead of one, differing only in the visibility of the properties in the request class.

### Steps to Reproduce

1. Define two endpoints, one with public setters and the other with private setters in the request classes as shown below:

```csharp
using Members.Signup;
using System;

namespace FastEpRepro.Features.Demo;

public static class DemoGet
{
    public class Request
    {
        public int A { get; set; }
        public int B { get; set; }
    }

    public class Response
    {
        public string Message { get; set; }
    }

    public class Endpoint : Endpoint<Request, Response>
    {
        public Endpoint()
        {
        }

        public override void Configure()
        {
            Get("demo/{@A}/{@B}", x => new { x.A, x.B });
        }

        public override async Task HandleAsync(Request request, CancellationToken ct)
        {
            var response = new Response { Message = $"The sum of {request.A} and {request.B} is {request.A + request.B}" };

            await SendOkAsync(response);
        }
    }
}

public static class DemoDelete
{
    public class Request
    {
        public int A { get; private set; }
        public int B { get; private set; }
    }

    public class Response
    {
        public string Message { get; set; }
    }

    public class Endpoint : Endpoint<Request, Response>
    {
        public Endpoint()
        {
        }

        public override void Configure()
        {
            Delete("demo/{@A}/{@B}", x => new { x.A, x.B });
        }

        public override async Task HandleAsync(Request request, CancellationToken ct)
        {
            var response = new Response { Message = $"The sum of {request.A} and {request.B} is {request.A + request.B}" };

            await SendOkAsync(response);
        }
    }
}
```

2. Generate the OpenAPI documentation.

### Actual Result

The OpenAPI documentation generates two different endpoints:

```json
{
    // ...
     "/demo/{a}/{b}": {
      "get": {
        "tags": [
          "Demo"
        ],
        // ...
    },
    "/demo/{A}/{B}": {
      "delete": {
        "tags": [
          "Demo"
        ],
        // ...
    }
  } 
}
```

### Expected Result

The OpenAPI documentation should generate a single endpoint with both methods:

```json
{
    // ...
     "/demo/{a}/{b}": {
      "get": {
        "tags": [
          "Demo"
        ],
        // ...
        },
        "delete": {
        "tags": [
          "Demo"
        ],
        // ...
    }
    }
}
```

### Additional Information

- **Library Version**: ``5.26.0``
- **.NET Version**: ``8.0``
- **OS**: Win 10

### Potential Cause

It seems that the OpenAPI generator is treating the visibility of the properties as part of the route parameter, causing it to differentiate between the two endpoints based on the casing or accessibility of the properties in the request classes.

Thank you for your attention to this issue.

**Comment by dj-nitehawk** [comment]
nice find but...
request dtos without publicly accessible (read & write) properties are not legal.
if you actuall try to send a request to the delete endpoint, you will be greeted with the following exception:
```yaml
System.NotSupportedException: Only request DTOs with publicly accessible properties are supported for request binding. Offending type: [DemoDelete+Request]
```
so i don't think there's anything to fix in the swagger generation. in fact, the swagger generation is incorrect due to the delete request dto not having any accessible/bindable properties.

**Comment by dj-nitehawk** [comment]
btw, you can have getter only props in dtos, but they shouldn't match any route parameter names.
