### ISSUE TITLE
POST/PUT endpoints without body gets 415

### ISSUE THREAD

**Issue by LaurentVandenbosch** [FastEndpoints/FastEndpoints#708]
Hello,

When a POST or PUT endpoint that get it's parameters exclusively from the path, Fastendpoints always return a 415 response.

In my example, it is configured like this :  

```
public class ConfirmAdvantageScreenViewedEndpoint(IMediator mediator) : Endpoint<ConfirmAdvantageScreenViewedRequest>
{
    public override void Configure()
    {
        Post("/api/carts/{CartId}/confirm-advantage-screen-viewed");
    }
}
public class ConfirmAdvantageScreenViewedRequest
{
    public Guid CartId { get; set; }
}
```

It seems that if I pass in a Content-Type in the request headers, it works, however, this is not the default behavior of Swagger, nor the Kiota client being generated.

Is this the intended behavior? If so, is there a workaround in my case?

Thanks !

**Comment by dj-nitehawk** [comment]
please see here: https://github.com/FastEndpoints/FastEndpoints/issues/492#issuecomment-1740210893

**Comment by LaurentVandenbosch** [comment]
Amazing, It works!
Thank you for the swift reply
