### ISSUE TITLE
Support for HTTP 422 Unprocessable Entity

### ISSUE THREAD

**Issue by StaticSphere** [FastEndpoints/FastEndpoints#715]
I just found out about this library, and love the concept of it. However, one thing that I'm noticing is that when the validation routine is run, it's returning HTTP 400 Bad Request, and not HTTP 422 Unprocessable Entity, which is the more correct HTTP status code to return when the data input is valid JSON, but violates a business rule (i.e. first name is required).

I did a code scan, but couldn't find anything that would enable this. Would you be OK with my creating a PR to add this functionality as an optional configuration? My thinking would be that you could configure it during the call to `UseFastEndpoints` in the validation options (like `options.Validation.HttpStatusCode`), or per API with a new method that you could call in the `Configure` method, something like `SetValidationErrorHttpStatusCode` (open to suggestions on name).

Great job on the library overall. Definitely like what I'm seeing!

**Comment by dj-nitehawk** [comment]
i believe the setting you're looking for is the following: 

https://github.com/FastEndpoints/FastEndpoints/blob/71cac4102c6c5831687beaece700c5e0a3e5ca95/Src/Library/Config/ErrorOptions.cs#L15

**Comment by StaticSphere** [comment]
Ah, sweet, thanks! I guess it just wasn't immediately clear. But yeah, that's exactly what I'm looking for. Thanks for following up! I'll close the issue. Have a fantastic weekend!
