### ISSUE TITLE
Duplicate endpoint name

### ISSUE THREAD

**Issue by franky1017** [FastEndpoints/FastEndpoints#718]
I had an existing API project (.net 8) using the standard controller/action for api endpoints.

I would like to convert all of them using fastendpoints, but I can't do them all at once. So my goal is to convert them one by one. I did a quick test like this -- I added a new folder called Holiday and added a new class called "EnableFederalHoliday". Here is the code:

```
public class EnableFederalHoliday : Endpoint<ClientFederalHolidaySchedule, bool>
    {
        public ClientService _client { get; set; }
        public override void Configure()
        {
            Post("/holiday/EnableFederalHoliday");
            AllowAnonymous();
        }

        public override async Task HandleAsync(ClientFederalHolidaySchedule req, CancellationToken ct)
        {
            var result = await _client.UpdateFederalHoliday(req);
            await SendAsync(result);
        }
    }
```

I didn't touch any of the existing APIs and just compiled. The error I am receiving is:

`InvalidOperationException: Duplicate endpoint name 'ApiHolidayEnableFederalHoliday' found on 'HTTP: POST /holiday/EnableFederalHoliday' and 'HTTP: POST /holiday/EnableFederalHoliday'. Endpoint names must be globally unique.`

I can guarantee you there was no previous API having the same endpoint. I completely made up the new /holiday/EnableFederalHoliday one. So why is it telling me I have duplicate ones? Also, where does the name "ApiHolidayEnableFederalHoliday" come from? I didn't define such name anywhere, but I guess the name doesn't matter, it's all about the actual endpoint.

Is it because I am mixing up both the traditional controller/action method with the fastendpoint method in a single project? Is this allowed/doable?

Thanks for any advice.

Frank

**Comment by dj-nitehawk** [comment]
is the exception thrown when you try to load the swagger page? or when you try to make a request to the new endpoint? or during app startup?

it is definitely possible to mix mvc controllers and fastendpoints in the same project and it's a common path taken by many when migrating. without knowing how exactly to reproduce the problem, it's just gonna be a guessing game. 

create a fresh new project and configure the startup code exactly how you've done in your existing app. then add a single mvc endpoint + a single fastendpoint to the project. does the error come up? if so, zip up the project and attach here.

> where does the name "ApiHolidayEnableFederalHoliday" come from?

see [this section](https://fast-endpoints.com/docs/swagger-support#short-endpoint-names) and the [one right below it](https://fast-endpoints.com/docs/swagger-support#custom-endpoint-names) for the answer.

**Comment by franky1017** [comment]
I am not able to re-produce this particular error anymore. But I have plenty of other problems. There are just quite a bit of conflict in swagger configuration between my existing controller configurations vs. the new fast-endpoints I am trying to add. I've decided to bite the bullet and convert all in a separate API project. Thanks for looking into it!
