### ISSUE TITLE
Expose generic IHost in AppFixture

### ISSUE THREAD

**Issue by dmalovric** [FastEndpoints/FastEndpoints#720]
Firstly, I would like to say that this is a brilliant library.

Just wondering, would it be possible to expose the generic IHost in the AppFixture?
Or alternatively the IHostBuilder by making the CreateHost(IHostBuilder builder) method overridable?

We use [Wolverine](https://wolverine.netlify.app/guide/testing.html#integration-testing-with-tracked-sessions) as our messaging library and need to obtain the WAF IHost in order to initialize Wolverine's testing harness.

Currently, we are achieving this by directly inheriting the WAF and overriding the CreateHost method:
```
public class IntegrationTestFixture : WebApplicationFactory<IApiMarker>, IAsyncLifetime
{
    internal IHost Host = null!;

    protected override IHost CreateHost(IHostBuilder builder)
    {
        Host = builder.Build();
        Host.Start();
        return Host;
    }
}
```

Then, in some integration test:
```
public class IntegrationTests
{
    readonly IntegrationTestFixture _fixture;
    public IntegrationTests(IntegrationTestFixture fixture)
    {
        _fixture = fixture;
    }

    public async Task Test()
    {
        // Arrange
        var request = new SomeMessage();

        // Act
         _ = await _fixture.Host.ExecuteAndWaitAsync(async () =>
        {
             _ = await client.SendAsync(request);
        }, timeoutInMilliseconds: 1000);

        // Assert
        ...
    }
}
```

This works, but we would really prefer to use the niceties that AppFixture gives us out of the box.
Thank you!

**Comment by dj-nitehawk** [comment]
i believe the following should do it?

```cs
public class Sut : AppFixture<Program>
{
    protected override void ConfigureApp(IWebHostBuilder builder)
    {
        var host = builder.Build();
    }
}

public class Tests(Sut sut) : TestBase<Sut>
{
    [Fact]
    public Task Name_Of_The_Test()
    {
        var host = sut.Server.Host;
    }
}
```

**Comment by dmalovric** [comment]
Unfortunately, this returns the IWebHost, not the generic IHost.

**Comment by dj-nitehawk** [comment]
right...
since `AppFixture` doesn't inherit `WebApplicationFactory` class and [uses WithWebHostBuilder()](https://github.com/FastEndpoints/FastEndpoints/blob/338ca235dd8a8acaf79baa55613a5325df2c4224/Src/Testing/AppFixture.cs#L165-L180), i don't think there's any way an `IHost` can be exposed because we don't have access to it :-(

**Comment by dmalovric** [comment]
If acceptable, I have come up with the following solution:

1. Expose an override on the AppFixture. By default, it uses the same code Microsoft have in the WAF definition.
```

    /// <summary>
    /// override this method if you'd like to provide any configuration for the generic app host of the underlying <see cref="WebApplicationFactory{TEntryPoint}" />
    /// />
    /// </summary>
    protected virtual IHost ConfigureAppHost(IHostBuilder a) 
    {
        var host = a.Build();
        host.Start();
        return host;
    }
```


2. Define a (really thin) WAF wrapper by subclassing it in a private class which accepts the override delegate in its primary constructor.

```
    private class WafWrapper(Func<IHostBuilder, IHost> configureAppHost) : WebApplicationFactory<TProgram>
    {
        protected override IHost CreateHost(IHostBuilder builder) => configureAppHost(builder);
    }
```


3. Call the WafWrapper instead of the WAF directly.
```
async Task<object> WafInitializer()
{
    await PreSetupAsync();

    //return new WebApplicationFactory<TProgram>().WithWebHostBuilder(
    return new WafWrapper(ConfigureAppHost).WithWebHostBuilder( //replace line above with this one, no other changes
        b =>
        {
            b.UseEnvironment("Testing");
            b.ConfigureLogging(
                l =>
                {
                    l.ClearProviders();
                    if (_messageSink is not null)
                        l.AddXUnit(_messageSink);
                    if (_outputHelper is not null)
                        l.AddXUnit(_outputHelper);
                });
            b.ConfigureTestServices(ConfigureServices);
            ConfigureApp(b);
        });
}
```

**Comment by dj-nitehawk** [comment]
looks alright to my eyes.
wanna do a PR?
