### ISSUE TITLE
How do I use custom authorization?

### ISSUE THREAD

**Issue by franky1017** [FastEndpoints/FastEndpoints#721]
In my traditional controller-based API project, I've created custom authorization filers and I used it like this:

```
[HttpPost]
[ApiExplorerSettings(IgnoreApi = true)]
[PermissionAuthorize(PermissionOperator.Or, Permissions.MakeCheckDecisions, Permissions.MakeACHDecisions)]
public async Task Test([FromBody] PaidCheck check)
{
...
}
```

"PermissionAuthorize" is a custom attribute where I look at the claims to find all the values from ClaimsType called "Permissions" and then make sure the values in that claims contains one of the required values listed in the attribute.

Is there any way I can use this authorization directly in fast endpoint? Right now, the only way I can think of is to create policies and use the RequireClaim() function.

How does your Permissions() method works? https://fast-endpoints.com/docs/security#permissions-method

I didn't find too much docs around this. What claim(s) does it look for?

**Comment by franky1017** [comment]
Oh wow, really awesome, works like a charm 🥇 

Thank you so much, such an awesome component 👍

**Comment by dj-nitehawk** [comment]
yeah the name of the game is convenience and getting rid of boilerplate ;-)

**Comment by franky1017** [comment]
@dj-nitehawk 

Do you have any recommendation on what kind of framework/components to use to consume APIs? Right now, I am just directly using the httpclient.PostJsonAsync() but a few problems like error handling, API endpoints are hard-coded in the call and not ideal.

I wonder if there is any components, like fast endpoint, but on the consuming end that you would recommend? Thanks!

**Comment by dj-nitehawk** [comment]
api client generation based on the swagger spec is my personal favorite. 

https://fast-endpoints.com/docs/swagger-support#api-client-generation
