### ISSUE TITLE
Swagger - DisplayOperationId

### ISSUE THREAD

**Issue by Iceeman76** [FastEndpoints/FastEndpoints#722]
Hello, probably a stupid question but how can I configure FE to generate Swagger documentation with the operationId visible in the UI?

Best regards

**Comment by dj-nitehawk** [comment]
here you go:
```cs
.UseSwaggerGen(uiConfig: c => c.AdditionalSettings["displayOperationId"] = true);
```

**Comment by Iceeman76** [comment]
Thanks alot it works!
Is this documented somewhere? I tried to fid it before asking here but obviously had no luck.

**Comment by dj-nitehawk** [comment]
didn't even know it existed until you asked ;-)
had to look it up [here](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/).
will add a note to the docs soon.
cheers!
