### ISSUE TITLE
swagger ui not displaying default value for nullable enum properties

### ISSUE THREAD

**Issue by aj-scram** [FastEndpoints/FastEndpoints#726]
so in the operation processor, you're assigning the ref directly to the param object via Schema; this causes invalid swagger which makes the default value not populate

https://github.com/FastEndpoints/FastEndpoints/blob/60efcbdbf7268af398c407b9d638e885807feffa/Src/Swagger/OperationProcessor.cs#L652

see generated swagger from NSwag below
![image](https://github.com/FastEndpoints/FastEndpoints/assets/150948796/afb3220c-4b96-4ec2-b9a2-162c89d6e23c)

![image](https://github.com/FastEndpoints/FastEndpoints/assets/150948796/cb6b30a7-2a9d-479b-8882-0efb3b6043e4)

![image](https://github.com/FastEndpoints/FastEndpoints/assets/150948796/93f915a5-cc33-4805-a33a-0d8fe7f92bdd)

Fix is that the $ref needs to be moved to oneOf or allOf collection for the param

![image](https://github.com/FastEndpoints/FastEndpoints/assets/150948796/fb5e7ff2-39bf-458b-b6e2-20a715bdb072)

**Comment by dj-nitehawk** [comment]
i believe it's being done as a workaround for #699 

https://github.com/FastEndpoints/FastEndpoints/blob/56be725f808fc25542d485e7355e3a66ef797cdb/Src/Swagger/OperationProcessor.cs#L651-L657

if we revert the workaround, then a nullable enum property is going to look like this in swagger ui:

![image](https://github.com/FastEndpoints/FastEndpoints/assets/7043768/88c39740-07ad-420c-b5cb-163667ccb0ca)

any ideas what exact swagger spec is needed for swagger ui to render a dropdown as well as honor default values for a nullable enum property?

**Comment by aj-scram** [comment]
I believe the correction here is to add to allOf instead

I already have an operation processor to do so for controller enums based on this comment/issue:

https://github.com/RicoSuter/NSwag/issues/3645#issuecomment-1457994616

That was to fix enums not generating as dropdowns as well, but I find using allOf continues to allow defaults to work as expected

There’s also an open issue where someone is asking for it to be configurable between the two

https://github.com/RicoSuter/NJsonSchema/issues/1509#issue-1181080784

**Comment by dj-nitehawk** [comment]
thanks! that helped...
check out `v5.26.0.26-beta` which should be available on nuget soon.
i believe it's working as expected now.
