### ISSUE TITLE
ClientGen.Kiota: Cannot find json with CleanOutput

### ISSUE THREAD

**Issue by austins** [FastEndpoints/FastEndpoints#729]
For FastEndpoints.ClientGen.Kiota (5.26.0.27-beta), if you specify CleanOutput for a client, you will get a `System.IO.FileNotFoundException`.

```cs
await app.GenerateApiClientsAndExitAsync(
    c =>
    {
        c.SwaggerDocumentName = "v1";
        c.Language = GenerationLanguage.CSharp;
        c.OutputPath = Path.Combine(app.Environment.WebRootPath, "ApiClients", "CSharp");
        c.ClientNamespaceName = "MyCompanyName";
        c.CleanOutput = true;
    },
    c =>
    {
        c.SwaggerDocumentName = "v1";
        c.Language = GenerationLanguage.TypeScript;
        c.OutputPath = Path.Combine(app.Environment.WebRootPath, "ApiClients", "Typescript");
        c.CleanOutput = true;
    });
```

This seems to be because the Swagger json is exported to the OutputPath before the Kiota generates and cleans the OutputPath.

https://github.com/FastEndpoints/FastEndpoints/blob/9b16c4e1a354a3105ef0428a3a137d93e60e693d/Src/ClientGen.Kiota/Extensions.cs#L203C9-L205C71

Would a good fix be to handle the output cleaning manually either in the library (then set CleanOutput to false for the Kiota call) or in the usage?

**Comment by dj-nitehawk** [comment]
starting with `v5.27.0.3-beta` the json file will be created in the system temp folder if "clean output" setting is enabled.
thanks for reporting 🙏
