### ISSUE TITLE
GenerateApiClientsAndExitAsync does not work as expected or is broken

### ISSUE THREAD

**Issue by JoeyRoeters** [FastEndpoints/FastEndpoints#730]
First time using FastEndpoints and do love the concept and how works in general. But, now I'm running into an issue with generating a client of the the project w/Kiota. When I use the `MapApiClientEndpoint` and go to the endpoint I do receive a generated ApiClient of my project, no issues so far. When I try to use the `GenerateApiClientsAndExitAsync` it doesn't do anything. I except (if I'm correct from reading the docs) that it will generate the client after building the project to a desired output destination. It does not do anything, nor gives any log info, while I'm using the `dotnet run --generateclients true --exportswaggerjson true` command. 

I've first tried the newest version of FastEndpoint(5.26.0.27-beta) and the stable release of 5.26, both do not work in the way I interpreted how the function works. 
Extra information:
- Using a M3 ARM processor macbook (MacOS: 14.5)
- .NET 8.0
- Tried latest release and beta of FastEndpoint
- MapApiClientEndpoint does work, Generate...AndExitAsync doesn't
- Tried different doc names, output destinations, languages, and dotnet run CLI options ; nothing generates.

Latests Program.CS:
```CS
using FastEndpoints;
using FastEndpoints.ClientGen.Kiota;
using FastEndpoints.Swagger;
using Kiota.Builder;
using NSwag;

var bld = WebApplication.CreateBuilder();
bld.Services
    .AddFastEndpoints()
    .SwaggerDocument(o =>
    {
        o.EnableJWTBearerAuth = false;

        o.DocumentSettings = s =>
        {
            s.Title = "AI Flow API";
            s.DocumentName = "v1";
            s.AddAuth("ApiKey",
                new OpenApiSecurityScheme
                {
                    Name = "api_key",
                    In = OpenApiSecurityApiKeyLocation.Header,
                    Type = OpenApiSecuritySchemeType.ApiKey
                });
        };
    });

var app = bld.Build();
app.UseFastEndpoints(c => { c.Endpoints.RoutePrefix = "api"; });

app.MapApiClientEndpoint("cs-download", c =>
    {
        c.SwaggerDocumentName = "v1"; //must match document name set above
        c.Language = GenerationLanguage.CSharp;
        c.ClientNamespaceName = "MyCompanyName";
        c.ClientClassName = "MyCsClient";
    },
    o => //endpoint customization settings
    {
        o.CacheOutput(p => p.Expire(TimeSpan.FromDays(365))); //cache the zip
        o.ExcludeFromDescription(); //hides this endpoint from swagger docs
    });

await app.GenerateApiClientsAndExitAsync(
    c =>
    {
        c.SwaggerDocumentName = "v1";
        c.Language = GenerationLanguage.CSharp;
        c.OutputPath = Path.Combine(app.Environment.WebRootPath, "ApiClients", "CSharp");
        c.CleanOutput = true;
    }
    );

app.Run();
```
Run command:
 `dotnet run --generateclients true --exportswaggerjson true`  and  `dotnet run --generateclients true` 
 
It can be that we completely understand the feature of `GenerateApiClientsAndExitAsync` wrong, we've looked with 2 other developers, but couldn't figure why it doesn't work. We hope someone can help us with either confirming we are using it wrong, the function works differently, or it indeed doesn't work as expected. Thanks in advance team FastEndpoints

**Comment by JoeyRoeters** [comment]
Update: it might have something to do that either kiota or FastEndpoints tries to open a build or something on port 5000 which is reserved on MacOS for airplay receiving, couldn't figure how to change the used port during the build.

**Comment by dj-nitehawk** [comment]
can you first try updating the host builder like so:
```cs
var bld = WebApplication.CreateBuilder(args); //pass down the args
```
or the app won't detect commandline arguments such as `--generateclients true` if i remember correctly.
let me know if that doesn't do it, and i'll investigate further.

cheers!

**Comment by JoeyRoeters** [comment]
Many thanks @dj-nitehawk! It indeed solved the issue, so dumb of us that we did not see this haha.

Sorry for the false issue report and keep the great features w/ FastEndpoint going!!
