### ISSUE TITLE
Is it possible to add a basic mapper between two classes?

### ISSUE THREAD

**Issue by jtuchel** [FastEndpoints/FastEndpoints#732]
Based on the docs https://fast-endpoints.com/docs/domain-entity-mapping#mapping-logic-in-a-separate-class I can map between Request, Domain Model and Response but in my case I want to map the Request to a Command object first. The result of the Command should get mapped to the Response.

Example:
```cs
public class Request
{
    public string Foo { get; set; }
}

public class Response
{
    public string Bar { get; set; }
}

public class Command : ICommand<string>
{
    public string Text { get; set; }
}

public class RequestToCommandMapper : Mapper<Request, Command>
{
    public override Command ToEntity(Request r) => new()
    {
        Text = r.Foo
    };
}

public class CommandToResponseMapper : Mapper<Command, Response>
{
    public override Response FromEntity(Command c) => new()
    {
        Bar = c.Text
    };
}
```

Drawbacks:
This would require to change the `Endpoint` class from `Endpoint<TRequest, TResponse, TMapper>` to `Endpoint<TRequest, TResponse, TMapper1, TMapper2, TMapper3>`

I would prefer having a mapper utility so you can use the mapping features of FastEndpoints outside from handlers and basically wherever you want to. So you don't have to use FastEndpoints and other mapping libraries in addition.

I am not an expert! Please let me know if this is already possible or if there are workarounds to achieve this :)

**Comment by dj-nitehawk** [comment]
the actual constraint on the `TMapper` on the endpoint class is simply a marker interface `IMapper`. so you can just create any kind of mapper class like so:

```cs
sealed class MyMapper : IMapper
{
    public Command ToCommand(Request request)
        => new() { Text = request.Foo };

    public Response ToResponse(Command command)
        => new() { Bar = command.Text };
}

[HttpPost("test"), AllowAnonymous]
sealed class MyEndpoint : Endpoint<Request, Response, MyMapper>
{
    public override async Task<Response> ExecuteAsync(Request req, CancellationToken ct)
    {
        await Task.CompletedTask;

        var cmd = Map.ToCommand(req);

        return Map.ToResponse(cmd);
    }
}
```
