### ISSUE TITLE
Adding Swagger Middleware prior to UseFastEndpoints

### ISSUE THREAD

**Issue by nhart12** [FastEndpoints/FastEndpoints#733]
I'm experiencing an issue with swagger UI due to our current application utilizing an Authorization fallback policy to require an authenticated user by default. For normal MVC controllers I'm able to bypass this for the swagger UI by adding the middleware for swagger prior to the .UseAuthorization call. 

This fails when doing something similar for FastEndpoints due to the Static Config.ServiceResolver not being set yet right here:
https://github.com/FastEndpoints/FastEndpoints/blob/1c5db30c632abf53280a0a8ca1ea5e2f5b57bc53/Src/Swagger/ValidationSchemaProcessor.cs#L45

Currently my only workaround is to have the following extension method to set the property via reflection

```
public static IApplicationBuilder UseFastEndpointServiceResolverWorkaround(this IApplicationBuilder app)
{
    var ep = ((app as IEndpointRouteBuilder) ?? throw new InvalidCastException("Cannot cast [app] to IEndpointRouteBuilder"));
    var type = typeof(Config);
    var field = type.GetField("_resolver", BindingFlags.NonPublic | BindingFlags.Static);
    field.SetValue(null, ep.ServiceProvider.GetRequiredService<IServiceResolver>());
    return app;
}
```

and with that I'm able to then order the middleware properly

```
app.UseFastEndpointServiceResolverWorkaround();
app.UseSwaggerGen();
app.UseAuthentication();
app.UseAuthorization();
app.UseFastEndpoints();
```

I'm not sure how common my scenario is & I'm happy to make a PR for this depending on feedback.

It looks like we can really simply use this same line of code in the UseSwaggerGen() extension:
https://github.com/FastEndpoints/FastEndpoints/blob/1c5db30c632abf53280a0a8ca1ea5e2f5b57bc53/Src/Library/Main/MainExtensions.cs#L65

or perhaps update the ValidationSchemaProcessor to take the services it depends on in the constructor

**Comment by dj-nitehawk** [comment]
pls check out `v5.27.0.6-beta`.
should be sorted now.
thanks!

**Comment by nhart12** [comment]
Yes, it is working in that version. Thanks for the quick turnaround!
