### ISSUE TITLE
Validation error on IEnumerable property in request

### ISSUE THREAD

**Issue by akordowski** [FastEndpoints/FastEndpoints#738]
I am using in a endpoint the following request object:

```csharp
public sealed class AddDocumentRequest
{
    public IEnumerable<TagDto> Tags { get; set; } = default!;
}
```

Calling the endpoint I always get this error:

```json
{
  "type": "https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "instance": "/documents",
  "traceId": "0HN56AK3S2PBM:00000011",
  "errors": [
    {
      "name": "tags",
      "reason": "Value [[{\"Name\":\"string\",\"Value\":\"string\"},\"{\\n  \\\"Name\\\": \\\"string\\\",\\n  \\\"Value\\\": \\\"string\\\"\\n}\"]] is not valid for a [IEnumerable`1] property!"
    }
  ]
}
```

I tested the `Tags` property with `string` instead of the `TagDto` and got instead of `["123","456","789"]` this result `["123,456,789"]`. This coresponds to the error message, where we can see an array inside an array.

I am using the version `5.27.0`.

Is there an setting that I'm missing or am I doing something wrong? Any help is appreciated.

Thank you for this great project!

**Comment by dj-nitehawk** [comment]
is this a GET or POST endpoint.
can you post the `TagDto` class pls.

**Comment by akordowski** [comment]
I might found the issue. When I'm executing using swagger ui in this way I get the described error:

![grafik](https://github.com/user-attachments/assets/9b096e30-6f6e-4759-a1c2-2a85cbce41f3)

But when I'm executing this way the array is correctly parsed into two objects.

![grafik](https://github.com/user-attachments/assets/404686e9-9dff-4d9c-b3ef-35f437948a1d)

Is this a swagger ui issue or could be somehow related with the FastEndpoints code?

**Comment by dj-nitehawk** [comment]
i'm trying to replicate your issue with the following code:
```cs
sealed class MyRequest
{
    public IEnumerable<TagDto> Tags { get; set; }

    public sealed class TagDto
    {
        public string Name { get; set; }
        public string Value { get; set; }
    }
}

sealed class MyEndpoint : Endpoint<MyRequest>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
        AllowFormData();
    }

    public override async Task HandleAsync(MyRequest r, CancellationToken c)
    {
        await SendAsync(r);
    }
}
```
but i can't seem to. it works:

![image](https://github.com/user-attachments/assets/205f902e-d14d-4709-966e-714113718721)

can you update my code and send back so i know how to reproduce it?

**Comment by akordowski** [comment]
Ok, found the issue. When I am using the default object in the Swagger UI then I get the error, when I change the `string` value then it works. I can reproduce it also with your endpoint.

```
{
  "name": "string",
  "value": "string"
}
```

Very weird, any idea what it can be?  
But at least it works as intended. Thank you for your time.

**Comment by dj-nitehawk** [comment]
definitely a swagger ui bug. when we don't modify the second object, swagger ui sends incorrect data:

```cs
{\n  \"name\": \"string\",\n  \"value\": \"string\"\n}
```
those line break characters should not be there.
