### ISSUE TITLE
RPC: Server took a long time to quit if it is streaming to client

### ISSUE THREAD

**Issue by luxl** [FastEndpoints/FastEndpoints#739]
I tested the provided 'Remote-Procedure-Call-Demo', start both server and client, and then send `http://localhost:5000/server-stream/100` to start server streaming, while the server is streaming, I want to quit the server by press CTRL-C, the server would take a long time to quit, likely waiting the stream ended. Is is possible to cancel the the streaming and quit immediately?

**Comment by dj-nitehawk** [comment]
thanks for reporting.
check the demo project now. should be sorted.
