### ISSUE TITLE
Route parameters binding.

### ISSUE THREAD

**Issue by Sunekaer** [FastEndpoints/FastEndpoints#740]
Question: Is it possible to bind route parameters to dto on a EndpointWithoutRequest<> ?
 
I know i can do Route<string>("Id") and to dto on Endpoint<>

Thanks! :)

**Comment by dj-nitehawk** [comment]
to be able to bind to a request dto property, you need to use an endpoint variant that takes a `TRequest` generic argument.
`EndpointWithoutRequest<TResponse>` is meant for when there is no request dto (TRequest).
when there is no TRequest, your only option for reading route parameters is the `Route<T>("...")` method.
or you'll have to read it yourself from the httpcontext.
hope that clears it up...
