### ISSUE TITLE
FastEndpoints unable to discover any endpoints despite having an endpoint in my project assemblies

### ISSUE THREAD

**Issue by Kermel** [FastEndpoints/FastEndpoints#742]
Hi I have created a new webapi project, currently I have 2 assemblies Project.Web and Project.Client.
I have added FastEndpoints as a reference and I have created a proimitive Endpoint in the Project.Client assembly (just an internal class inheritting from EndpointWithoutRequest, returning empty list.

I'm starting the app in the most primitive way, as recommended:
```cs
var builder = WebApplication.CreateBuilder(args);

builder.Services.AddFastEndpoints()
    .SwaggerDocument();

var app = builder.Build();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseFastEndpoints()
    .UseSwaggerGen();

app.Run();
```

But I'm still getting this "unable to discover any endpoints" exception.

I have debugged into the AddFastEndpoints() extension methods and I have found out that the assemblies are taken as follows:
`assemblies = assemblies.Union(AppDomain.CurrentDomain.GetAssemblies());`
(line 60 in the class EndpointData) and the second assembly is indeed not present :-/

Do you have any idea what I might be doing wrong that my second assembly is not present in the AppDomain ?

**Comment by dj-nitehawk** [comment]
have a look at the following: https://github.com/FastEndpoints/FastEndpoints/issues/712#issuecomment-2182647545
also, you only need the one `.UseSwaggerGen()` call.

**Comment by Kermel** [comment]
That was not the problem.
It seems that the other assemblies (besides the main - typically ".Web" - project) are only loaded to AppDomain when they are directly referenced in code (i.e. not only via the project references).

What actually helped were the the two things (either of them)

1. Directly specify which assemblies to load in the UseFastEndpoints() method
`builder.Services.AddFastEndpoints(options =>
    {
        options.Assemblies = [MyFirstAssembly.Get(), MySecondAssembly.Get(), ...];
    })`

(i'm using the assembly provider helper classes for other purposes in the other projects, they might look as follows:
`public static class MyFirstAssembly
{
    public static Assembly Get()
    {
        return typeof(MyFirstAssembly).Assembly;
    }
}`

2. Providing somewhere some piece of code in the Program.cs of the ".Web" project that references something from the other assemblies - for example DI wiring as follows (the code doesn't necessarilly need to preceede the "AddFastEndpoints()" call:
`//in the Program.cs
builder.Services.AddMyFirstModuleServices(builder.Configuration, logger);`
then in the MyFirstAssembly project I have the helper static class:
`public static class MyFirstModuleInstaller 
{
    public static IServicveCollection AddMyFirstModuleServices(this IServiceCollection services,
        ConfigurationManager config,
        ILogger logger)
    {
        //Do Some DI wiring-up
        //_services.AddMediatR(cfg => cfg.RegisterServicesFromAssembly(thisAssembly));
        //_services.AddFluentValidation(new[] { thisAssembly }, includeInternalTypes: true);
        logger.Information("{Module} module services registered.", "MyFirstModule");

        return services;
    }
}`

and that makes it work, the assembly is then present in the ApplicationDomain and it is enough to just have the empty "AddFastEndpoints()" call.

Might be worth mentionining somewhere in the docs... (i.e. it was not the problem of incorrect naming of the assembly that is then dropped by the used filter, you just need to reference them in the code).

**Comment by dj-nitehawk** [comment]
great!
will improve the docs in due course.
