### ISSUE TITLE
Support for Microsoft.AspNetCore.OpenApi?

### ISSUE THREAD

**Issue by christophwille** [FastEndpoints/FastEndpoints#743]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi

Is this possible / planned? I am mostly interested in using https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/aspnetcore-openapi?view=aspnetcore-9.0&tabs=visual-studio#using-scalar-for-interactive-api-documentation

**Comment by dj-nitehawk** [comment]
this is the [current position](https://github.com/FastEndpoints/FastEndpoints/issues/677#issuecomment-2115417563) on the ms openapi pkg.

you can already use scalar with FE. the following worked last i checked:

```cs
using Scalar.AspNetCore;

var bld = WebApplication.CreateBuilder(args);
bld.Services
   .AddFastEndpoints()
   .SwaggerDocument();

var app = bld.Build();
app.UseFastEndpoints();

if (app.Environment.IsDevelopment())
{
    app.UseOpenApi(c => c.Path = "/openapi/{documentName}.json");
    app.MapScalarApiReference();
}

app.Run();
```

**Comment by christophwille** [comment]
In the case of your code - the URL for the Scalar UI would be ... ?

**Comment by dj-nitehawk** [comment]
`http://localhost:{port}/scalar/v1` if i remember correctly.

`v1` is the default doc name when you don't specify anything as in the above example.

**Comment by dustyroberts** [comment]
This appears to work fine, until versioning comes into play.

For some reason it only pulls in non-versioned endpoints.

example of endpoint being included in the openapi json:

`public override void Configure()
{
    Head("/Health");
    AllowAnonymous();
    Summary(s =>
    {
        s.Summary = "Get the current health status of the api";
    });
}`

example of endpoint being ignored:

`public override void Configure()
{
    Head("/Health");
    AllowAnonymous();
    Version(1); // <-- This causes it not to be included in the openapi.json
    Summary(s =>
    {
        s.Summary = "Get the current health status of the api";
    });
}`

**Comment by dustyroberts** [comment]
just an update on the above.

you need to specify DocumentName in builder.services.userswaggerdoc()

```
builder.Services.SwaggerDocument(o =>
 {
     o.EnableJWTBearerAuth = false;
     o.DocumentSettings = s =>
     {
         s.DocumentName = "v1";
         s.Version = "v1";
     };
 });
```

this fixes the problem

**Comment by uzairali001** [comment]
> builder.Services.SwaggerDocument(o =>
>  {
>      o.DocumentSettings = s =>
>      {
>          s.DocumentName = "v1";
>          s.Version = "v1";
>      };
>  });

adding these won't help me in my case, and if I add `c.Versioning.DefaultVersion = 1;` then scalar doesn't show any endpoint at all

**Comment by dj-nitehawk** [comment]
after months of chipping away at it, i've finally managed to port `FastEndpoints.Swagger` to use `Microsoft.AspNetCore.OpenApi`. the swagger/nswag package remains intact and a new beta package called "FastEndpoints.OpenApi" has been published. if you'd like to take it for a spin, the preview documentation is here: https://dev.fastendpoints-doc-site.pages.dev/docs/openapi-support
