### ISSUE TITLE
How can i add UseOneOfForPolymorphism

### ISSUE THREAD

**Issue by kevinvenclovas** [FastEndpoints/FastEndpoints#744]
How can i use UseOneOfForPolymorphism with FastEndpoints to add my Polymorphis to swagger?

```c#
service.AddSwaggerGen(c =>
{ 
    c.UseOneOfForPolymorphism();
}
```

I added already the JsonSubtypes.KnownSubType to my base class

```c#
 [JsonConverter(typeof(JsonSubtypes), "Type")]
 [JsonSubtypes.KnownSubType(typeof(SelectDynamicFieldReponse), DynamicFieldType.SELECT)]
 public abstract class DynamicFieldBaseReponse
 {
  [Required]
  public abstract DynamicFieldType Type { get; }
 }
```

Endpoint

```c#
public class SettingsEndpoint : EndpointWithoutRequest<IEnumerable<ApplicationSettingSubGroupReponse>>
```

Reponse 
```c#
public class ApplicationSettingSubGroupReponse
{
    [Required]
    public required IEnumerable<DynamicFieldBaseReponse> Items { get; set; }
}
```

Swagger output

Base class missing Type and no sub class like SelectDynamicFieldReponse available on swagger

![image](https://github.com/user-attachments/assets/9c6bd7ed-a607-459a-b32b-802e9543b30b)

**Comment by dj-nitehawk** [comment]
nswag does polymorphism a bit differently than swashbuckle, which is what you're asking about i believe. FE only supports nswag and here's an example of a polymorphic request dto:

```cs
using System.Text.Json.Serialization;

var bld = WebApplication.CreateBuilder(args);
bld.Services
   .SwaggerDocument()
   .AddFastEndpoints();

var app = bld.Build();
app.UseFastEndpoints()
   .UseSwaggerGen();
app.Run();

public class Apple : Fruit
{
    public string Foo { get; set; }
}

public class Orange : Fruit
{
    public string Bar { get; set; }
}

[
    JsonPolymorphic(TypeDiscriminatorPropertyName = "_t"),
    JsonDerivedType(typeof(Apple), "a"),
    JsonDerivedType(typeof(Orange), "o")
]
public class Fruit
{
    public string Baz { get; set; }
}

sealed class MyEndpoint : Endpoint<Fruit>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Fruit r, CancellationToken c)
    {
        await SendAsync(r as Orange);
    }
}
```

![image](https://github.com/user-attachments/assets/aee0946a-8309-4e0b-a064-43ef355967e4)

also afaik, swagger ui will only give you the base class schema such as the following if your request dto type is the base class type:

![image](https://github.com/user-attachments/assets/e70de6de-035f-428c-a918-b0e6fcf1b16b)

you'd have to manually add the discriminator field `_t` and derived class properties when "trying it out" in the swagger ui.
hope that helps...

**Comment by kevinvenclovas** [comment]
@dj-nitehawk Thanks. With this version the child classes now available on swagger

But im missing the oneOf Parameter on my swagger now. On your example Fruit can be oneOf Apple  or Orange like this on my other project without Fastendpoint:

![image](https://github.com/user-attachments/assets/7eaa38be-169c-4399-860e-4921138c62c4)

**Comment by dj-nitehawk** [comment]
i can't find any info on `oneOf` support for polymorphic schema for nswag. `UseOneOfForPolymorphism()` or an equivalent doesn't seem to exist in the nswag world (as far as i can tell). they [only seem to be concerned about](https://github.com/RicoSuter/NJsonSchema/blob/9bf8f695b373410e8b51e1363270c08dda7b8127/src/NJsonSchema.Tests/Generation/SystemTextJson/SystemTextJsonInheritanceTests.cs#L68-L107) the discriminator mapping.

**Comment by kevinvenclovas** [comment]
Hmm, im played a little bit. On a single object like Exception swagger shows the oneOf parameter:

![image](https://github.com/user-attachments/assets/01f82eb1-2275-481a-87bb-1e7472a5bf5f)
![image](https://github.com/user-attachments/assets/350aae43-81ff-4cfb-bd9b-f131ac2f1c69)

**Comment by dj-nitehawk** [comment]
already implemented in https://github.com/FastEndpoints/FastEndpoints/commit/2f5540617bdbd784191f3608754960062d63c4e7
doing some final testing and trying to figure out how to add the descriminator field to the default/example.

**Comment by dj-nitehawk** [comment]
check out `v5.27.0.14-beta`.
enable the FE version of `UseOneOfForPolymorphism` like so:

```cs
.SwaggerDocument(c => c.UseOneOfForPolymorphism = true)
```

annotate the base class correctly:

```cs
[
    JsonPolymorphic(TypeDiscriminatorPropertyName = "_t"),
    JsonDerivedType(typeof(Apple), "a"),
    JsonDerivedType(typeof(Orange), "o")
]
public class Fruit
{
    ...
}
```

swagger schema will now list the derived types under a `oneOf` field like so:

![image](https://github.com/user-attachments/assets/937e745b-c100-49a3-9211-3f164ae69e1f)


i have not however been able to get the example json to show the discriminator field in swagger ui. it seems like a swagger ui limitation as the swagger spec seems to be generated correctly with a required property. how does the example show in swashbuckle? or does it have the same limitation?

**Comment by dj-nitehawk** [comment]
`v5.28` is out and it does the default example json with the discriminator field correctly.
