### ISSUE TITLE
Charset in the content-type header

### ISSUE THREAD

**Issue by ftrl** [FastEndpoints/FastEndpoints#746]
The ‘Content-Type’ header in the response does not contain the ‘Charset’ information. How can I specify this?

**Comment by dj-nitehawk** [comment]
implemented in `v5.28.0.1-beta`

 A new config setting has been added for customizing the charset of JSON responses. `utf-8` is used by default. can be set to `null` for disabling the automatic appending of the charset to the `Content-Type` header of responses. 
  
 ```csharp 
 app.UseFastEndpoints(c => c.Serializer.CharacterEncoding = "utf-8") 
 ``` 
 
 thanks for bringing this to our attention 🙏
