### ISSUE TITLE
Endpoint with Request DTO where all properties are mapped from RouteValues fails with error 415 Unsupported Media Type

### ISSUE THREAD

**Issue by hrachovm** [FastEndpoints/FastEndpoints#748]
Hi,
I have endpoint `POST /users/{userId}/contacts/{contactId}/disable` which disables a contact and returns the contact's data

Creating endpoint `PostDisableUserContact : Endpoint<EmptyRequest, ContactDto>...` and accessing the IDs by `Route<int>("userId")` works perfectly fine.

However if I introduce record `DisableUserContactDto(int UserId, int ContactId)` and change the enpoint to `PostDisableUserContact : Endpoint<DisableUserContactDto, ContactDto>...` the endpoint starts returning error 415 Unsupported Media Type.

If I add some additional property into the request e.g. `record DisableUserContactDto(int UserId, int ContactId, string Dummy)` everything starts to work fine. Obviously in swagger I can see info that the endpoint is expecting `{ "dummy": "string" }` as an input, I don't really want to have.

Please can you help me to understand how should I configure the endpoint so I can use Request DTO but I don't need to use this fake property as a work around?

Thank you.

**Comment by dj-nitehawk** [comment]
pls have a look at the following: https://github.com/FastEndpoints/FastEndpoints/issues/492#issuecomment-1740210893
even though that is concering a PUT request, it does apply to POST as well.
basically, you just have to clear/redefine the default "accepts" metadata.
let me know if that doesn't do it, will look in to it further.

**Comment by hrachovm** [comment]
Worked like a charm! Thank you so much for the quick response.
