### ISSUE TITLE
Event Bus Documentation link is not working

### ISSUE THREAD

**Issue by dmitriybelous** [FastEndpoints/FastEndpoints#750]
Event Bus Documentation link is not working:

https://fast-endpoints.com/docs/event-bus

![Screenshot_6-8-2024_163457_fast-endpoints com](https://github.com/user-attachments/assets/4ec05c10-2332-47a5-bef9-9bcd54c2c672)

**Comment by dj-nitehawk** [comment]
must've been a temporary blip.
seems to work fine now.
if you continue to have trouble, try clearing your browser cache.
you can try the [beta docs](https://dev.fastendpoints-doc-site.pages.dev/docs/event-bus) as well.

**Comment by dmitriybelous** [comment]
Works fine now thanks.
