### ISSUE TITLE
MinimalAPI Endpoint Auth not working with FastEndpoints

### ISSUE THREAD

**Issue by d4rkm0nkey** [FastEndpoints/FastEndpoints#752]
This is how I add authorization to my minimal api endpoints with nSwag.
```csharp
services
            .AddAuthorizationBuilder()
            .AddPolicy(jobName, policy => policy.AddRequirements(options.AuthorizationRequirement));
            
             app.MapPost(...)
                    =>
                {
                    ...
                })
             .WithOpenApi()
            .RequireAuthorization(jobName);
```

However as soon as I add FastEndpoints and add nSwag with it, the endpoints are not secured anymore and dont have locks in swagger.

**Comment by dj-nitehawk** [comment]
can you show me how to reproduce the issue by updating the following repro? i see locks in swagger ui for minimal and fe endpoints when i tried it.
[Repro.zip](https://github.com/user-attachments/files/16634619/Repro.zip)

**Comment by d4rkm0nkey** [comment]
Ok, I am trying it out. So far it works with your example. Not sure, what the difference is that causes the problem.
Give me some time.

**Comment by d4rkm0nkey** [comment]
I found the problem. I had an [AllowAnonymous] infront of my endpoints, which seems to work differently with FastEndpoints.
