### ISSUE TITLE
Default Tag override in Swagger UI

### ISSUE THREAD

**Issue by KUTlime** [FastEndpoints/FastEndpoints#753]
Dear FastEndpoinsts community,

I have a problem with overriding the default tag created for my endpoint. 

When I set a tag, I just get the duplicate endpoint in Swagger UI. I just need to set the default tag for the endpoint(s). Documentation isn't very helpful in this.

Is there a way how to do that?

![image](https://github.com/user-attachments/assets/1c57d5e9-2599-48f0-9f66-deaae2491e8c)

**Comment by dj-nitehawk** [comment]
have you seen [this part](https://fast-endpoints.com/docs/swagger-support#swagger-operation-tags) in the docs?
basically, you can't have the default "auto tagging" (which is based on route path segments) turned on if you are tagging endpoints manually. you'd have to choose a single strategy to avoid the duplication like you're seeing.

**Comment by dj-nitehawk** [comment]
starting from `v5.28.0.7-beta`, you can override the auto-tag value per endpoint.

![image](https://github.com/user-attachments/assets/ed667b57-f811-440f-bbfe-8fa7937ea018)

**Comment by KUTlime** [comment]
Dear @dj-nitehawk, you have my deeeeep respect for the support. 

Reported on Friday, and Monday, a new NuGet version with the feature that I need... WAU! 💥
