### ISSUE TITLE
HttpClientExtensions doesn't handle null IFormFile

### ISSUE THREAD

**Issue by clumsyninja007** [FastEndpoints/FastEndpoints#758]
When using the `HttpClientExtensions` for integration testing and posting to an endpoint which takes in form data, the static method `ToForm<TRequest>(this TRequest req)` is called to transform the request into `MultipartFormDataContent`.

I have an endpoint with a request DTO that looks something like
```
public record Request
{
    [HideFromDocs]
    [FromClaim(ClaimTypes.Role, isRequired: false)]
    public string? OptionalRoleClaim { get; init; }

    public int RouteParam { get; init; }

    public string? Name { get; init; }

    public IFormFile? File { get; init; }

    public SomeObject? AdditionalInfo { get; set; }
}
```

`ToForm` contains a check that looks like `if (p.PropertyType == Types.IFormFile) AddFileToForm((IFormFile)p.GetValue(req)!, p);` which asserts that my file is not null, but it's allowed to be null in my request.

**Comment by dj-nitehawk** [comment]
thanks for reporting.
fix is available in `v5.29.0.3-beta`
