### ISSUE TITLE
Feature: Support route constraints for parameter typing in swagger 

### ISSUE THREAD

**Issue by kylelaverty** [FastEndpoints/FastEndpoints#759]
**Issue:**
Based on the conversation in #658, it appears that the swagger processor has not been configured to have support for something like this: `Get("/users/{UserId:int}");` to be able to correctly show the parameter as type int in the generated swagger docs.

Current state:
![image](https://github.com/user-attachments/assets/cc67d5d1-ae89-4116-81d9-9651e1c67e55)

I am interested in helping but I am not sure where to start looking so if someone more familiar with the repo can point me in the right direction I can start poking away at it.

**Use:**
Since FastEndpoints supports the usage of route parameters without a DOT object it would be ideal to be able to support the correct Swagger formatting.

**Docs:**
[Attribute Routing - Route Constraints](https://learn.microsoft.com/en-us/aspnet/web-api/overview/web-api-routing-and-actions/attribute-routing-in-web-api-2#route-constraints)

**Comment by dj-nitehawk** [comment]
this works out of the box if you instruct swagger to not use `PropertyNamingPolicy`:
```cs
.SwaggerDocument(d => d.UsePropertyNamingPolicy = false);
```
![image](https://github.com/user-attachments/assets/04f66947-a327-4bc0-9ead-77439de81f9c)
if you keep the default which is to use property naming policy for matching property names, you have to name the routes in camel case which is the default policy, like so: 

```cs
{userId:int}
```
setting the serializer's property naming poicy to `null` like below would also do the trick:
```cs
.UseFastEndpoints(c => c.Serializer.Options.PropertyNamingPolicy = null)
```

**Comment by kylelaverty** [comment]
@dj-nitehawk I tried to implement the recommended approach a number of different ways with the attached sample project and it always results in `string` being shown.
[RouteParameterIssue.zip](https://github.com/user-attachments/files/16994316/RouteParameterIssue.zip)

I assume I have something configured strange, if you have a few minutes to take a look I would appreciate it.

**Comment by kylelaverty** [comment]
That Solved it, thanks
