### ISSUE TITLE
Issue with FastEndpoints PostProcessors - Exceptions Not Caught, Always Returning 200

### ISSUE THREAD

**Issue by itsoli91** [FastEndpoints/FastEndpoints#761]
I am attempting to implement a feature similar to MediatR's TransactionBehavior using FastEndpoints by leveraging post-processors. However, I am facing an issue where exceptions thrown during EF Core's `SaveChangesAsync` are not being caught properly, and the endpoint always returns a 200 status code, even when an exception occurs.

### **What I want to achieve:**
I want to handle exceptions that occur when EF Core's `SaveChangesAsync` throws an error, ensuring that proper error codes are returned (e.g., 500, 501) instead of always returning a 200 response.

### **Code Samples:**

**Endpoint class:**

```csharp
public class Create : EndpointBase<CreateRoleRequest, CreateRoleResponse>
{
    private readonly IRoleService _roleService;

    public Create(IRoleService roleService)
    {
        _roleService = roleService;
    }

    public override void Configure()
    {
        Post("roles");
        Version(1);
        Description(b =>
        {
            b.WithName("CreateRole")
             .Produces<CreateRoleResponse>();
        });
        Summary(s =>
        {
            s.Summary = "CreateAsync roles endpoint.";
            s.Description = "CreateAsync roles endpoint.";
        });

        Policy(x =>
            x.IAMPermissions(AclSubjectEnum.UserRoles.Value, AclActionEnum.Create.Value));
    }

    public override async Task HandleAsync(CreateRoleRequest req, CancellationToken ct)
    {
        var role = RoleMapper.Map(req);
        var result = await _roleService.CreateAsync(role);

        await SendOkAsync(new CreateRoleResponse(result), ct);
    }
}
```

**Global PostProcessors:**

1. **Exception Processor:**

```csharp
public class ExceptionProcessor : IGlobalPostProcessor
{
    public async Task PostProcessAsync(IPostProcessorContext ctx, CancellationToken ct)
    {
        // never hits

        if (!ctx.HasExceptionOccurred)
            return;

        if (ctx.ExceptionDispatchInfo.SourceException.GetType() == typeof(NotImplementedException))
        {
            ctx.MarkExceptionAsHandled(); // only if handling the exception here.

            await ctx.HttpContext.Response.SendAsync("This endpoint is not implemented yet!", 501, cancellation: ct);
            return;
        }

        ctx.ExceptionDispatchInfo.Throw();
    }
}
```

2. **Transaction PostProcessor:**

```csharp
public class TransactionPostProcessor : IGlobalPostProcessor
{
    public async Task PostProcessAsync(IPostProcessorContext ctx, CancellationToken ct)
    {
        var requestType = ctx.Request.GetGenericTypeName();

        var mainContext = ctx.HttpContext.Resolve<MainContext>();
        var logger = ctx.HttpContext.Resolve<ILogger<TransactionPostProcessor>>();

        logger.LogInformation("Saving changes for {requestType} in TransactionPostProcessor.", requestType);

        await mainContext.SaveChangesAsync(ct);
    }
}
```

**PostProcessor Registration:**

```csharp
public static void UseCustomFastEndpoints(this WebApplication app)
{
    app.UseFastEndpoints(c =>
    {
        c.Endpoints.Configurator = ep =>
        {
            ep.Description(b =>
            {
                b.Produces(401);
                b.Produces(403);
                b.Produces<ExtendedProblemDetails>(400);
                b.Produces<ExtendedProblemDetails>(409);
                b.Produces<ProblemDetails>(500);
            });
            ep.PostProcessor<TransactionPostProcessor>(Order.After);
            ep.PostProcessor<ExceptionProcessor>(Order.After);
        };
        c.Errors.UseProblemDetails();
        c.Versioning.Prefix = "v";
        c.Versioning.PrependToRoute = true;
        c.Serializer.Options.Converters.Add(new JsonStringEnumConverter());
    });
}
```

### **Observed Behavior:**
- The `ExceptionProcessor` never gets hit, even when an exception occurs.
- The transaction logic runs, but in case of an exception in `SaveChangesAsync`, the endpoint still returns a 200 status code.
- I expect proper exception handling and response codes (such as 500 or 501) but am getting a 200 OK response regardless of the error.

### **Expected Behavior:**
- The `ExceptionProcessor` should catch the exception, handle it, and return the appropriate HTTP status code (e.g., 500 for general exceptions or 501 for unimplemented functionality).
- The response should not be a 200 when an error occurs during the transaction.

### **Additional Information:**
- I am using FastEndpoints with EF Core.
- Post-processors are registered as per the documentation, but exceptions in the EF Core transaction are not propagated correctly, nor is the `ExceptionProcessor` hit.

Any advice on how to properly catch exceptions and return the correct status code would be greatly appreciated!

**Comment by dj-nitehawk** [comment]
i don't think an "exception catching post processor" is the right tool for this job as they are not designed to catch/handle exceptions in other post processors.

[IEndpointFilters](https://gist.github.com/dj-nitehawk/3edcd59ce03230b98369e2f2259bc5d3) introduced in .net 7 seems like a better choice here, as it's comparable to a mediatr like pipeline, whereas the FE pre/post processors are not.
