### ISSUE TITLE
PUT or POST with empty bodies gives me 415 Media type not supported

### ISSUE THREAD

**Issue by kevinopensquiggly** [FastEndpoints/FastEndpoints#762]
If I create an endpoint that uses either a PUT or a POST verb, and either the parameters are not needed (EmptyRequest) or the parameters are fully contained within the route ("foo/{Id}"), then shouldn't I be able to send the request with an empty body for the data (works just fine with GET verbs).

When I do that I always get back a 415 Media type not supported exception.

The only workaround I've found is to send "{}" as the body of the request.

But this is highly inconvenient. For example, let's say the endpoint is a web hook, that means you can't just configure your system to send a regular request, you have to have the system configured to send "{}" in with the body, which might not be very obvious to the user and they'll be left wondering why their webhook doesn't work.

Has anyone else run into this or am I doing something wrong? I didn't find anything in the docs about it. Thank you.

**Comment by dj-nitehawk** [comment]
i believe the following should answer your question: https://github.com/FastEndpoints/FastEndpoints/issues/492#issuecomment-1740210893
