### ISSUE TITLE
DTO property "Tag" does not get serialized in to the OpenAPI3 spec

### ISSUE THREAD

**Issue by BasJ93** [FastEndpoints/FastEndpoints#764]
When defining a DTO with a property `Tag`, the property is not serialized in to the OpenAPI3 spec.

For example:
```C#
public class AddTagToActorRequestDto
{
    public int Id { get; set; }
    
    public string Tag { get; set; } = string.Empty;
    
    public string TagName { get; set; } = string.Empty;
}
```

Resulting definition:

![image](https://github.com/user-attachments/assets/54714752-0c5e-4121-9992-7428bee374d3)

With the remark that the endpoint accepts the Id property as part of the path, so it is logical that the Id property is not serialized in to the body of the request.

It actually get stranger. After rebuilding my code, suddenly the `Tag` property shows up and the `TagName` property disappears.

**Comment by BasJ93** [comment]
Yes, the dto is also used in another endpoint. The other endpoint sets the `Tag` property from the request path.

**Comment by dj-nitehawk** [comment]
i see...
sharing dtos can lead to strange behavior with swagger generation.
the recommended aproach is to put the common properties in a base dto class and create unique derived request dtos per endpoint.
ideally you should have totally isolated request dto per endpoint according to REPR pattern. even though it means duplicating a bit of code. it pays off in the longrun having totally decoupled vertical slices.
