### ISSUE TITLE
Request DTO showing up in generated swagger despite using FromBody on property

### ISSUE THREAD

**Issue by aj-scram** [FastEndpoints/FastEndpoints#766]
I'm using the FromBody in combination with FromCliams and so on to bind things to the request DTO of endpoints. 

Discovered that DTOs with FromBody properties were being added to generated Swagger despite the endpoint definition being as expected (references the type the FromBody property is).

I think this is, in part, because I have RemoveEmptyRequestSchema set to True and everything else is being removed from the schema _except_ the FromBody property during Swagger generation.

Can we avoid the parent DTO type being added to Swagger in these scenarios? It seems intuitive to me that if I'm using FromBody the request DTO shouldn't be exposed. 

I believe removing the property from the schema would work in my case, given the schema would then be Empty

![image](https://github.com/user-attachments/assets/f67a0462-3e2d-4cd5-aac2-f026727babee)

![image](https://github.com/user-attachments/assets/067c0f1b-d092-43e7-9740-9b51cb929cfb)

![image](https://github.com/user-attachments/assets/b11d697e-35c3-4457-bffb-d821f526d5b2)

![image](https://github.com/user-attachments/assets/d6a3a937-c097-4963-b195-b3ef909af933)

**Comment by aj-scram** [comment]
I guess I'm also a little confused if the intention here was to decorate the main api contract class with FromHeader, FromQuery, etc..... and leave the non-decorated properties to be bound from JSON body in request

OR

If it's a reasonable pattern to define a request DTO for every endpoint and use From* attributes to specify where to bind from, including FromBody

I've doing the latter, as I like to separate out the request DTO for FE endpoint vs my classes for api contracts; avoids confusion for new devs when looking at stuff.

**Comment by dj-nitehawk** [comment]
this has been sorted in `v5.29.0.6-beta`
the orphaned parent schema will no longer be present in the generated swagger spec.
thanks for reporting!

**Comment by aj-scram** [comment]
You're amazing. Thx so much
