### ISSUE TITLE
example values not respected on FromBody type on request DTO when generating sample request in swagger

### ISSUE THREAD

**Issue by aj-scram** [FastEndpoints/FastEndpoints#767]
if I have a complex type on the request DTO bound to via FromBody and example xml on the properties, the generated swagger should use that for the example request in swagger, but this is not the case

if you do the same (document example values) to the request DTO directly this isn't a problem when it is also the thing JSON is being bound to

additionally, trying to use EndpointSummary.ExampleRequest as a workaround doesn't work cause the request body type and the request dto type are different; again it acts as expected when this isn't the case

code: 

![image](https://github.com/user-attachments/assets/7f0d8661-8eb7-4996-981c-0a71dfe28b6e)
![image](https://github.com/user-attachments/assets/00ca2fb1-aac4-4977-a41f-8209fc4f2fc8)
![image](https://github.com/user-attachments/assets/818085ce-7ef4-47ef-a125-95577fdd5397)

generated swagger:

![image](https://github.com/user-attachments/assets/f8f3a013-4d24-4a3d-a2e2-1b87de653175)
![image](https://github.com/user-attachments/assets/729eed65-b70d-4b6b-a9b3-244e9a6b4d40)

**Comment by dj-nitehawk** [comment]
issue sorted in `v5.29.0.7-beta`. 
the following will just work now:
```cs
sealed class Request
{
    ///<example>12345</example>
    public string Id { get; set; }

    [FromBody]
    public Person Person { get; set; }
}

sealed class Person
{
    ///<example>johnny</example>
    public string FirstName { get; set; }

    ///<example>doe</example>
    public string LastName { get; set; }
}

sealed class MyEndpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();

        // uncomment to override xml doc example
        //Summary(s => s.ExampleRequest = new Person { FirstName = "JANE", LastName = "DOE" });
    }
}
```

![image](https://github.com/user-attachments/assets/b3fc8eef-61b1-4a2c-84d1-ad039d3c6333)
