### ISSUE TITLE
types without inheritance showing as OneOf property in schema

### ISSUE THREAD

**Issue by aj-scram** [FastEndpoints/FastEndpoints#768]
this seems related to the other open issue with enums showing as OneOf

![image](https://github.com/user-attachments/assets/3999d9a2-a61c-4901-a70b-94303ec6886c)

![image](https://github.com/user-attachments/assets/5dd26cde-745b-435c-a2ae-f55b84623bd5)

**Comment by dj-nitehawk** [comment]
can you update and send back the following code to replicate this issue?

```cs
var bld = WebApplication.CreateBuilder(args);
bld.Services
   .AddFastEndpoints()
   .SwaggerDocument();

var app = bld.Build();
app.UseFastEndpoints()
   .UseSwaggerGen();
app.Run();

sealed class Request
{
    public string Id { get; set; }
    public Person Person { get; set; }
}

sealed class Person
{
    public string FirstName { get; set; }
    public string LastName { get; set; }
}

sealed class MyEndpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Post("test");
        AllowAnonymous();
    }

    public override async Task HandleAsync(Request r, CancellationToken c) { }
}
```

because, this is what i'm seeing:

![image](https://github.com/user-attachments/assets/79d5849a-be17-4bfb-9ced-ecbfdc93bb16)

could it be some custom nswag processor in your app messing things up?

**Comment by aj-scram** [comment]
![image](https://github.com/user-attachments/assets/96663186-85f3-4e02-a4f6-1e719ac1ce5a)

![image](https://github.com/user-attachments/assets/b378657c-8299-4dba-a480-249988836671)

no processors, involved. 

seems to be related to nullable, actually.

changing Person -> Person? causes oneOf

**Comment by dj-nitehawk** [comment]
so....
apparently this seems to be the way nswag does it by default.
good news is the following nswag setting can be used to change that behavior.

```cs
.SwaggerDocument(d => d.DocumentSettings = s => s.SchemaSettings.AllowReferencesWithProperties = true);
```
