### ISSUE TITLE
enums with a shared value get serialized to same string in Swagger

### ISSUE THREAD

**Issue by aj-scram** [FastEndpoints/FastEndpoints#769]
C# supports having multiple enums refer to each other (cause they're the same value), but looks like this isn't handled well when generating swagger

![image](https://github.com/user-attachments/assets/f089c2d3-cf2d-4efd-be53-6c88d857786d)
![image](https://github.com/user-attachments/assets/7217b4ed-b9a4-4f91-a561-a0484b0740f3)

**Comment by dj-nitehawk** [comment]
even though it's allowed in .net, it doesn't seem to be allowed by the swagger spec:

![screen-record-1726984532](https://github.com/user-attachments/assets/918c3b61-f079-4e8a-83dd-256801d2a2dd)

that's most likely why the swagger ui doesn't display the dropdown correctly.

**Comment by aj-scram** [comment]
ah fair stuff
