### ISSUE TITLE
PostProcessor Fails to Persist Changes to Response Properties in ID Encoding/Decoding Process

### ISSUE THREAD

**Issue by jonathanperis** [FastEndpoints/FastEndpoints#770]
I have a structure that contains pre and post processors, which are used to encode/decode an ID. The pre-processor works as expected: when I receive an incoming request, the ID is encoded, and I decode it successfully during the pre-processing phase. By the time the request reaches the handler, the value is decoded correctly.

However, in the post-processor phase, my goal is to re-encode the ID (to avoid exposing the original value) before sending the response. Unfortunately, even though I modify the properties in the post-processing phase, the values are not being persisted. The response returns without any changes.

**Steps to Reproduce**

The issue can be reproduced using a similar structure:

```csharp
public class Models
{
    public class Request
    {
        public string ClientId { get; set; }
    }

    public class PreProcessor(IServiceScopeFactory scopeFactory) : IPreProcessor<Request>
    {
        public Task PreProcessAsync(IPreProcessorContext<Request> context, CancellationToken ct)
        {
            using var scope = scopeFactory.CreateScope();
            var sqidsService = scope.Resolve<ISqidsService>();
            
            // Decode the encoded ID (e.g., receive '8BDEC71I', decode to '12345')
            context.Request.ClientId = sqidsService.DecodeClientId(context.Request.ClientId);

            return Task.CompletedTask;
        }
    }

    public class PostProcessor(IServiceScopeFactory scopeFactory) : IPostProcessor<Request, Response>
    {
        public Task PostProcessAsync(IPostProcessorContext<Request, Response> context, CancellationToken ct)
        {
            using var scope = scopeFactory.CreateScope();
            var sqidsService = scope.Resolve<ISqidsService>();
            
            // Encode the ID back (expected to return '8BDEC71I' from the original 12345 value at the end. On runtime it works, but when I receive a json outside this process the value isn't been changed)
            context.Response.ClientId = sqidsService.EncodeClientId(context.Response.ClientId);

            // This value is not persisted either, should be "Testing write a new value here."
            context.Response.ClientId2 = "Testing write a new value here.";

            return Task.CompletedTask;
        }
    }

    public class Validator : Validator<Request>
    {
        public Validator()
        {
            RuleFor(req => req).NotEmpty().WithMessage("Request must not be empty.");
            RuleFor(req => req.ClientId).NotEmpty().WithMessage("Request must contain a Client ID.");
        }
    }

    public class Response
    {
        public string ClientId { get; set; }
        public string ClientId2 { get; set; }
    }
}
```

In the response body, I expect:

```json
{
   "ClientId": "8BDEC71I",  // Expected encoded value
   "ClientId2": "Testing write a new value here."  // Expected new value
}
```

However, the actual response is:

```json
{
   "ClientId": "12345",  // The value remains decoded (incorrect)
   "ClientId2": null  // This value is not persisted (incorrect)
}
```

**Additional Details**

•	The PreProcessor works as intended, successfully decoding the incoming value.
•	The issue occurs in the PostProcessor, where:
  ••	The ClientId value should be re-encoded but isn’t.
  ••	The newly assigned value for ClientId2 is not persisted.

**Relevant Code**

The endpoint is configured as follows:

```csharp
public class Endpoint : Endpoint<Request, Response>
{
    public override void Configure()
    {
        Get("/client/list");
        Version(1, deprecateAt: 2);
        PreProcessor<PreProcessor>();
        PostProcessor<PostProcessor>();
    }

    public override async Task HandleAsync(Request request, CancellationToken ct)
    {
        // Processing request before sending response
        var response = new Response
        { 
            ClientId = result.ClientId
        };

        await SendAsync(response, cancellation: ct);
    }
}
```

**Expected Behavior**

•	The PostProcessor should re-encode the ClientId (from “12345” to “8BDEC71I”).
•	The value assigned to ClientId2 should be persisted in the response.

**Actual Behavior**

•	The ClientId remains decoded (“12345”).
•	The ClientId2 value is not persisted (remains null).

**Comment by dj-nitehawk** [comment]
post processors are executed after the endpoint handler sends the response. so modifying the response dto from a post processor won't have the expected effect here.

you could however achieve it if you put a post processor in charge of sending the response as [done here](https://gist.github.com/dj-nitehawk/6e23842dcb7640b165fd80ba57967540). you don't necessarily have to use the results pattern.

**Comment by dj-nitehawk** [comment]
alternatively you might be able to utilize the [IEndpointFilter](https://gist.github.com/dj-nitehawk/3edcd59ce03230b98369e2f2259bc5d3)s that were introduced in .net 7
