### ISSUE TITLE
When exporting swagger.json with exportswaggerjson, server part is omited.

### ISSUE THREAD

**Issue by dziedrius** [FastEndpoints/FastEndpoints#774]
If I start application and go to swagger.json file, I see server section as expected:
```
"servers": [
    {
      "url": "http://localhost:5050"
    }
  ],
```
If I export this file using
```
dotnet run --exportswaggerjson true
```
It does not have that section.
Also I could not find example, how could I add manually additional servers to OpenAPI spec when configuring FastEndpoints?

**Comment by dj-nitehawk** [comment]
looks like nswag doesn't add servers by default when the swagger doc is exported.
so you'll have to add your own document processor such as the following to get it done:
```cs
sealed class DocProcessor : IDocumentProcessor
{
    public void Process(DocumentProcessorContext ctx)
    {
        ctx.Document.Servers.Add(new() { Url = "https://my.company.com" });
    }
}

.SwaggerDocument(d => d.DocumentSettings = s => s.DocumentProcessors.Add(new DocProcessor()));
```

also have a look at [this gist](https://gist.github.com/dj-nitehawk/ba223a3dd415407a3e664a4a2b61dbc7) for other related customizations. 

note: the `PostProcess` func is not executed during swagger.json export.

**Comment by dziedrius** [comment]
@dj-nitehawk, thanks, this was useful.
