### ISSUE TITLE
[UsedImplicitly] attribute usages are not present in NuGet package

### ISSUE THREAD

**Issue by sirduke** [FastEndpoints/FastEndpoints#775]
`[UsedImplicitly]` attribute, which is applied to `Endpoint`, `EndpointWithMapper` and others, is erased from the compiled dll because it is `[Conditional("JETBRAINS_ANNOTATIONS")]`. This causes false positive warnings about unused types in JetBrains Rider and Resharer like described in #191

**Comment by dj-nitehawk** [comment]
check the attached freshly scaffolded project.
[Repro.zip](https://github.com/user-attachments/files/17127220/Repro.zip)

i don't see any compiler warnings in rider with that project:

![screen-record-1727250218](https://github.com/user-attachments/assets/266811b7-6bcf-465b-9bcc-38ee380a229f)

the jetbrains documentation says to use `[Conditional("JETBRAINS_ANNOTATIONS")]`:

[![image](https://github.com/user-attachments/assets/6643355d-719f-4f57-bae3-1c9da6851b61)](https://www.jetbrains.com/help/resharper/Code_Analysis__Annotations_in_Source_Code.html#embedding-declarations-of-code-annotations-in-your-source-code)

**Comment by sirduke** [comment]
No warning is shown for `Endpoint` in the repro solution because the type is explicitly used in tests and in generated code:
![image](https://github.com/user-attachments/assets/f18d4a2d-29f3-4ff4-9026-697a0ab9c338)
If another endpoint is added which is not explicitly used then a warning "class is never used" is shown:
![image](https://github.com/user-attachments/assets/26f9c2c1-ea1e-49ce-b106-821dd9d75b5d)
The section of JetBrains documentation referenced pertains to the internal use of JetBrains.Annotations when developing a library. Applying `UsedImplicitly` to Endpoint base classes seems intended for external users of the NuGet package, but they cannot benefit from it if the annotations are removed during compilation.

**Comment by dj-nitehawk** [comment]
right! 
my bad...
fixed in `v5.29.0.11-beta`
