### ISSUE TITLE
FastEndpoints was unable to find any endpoint declarations!

### ISSUE THREAD

**Issue by rpbs** [FastEndpoints/FastEndpoints#777]
Hey all, I'm new at FastEndpoints and I think the project is awesome. 

However, I followed the sample from the projects page and I'm getting this exception.

![image](https://github.com/user-attachments/assets/e49f8768-a5d1-4aff-9b26-313d56fa24a3)

If you noticed my solution explorer, the files are the same from the sample of the projects page **(https://fast-endpoints.com/).**

What am I missing ?

Thanks

**Comment by rpbs** [comment]
Closing it, now I realize I should not create a project name containing "FastEndpoints"

**Comment by dj-nitehawk** [comment]
here's an alternative: https://gist.github.com/dj-nitehawk/b3615fad393beabefe929e3f81af6822

**Comment by rpbs** [comment]
> here's an alternative: https://gist.github.com/dj-nitehawk/b3615fad393beabefe929e3f81af6822

That's a lot better, thanks
