### ISSUE TITLE
Question about unit testing groups and policies

### ISSUE THREAD

**Issue by Iceeman76** [FastEndpoints/FastEndpoints#780]
Hi folks!

Using the following Configure override:

```cs
public override void Configure()
{
    Post("/user/users");
    Version(1);
    Group<MyGroup>();
    Policy(policyBuilder => policyBuilder.RequireAssertion(async context => await permission.PermissionHandler(context, new PermissionRequirement(UserRepositoryKey, PermissionLevel.Write))));
}
```

Is it possible, and if so, how can I write a unit test that verifies the group and policy if I create the endpoint by doing Factory.Create<MyEndpoint>()?

**Comment by dj-nitehawk** [comment]
a unit test is not the right choice for this scenario.
see https://github.com/FastEndpoints/FastEndpoints/issues/581#issuecomment-1910588226 for an explanation why.
