### ISSUE TITLE
Error Handling in FastEndpoints does not work

### ISSUE THREAD

**Issue by diem1783** [FastEndpoints/FastEndpoints#781]
I am trying to handle errors globally in my project. I hate the idea to have try-catch in each endpoint.

I have the following endpoint for testing:

```cs
public sealed class Endpoint(SepukuDbContext dbContext, IJwtTokenService jwtTokenService, IUserAuthorizationService userAuthorizationService) : Endpoint<Request>
{
    public override async Task HandleAsync(Request req, CancellationToken ct)
    {
        var user = await dbContext.Users.Where(x => x.Email == req.Email).Select(x => x).SingleOrDefaultAsync(ct);

        if (user is null)
        {
            ThrowError("The supplied credentials are invalid!");
            return;
        }

        if (userAuthorizationService.IsAuthorized(user, req.Password))
        {
            await SendAsync(
                    new
                    {
                        Username = user.Name,
                        Token = jwtTokenService.GetToken(user),
                    });
        }
        else
        {
            ThrowError("The supplied credentials are invalid!");
        }
    }
}
```

To test the error handling, jwtTokenService.GetToken(user) throws InvalidDataException. However, the endpoints returns 200 Response.Ok. Why?

I added app.UseDefaultExceptionHandler() for global error handling, but it did not help.

**Comment by dj-nitehawk** [comment]
i can't replicate your problem.
can you update the following repro project to show your issue and send it back?
[Repro.zip](https://github.com/user-attachments/files/17219380/Repro.zip)

**Comment by diem1783** [comment]
Sorry, I will be more specific. I created Postprocessor for my endpoint. It looks as follows:

    public Task PostProcessAsync(IPostProcessorContext context, CancellationToken ct)
    {
        var user = GetUser(context.HttpContext);
        var endpointName = context.HttpContext.GetEndpoint()?.DisplayName;
        
        if (!context.ValidationFailures.IsNullOrEmpty())
        {
            foreach (var failure in context.ValidationFailures)
            {
                logger.LogError("[Post-Processor] {timestamp}: Validation failed for endpoint '{endpointName}'. Error: {errorMessage}. User: {user}", DateTime.UtcNow, endpointName, failure.ErrorMessage, user);
            }
        }
        else if (context.HttpContext.Response.StatusCode >= 400)
        {
            logger.LogError("[Post-Processor] {timestamp}: Endpoint '{endpointName}' returned status code {statusCode}. User: {user}", DateTime.UtcNow, endpointName, context.HttpContext.Response.StatusCode, user);
        }
        else
        {
            logger.LogInformation("[Post-Processor] {timestamp}: Endpoint '{endpointName}' completed successfully. User: {user}", DateTime.UtcNow, endpointName, user);
        }

        return Task.CompletedTask;
    }

The question is. When I invoke InvalidDataException, why in postprocessor seecontext.HttpContext.Response.StatusCode equal to 200 Response and Response in Swagger is 500 - Internal Server Error? I expected StatusCode 400 everywhere.

**Comment by dj-nitehawk** [comment]
your post-processor just needs to do the following:

```cs
        // handle internal server errors
        if (context.HasExceptionOccurred)
        {
            logger.LogCritical(
                context.ExceptionDispatchInfo.SourceException,
                "[Post-Processor] {timestamp} An Unhandled exception occurred in endpoint '{endpointName}'",
                DateTime.UtcNow,
                endpointName);

            //need to set 500 here because code below is checking for status code
            context.HttpContext.Response.StatusCode = 500;
        }
```

[documentation](https://fast-endpoints.com/docs/pre-post-processors#handling-unhandled-exceptions-with-post-processors) shows an example of a post-processor that handles 500 internal server errors.

updated project: [Repro.zip](https://github.com/user-attachments/files/17220594/Repro.zip)

**Comment by diem1783** [comment]
Thanks, I will definitelly try it. My question is, which approach is better? Use preprocessor to log errors or use error handler?

**Comment by dj-nitehawk** [comment]
i think that's a personal preference.
either should be fine.
