### ISSUE TITLE
Does IAuthorizationFilter Attribute work with FastEndpoint?

### ISSUE THREAD

**Issue by lucasfogliarini** [FastEndpoints/FastEndpoints#784]
How can I implement my IAuthorizationFilter attribute correctly on a FastEndpoints endpoint?

**Comment by dj-nitehawk** [comment]
`IAuthorizationFilter` does not exist in the asp.net minimal api world.
the closest you get is [IEndpointFilter](https://learn.microsoft.com/en-us/aspnet/core/fundamentals/minimal-apis/min-api-filters?view=aspnetcore-8.0).
here's an [example](https://gist.github.com/dj-nitehawk/3edcd59ce03230b98369e2f2259bc5d3) endpoint filter being used with fastendpoints.
