### ISSUE TITLE
Allow curly braces in route parameters

### ISSUE THREAD

**Issue by steinhilber** [FastEndpoints/FastEndpoints#788]
Hi,
I'm having trouble with the default request binder.

My request contains curly braces in the route (e.g. `/api/items/{123-456}`). 
Unfortunately I cannot remove these curly braces because these ids are generated by an external system.

It looks like the default request binder is not able to parse them, the related property in my request object is always set to null.

In the `RequestBinder` there is a special handling for curly braces:
https://github.com/FastEndpoints/FastEndpoints/blob/49e85726c0ff6730bfc6e0b0f2ebbb22c20e5fc7/Src/Library/Binder/RequestBinder.cs#L308

Are curly braces in route parameters not supported by design or is this a bug?

**Comment by dj-nitehawk** [comment]
should be sorted in `v5.30.0.6-beta`
give that a go and report back pls.
thanks!

**Comment by steinhilber** [comment]
It works. Thank you!
