### ISSUE TITLE
Integration tests does not work

### ISSUE THREAD

**Issue by diem1783** [FastEndpoints/FastEndpoints#789]
Hello,

I am trying to do integration tests over one endpoint using one service. Since, it works with database, I use MemoryDb for this purpose.
My code is as follows:

```
[DisableWafCache]
public class SepukuFixture : AppFixture<Program>
{
    protected override Task SetupAsync()
    {
        // place one-time setup code here
        return Task.CompletedTask;
    }

    protected override void ConfigureApp(IWebHostBuilder a)
    {
        a.UseStartup<Program>();
    }

    protected override void ConfigureServices(IServiceCollection s)
    {
        s.AddDbContext<SepukuDbContext>(options =>
        {
            options.UseInMemoryDatabase("TestDb"); 
        });

        s.AddScoped<IJwtTokenService, JwtTokenService>();
        s.AddScoped<IUserAuthorizationService, UserAuthorizationService>();
    }

    protected override Task TearDownAsync()
    {
        // do cleanups here
        return Task.CompletedTask;
    }
}
```

```
public class LoginTests(SepukuFixture app, IJwtTokenService jwtTokenService) : TestBase<SepukuFixture>
{
    [Fact, Priority(1)]
    public async Task Empty_User_Input()
    {
        var (response, result) = await app.Client.POSTAsync<LoginEndpoint, LoginRequest, ProblemDetails>(new LoginRequest()
        {
            Email = string.Empty,
            Password = string.Empty
        });
        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        result.Errors.Count().Should().Be(2);
        result.Errors.Select(e => e.Name).Should().Equal("Email address is required!", "Password is required!");
    }

    [Theory, Priority(2)]
    [InlineData("x@x.com", "x", "X X")]
    [InlineData("y@y.com", "y", "Y Y")]
    public async Task Valid_User_Found(string email, string password, string fullName)
    {
        var (response, result) = await app.Client.POSTAsync<LoginEndpoint, LoginRequest, LoginResponse>(new LoginRequest()
        {
            Email = email,
            Password = password
        });

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        result.Should().NotBeNull();
        result.Username.Should().Be(fullName); 
        result.Token.Should().NotBeNullOrEmpty();

        var isValidToken = await jwtTokenService.ValidateTokenAsync(result.Token, CancellationToken.None);
        isValidToken.Should().BeTrue();
    }
}
```

When I start the tests, I am getting following error:
System.InvalidOperationException : Can't find '.....\bin\Debug\net8.0\testhost.deps.json'. 
This file is required for functional tests to run properly. There should be a copy of the file on your source project bin folder. 
If that is not the case, make sure that the property PreserveCompilationContext is set to true on your project file. E.g '<PreserveCompilationContext>true</PreserveCompilationContext>'.
 For functional tests to work they need to either run from the build output folder or the testhost.deps.json file from your application's output directory must be copied to the folder 
 where the tests are running on. A common cause for this error is having shadow copying enabled when the tests run.

PreserveCompilationContext is set on true in the test project. The mentioned file readly does not exists. Any idea how to solve it?
Thanks

**Comment by dj-nitehawk** [comment]
most likely the same cause as [this discord post](https://discord.com/channels/933662816458645504/1247983349268611072).

try to fully qualify your `Program` class:

```cs
public class SepukuFixture : AppFixture<Full.Namespace.To.Program> { ... }
```

if that doesn't help, i'm gonna need a minimalistic/debuggable repro project to check. you can zip it up and attach here.

**Comment by diem1783** [comment]
Program.cs does not have any namespace. I could add to the file empty class, but it is pretty ugly solution.

Also, I found out, that "UseStartup" can not be used, since there is no Startup anymore. Is there any example using configuration from Program.cs?

**Comment by diem1783** [comment]
Thanks a lot for a help. However, I still have one problem. In Program.cs, I register dbcontext for PostgresSQL database. In fixture, I am trying to replace this dbcontext with dbcontext for InMemory database. However, replacement does not work (registering new dbcontext does not override old dbcontext). Why? Should not it work? Only way I found is to remove dbcontext for PostgreSQL and then register dbcontext for InMemory. My code is as follows:

```
[DisableWafCache]
public class MyFixture : AppFixture<Program>
{
    protected override void ConfigureServices(IServiceCollection s)
    {
        var descriptor = s.SingleOrDefault(d => d.ServiceType == typeof(DbContextOptions<MyDbContext>));
        if (descriptor != null)
        {
            s.Remove(descriptor);
        }

        s.AddDbContext<MyDbContext>(options => options.UseInMemoryDatabase("TestDb"));

        var context = s.BuildServiceProvider().GetService<MyDbContext>();
        if (context is not null)
        {
            context.Users.Add(...), 
            context.Users.Add(...);
            context.SaveChanges();
        }
    }
}
```
