### ISSUE TITLE
FastEndpoints.Generator is Error on Version 5.30.0 DiscoveryTypes is not 

### ISSUE THREAD

**Issue by jveko** [FastEndpoints/FastEndpoints#790]
Hi,
I have some trouble when using latest version (5.30.0) of FastEndpoints.Generator, i always got this 

![image](https://github.com/user-attachments/assets/d3446575-7428-4221-a16c-6353da8a90b9)

but when i use version 5.27.0 it perfectly fine

is that bug or something i missing?

**Comment by dj-nitehawk** [comment]
is your project targetting .net 9 by any chance?
source generation is currently broken in .net 9.
should get automatically sorted out when .net 9 comes out and/or rider/vs updates support for .net 9.

if that's not the case, please attach a minimalistic debuggable repro project with just 1 endpoint.

**Comment by jveko** [comment]
Hey i have a repro project in this zip you can try it 

[SourceGenRepro.zip](https://github.com/user-attachments/files/17301544/SourceGenRepro.zip)

**Comment by dj-nitehawk** [comment]
there's nothing wrong with the attached repro other than needing to expose the internal classes to the test project.
have a look: https://streamable.com/y9kj07

do you have any other source generators working on your system?
most likely you don't have the `.NET Compiler Platform SDK` .net workload installed.
see here: https://github.com/FastEndpoints/FastEndpoints/issues/117#issuecomment-1136891324

**Comment by dj-nitehawk** [comment]
first try the latest beta version.
and then post the output of `dotnet build` in your project folder.
you seem to be the only person who's having this problem. so i'm assuming it's something wrong in your environment.
do you have the latest rider version?

**Comment by jveko** [comment]
i try the latest stable version, and i use latest rider version too,

i attached vidio to reproduce the issue, [https://streamable.com/g4guk3](https://streamable.com/g4guk3)

**Comment by dj-nitehawk** [comment]
i can see that the source generator is actually working and produced the `DiscoveredTypes` static class with the correct data. your project for some reason can't seem to find it. can you try fully qualifying it like `FEExample.Application.DiscoveredTypes.All` and see if that does it.

if not, can you scaffold a new project with `dotnet new feproj -n SourceGenRepro` and take a video of that and send me?

also, try deleting the `bin` and `obj` folders from all the projects in your solution. and also invalidate caches in rider and restart the ide.

**Comment by jveko** [comment]
I already try all possible solution from you, no one works, 
this the vidio from the feproj https://streamable.com/m89n15
and this the source code of project SourceGenRepro 
[SourceGenRepro.zip](https://github.com/user-attachments/files/17554207/SourceGenRepro.zip)

**Comment by dj-nitehawk** [comment]
your rider is definitely messed up somehow. the attached project builds and runs perfectly fine on 2 of my computers.
what happens when you do `dotnet build` in a terminal/cmd without using an ide? if it builds without any errors, then that's the confirmation that rider is to blame. if it has build errors in the terminal, post them here.

**Comment by jveko** [comment]
Thank you very much @dj-nitehawk. My problem resolved now, i used to upgrade my dotnet, and change the MSBuild to a newer version (.net 9 rc2)

**Comment by dj-nitehawk** [comment]
great 👍
