### ISSUE TITLE
ProblemDetails discrepancy between Status Code and the Type RFC section

### ISSUE THREAD

**Issue by BinaryAlley** [FastEndpoints/FastEndpoints#793]
`FastEndpoints.ProblemDetails` class offers constructor overloads that allow specifying a custom HTTP status code like so:

```csharp
public ProblemDetails(IReadOnlyList<ValidationFailure> failures, int? statusCode = null)
{
    Initialize(failures, null!, null!, statusCode ?? Cfg.ErrOpts.StatusCode);
}

public ProblemDetails(IReadOnlyList<ValidationFailure> failures, string instance, string traceId, int statusCode)
{
    Initialize(failures, instance, traceId, statusCode);
}
```

but the `Type` property is read-only and set by default to point to the RFC section for HTTP [Bad Request](https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1):

```csharp
[DefaultValue("https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1")]
public string Type => Cfg.ErrOpts.ProblemDetailsConf.TypeValue;
```

This can lead to discrepancies in the returned ProblemDetails, with a structure like this:

```json
{
  "type": "https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 422,
  "instance": "/api/v1/path/get-path-root",
  "traceId": "0HN7BKACQR052:00000001",
  "errors": [
    {
      "name": "ValidationFailure",
      "reason": "Path must not be empty"
    }
  ]
}
```
where the HTTP status code is set to [Unprocessable Entity](https://www.rfc-editor.org/rfc/rfc4918#section-11.2), but the type is still pointing to RFC Bad Request section. The library should either update the referenced section internally, based on the provided status code, or should not allow specifying a different status code, if the `Type` must continue to point to Bad Request.

**Comment by dj-nitehawk** [comment]
implemented in `v5.30.0.8-beta`

![image](https://github.com/user-attachments/assets/15a0177b-17bf-4be7-8232-69266de3e302)
