### ISSUE TITLE
Integration tests - fixture issue

### ISSUE THREAD

**Issue by diem1783** [FastEndpoints/FastEndpoints#797]
I still have one problem with Fixtures. In Program.cs, I register dbcontext for PostgresSQL database. In fixture, I am trying to replace this dbcontext with dbcontext for InMemory database. However, replacement does not work (registering new dbcontext does not override old dbcontext). Why? Should not it work? Only way I found is to remove dbcontext for PostgreSQL and then register dbcontext for InMemory. My code is as follows:

```
[DisableWafCache]
public class MyFixture : AppFixture<Program>
{
    protected override void ConfigureServices(IServiceCollection s)
    {
        var descriptor = s.SingleOrDefault(d => d.ServiceType == typeof(DbContextOptions<MyDbContext>));
        if (descriptor != null)
        {
            s.Remove(descriptor);
        }

        s.AddDbContext<MyDbContext>(options => options.UseInMemoryDatabase("TestDb"));

        var context = s.BuildServiceProvider().GetService<MyDbContext>();
        if (context is not null)
        {
            context.Users.Add(...), 
            context.Users.Add(...);
            context.SaveChanges();
        }
    }
}
```

**Comment by dj-nitehawk** [comment]
you seem to be on the right track: https://github.com/FastEndpoints/FastEndpoints/issues/666#issuecomment-2080411317
worst case scenario, try this: https://github.com/FastEndpoints/FastEndpoints/issues/666#issuecomment-2350417311
