### ISSUE TITLE
Condition of JsonIgnore is ignored

### ISSUE THREAD

**Issue by vzam** [FastEndpoints/FastEndpoints#798]
Sometimes I don't want to send a full DTO when most of it is null so I would like to use `[JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]` but FastEndpoint removes these properties from the docs, which is not the intended thing when there is a condition. I would expect it to be removed only when the `JsonIgnore` has no condition. Related code:

https://github.com/FastEndpoints/FastEndpoints/blob/a672b64081805e6f883cda9db0da06f6d756690a/Src/Swagger/OperationProcessor.cs#L303C4-L303C9

**Comment by dj-nitehawk** [comment]
check out `v5.30.0.10-beta`
should be sorted now...
