### ISSUE TITLE
Same fixture for more testing classes

### ISSUE THREAD

**Issue by diem1783** [FastEndpoints/FastEndpoints#802]
My fixture looks as follows:

```cs
[DisableWafCache]
public class SepukuFixture : AppFixture<Program>
{
    private SepukuDbContext? _context;

    protected override void ConfigureServices(IServiceCollection s)
    {
        var descriptor = s.SingleOrDefault(d => d.ServiceType == typeof(DbContextOptions<SepukuDbContext>));
        if (descriptor is not null)
        {
            s.Remove(descriptor);
        }

        s.AddDbContext<SepukuDbContext>(options =>
           options.UseSqlite("DataSource=file::memory:?cache=shared").UseLazyLoadingProxies());

        _context = s.BuildServiceProvider().GetService<SepukuDbContext>();
        if (_context is not null)
        {
            _context.Database.OpenConnection();
            _context.Database.EnsureCreated();

            SeedDatabase();
        }
    }
}
```

I am trying to use the fixture in more testing classes, however I am getting the error that data are already in db. How to solve this issue? I tried to add method TearDownAsync, but it is executed after each test, not after testing class is done. I also tried to add condition _context is null int method ConfigureServices, but without any impact.

**Comment by dj-nitehawk** [comment]
sorry about the delay. i tried to replicate this with the limited context provided above but could not.
can you throw together a small repro project and attach here pls?
thanks!
