### ISSUE TITLE
[Feature Request] Polymorphism with TypedResults

### ISSUE THREAD

**Issue by SpaceOgre** [FastEndpoints/FastEndpoints#807]
I want to have an endpoint return a polymorphic response. I thought that I could do that using the TypedResults and defining the Results like this:

```c#
Results<Ok<SubAreaContractProfileData>, Ok<DirectProcurementContractProfileData>, NotFound>
```

But in the Swagger only the last `Ok` model i shown, I expected both to be shown using the oneOf support of swagger.

There is no problem with return the JSON, it looks as it should, so it is only a problem with swagger.

If I add this: 

```c#
[JsonPolymorphic(TypeDiscriminatorPropertyName = "_t")]
[JsonDerivedType(typeof(SubAreaContractProfileData), "a")]
[JsonDerivedType(typeof(DirectProcurementContractProfileData), "o")]
```

The Swagger schema looks like this:
![image](https://github.com/user-attachments/assets/f66d1e8f-dc5d-45ee-95f0-12d78864c2e1)
So the nesting is wrong, I guess since I don't have the base class as return?

If I change to HandleAsync and use the base class as return the swagger looks like it should.

So I guess this is a feature request (if it is possible) to add support for polymorphism for typed results without the JsonPolymorphic attributes.

**Comment by dj-nitehawk** [comment]
i believe [this is](https://gist.github.com/dj-nitehawk/8a938ac7edb1ac840ed0601121d557ea) what you're after? maybe?

> support for polymorphism for typed results without the JsonPolymorphic attributes

i don't think that's going to work because STJ (the serializer) won't work without the correct attribute annoations.

**Comment by dj-nitehawk** [comment]
looked into this a bit more and it seems to be producing the correct `oneOf` schema when used like this:
```cs
var bld = WebApplication.CreateBuilder(args);
bld.Services
   .AddFastEndpoints()
   .SwaggerDocument(c => c.UseOneOfForPolymorphism = true);

var app = bld.Build();
app.UseFastEndpoints()
   .UseSwaggerGen();
app.Run();

[
    JsonPolymorphic,
    JsonDerivedType(typeof(Dog), nameof(Dog)),
    JsonDerivedType(typeof(Cat), nameof(Cat))
]
public class Animal
{
    public string Name { get; set; }
}

public class Dog : Animal
{
    public string Breed { get; set; }
}

public class Cat : Animal
{
    public bool IsIndoor { get; set; }
}

sealed class MyEndpoint : EndpointWithoutRequest<Results<Ok<Animal>, NotFound>>
{
    public override void Configure()
    {
        Post("test");
    }
}
```
![image](https://github.com/user-attachments/assets/cd86207e-0b2d-4198-b701-eddb6bffe4ff)

**Comment by SpaceOgre** [comment]
What I would like is for the swagger to look like this:
![image](https://github.com/user-attachments/assets/10c2edf0-d28b-46bc-ad2a-b99e38d97d20)

Part of the swagger doc (here I have manually changed the 200 response to a oneOf array) to make it look like above:
```json
    "/contracts/{contractId}": {
      "get": {
        "tags": [
          "Contracts"
        ],
        "summary": "Get basic contract information for profile page",
        "operationId": "GetContractProfileEndpoint",
        "parameters": [
          {
            "name": "contractId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "X-XSRF-TOKEN",
            "in": "header",
            "description": "Antiforgery Token",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "oneOf": [
                    { "$ref": "#/components/schemas/SubAreaContractProfileData" },
                    { "$ref": "#/components/schemas/DirectProcurementContractProfileData"}
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
```

Atm the Swagger docs look like this when using the solution of Json attributes and setting the base class as the return type:
```json
"/contracts/{contractId}": {
      "get": {
        "tags": [
          "Contracts"
        ],
        "summary": "Get basic contract information for profile page",
        "operationId": "GetContractProfileEndpoint",
        "parameters": [
          {
            "name": "contractId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "X-XSRF-TOKEN",
            "in": "header",
            "description": "Antiforgery Token",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ContractProfileData"
                }
              }
            }
          },
          "404": {
            "description": "Not Found"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ProblemDetails"
                }
              }
            }
          }
        }
      }
    },
```

So, I would like something like this:
If the endpoint has multiple Ok results change the `$ref` to `oneOf` with a list of all `$ref`

As a bonus it would be nice to be able to manually config the discriminator property 😄 

In my case the STJ support is not needed since I will not deserialize the response model and the frontend app reading the API can type check against a custom property.

**Comment by dj-nitehawk** [comment]
huh... you seem to right...
just read the OAS3.0 spec and that's how it's supposed to look like for polymorphic responses.
wonder why nswag is doing it this way 🤔
will investigate what we can do to correct that...

do you know if the new ms openapi package is doing it correctly?

**Comment by SpaceOgre** [comment]
I don't know but will check 😄

I guess NSwag might do it like that either for legacy resons, I think this is new for OAS3.0 and did not work like this for Swagger 2.
Or the NSwag support might be before they introduced TypedResults and thus it you hade to return the base type unless they depended on a DU 3-party library?

**Comment by SpaceOgre** [comment]
I have now tested MS new OpenAPI package and that does the same as NSwag, if defined like this:

```c#
Results<Ok<WeatherForecast>, Ok<WeatherForecast[]>> GetWeatherForecast()
{
    bool returnSingle = /* your condition here */ true; // Replace with actual condition

    if (returnSingle)
    {
        var singleForecast = new WeatherForecast
        (
            DateOnly.FromDateTime(DateTime.Now),
            Random.Shared.Next(-20, 55),
            summaries[Random.Shared.Next(summaries.Length)]
        );
        return TypedResults.Ok(singleForecast);
    }
    else
    {
        var forecast = Enumerable.Range(1, 5).Select(index =>
            new WeatherForecast
            (
                DateOnly.FromDateTime(DateTime.Now.AddDays(index)),
                Random.Shared.Next(-20, 55),
                summaries[Random.Shared.Next(summaries.Length)]
            ))
            .ToArray();
        return TypedResults.Ok(forecast);
    }
}
```
Only the last `Ok<>` model will be added as response.

If instead I use the `JsonDerivedType` on the base class and return that it looks like this:
![image](https://github.com/user-attachments/assets/4ccf51b2-c4a0-43e0-bd60-04ddcdd37905)
So they are using the anyOf instead of oneOf.

Might need to wait for real DU support in C# before MS fixes this on their side 😞

**Comment by dj-nitehawk** [comment]
can you try `v5.31.0.4-beta`.
should be sorted now.

**Comment by SpaceOgre** [comment]
Will try as soon as I can get the version from NuGet

**Comment by dj-nitehawk** [comment]
it's there: https://www.nuget.org/packages/FastEndpoints/5.31.0.4-beta

**Comment by SpaceOgre** [comment]
I'm getting a oneOf/allOf loop now:
![image](https://github.com/user-attachments/assets/e5c77d88-1783-475e-9d4f-8862457ea85b)

Code:
```c#
//endpoint
public override async Task<Results<Ok<ContractProfileData>, NotFound>> ExecuteAsync(CancellationToken ct)
{
       //other stuff here...

        if (contractData == null)
            return TypedResults.NotFound();

        if (contractData is SubAreaContractProfileData subAreaData)
        {
            return TypedResults.Ok((ContractProfileData)subAreaData);
        }
        else
        {
            contractData.Breadcrumbs.Add("Direktupphandling");
            return TypedResults.Ok(contractData);
        }
}


//Return records
[JsonPolymorphic(TypeDiscriminatorPropertyName = "_t")]
[JsonDerivedType(typeof(SubAreaContractProfileData), "a")]
[JsonDerivedType(typeof(DirectProcurementContractProfileData), "o")]
public record ContractProfileData : IProfileMetadata, IContainsBreadcrumbs
{
    public Guid Id { get; init; }
    public ContractStatus Status { get; init; }
    public string SupplierName { get; init; } = null!;
    public string OperationName { get; init; } = null!;
    public ChangeInfo ChangeInfo { get; init; } = null!;
    public List<string> Breadcrumbs { get; init; } = [];
}

public sealed record SubAreaContractProfileData : ContractProfileData, IContainsAdministrations, IContainsArticleValues, IContainsContacts
{
    public required ContractType Type { get; init; }
    public required string ContractNumber { get; init; }
    public required string ContractTemplateName { get; init; }
    public required string SubAreaName { get; init; }
    public required int? Ranking { get; init; }
    public required List<ArticleValueItem> ArticleValues { get; init; }
    public required List<Contact> Contacts { get; init; }
    public required List<AdministrationItem> Administrations { get; init; }
}

public sealed record DirectProcurementContractProfileData : ContractProfileData, IContainsAdministrations
{
    public required ContractType Type { get; init; }
    public required List<AdministrationItem> Administrations { get; init; }
}
```

And it still requires me to return the base class as the only return type instead of two `Ok<>`

**Comment by dj-nitehawk** [comment]
can you check if the generated swagger.json also has the problem or is it just the swagger ui that's causing it?

**Comment by SpaceOgre** [comment]
Hi, sorry it took so long for me to get back on this.

The response in the swagger.json looks good:
![image](https://github.com/user-attachments/assets/74f68fd8-1019-455d-921e-b699e4e0a79f)

But I think the problem the schemas for the types.
The base schema looks like this:
![image](https://github.com/user-attachments/assets/69623e1b-9219-4c25-8354-fb50212985ac)
It has it's own oneof.

And looking at DirectProcurementContractProfileData
![image](https://github.com/user-attachments/assets/0e053a89-10f5-479c-b281-ebddcac9e861)
It has an allof to the base type so i think this is where the loop comes from.

C# code is the same as my post above.

**Comment by maxwoedl** [comment]
I've run into the same issue as @SpaceOgre where i have cyclic dependencies because the base class has a `oneOf` field for all children. This leads to type issues when generating a typescript client from the swagger doc. Does anybody have a fix for that?
