### ISSUE TITLE
Unable to instantiate request struct

### ISSUE THREAD

**Issue by xxAtrain223** [FastEndpoints/FastEndpoints#809]
I upgraded from 5.30 to 5.31 and had tests fail with a NotSupportedException with Message `Unable to instantiate type without a constructor! Offender: [CreateLocationRequest]`. I tracked it down to the following snippet and that my `CreateLocationRequest` was a readonly record struct.

https://github.com/FastEndpoints/FastEndpoints/blob/9af53996d4319181b52d766fd558ea767e21aa58/Src/Library/Binder/BinderExtensions.cs#L97-L99

Turns out `GetConstructors` returns an empty array for structs without an explicit default constructor.

I was trying to use readonly record structs to minimize heap usage, but after more research, I should probably be using classes for Request and Response objects.

So, I'll be switching to classes, but I wanted to let you know others may have issues upgrading to 5.31. Feel free to close.

**Comment by dj-nitehawk** [comment]
fixed in `v5.31.0.1-beta`
however, you shouldn't blindly use structs as request dtos without proper benchmarking, because there's gonna boxing/unboxing involted.
