### ISSUE TITLE
Response polymorphism with attributes in base

### ISSUE THREAD

**Issue by Pt4r** [FastEndpoints/FastEndpoints#810]
Hello, 

I'm experiencing an issue when using polymorphism in the response models. Specifically, when I set properties in the base model to be fetched from the header and marked as optional (this happens _only_ when they are IsRequired = false), these header properties appear both in the header and the body. Here’s an example:

```csharp
public record BaseRequest 
{
    /// <summary>
    /// The Correlation ID
    /// </summary>
    [FromHeader("x-correlation-id", IsRequired = false)]
    public Guid CorrelationId { get; init; }
}

public record Request : BaseRequest 
{
     public string Action { get; init; } 
}
```
![image](https://github.com/user-attachments/assets/acf71cbf-3bbd-4882-83d6-9340104a1227)
![image](https://github.com/user-attachments/assets/b5c1e66e-7ef4-4b2b-8305-294abe196217)

In the generated Swagger documentation, the CorrelationId is correctly shown as a header parameter, but it also unexpectedly appears in the body.

```json
...
{
    "name": "x-correlation-id",
    "in": "header",
    "description": "The Correlation ID",
    "schema": {
        "type": "string",
        "format": "guid",
        "nullable": false
    }
}
...
"requestBody": {
    "x-name": "Request",
    "description": "",
    "content": {
        "application/json": {
            "schema": {
                "$ref": "#/components/schemas/Request"
            }
        }
    },
    "required": true,
    "x-position": 1
}
```

It seems like Swagger is duplicating the CorrelationId property by placing it in both the header and the body.

**Comment by dj-nitehawk** [comment]
setting `RemoveFromSchema` to `true` should do the trick:

```cs
    [FromHeader("x-correlation-id", IsRequired = false, RemoveFromSchema = true)]
    public Guid CorrelationId { get; init; }
```

let me know if that's not what you need and i'll look in to it further.

cheers!
