### ISSUE TITLE
SwaggerDocument a Fetch error when the DocumentName property is not set

### ISSUE THREAD

**Issue by jeffreymonroe** [FastEndpoints/FastEndpoints#811]
When defining a singular SwaggerDocument without a DocumentName, an error is thrown in the Swagger UI of "Fetch error". 

`    builder.Services.SwaggerDocument(o =>
    {
        o.DocumentSettings = s =>
        {
            s.DocumentName = "My Api v1.0"; // commenting this causes the error.
            s.Title = "My Api";
            s.Version = "v1.0";
        };
    });
`

I believe it has something to do with the default document "v1" already existing. If I uncomment the DocumentName property, I get two documents: v1 and My Api v1.0.

Can Swagger be defined through Swashbuckle instead of FastEndpoints?

**Comment by dj-nitehawk** [comment]
i believe something has gone wrong in your startup config.
can you try scaffolding a new project with the following and see if you can replicate the issue?
```cs
dotnet new install FastEndpoints.TemplatePack
dotnet new feproj -n ReproProject
```
if you can replicate it, please zip it up and attach here so i can have a look.

btw, we moved away from swashbuckle long time ago and i believe it has been deprecated now.
FE only has swagger support via nswag atm.

**Comment by dj-nitehawk** [comment]
you can't define more than one v1 docs as v1 is the default value if you don't specify anything. it was failing because you had an empty `.SwaggerDocument()` call which uses the v1 default value. do it like this, if you need multiple docs.
```cs
var bld = WebApplication.CreateBuilder(args);
bld.Services
   .AddFastEndpoints()
   .SwaggerDocument(
       o =>
       {
           o.DocumentSettings =
               s =>
               {
                   s.DocumentName = "v1"; //default is v1 if you don't specify it
                   s.Title = "My Api";
                   s.Version = "v1";
               };
       })
   .SwaggerDocument(
       o =>
       {
           o.DocumentSettings =
               s =>
               {
                   //s.DocumentName = "v1"; // can't have duplicate doc names like this
                   s.DocumentName = "v2";
                   s.Title = "My Api";
                   s.Version = "v2";
               };
       });

var app = bld.Build();
app.UseFastEndpoints()
   .UseSwaggerGen();
app.Run();
```
