### ISSUE TITLE
Changes to RequestBinder in 5.31 break polymorphic binding

### ISSUE THREAD

**Issue by mattjones0111** [FastEndpoints/FastEndpoints#812]
Using FastEndpoints v5.30 I implemented my own request-specific [RequestBinder](https://github.com/FastEndpoints/FastEndpoints/blob/v5.30/Src/Library/Binder/BinderExtensions.cs) that implements `IRequestBinder<ThingBase>` where ThingBase is an abstract class. The concrete type that gets bound is determined by a custom MIME type provided in the `Content-Type` header, like so...

Given the types `Thing1` and `Thing2` inherit from the abstract `ThingBase`...
- `Content-Type: application/vnd.thing-1.json` -> deserializes the body to an instance of `Thing1`.
- `Content-Type: application/vnd.thing-2.json` -> deserializes the body to an instance of `Thing2`. 

Now the changes in v5.31 have broken this behavior ([this line](https://github.com/FastEndpoints/FastEndpoints/blob/57c49429678ec891de3638785058729baec92b30/Src/Library/Binder/BinderExtensions.cs#L68) throws the exception at startup) because it cannot find a constructor on the base type, not unreasonably.

I can fix this by hobbling my contracts to make ThingBase instantiable, but I'd rather not. Any ideas for resolution?

Many thanks indeed.
Matt

**Comment by dj-nitehawk** [comment]
i tried to replicate the issue with the following, but i could not.
```cs
abstract class ThingBase
{
    [FromHeader]
    public int Id { get; set; }
}

sealed class ThingA : ThingBase
{
    public string IdA { get; set; }
}

sealed class ThingB : ThingBase
{
    public string IdB { get; set; }
}

sealed class ThingBinder : IRequestBinder<ThingBase>
{
    public async ValueTask<ThingBase> BindAsync(BinderContext ctx, CancellationToken ct)
    {
        await Task.CompletedTask;

        if (ctx.HttpContext.Request.Headers.TryGetValue("Id", out var id))
        {
            if (id == "1")
                return new ThingA { IdA = id.ToString() };
            if (id == "2")
                return new ThingB { IdB = id.ToString() };
        }

        throw new ArgumentException();
    }
}

sealed class MyEndpoint : Endpoint<ThingBase>
{
    public override void Configure()
    {
        Get("test");
        RequestBinder(new ThingBinder());
        AllowAnonymous();
    }

    public override async Task HandleAsync(ThingBase r, CancellationToken c)
    {
        await SendAsync(r);
    }
}
```

when registered with `RequestBinder(new ThingBinder());` it shouldn't go [here](https://github.com/FastEndpoints/FastEndpoints/blob/ee05defb0b5488e19edc876c3ec69076112436a1/Src/Library/Binder/BinderExtensions.cs#L73) at all. 

i suppose you're doing something else.

could you update my code to show how you're doing it so i can see the exception being thrown?

**Comment by mattjones0111** [comment]
Ah! I know why now. I was deriving from the concrete `RequestBinder<T>` not simply implementing the interface `IRequestBinder<T>`. It works now.

Thank you very much indeed. 🥇
