### ISSUE TITLE
Support custom empty requests with Endpoint<TRequest, TResponse>

### ISSUE THREAD

**Issue by lolhans** [FastEndpoints/FastEndpoints#814]
Hi, i just got started with FastEndpoints and am wondering why I cant work with Endpoint<MyRequest, MyResponse> class when my request does not have properties in it. I know, that there are other endpoint types like EndpointWithoutRequest for that. But i see, that it is working using: `public class MyEndpoint : Endpoint<EmptyRequest,EmptyResponse> { }` Similar to that, i also expect this to work the same way. Instead Swagger gives me a 500 error "Failed to load API definition." and the endpoint does not work anymore. 

Is there a way to achieve that? I don't know whats the difference between my own empty request and the EmptyRequest struct that comes with FastEndpoints. Any help here would be nice.

```
public class MyRequest
{
    // Leave this empty
}

public class MyResponse
{
    public string Message { get; set ; }
}

public class MyEndpoint : Endpoint<MyRequest, MyResponse>
{
    public override void Configure()
    {
        Get("/testrequest");
        AllowAnonymous();
    }

    public override async Task HandleAsync(MyRequest req, CancellationToken ct)
    {
        await SendAsync(new()
        {
            Message = "Hi from server"
        });
    }
}
```

**Comment by dj-nitehawk** [comment]
there's an undocumented setting for that:
```cs
app.UseFastEndpoints(c => c.Endpoints.AllowEmptyRequestDtos = true)
```
but, curious why exactly you need to use empty request dtos?

if it's just for consistency's sake, maybe the fluent generics approach would suffice?

```cs
class MyEndpoint : Ep.NoReq.Res<MyResponse>
```

**Comment by lolhans** [comment]
Thanks for providing this config. Using `app.UseFastEndpoints(c => c.Endpoints.AllowEmptyRequestDtos = true)` resolves the Swagger error. However making the request through `Post` with an empty request class does result `Error: response status is 415`. Making it through `Get` it works.

Yes, it is just for consistency's sake, so basically every endpoint follows the same structure.

**Comment by dj-nitehawk** [comment]
a global config to clear the default "accpets metadata" for endpoints with your empty request dto type should do the trick:
```cs
app.UseFastEndpoints(
       c =>
       {
           c.Endpoints.AllowEmptyRequestDtos = true;
           c.Endpoints.Configurator =
               ep =>
               {
                   if (ep.ReqDtoType == typeof(MyEmptyRequest))
                       ep.Description(x => x.ClearDefaultAccepts());
               };
       })
```
