### ISSUE TITLE
How do set / pass Instance of T that can be resolved in Resolve<TService>() ?

### ISSUE THREAD

**Issue by risogolo** [FastEndpoints/FastEndpoints#818]
I have mapper that derives from Mapper class, 
I need to set Instance in unit test to be able to resolve it by calling

```
public override ResponseType ToEntity(RequestType request)
{
    var instance = Resolve<T>();
```
    
    
    so then I can create Instance of Mapper in unit test and call ToEntity
    this issue is that I am getting "Service resolver is null! Have you done the unit test setup correctly?" I do not know how to set that

**Comment by dj-nitehawk** [comment]
have you seen this part from the docs?

![image](https://github.com/user-attachments/assets/c543b0df-42b4-4401-84d3-d92634f40cfc)

let me know if that doesn't help and i'll look in to it further.

**Comment by risogolo** [comment]
I got it, I need to create mapper instance via Factory.CreateMapper
