### ISSUE TITLE
Question about permissions 

### ISSUE THREAD

**Issue by scharada** [FastEndpoints/FastEndpoints#823]
Hi there. thank you for your great work and for sharing :)

in my scenario, i have to use HasPermission attribute for my endpoints. since i used to have controllers , i do restrict access to the controller as a whole, then if permission is granted, i also check for each of the functions exposed which gives the following:
```cs
[HasPermission ("TestModule")]
class Testcontroller : base controller
{
     [HasPermission("View")]
     public Task<Result> Get(){ ... }

     [HasPermission("Save")]
     public Task<Result> Save(){ ... }

     [HasPermission("DoThis")]
     public Task<Result> DoThis(){ ... }
}
```
i need to make sure a call to a custom Auth api is made every time a permission is verified.

how can i create scenario this using FE and the current permission attribute ?

thank you.

**Comment by dj-nitehawk** [comment]
the `HasPermission` attribute [in fastendpoints](https://fast-endpoints.com/docs/model-binding#has-permissions) is just a convenience to automatically bind a boolean property to `true` if the current user principal has a particular claim. it's not meant as a security feature and is more of a modelbinding feature. 

for denying access for requests that don't have the right permission claims, you can use the `Permission()` method within the endpoint configuration as [explained here](https://fast-endpoints.com/docs/security#endpoint-authorization).

let me know if you need further help, after reading the docs.

**Comment by scharada** [comment]
@dj-nitehawk  thank you. i did not pay attention to that part of the doc. i'll give it a shot.
