### ISSUE TITLE
Changed behaviour with EndpointWithoutRequest

### ISSUE THREAD

**Issue by delasource** [FastEndpoints/FastEndpoints#825]
I just upgraded to the most recent version (from 5.20) and stumbled across a problem.
I have a lot of "EndpointWithoutRequest" Endpoints, where i just access the Route-Parameters, as you can see in the image. But just now as i upgraded, the Route variable contains a weird string, causing all endpoints to stop working properly.

![CleanShot_2024-11-17_234049](https://github.com/user-attachments/assets/ffb5d640-2185-4247-9165-74c7d15c0953)

I use the Typescript generated client, maybe there is a problem.

I fixed it by simply adding a Request-Type (inherit from `Endpoint<XxRequest, ...` instead of `EndpointWithoutRequest<...` ) that has a string property with the same name `UserName`. This of course changes the generated Typescript code.

**Comment by dj-nitehawk** [comment]
i believe the following is the answer for you: https://github.com/FastEndpoints/FastEndpoints/issues/759#issuecomment-2348137673

somewhere along the way, `UsePropertyNamingPolicy = true` was made the default which is causing your issue.
setting it to `false` or updating your route param names to match the property naming policy should do the trick.

if that doesn't do it, please update the attaced repro and send back so i can investigate further.

thanks!

[Repro.zip](https://github.com/user-attachments/files/17800303/Repro.zip)
