### ISSUE TITLE
v5.31.0 routing breaking change

### ISSUE THREAD

**Issue by dmalovric** [FastEndpoints/FastEndpoints#826]
Consider the following Endpoint, Request DTO and Validator:

````
public class Endpoint : Endpoint<Request>
{
    public override void Configure()
    {
        Verbs(Http.PUT);
        Routes("test/{Payload}");
        Version(1);
        AllowAnonymous();
    }
    ...
}

public sealed record Request(string Payload);

public sealed class Validator : Validator<Request>
{
    public Validator()
    {
        RuleFor(x => x.Payload).NotEmpty();
    }
}
````

A simple test to trigger the validation of the Payload property:
````
[Fact]
public async Task BadRequest_NullPayload()
{
    //  Arrange
    var request = new Request(null!);

    //  Act
    var response = await Fixture.Client.PUTAsync<Endpoint, Request>(request);

    //  Assert
    response.StatusCode.Should().Be(System.Net.HttpStatusCode.BadRequest);
}
````

With version 5.30.0 the test passes, but in 5.31.0 it fails because the Status Code returned is actually 404 instead of 400.

**Comment by dj-nitehawk** [comment]
this scenario should now be better handled in `v5.31.0.14-beta`.
i.e. if it's a required route param, you won't be able to submit the requesest with a `null` value for the required parameter.
have a look at the following test:

https://github.com/FastEndpoints/FastEndpoints/blob/34ebe062156ad43e2f849af3ae4170d474a3f0ac/Tests/IntegrationTests/FastEndpoints/EndpointTests/EndpointTests.cs#L105-L115

to be able to submit a `null` value, you must now make the route parameter optional such as: `test/{Payload?}`, in which case you can successfully submit a null value like the following test is doing:

https://github.com/FastEndpoints/FastEndpoints/blob/34ebe062156ad43e2f849af3ae4170d474a3f0ac/Tests/IntegrationTests/FastEndpoints/EndpointTests/EndpointTests.cs#L117-L127
