### ISSUE TITLE
Using FastEndpoints Postprocessor and the SendResultAsync doesn't provide the filled "Result" in the context

### ISSUE THREAD

**Issue by Kermel** [FastEndpoints/FastEndpoints#832]
I'm experimenting with FastEndpoints and I have an endpoint that finishes with the following call in the HandleAsync method:
Endpoint class:
`internal class LoginEndpoint : Endpoint<LoginRequest, Result<LoginResponse>>`

Handler method:
```
public override async Task HandleAsync(LoginRequest req, CancellationToken ct)
{
    var loginResponse = ...;
    ...//login response is of the Result<LoginResponse> type
    await SendResultAsync(loginResponse.ToMinimalApiResult()); //using the Ardalis.Results extension that provides the (Microsoft.AspNetCore.Http.)IResult type
}
```

Configure method:
```
public override void Configure()
{
    Verbs(Http.POST);
    Routes("/login");
    AllowAnonymous();
    PostProcessor<LoginPostProcessor>();
}
```

And the LoginPostProcessor:
```
internal class LoginPostProcessor : IPostProcessor<LoginRequest, Result<LoginResponse>>
{
    public async Task PostProcessAsync(IPostProcessorContext<LoginRequest, Result<LoginResponse>> context, CancellationToken ct)
    {
        if(context.Response?.Status == ResultStatus.Ok) // Login successful
        {
            //...do something
        }
    }
}
```

But the context.Response is null.

When I finish my Handler method just by this call:
`await SendAsync(loginResponse, cancellation: ct);`

then everything works. and the context.Response is correctly filled in the postprocessor...

Am I doing something wrong?

**Comment by dj-nitehawk** [comment]
since the `IResult` type is in-charge of serializing the response to the response stream, there is no way for the endpoint/context itself to know what was serialized. due to this technical block, i'd have to say what you're trying to achieve is not possible. will update the documentation regarding this limitation when using `IResult/SendResultAsync`.
