### ISSUE TITLE
Endpoint with NoContent produces wrong swagger schema after migrating to dotnet 9

### ISSUE THREAD

**Issue by dziedrius** [FastEndpoints/FastEndpoints#833]
We did migration of our project to dotnet 9 and noticed, that it started to produce wrong schema.
For endpoints that are returning `NoContent`, it is adding HTTP response 200, which looks like this:
```
 "200": {
            "description": "Success",
            "content": {
              "text/plain": null
            }
          },
```
Notice, that content type is `"text/plain": null` which is not only strange, but also not valid.

Currently we did workarround with `Description(b => b.ClearDefaultProduces(200));`, but it would be nice if there was no need to do it.
I've tested with 5.31.0 and 5.31.0.14-beta, same behavior in both.

Code:
```
using FastEndpoints;
using FastEndpoints.ClientGen;
using FastEndpoints.Swagger;
using Microsoft.AspNetCore.Http.HttpResults;

var bld = WebApplication.CreateBuilder();
bld.Services.AddFastEndpoints().SwaggerDocument();

var app = bld.Build();
app.UseFastEndpoints().UseSwaggerGen(); 

await app.ExportSwaggerJsonAndExitAsync("Example", "./");

app.Run();

public class MyEndpoint : Endpoint<MyRequest, NoContent>
{
    public override void Configure()
    {
        Post("/api/user/create");
        AllowAnonymous();
    }

    public override async Task HandleAsync(MyRequest req, CancellationToken ct)
    {
        await SendNoContentAsync(ct);
    }
}

public class MyRequest
{
    public string FirstName { get; set; }
}
```

On the side note, for some reason `dotnet run --exportswaggerjson true` in this example app was simply launching web app, not sure why, it was working as expected in original app though.

**Comment by dj-nitehawk** [comment]
there is a [known bug](https://github.com/dotnet/aspnetcore/issues/57801#issuecomment-2439578287) in .net 9 sdk i believe that's causing this. i've added a workaround until they sort that out. should be all good now starting `v5.31.0.15-beta`.
