### ISSUE TITLE
Swagger Issue with Duplicated Response Status Key when endpoints has a Validator and uses Results Union containing `BadRequest`

### ISSUE THREAD

**Issue by PeterMarinov** [FastEndpoints/FastEndpoints#834]
### Summary
The issue occurs on .NET 9 only when using Union-Type Returning Handler and validator associated with the endpoint. It **only** reproduces if the Results union contains `BadRequest` e.g. `Results<BadRequest, TResult1, ... TResultN>` in its' response signature since both responses the [Default validation error](https://fast-endpoints.com/docs/swagger-support#describe-endpoints) and `BadRequest` generate response metadata with 400 Status Code.

### Details

The issue pin points to the workaround for the ASP.NET Core OpenApiGenerator limitation (https://github.com/dotnet/aspnetcore/issues/57801#issuecomment-2439578287) implemented
within the `FastEndpoints.Swagger.OperationProcessor.Process(OperationProcessorContext ctx)` method.

@dj-nitehawk - I can explore fixing the issue in the `OperationProcessor` by checking if the key exists before calling `op.Responses.Add(meta.Key, res);` and if it exists, we can mitigate the duplication. Before doing or chasing an alternative solution, I was wondering on your thoughts on the following:
* This used to work on .NET 8 as it's handled there, but do you see using Endpoint with validation alongside `Results<BadRequest, TResult1, ... TResultN>` against the FastEndpoint's intent?
* If so, then I can just move away to `Results<ProblemDetails, TResult1, ... TResultN>` and also override the default validation response to be of type `ProblemDetails`
* Is there anything I can do contribute to the repo for this use case?

### Steps to Reproduce

1. Use this code below within the test FastEndpoints.Web project:
```c#
using FluentValidation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using static Microsoft.AspNetCore.Http.TypedResults;

namespace TestCases.TypedResultWithValidationTest;

sealed class Request
{
    public int Id { get; set; }
}

sealed class RequestValidator : Validator<Request>
{
    public RequestValidator()
    {
        RuleFor(x => x.Id).GreaterThanOrEqualTo(0).WithMessage("an Id cannot be negative number");
    }
}

sealed class Response
{
    public int RequestId { get; set; }
}

[HttpPost("multi-test-with-validation"), AllowAnonymous]
sealed class MultiResultEndpoint : Endpoint<Request, Results<Ok<Response>, BadRequest, ProblemDetails>>
{
    public override async Task<Results<Ok<Response>, BadRequest, ProblemDetails>> ExecuteAsync(Request req, CancellationToken ct)
    {
        await Task.Delay(1); //simulate some work

        if (req.Id == 0)
        {
            return BadRequest();
        }

        if (req.Id == 1)
        {
            AddError(r => r.Id, "value has to be greater than 1");
            return new ProblemDetails(ValidationFailures);
        }

        return Ok(new Response
        {
            RequestId = req.Id
        });
    }
}
```
2. Build the project and navigate
3. Navigate to Swagger http://localhost:5001/swagger

Swagger fails with a fatal exception
![image](https://github.com/user-attachments/assets/4444294a-acb3-4af5-b978-a57be3866925)

Exception details here:
```bash
TYPE: ArgumentException
      REASON: An item with the same key has already been added.
      ---------------------------------
         at NSwag.Collections.ObservableDictionary`2.Insert(TKey key, TValue value, Boolean add)
         at NSwag.Collections.ObservableDictionary`2.Add(TKey key, TValue value)
         at FastEndpoints.Swagger.OperationProcessor.Process(OperationProcessorContext ctx) in /Users/some-user/Code/FastEndpoints/Src/Swagger/OperationProcessor.cs:line 161
```

**Comment by dj-nitehawk** [comment]
the duplicate key issue has been fixed in `v5.31.0.17-beta`.

however, the the root cause of this is not the validator. it's happenning because you have 2 different responses that fall under the same 400 status code: `BadRequest` and `ProblemDetails`

even though the endpoint works fine with this, the generated swagger spec will not be exactly what you'd expect.
as of now, you'll only see the last 400 response in swagger.

the `OperationProcessor` doesn't have support for multiple schema (response shapes) for a single status code. we've done it this way because we believe it's better for the consumer if there's only one shape of response per status code. 

so the suggestion is to just keep `ProblemDetails` as the only response for a 400 status code, and get rid of the `BadRequest`. the consumer can just check if there's actually any errors in the body and act accordingly.

---

if someone has the capacity to do a PR to support multiple response shapes per status code, please go ahead.
i believe the following block of code would have to be rewritten to achieve it:

https://github.com/FastEndpoints/FastEndpoints/blob/749fbad30fad5b6a1e80328dce5e593b79ec1935/Src/Swagger/OperationProcessor.cs#L110-L225

**Comment by PeterMarinov** [comment]
Thanks for the quick fix and the input. I have tested it and verified it is working. Great stuff! 🙇 

I agree that having different shapes of the same response code, especially for BadRequest, is not a great API design. I will certainly move away from BadResult and rely on `FastEndpoints.ProblemDetails` for both auto-generated failed validation responses and other flows that return 400 - will achieve a cleaner API design this way. It's great that we can change the default validation response to `FastEndpoint.ProblemDetails` with one line of code!

My thoughts on improving FastEndoints to support multiple shapes of the same status code:
I see the code you have pointed me to and it seems pretty straightforward. 

I am mostly concerned with:
1. Does NSwag fully support this - I saw couple of directions, but need to test
2. Business wise - does this seem like a good use case or will open the gate to bad API design

In any case, I will be happy to contribute. Please give me some time to research and we can chat in Discord about this feature so I get some input before I start.

**Comment by dj-nitehawk** [comment]
did some digging and according to the open api 3 spec, the following is not valid:

```yaml
responses:
  '400':
    description: Bad Request
    content:
      application/problem+json:
        schema:
          $ref: '#/components/schemas/ProblemDetails'
  '400':
    description: Bad Request with no body
```

only the following is valid (one status code and multiple content/mime types):

```yaml
responses:
  '200':
    description: OK
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/JsonResponse'
      application/xml:
        schema:
          $ref: '#/components/schemas/XmlResponse'
```

since FE nor minimal apis support content negotiation, i don't see a dire need for us to support that. so, consider this as extremely low priority and proceed at your leisure.

if we go down this path, we need to rethink how the `Summary()` allows the user to provide the details (example/description) per each response model. seems like unnecessary complexity to manage if you ask me 😉

**Comment by PeterMarinov** [comment]
Thanks for the suggestions. 

What if we use [discriminator object](https://spec.openapis.org/oas/v3.1.1.html#discriminator-object) with `oneOf` to list multiple ErrorResponses in case they share the same content/mime type? Example:

```yml
responses:
  '400':
    description: Bad Request
    content:
      application/problem+json:
        schema:
          oneOf:
             $ref: '#/components/schemas/ErrorResponse',
             $ref: '#/components/schemas/ProblemDetails'
```

I am certainly not grasping all implications as I am not too deep into the OpenAPI schema, but the following considerations occur to me:
* **content/mime types** - this will only be valid when the error responses share the same content/mime type, e.g. "application/problem+json", while for OK responses this can be broken into multiple content groups you've described

```yml
responses:
  '200':
    description: OK
    content:
      application/json:
        schema:
          $ref: '#/components/schemas/JsonResponse'
      application/xml:
        schema:
          $ref: '#/components/schemas/XmlResponse'
```

* if we go with `oneOf` there will be also a need to rethink the logic for the discriminator field, which cannot be auto-generated, so we will have to skip it or add some logic, which might make the framework too opinionated.

In any case, I see more value into guiding devs to design with single 400 response type so that both auto-generated and method-body generated responses share the same response schema. Too much flexibility can create bad habits :)

I know this is low priority, but eager to help if this is of any value for the framework, Let me know if any of this seems like a scope I can help with and will continue to dig in.

**Comment by dj-nitehawk** [comment]
afaik, `OneOf` is used for polymorphic models. we have that working already as shown in [this example](https://gist.github.com/dj-nitehawk/8a938ac7edb1ac840ed0601121d557ea).

i personally think there's no need to complicate things here and like you say, allow developers to do whaky shit which might lead to bad api design. if someone really wants to, they can write an nswag `IOperationProcessor` to add the additional responses for a single status code however they wish.

only thing we should spend any time on is improving the support for listing multiple mime types for a single status code such as in the case of a json as well as an xml response like above.

**Comment by PeterMarinov** [comment]
Perfect, we have a winner then - Multiple mime types it is...and this will probably open the gates for content negotiation.

=> I will research the OpenAPI docs and try to plan my first contribution to the project. Cheers
