### ISSUE TITLE
Generated OpenApi doesn't route parameters definition

### ISSUE THREAD

**Issue by matteotrapani** [FastEndpoints/FastEndpoints#838]
Hi,

I'm using the latest version of this library along with .NET9. Since Swagger is not anymore the default library I don't want to use `FastEndpoints.Swagger` package to generate the OpenApi document (and I'd like to use a different UI tool).
When trying to create a simple endpoint with a route parameter, the route parameter isn't added in the OpenApi definition both if I use a DTO or not to map the request.

Here you have a sample of the code (obviously not complete since it contains reference to my company :) )

`Program.cs`
```csharp
var builder = WebApplication.CreateBuilder(args);
StartupServices(builder);

var app = builder.Build();
ConfigureApp(app);
app.Run();
return;

void StartupServices(WebApplicationBuilder webApplicationBuilder)
{
    webApplicationBuilder.Host.UseSerilog((context, configuration) => configuration.ReadFrom.Configuration(context.Configuration));
    webApplicationBuilder.Services
            .AddFastEndpoints()
            // Learn more about configuring OpenAPI at https://aka.ms/aspnet/openapi
            .AddOpenApi()
            .AddEndpointsApiExplorer()
            .AddHealthChecks();
}

void ConfigureApp(WebApplication app)
{
    app.UseFastEndpoints(c =>
        {
            c.Versioning.Prefix = "v";
            c.Versioning.DefaultVersion = 1;
            c.Versioning.PrependToRoute = true;
            c.Endpoints.RoutePrefix = "api";
        });
    app.MapHealthChecks("/health/live");
    app.MapOpenApi();
    app.MapScalarApiReference();
    app.UseHttpsRedirection();
}
```

```csharp
// cf https://fast-endpoints.com/
public class GetWeatherForecastsEndpoint : EndpointWithoutRequest<IEnumerable<GetWeatherForecastsDto>>
{
    private readonly IMediator _mediator;

    public GetWeatherForecastsEndpoint(IMediator mediator) => _mediator = mediator;

    public override void Configure()
    {
        // cf https://fast-endpoints.com/docs/get-started#configuring-with-attributes
        Get("/weatherforecast/{Test}");
        Description(x => x.WithTags("WeatherForecast"));
        AllowAnonymous();
    }

    public override async Task HandleAsync(CancellationToken ct)
    {
        var test = Route<string>("Test");
        Logger.LogInformation(test);
        var result = await _mediator.Send(new GetWeatherForecastQuery(), ct);
        // an automatic mapper can be used, but there is an issue for unit tests
        // cf https://fast-endpoints.com/docs/domain-entity-mapping https://github.com/FastEndpoints/FastEndpoints/issues/836
        await SendAsync(result.Select(r => r.ToWeatherForecastDto()), cancellation: ct);
    }
}
```

Am I doing something wrong or forgetting something?

Thanks a lot!

**Comment by dj-nitehawk** [comment]
the new ms opeapi package is not yet supported. see here: https://github.com/FastEndpoints/FastEndpoints/issues/743#issuecomment-2255772977

`FastEndpoints.Swagger` package is our NSwag integration package and it is not optional. however as you can see from the issue linked above, you're free to use any swagger ui library even with the `FastEndpoints.Swagger`.

also we don't support swashbuckle at all which is what has been deprecated.

let me know if you need any further help after reading the [swagger documentation](https://fast-endpoints.com/docs/swagger-support#configuration).

**Comment by matteotrapani** [comment]
Wow, thanks for the quick response. Will give it a try!

Il giorno gio 28 nov 2024 alle ore 12:20 Dĵ ΝιΓΞΗΛψΚ <
***@***.***> ha scritto:
