### ISSUE TITLE
Throwing Duplicate Endpoint name error while loading Swagger when enabling API version

### ISSUE THREAD

**Issue by ajiththamban90** [FastEndpoints/FastEndpoints#839]
Hi ,
I was trying to enable versioning as per the documentation.
When I set following code to enable versioning
app.UseFastEndpoints(c => 
{
  c.Versioning.Prefix = “v”;
});
My application is throwing Duplicate endpoint name error even though there is no duplicate endpoint. When I remove above , there is no error and swagger is loading my apis. How do I resolve this? Do I need to keep this to have API versioning? Any helps or thoughts would be appropriated. I am using .net 8 and my web api is completely with FastEndPoints API

**Comment by dj-nitehawk** [comment]
need to know how to reproduce this as it's not a common occurance.
pls attach a minimalistic repro project with just one or two endpoints showcasing the issue.
thanks!

**Comment by P1Rh0** [comment]
I just got this too, it was solved by changing the class names containing the endpoints (I have one endpoint per class and the outer class names were not unique and in different namespaces). Not sure if that's the cause but I'll try to add some repro steps at some point.
