### ISSUE TITLE
"Opt out" of Swagger default params

### ISSUE THREAD

**Issue by dgg** [FastEndpoints/FastEndpoints#840]
In our API, vast majority of endpoints require a custom header.

That header is not declared in the request of any of the endpoints (don't know the reasons behind) and it is accessed via `HttpContext` extensions.

The way we have exposed that requirement to the OpenAPI spec of our service is by adding as a param in an operation processor added in the `.SwaggerDocument()` method in _Program.cs_.

```csharp
builder.Services.AddFastEndpoints()
	.SwaggerDocument(opts =>
	{
		opts.DocumentSettings = s =>
		{
			s.OperationProcessors.Add(new OperationProcessor(x =>
			{
				var parameter = new OpenApiParameter
				{
					// fill up
				}
				x.OperationDescription.Operation.Parameters.Add(parameter);
			}

			return true;
		}));
	});

```

That makes the parameter available in our Swagger UI for **all** the operations.

Tried to remove it in the endpoints that don't need that header with the `.Summary()` method, but it is called before the defaults are added so I cannot "remove" it from the collection.

What would be the best way to remove that default parameter from certain endpoints?

Thanks in advance

**Comment by dj-nitehawk** [comment]
add an endpoint tag to the endpoints that shouldn't have the header like so:

```cs
public override void Configure()
{
    Tags("NoHeader");
}
```

then look for this tag in the operation processor and don't add the header:

```cs
public class MyOperationProcessor : IOperationProcessor
{
    public bool Process(OperationProcessorContext ctx)
    {
        var op = ctx.OperationDescription.Operation;

        var endpointDefinition = ctx.GetEndpointDefinition();

        if (endpointDefinition?.EndpointTags?.Contains("NoHeader") is true)
            return true;

        op.Parameters.Add(
            new()
            {
                Name = "x-custom-header",
                Kind = OpenApiParameterKind.Header,
                Schema = new() { Type = NJsonSchema.JsonObjectType.String }
            });

        return true;
    }
}
```

that should do the trick...

**Comment by dgg** [comment]
Thanks a lot, something like that is exactly what I was looking for and could not find.
