### ISSUE TITLE
Thread safety issues with NullabilityInfoContext.

### ISSUE THREAD

**Issue by AlexAlappsis** [FastEndpoints/FastEndpoints#842]
I've been getting intermittent errors with the swagger generation in my project, and have narrowed down the issue, but not entirely sure of the right fix.

There are two errors:
 System.ArgumentException: 'An item with the same key has already been added. Key: [One of my request classes]

and 

System.InvalidOperationException: 'Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.'

The issue is happening on https://github.com/FastEndpoints/FastEndpoints/blob/10283419d82d5bea494b7f498f4bdf0d95d9cec0/Src/Swagger/Extensions.cs#L341

And I think is ultimately caused by how _nullCtx is initialized on https://github.com/FastEndpoints/FastEndpoints/blob/10283419d82d5bea494b7f498f4bdf0d95d9cec0/Src/Swagger/Extensions.cs#L323

NullabilityInfoContext is not threadsafe, as indicated by https://github.com/dotnet/runtime/issues/100254

I'm not certain why there are multiple threads calling into the IsNullable static function, it's entirely possible I have a configuration error, but I haven't been able to track it down if so.  Also interestingly, the same key error is always on the same key, a request object with a single string property.  I think that request shape is unique in my project, so it may be related to that.

I have been able to fix the issue by changing the IsNullable function to:

```
internal static bool IsNullable(this PropertyInfo p)
    return new NullabilityInfoContext().Create(p).WriteState == NullabilityState.Nullable;
```

But ideally the NullabilityInfoContext would be shared and not re-instantiated every time, so I'm not sure what the best fix is.

I haven't had time to try a small sample project to see if I can reliably replicate the issue, but may be able to later if that will help.

**Comment by dj-nitehawk** [comment]
can you try `v5.32.0.4-beta` and report back please.
should be sorted now.

**Comment by dj-nitehawk** [comment]
> System.ArgumentException: 'An item with the same key has already been added. Key: [One of my request classes]

going to need a repro for this one as i have no idea where to even start looking.

**Comment by AlexAlappsis** [comment]
Yep, that fixed it.

And both exceptions were happening in the same place, and are fixed.  I'm pretty sure it was just a matter of timing between the threads on if I was getting one exception or the other, or none.

Thanks
