### ISSUE TITLE
Multiple JWT tokens (Keycloak and Custom)

### ISSUE THREAD

**Issue by lucasrabiec** [FastEndpoints/FastEndpoints#852]
I have configured the Keycloak auth server to authorize users with JWT tokens. I also grant access to specific endpoints via Policies ("admin", "user" etc). It works.

I also want to generate a second JWT token (via a special endpoint from fast endpoints api) with a stringified `permissions` claim which will hold info about multiple scopes for multiple resources like: `"permissions": "[{\"resourceType\":\"Repo\",\"resourceId\":\"some-guid\",\"scopes\":[\"push\"]}]",`
Similar to GitHub personal access token and validate it if the Keycloak JWT is not provided.

I'm wondering if the resource's endpoint configuration can look like this
```
    public override void Configure()
    {   
        Get("/some-resource-endpoint/{resourceId}");
        Policies(ApiPolicy.AdminsOnly); // for Keycloak token
        PreProcessors(  // for generated custom jwt
            new ValidateTokenPreProcessor<SomeRequest>(
                ResourceType.Repo,
                "resourceId", // param name to get resource Id from the route when validating permissions from token
                Scope.Push
            )
        );
    }
```

Is it possible to use PreProcessor if Keycloak's policies are not met? If not how can I make it work with two different JWT tokens and use the custom one only if the Keycloak token is not present?

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

This change implements a custom JWT token validation system for resource-specific permissions, alongside the existing Keycloak authentication. It adds a new PreProcessor for validating these custom tokens, and modifies the AuthExtensions to support both Keycloak and custom JWT validation.

You can review changes in this commit: https://github.com/wwqwq2313/FastEndpoints-FastEndpoints-852/commit/d0fec429c794d9bdb42ba6c5824724c967e9cbc2.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by dj-nitehawk** [comment]
i haven't tested the following but i think the way to go would be to setup two different jwt auth schemes like this:

```cs
builder.Services.AddAuthentication(options =>
{
    //make keycloak the default scheme
    options.DefaultAuthenticateScheme = "Keycloak";
    options.DefaultChallengeScheme = "Keycloak";
})
.AddJwtBearer("Keycloak", options =>
{
    options.Authority = "https://your-keycloak-server/auth/realms/your-realm";
    options.Audience = "your-audience";
    options.RequireHttpsMetadata = false; // Set to true in production
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidIssuer = "https://your-keycloak-server/auth/realms/your-realm",
        ValidateAudience = true,
        ValidAudience = "your-audience",
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true
    };
})
.AddJwtBearer("CustomIssuer", options =>
{
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidIssuer = "https://your-custom-issuer",
        ValidateAudience = true,
        ValidAudience = "your-audience",
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes("your-custom-signing-key"))
    };

    options.Events = new JwtBearerEvents
    {
        OnTokenValidated = context =>
        {
            var claimsIdentity = context.Principal.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                //find your stringified "permissions" claim and convert the scopes to regular claims
                //and add those claims to the identity:
                claimsIdentity.AddClaim(...);
            }
        }
    };
});
```

and in endpoints where you want to enable the custom tokens as well, do the following:

```cs
public override void Configure()
{
    AuthSchemes("Keycloak","CustomIssuer");
}
```

i believe that should get you started. you can also read route parameters from the httpcontext within the `OnTokenValidated` hook.

pre-processors are not the right tool for this job because they are executed once the authorization middleware passes and this should ideally happen when the jwt tokens are validated.

**Comment by dj-nitehawk** [comment]
`Policies("AdminsOnly")` does the same thing as if you'd done `Options(b => b.WithMetadata(new AuthorizeAttribute("AdminsOnly")));`

so you can in your `CustomHandler` grab the endpoint's metada collection and look for the `AuthorizeAttribute` to get the policy name for that endpoint.

```cs
httpContext.GetEndpoint()?.Metadata.OfType<AuthorizeAttribute>()?.SingleOrDefault()?.Policy;
```

also, i'm not sure if `b.WithMetadata("required scope", "required resource")` is a good idea. might wanna use a custom class/attribute to store scope names.

btw, there's an example of a combined auth scheme [here](https://fast-endpoints.com/docs/security#combined-authentication-scheme) which might offer some insight.

**Comment by lucasrabiec** [comment]
Thanks, I ended up with a custom authorization handler that ran when I gave my CustomRequirements to the endpoint policy. 👍🏻
