### ISSUE TITLE
Serialization options SnakeCaseLower issue with request query strings

### ISSUE THREAD

**Issue by moxplod** [FastEndpoints/FastEndpoints#854]
When I add SnakeCaseLower. It makes everything correctly snake case, including the request query string parameters in the documentation. But when I send a request to the endpoint it does not deserialize it correctly. 

In the following example `comments_url` does not work but `commentsUrl` works. It is most likely due to model binding being different to Json Serialization settings. But in that case the documentation should not be changed as well for query parameters. 

Any recommended way of fixing this?
Ideally it keeps the name in the documentation and what it binds to consistent.

`o.Serializer.Options.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;`

```c#

            endpoints.MapFastEndpoints(o =>
            {
                o.Versioning.DefaultVersion = 1;
                o.Versioning.Prefix = "v";
                o.Versioning.PrependToRoute = true;
                o.Serializer.Options.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;
                o.Endpoints.RoutePrefix = "API";
             }   
                
 // Example request class
public class PostCommentsRequest
{
    public string CommentsUrl { get; set; }
    public int? Page { get; set; }
} 

``` 

It makes this as follows in the documentation: 

Query Parameters
comments_url string required

For now - To solve this I have used [BindFrom("comments_url")] 
Still think this is a bug, as the documentation and the model binding are inconsistent if you just use the naming policy.

**Comment by dj-nitehawk** [comment]
there's a setting you can turn off which will prevent the json naming policy from being used by swagger:
```cs
.SwaggerDocument(o => o.UsePropertyNamingPolicy = false)
```

this is usually not a concern with camel case and pascal case naming, because the binder ignores case altogether for non-json binding sources. it becomes an issue for snake case though because the name is a completely different string and you must use the `[BindFrom(...)]` attribute to instruct the binder what to match with.

**Comment by moxplod** [comment]
But wouldn’t that change the request and response body properties also?

I prefer snake case in my jsons. Those I don’t have a problem with. The
only issue is model binding.

**Comment by dj-nitehawk** [comment]
okay... the behavior has been changed starting `v5.32.0.15-beta`.
see [changelog](https://github.com/FastEndpoints/FastEndpoints/blob/main/Src/Library/changelog.md) for details.

**Comment by moxplod** [comment]
Hey, thanks for the quick turn around on that. 

I tried this beta release and it still does not bind properly. Here is my setup. Without the attribute BindFrom the CommentsUrl is empty, with it, it has the value that I pass.


```c#

    [BindFrom("comments_url")]
    public string CommentsUrl { get; set; }


endpoints.MapFastEndpoints(o =>
            {
                o.Versioning.DefaultVersion = 1;
                o.Versioning.Prefix = "v";
                o.Versioning.PrependToRoute = true;
                o.Serializer.Options.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;
                o.Binding.UsePropertyNamingPolicy = true;
                o.Endpoints.RoutePrefix = "api";
                o.Endpoints.Configurator = c =>
                {
                    c.AuthSchemes(ApiKeyAuth.SchemeName);
                    c.Throttle(3, 1, ApiKeyAuth.HeaderName);
                    c.Description(b =>
                    {
                        b.ClearDefaultProduces(403);
                        b.ProducesProblemFE(429);
                    });
                    c.PreProcessor<CreditCheckPreProcessor>(Order.Before);
                    c.PostProcessor<GlobalExceptionPostProcessor>(Order.After);
                    c.PostProcessor<CreditPostProcessor>(Order.After);
                };
            });

```

**Comment by dj-nitehawk** [comment]
just got hit with a bad flu. will have a look as soon as i'm better.

**Comment by moxplod** [comment]
Feel better soon! Thanks for looking into this.

**Comment by dj-nitehawk** [comment]
looks like i missed a few spots.
pls try again with `v5.32.0.16-beta`.
do note the new setting is now disabled by default.
seems it has a far reaching impact than initially thought and it's going to break a lot of things for existing projects.
so the setting will be opt-in for fresh projects.
please give it a thoughrough test if you can. still feeling a bit delirious from the fever 😜

**Comment by moxplod** [comment]
Hey, I just got to trying this out. This changes the Query parameters as expected in swagger but does not bind to them. So when I make the call the data is not present in the variables.

Example endpoint: 

```c#
sealed class ProtectedEndpoint : Endpoint<ProtectedRequest>
{
    public override void Configure()
    {
        Get("/protected");
        Tags(SiteApi.TAG_DEVELOPMENT);
        Description(r => r.WithTags(SiteApi.TAG_DEVELOPMENT));
    }

    public override async Task HandleAsync(ProtectedRequest req, CancellationToken ct)
    {
        Log.Debug($"Protected Endpoint called with params: {req.ParamName1}, {req.ParamName2}, {req.NoCache}");
        await SendOkAsync(ct);
    }
}

public class ProtectedRequest
{
    /// <summary>
    /// Parameter 1
    /// </summary>
    public string ParamName1 { get; set; }
    
    /// <summary>
    /// Parameter 2
    /// </summary>
    public string ParamName2 { get; set; }
    
    /// <summary>
    /// Set No Cache
    /// </summary>
    public bool? NoCache { get; set; }
    
    public bool IsCacheDisabled()
    {
        return NoCache.HasValue && NoCache.Value;
    }
}
```

**Comment by dj-nitehawk** [comment]
just tried the following program:
```cs
var bld = WebApplication.CreateBuilder(args);
bld.Services
   .SwaggerDocument()
   .AddFastEndpoints();

var app = bld.Build();
app.UseFastEndpoints(
       c =>
       {
           c.Serializer.Options.PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower;
           c.Binding.UsePropertyNamingPolicy = true;
       })
   .UseSwaggerGen();
app.Run();

sealed class ProtectedEndpoint : Endpoint<ProtectedRequest>
{
    public override void Configure()
    {
        Get("/protected");
        AllowAnonymous();
    }

    public override async Task HandleAsync(ProtectedRequest req, CancellationToken ct)
    {
        await SendOkAsync($"Protected Endpoint called with params: {req.ParamName1}, {req.ParamName2}, {req.NoCache}");
    }
}

public class ProtectedRequest
{
    public string ParamName1 { get; set; }
    public string ParamName2 { get; set; }
    public bool? NoCache { get; set; }
}
```

and it produces this:

![Image](https://github.com/user-attachments/assets/bfbd1bc5-25d4-4470-8b57-f0a3194549a0)

if it doesn't work for you, please attach a simplified repro project i can have a look at.

**Comment by moxplod** [comment]
I was able to get this to work. I may have not had the right build that I was trying. 
Thanks for your help!!

**Comment by moxplod** [comment]
Great to have got rid of the annoying BindFrom's everywhere now
