### ISSUE TITLE
Rate limiting response json

### ISSUE THREAD

**Issue by moxplod** [FastEndpoints/FastEndpoints#855]
Hi, Is there any way to return the error json how we do for other errors on rate limiting?

` c.Throttle(3, 1, ApiKeyAuth.HeaderName);`

This returns 429 per endpoint when the limits are hit with a text message. I would like to add the rate limits in the error message. 

<img width="805" alt="image" src="https://github.com/user-attachments/assets/6e624874-7eef-4ffc-b36a-438c2b60304a" />

**Comment by dj-nitehawk** [comment]
the built-in rate limiter is very basic and doesn't offer a lot of customization opportunities for the sake of performance.
you can only customize the global message here:
```cs
app.UseFastEndpoints(c => c.Throttle.Message = "a custom 429 message")
```

if you need anything more, might pay to explore the asp.net [rate limiting options](https://learn.microsoft.com/en-us/aspnet/core/performance/rate-limit?view=aspnetcore-7.0). which you can add to endpoints like so:

```cs
public override void Configure()
{
    Options(x => x.RequireRateLimiting("limiterPolicy"));
}
```
